Improve styling of existing components in statistics popup
opossum-tool/OpossumUI pull request #1006
Opened 2022-09-21 07:41 UTC by someshkhandelia

### Summary of changes

Make tables in statistics popup look more modular

### Context and reason for change

- The existing components were not styled in a modular way.
- In future, more components can now be conveniently added to the popup.

Fix: #948

Signed-off-by: someshkhandelia <someshkhandelia@gmail.com>

2022-09-21 07:43 UTC, someshkhandelia commented
Previously, the statistics popup looked like this:
![image](https://user-images.githubusercontent.com/9270691/191445125-e48e90f7-08a2-410c-8be1-9a19a35fd85d.png)

2022-09-21 07:45 UTC, someshkhandelia commented
After the commit https://github.com/opossum-tool/OpossumUI/pull/1006/commits/9a98a4ebb2c58032fd35f9bddcb0571b71599d81, the statistics popup looks like this:
![image](https://user-images.githubusercontent.com/9270691/191445562-592ea71b-edc3-492b-8414-ca0db3ff8922.png)

2022-09-21 10:56 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/AttributionPropertyCountTable.tsx
> +    props.attributionPropertyCountsEntries.map((entry) => entry[0].toString());
Here we could already generate the display names:

```
  const attributionPropertyDisplayNames =
    props.attributionPropertyCountsEntries.map((entry) => getAttributionPropertyDisplayNameFromId(entry[0].toString()));

```

2022-09-21 10:56 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/AttributionPropertyCountTable.tsx
> +  const attributionPropertyCounts: Array<string> =
Type annotation `: Array<string>` seems not necessary

2022-09-21 10:56 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/AttributionPropertyCountTable.tsx
> +          <MuiTableFooter style={{ position: 'sticky', bottom: 0 }}>
`style` should be replaced in favor of `sx`

2022-09-21 10:56 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/AttributionPropertyCountTable.tsx
> +      <MuiTableContainer sx={{ width: '30vw', marginBottom: 3 }}>
extract `{ width: '30vw', marginBottom: 3 }`. Might be part of `projectStatisticsPopupClasses`

2022-09-21 10:57 UTC, benedikt-richter commented
It really does look much better now 👍

2022-09-21 12:17 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/AttributionPropertyCountTable.tsx
> +    props.attributionPropertyCountsEntries.map((entry) => entry[0].toString());
Should be resolved here: https://github.com/opossum-tool/OpossumUI/commit/76d8c390a41b09634d9dbc0e0f76baa1c6469d5e

2022-09-21 12:18 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/AttributionPropertyCountTable.tsx
> +  const attributionPropertyCounts: Array<string> =
Should be resolved here: https://github.com/opossum-tool/OpossumUI/commit/76d8c390a41b09634d9dbc0e0f76baa1c6469d5e

2022-09-21 12:18 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/AttributionPropertyCountTable.tsx
> +          <MuiTableFooter style={{ position: 'sticky', bottom: 0 }}>
Should be resolved here: https://github.com/opossum-tool/OpossumUI/commit/76d8c390a41b09634d9dbc0e0f76baa1c6469d5e

2022-09-21 12:18 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/AttributionPropertyCountTable.tsx
> +      <MuiTableContainer sx={{ width: '30vw', marginBottom: 3 }}>
Should be resolved here: https://github.com/opossum-tool/OpossumUI/commit/76d8c390a41b09634d9dbc0e0f76baa1c6469d5e

2022-09-21 12:42 UTC, benedikt-richter requested changes
With the ORT example the table looks a bit broken.

![Screenshot 2022-09-21 at 14 41 47](https://user-images.githubusercontent.com/46576389/191506486-beba4b22-5f72-499e-b1d4-fb70a0c78a82.png)

2022-09-21 12:54 UTC, someshkhandelia commented
In response to: https://github.com/opossum-tool/OpossumUI/pull/1006#pullrequestreview-1115348632 , am I missing something because it looks fine on my system ?
![image](https://user-images.githubusercontent.com/9270691/191508594-b5413df4-6891-4dd9-8006-e709349c5b9e.png)

2022-09-22 07:08 UTC, benedikt-richter commented
I guess it is related to the zoom that is activated. I'll chaeck again

2022-09-22 08:28 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/shared-project-statistics-popup-styles.ts
> +    width: '40vw',
Having this fixed width will cause the table not to show all it's contents without horizontal scrollbar

2022-09-22 08:45 UTC, FlorianSchepers commented
> I guess it is related to the zoom that is activated. I'll check again

Yes it is zoom related. I have the same issue.

2022-09-22 09:59 UTC, someshkhandelia commented
Learning (notes for future reference):
![image](https://user-images.githubusercontent.com/9270691/191716851-540bd045-83f7-4317-9072-d1f6a1913665.png)
In response to https://github.com/opossum-tool/OpossumUI/pull/1006#issuecomment-1254618271, https://github.com/opossum-tool/OpossumUI/pull/1006#discussion_r977354854 and https://github.com/opossum-tool/OpossumUI/pull/1006#issuecomment-1254716089, 

- To have dynamic sizes **maxHeight** and **maxWidth** style attributes are useful. 
- Not only do they make your components dynamic to zooming but also they make it dynamic to the quantity of content contained by them. 
- Also, a point to note would be that the values must be specified in **px** units and not **vh** or **vw**, because they don't make it dynamic.

2022-09-22 10:01 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/shared-project-statistics-popup-styles.ts
> +    width: '40vw',
Should be resolved here: https://github.com/opossum-tool/OpossumUI/commit/ea8ccec429cd930f657fa4a50a0e40953ecb4cb7

I verified the change with several zoom-in and zoom-out levels as well as different input files that have different content both width-wise and height-wise.

2022-09-22 11:51 UTC, someshkhandelia commented
It was verbally agreed upon to keep the "Signal per Sources" table full-width of the popup, since in most real-life use-cases, we will be having several sources (columns).

2022-09-22 12:28 UTC, someshkhandelia commented
- Performed rebase to main, since this PR: https://github.com/opossum-tool/OpossumUI/pull/987 was merged and it contained changes in same files as the current PR. 
 - Resolved merge conflicts that arose from the rebase.
 - Find commit : https://github.com/opossum-tool/OpossumUI/commit/1535c5d02515e4c42fa58c7e6428d41eb4717332

2022-09-22 12:33 UTC, someshkhandelia commented
After the commit https://github.com/opossum-tool/OpossumUI/commit/1535c5d02515e4c42fa58c7e6428d41eb4717332, the popup looks like this:
![image](https://user-images.githubusercontent.com/9270691/191747770-b295155f-3b65-40b2-a380-94f30664064a.png)

2022-09-22 13:00 UTC, someshkhandelia commented
It was verbally discussed with @benedikt-richter to have the column containing license names to be aligned to the left, while all the other columns must be centrally aligned

2022-09-22 13:05 UTC, someshkhandelia commented
Incorporated https://github.com/opossum-tool/OpossumUI/pull/1006#issuecomment-1254989685. After the commit https://github.com/opossum-tool/OpossumUI/commit/6f3b2f880d8942e741bcc41787fd6459fdcb5b19, popup looks like this:
![image](https://user-images.githubusercontent.com/9270691/191754675-916820fb-855c-4baf-b8af-3fd4cad402ef.png)

2022-09-22 13:54 UTC, benedikt-richter approved these changes

2022-09-22 13:58 UTC, merged