Add critical licenses table to statistics popup
opossum-tool/OpossumUI pull request #1013
Opened 2022-09-23 14:40 UTC by someshkhandelia

### Summary of changes

Add critical licenses table to statistics popup

### Context and reason for change

- The table shows only high and medium critical licenses.
- The high critical licenses are placed above the medium critical ones.
- Both groups are sorted within themselves.

Fix: #947

Signed-off-by: someshkhandelia <someshkhandelia@gmail.com>

2022-09-26 06:54 UTC, benedikt-richter requested changes

2022-09-26 06:54 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/CriticalLicensesTable.tsx
> +export function CriticalLicensesTable(
Generally, it seems the comments could be replaced by introducing functions with good names that do the respective calculations described in the comments.

2022-09-26 06:54 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/CriticalLicensesTable.tsx
> +  return (
There are some parts of this component that are used in all three current tables (mainly header and footer). Seems to be good to extract these.

2022-09-26 06:54 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/CriticalLicensesTable.tsx
> +                    }}
This logic seems related to the one in the other table showing licenses highlighted by criticality.

2022-09-26 06:54 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/CriticalLicensesTable.tsx
> +  const tableColumnNames = ['LICENSE'].concat(SOURCE_TOTAL_HEADER);
This table has no relation to "sources". Seems the constant `SOURCE_TOTAL_HEADER` should not be used in the current context.
Further, `'LICENSE'` should be a constant.

2022-09-26 06:54 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/CriticalLicensesTable.tsx
> +    .filter((licenseName) => !isNull(licenseName));
filtering should happen before mapping.

2022-09-26 06:54 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/CriticalLicensesTable.tsx
> +      .map((license) => [license[0], license[1][SOURCE_TOTAL_HEADER]])
here logic is duplicated and should be extracted.

2022-09-26 06:54 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/CriticalLicensesTable.tsx
> +  );
Why do we do this conversion? Can't we just look up the relevant data for the licenses we are interested in (i.e. the critical ones) in `attributionCountPerSourcePerLicense`?

Here we convert a huge object into nested arrays and then filter it two times with subsequent mapping and sorting. That seems an unnecessarily expensive calculation.

2022-09-26 07:34 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/CriticalLicensesTable.tsx
> +export function CriticalLicensesTable(
Yes, I agree with you.

What I had thought was to extract the content of the current issue, and create functions when I work on https://github.com/opossum-tool/OpossumUI/issues/1011 so that I can use those functions in the other table as well.

2022-09-26 07:37 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/CriticalLicensesTable.tsx
> +  return (
Should be addressed in https://github.com/opossum-tool/OpossumUI/issues/1011

2022-09-26 07:38 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/CriticalLicensesTable.tsx
> +                    }}
Should probably be addressed in https://github.com/opossum-tool/OpossumUI/issues/1011

2022-09-26 07:40 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/CriticalLicensesTable.tsx
> +    .filter((licenseName) => !isNull(licenseName));
I am filtering out the null values that are being produced as a result of the map function. Thus, filtering should follow mapping in this case.

2022-09-26 07:43 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/CriticalLicensesTable.tsx
> +  );
I received an error that `attributionCountPerSourcePerLicense` could be undefined (it being a prop that is received from another component) and therefore I could not access its contents unless I used Object.entries()

2022-09-26 08:45 UTC, vasily-pozdnyakov requested changes

2022-09-26 08:45 UTC, vasily-pozdnyakov commented on src/Frontend/Components/ProjectStatisticsPopup/CriticalLicensesTable.tsx
> +    );
Can we use just one for-loop through licenseNamesWithCriticality instead of all these duplicated reduce-map pairs?

2022-09-26 08:45 UTC, vasily-pozdnyakov commented on src/Frontend/Components/ProjectStatisticsPopup/CriticalLicensesTable.tsx
> +  const tableColumnNames = ['LICENSE'].concat(SOURCE_TOTAL_HEADER);
We will always have two columns: 'LICENSE' and 'TOTAL'. Not sure that we need to use concat here. Just create a list with two elements.

2022-09-26 08:45 UTC, vasily-pozdnyakov commented on src/Frontend/Components/ProjectStatisticsPopup/CriticalLicensesTable.tsx
> +                      : license[1] || PLACEHOLDER_ATTRIBUTION_COUNT}
What do you mean by "license"? Is it like licenseNameWithCount? This is all through the code.
Also [0] and [1] are not really clear. Can we use dictionary instead of array?

2022-09-26 08:45 UTC, vasily-pozdnyakov commented on src/Frontend/Components/ProjectStatisticsPopup/CriticalLicensesTable.tsx
> +const PLACEHOLDER_ATTRIBUTION_COUNT = '-';
There is the same constant in AttributionCountPerSourcePerLicenseTable.tsx.  Do we really need it here?

2022-09-26 08:45 UTC, vasily-pozdnyakov commented on src/Frontend/Components/ProjectStatisticsPopup/CriticalLicensesTable.tsx
> +                          'high'
Btw, it would be nice to use Criticality enum from shared-types instead of hard-coded strings 'high' and 'medium'. Could you please also change it in AttributionCountPerSourcePerLicenseTable.tsx?

2022-09-26 08:45 UTC, vasily-pozdnyakov commented on src/Frontend/Components/ProjectStatisticsPopup/shared-project-statistics-popup-styles.ts
>    tableFooter: {
Can we merge footer and tableFooter styles?

2022-09-26 08:45 UTC, vasily-pozdnyakov commented on src/Frontend/Components/ProjectStatisticsPopup/shared-project-statistics-popup-styles.ts
> +    maxHeight: '600px',
Why does it have maxHeight of 600px, when the main table attributionCountPerSourcePerLicenseTable has maxHeight of 400px?

2022-09-26 12:12 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/CriticalLicensesTable.tsx
> +                      : license[1] || PLACEHOLDER_ATTRIBUTION_COUNT}
I have introduced functions and better variable names that will clarify what (and what type) is being contained by such variables.

2022-09-26 12:13 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/CriticalLicensesTable.tsx
> +    );
For loop was not essential. Function calls have removed the need for duplicated reduce-map pairs.

2022-09-26 13:00 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/shared-project-statistics-popup-styles.ts
> +  criticalLicensesTable: {
Done.

2022-09-26 13:02 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/shared-project-statistics-popup-styles.ts
> +    maxHeight: '600px',
changed it to 400px.

2022-09-26 13:09 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/CriticalLicensesTable.tsx
> +const PLACEHOLDER_ATTRIBUTION_COUNT = '-';
Removed and moved to a common place. Done.

2022-09-26 13:14 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/CriticalLicensesTable.tsx
> +                          'high'
Done.

2022-09-26 13:20 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/shared-project-statistics-popup-styles.ts
>    tableFooter: {
Done.

2022-09-26 14:41 UTC, vasily-pozdnyakov requested changes

2022-09-26 14:41 UTC, vasily-pozdnyakov commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
>  const UNKNOWN_SOURCE_PLACEHOLDER = '-';
Can we merge them?

2022-09-26 14:41 UTC, vasily-pozdnyakov commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +export const TOTAL_COLUMN_NAME_IN_TABLE_HEADER = 'Total';
Would be nice to merge all "Total", as it is always a column name.

2022-09-26 14:41 UTC, vasily-pozdnyakov commented on src/Frontend/Components/ProjectStatisticsPopup/CriticalLicensesTable.tsx
> +interface CriticalLicensesTableProps {
Interface declaration should be before functions.

2022-09-26 14:41 UTC, vasily-pozdnyakov commented on src/Frontend/Components/ProjectStatisticsPopup/CriticalLicensesTable.tsx
> +    );
However, we can do all calculations in one run instead of mapping multiple times over the array. In this case you won't need to transform dictionary into array, and you can directly write licenses into separate lists based on criticality (plus: you do not need to use reduce).

2022-09-26 14:41 UTC, vasily-pozdnyakov commented on src/Frontend/Components/ProjectStatisticsPopup/CriticalLicensesTable.tsx
> +                      : license[1] || PLACEHOLDER_ATTRIBUTION_COUNT}
Could we do array of dictionaries? In this case it will be clear that [0]=licenseName, [1]=count

2022-09-26 14:41 UTC, vasily-pozdnyakov commented on src/Frontend/Components/ProjectStatisticsPopup/CriticalLicensesTable.tsx
> +  const tableColumnNames = ['LICENSE'].concat(SOURCE_TOTAL_HEADER);
SOURCE_TOTAL_HEADER is not an appropriate name here, I think.

2022-09-26 14:41 UTC, vasily-pozdnyakov commented on src/Frontend/Components/ProjectStatisticsPopup/CriticalLicensesTable.tsx
> +): Array<string> {
Btw, you can use set.

2022-09-26 14:41 UTC, vasily-pozdnyakov commented on src/Frontend/Components/ProjectStatisticsPopup/CriticalLicensesTable.tsx
> +    .reduce((total1, total2) => +total1 + +total2, 0);
See reduce usage in project-statistics-popup-helpers.ts. Would be nice to make it consistent.

2022-09-26 14:41 UTC, vasily-pozdnyakov commented on src/Frontend/Components/ProjectStatisticsPopup/CriticalLicensesTable.tsx
> +    );
Can we do both calculations in one function?

2022-09-26 14:48 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
>  const UNKNOWN_SOURCE_PLACEHOLDER = '-';
Depending on the context these variables are used in, we are having different names, despite having the same values. That's what I understood from @benedikt-richter's comment here: https://github.com/opossum-tool/OpossumUI/pull/1013#discussion_r979607836

2022-09-26 14:49 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +export const TOTAL_COLUMN_NAME_IN_TABLE_HEADER = 'Total';
Please see https://github.com/opossum-tool/OpossumUI/pull/1013#discussion_r980130507

2022-09-26 14:51 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/CriticalLicensesTable.tsx
> +interface CriticalLicensesTableProps {
The interface here refers to the props of the function that is just after it. I think it is more readable if props and function are close to each other.

2022-09-26 14:57 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/CriticalLicensesTable.tsx
> +                      : license[1] || PLACEHOLDER_ATTRIBUTION_COUNT}
I am trying to have a more generic table construct overall, where we have an array of table rows, instead of key, value pairs that say that license name is a key and number of attributions is a value.
Besides, because of the variable naming and function definition, it should be clear what does the variable contain.

2022-09-26 15:08 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/CriticalLicensesTable.tsx
> +    );
I would prefer to have separate functions rather than have a single function that does too many things.
Regarding  multiple runs, the complexity will stay O(n) in both cases, and in this case the code is more readable

2022-09-26 15:13 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/CriticalLicensesTable.tsx
> +    .reduce((total1, total2) => +total1 + +total2, 0);
I am trying to calculate a grand total of several totals, that is why I have the variables named the way they are. The initial value starts with 0, which is more clear here than the reference you have pointed to.

2022-09-26 15:15 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/CriticalLicensesTable.tsx
> +  const tableColumnNames = ['LICENSE'].concat(SOURCE_TOTAL_HEADER);
It is no longer being used in the recent version of the code.

2022-09-26 15:18 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +export const TOTAL_COLUMN_NAME_IN_TABLE_HEADER = 'Total';
Also it is not always a column name. Depending on context, it is used as a key to access different parts of a dictionary in another table.

2022-09-26 15:39 UTC, benedikt-richter requested changes

2022-09-26 15:39 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/CriticalLicensesTable.tsx
> +      licenseNameAndCriticality[1] === criticality
Having used an object that would be `licenseNameAndCriticality.criticality === criticality`

2022-09-26 15:39 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/CriticalLicensesTable.tsx
> +    .filter((licenseName) => licenseName != '');
Could also be `.filter(Boolean)`

2022-09-26 15:39 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/CriticalLicensesTable.tsx
> +): Array<[string, number]> {
as above, using objects make it easier to understand the semantics from the signature of a function

2022-09-26 15:39 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/CriticalLicensesTable.tsx
> +                      : license[1] || PLACEHOLDER_ATTRIBUTION_COUNT}
I also find the name `license` confusing. I'd not expect it to be a tuple.

2022-09-26 15:39 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/CriticalLicensesTable.tsx
> +                      : license[1] || PLACEHOLDER_ATTRIBUTION_COUNT}
> I am trying to have a more generic table construct overall, where we have an array of table rows, instead of key, value pairs that say that license name is a key and number of attributions is a value. Besides, because of the variable naming and function definition, it should be clear what does the variable contain.

I like that idea. However, I'd prefer to have all calculations using objects (as the names of the keys help understanding what's going on: the business logic) and then to have a final step where the data is transformed into what the component needs (this might be arrays) where the display logic lives.

2022-09-27 08:41 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/CriticalLicensesTable.tsx
> +    .reduce((total1, total2) => +total1 + +total2, 0);
Done

2022-09-27 08:41 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/CriticalLicensesTable.tsx
> +export function CriticalLicensesTable(
Done

2022-09-27 08:42 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/CriticalLicensesTable.tsx
> +  const tableColumnNames = ['LICENSE'].concat(SOURCE_TOTAL_HEADER);
Done

2022-09-27 08:43 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/CriticalLicensesTable.tsx
> +      .map((license) => [license[0], license[1][SOURCE_TOTAL_HEADER]])
Done.

2022-09-27 08:43 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/CriticalLicensesTable.tsx
> +  );
Done.

2022-09-27 08:44 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/CriticalLicensesTable.tsx
> +  const tableColumnNames = ['LICENSE'].concat(SOURCE_TOTAL_HEADER);
Done.

2022-09-27 08:44 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/CriticalLicensesTable.tsx
> +                      : license[1] || PLACEHOLDER_ATTRIBUTION_COUNT}
Done.

2022-09-27 08:45 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/CriticalLicensesTable.tsx
> +    .filter((licenseName) => licenseName != '');
Done

2022-09-27 08:45 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/CriticalLicensesTable.tsx
> +  allLicensesWithCriticality: Array<[string, Criticality | undefined]>,
Done.

2022-09-27 08:46 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/CriticalLicensesTable.tsx
> +): Array<[string, number]> {
Done.

2022-09-27 08:47 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/CriticalLicensesTable.tsx
> +    getCriticalLicenseNamesWithTheirTotalAttributions(
Thanks.

2022-09-27 08:48 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/CriticalLicensesTable.tsx
> +): Array<string> {
Used Array of Dictionaries as suggested by you and @benedikt-richter. Keeping other things the same.

2022-09-27 10:43 UTC, benedikt-richter approved these changes

2022-09-27 13:23 UTC, vasily-pozdnyakov approved these changes

2022-09-27 13:27 UTC, merged