Introduce pie chart for most frequent licenses in signals in statisti…
opossum-tool/OpossumUI pull request #1016
Opened 2022-09-26 06:58 UTC by Billwuzl

### Summary of changes

Introduce pie chart for most frequent licenses in signals in statistic popup

### Context and reason for change

Created a function in project-statistics-popup-helpers.ts to obtain the most frequent licenses
Pie chart is created in PieCharts.tsx

Fix: #944

Signed-off-by: Billwuzl <wu.zhuolin2000@gmail.com>

Note: Please review the [guidelines for contributing](https://github.com/opossum-tool/OpossumUI/blob/main/CONTRIBUTING.md) to this repository.

2022-09-26 08:48 UTC, Billwuzl commented
I will try to fix the problems of overlapping texts in the pie chart and the failing test cases now

2022-09-26 10:17 UTC, vasily-pozdnyakov requested changes
* Can we have more space between license names?
![image](https://user-images.githubusercontent.com/85183359/192252183-07c81fe1-223d-45bf-b9b0-5e23daf4b878.png)


* If there are no licenses (very unlikely, but still) we see a lot of empty space
![image](https://user-images.githubusercontent.com/85183359/192237270-21067751-8d45-42a9-8532-a3f4e06249cb.png)

* Would be nice to add some testing.

2022-09-26 10:17 UTC, vasily-pozdnyakov commented on src/Frontend/Components/ProjectStatisticsPopup/PieCharts.tsx
> +            <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
Can we just use COLOR[index]?

2022-09-26 10:17 UTC, vasily-pozdnyakov commented on src/Frontend/Components/ProjectStatisticsPopup/PieCharts.tsx
> +// eslint-disable-next-line @typescript-eslint/no-explicit-any
Can we somehow avoid usage of it?

2022-09-26 10:17 UTC, vasily-pozdnyakov commented on src/Frontend/Components/ProjectStatisticsPopup/PieCharts.tsx
> +      <PieChart width={730} height={250}>
Such hard-coded values do not look good to me:) Can we use relative values?

2022-09-26 10:56 UTC, Billwuzl commented on src/Frontend/Components/ProjectStatisticsPopup/PieCharts.tsx
> +          fill="#8884d8"
actually we don't need this fill

2022-09-27 07:00 UTC, benedikt-richter commented
The warning of the kind 
```

FAIL src/Frontend/Components/AppContainer/__tests__/AppContainer.test.tsx
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /home/runner/work/OpossumUI/OpossumUI/node_modules/d3-shape/src/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){export {default as arc} from "./arc.js";


```

that cause the tests to fail, can be fixed by modifying the value of the key `"jest"` in `package.json` to be

```

  "jest": {
    "resetMocks": false,
    "transformIgnorePatterns": [
      "/node_modules/(?!d3-*|internmap)"
    ],
    "transform": {
      "/node_modules/(?!d3-*|internmap)": "babel-jest"
    }
  },

```

2022-09-27 09:02 UTC, Billwuzl commented
Now larger gaps between license names are created.

If there is no license, the pie chart will disappear now

2022-09-27 09:39 UTC, Billwuzl commented
Test Cases added

2022-09-27 13:37 UTC, vasily-pozdnyakov commented
General things:
* Margins before and after the pie chart are too big 
![image](https://user-images.githubusercontent.com/85183359/192540295-20988e45-41ff-44e4-8877-90c72df07ca7.png)

* It would be nice to have a positive test for the pie chart (when the ui actually renders it)

2022-09-28 08:15 UTC, antonbauhofer commented
The labels appear with a delay. Also, as pointed out before, the gaps between the fractions seem to be a bit big.
See screenshot:

<img width="1440" alt="Screenshot 2022-09-28 at 10 12 51" src="https://user-images.githubusercontent.com/48415604/192726126-797e2112-4ea5-4a08-b446-79640f8101db.png">

2022-09-28 08:30 UTC, antonbauhofer commented on src/Frontend/Components/ProjectStatisticsPopup/PieCharts.tsx
> +            cx="40%"
I would either put this to 50% to have it horizontally centered, or have it left aligned.

2022-09-28 08:30 UTC, antonbauhofer commented on src/Frontend/Components/ProjectStatisticsPopup/PieCharts.tsx
> +            paddingAngle={3}
I would prefer to have this set to 1, so that the distances between the fractions are reduced.

2022-09-28 08:56 UTC, antonbauhofer requested changes
Looks good so far.
I think the styling could be improved and some tests are missing.

2022-09-28 08:56 UTC, antonbauhofer commented on src/Frontend/Components/ProjectStatisticsPopup/PieCharts.tsx
> +function renderCustomizedLabel(props: PieLabelRenderProps): ReactElement {
Can you adjust the font to be the same as in the rest of the app?

2022-09-28 09:45 UTC, Billwuzl commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +export interface PieChartData {
I think we might keep all pie chart data formats the same, as the current format seems to be the only data format accepted by Recharts PieCharts. :)

2022-09-28 11:19 UTC, vasily-pozdnyakov commented
Good job. See comments from Toni. Need to do something with gaps before and after the chart: if there are no labels, the margins are too big.

2022-09-28 13:27 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/PieCharts.tsx
> +  props: AttributionCountPerSourcePerLicenseTableProps
Looks strange to use here the same props as for the table. The PieChart should have its own props.

2022-09-29 06:39 UTC, benedikt-richter commented
Currently, the PieChart component is customized to display the most common licenses. Before, introducing the next pie chart in project overview we should extract a generic component `PieChart` that lives at the same level as `ProjectStatisticsPopup` and has a interface that can also be used for following pie charts. Otherwise we would duplicate the code that is relevant for the display logic three times. This does not have to happen in this PR, though.

2022-09-29 12:10 UTC, Billwuzl commented on src/Frontend/Components/ProjectStatisticsPopup/PieCharts.tsx
> +  props: AttributionCountPerSourcePerLicenseTableProps
yeah. This will be fixed in the following PR if more pie charts are added

2022-09-29 13:11 UTC, Billwuzl commented on src/Frontend/Components/ProjectStatisticsPopup/__tests__/ProjectStatisticsPopup.test.tsx
> +    expect(screen.getByText('Most Frequent Licenses')).toBeInTheDocument();
Actually, this might be a bit hard. We can discuss this later 👍

2022-09-30 07:22 UTC, benedikt-richter commented on src/Frontend/Components/GlobalPopup/__tests__/GlobalPopup.test.tsx
> +import { mockResizeObserver } from '../../ProjectStatisticsPopup/__tests__/project-statistics-popup-helpers.test';
we should not import from one test to another.

2022-09-30 07:48 UTC, vasily-pozdnyakov approved these changes
From my side it looks fine, just please check ProjectStatisticsPopup.test.tsx for duplicating tests.
Final styling can be done later, when we have all functionality implemented.

2022-09-30 07:59 UTC, Billwuzl commented on src/Frontend/Components/GlobalPopup/__tests__/GlobalPopup.test.tsx
> +import { mockResizeObserver } from '../../ProjectStatisticsPopup/__tests__/project-statistics-popup-helpers.test';
I just realized that ProjectStatisticsPopup.test.tsx is the only file that needs to use mockResizeObserver.

2022-09-30 08:01 UTC, Billwuzl commented on src/Frontend/Components/GlobalPopup/__tests__/GlobalPopup.test.tsx
> +import { mockResizeObserver } from '../../ProjectStatisticsPopup/__tests__/project-statistics-popup-helpers.test';
but I think I will put mockResizeObserver in src/Frontend/test-helpers/popup-test-helpers.ts. Just in case we need this function again.

2022-09-30 13:07 UTC, benedikt-richter approved these changes

2022-09-30 13:38 UTC, antonbauhofer approved these changes
Looks good now and works well. Nice job!

2022-09-30 13:53 UTC, merged