Initial clean up of project statistics popup
opossum-tool/OpossumUI pull request #1053
Opened 2022-10-06 12:41 UTC by vasily-pozdnyakov

### Summary of changes

* Changes in styling
* Pie chart extracted into a separate component to use it for next pie charts
* Refactoring

### Context and reason for change

Need to prepare for introduction of more pie charts.

Initial fix #1011

Before:
![image](https://user-images.githubusercontent.com/85183359/194850006-6e3ecc08-81c5-43d7-b233-b53b55f49bbb.png)

After:
![image](https://user-images.githubusercontent.com/85183359/195036269-4afd53ff-d391-4ec8-83c0-4491388bd3a9.png)

2022-10-10 10:33 UTC, JakobSchubert commented
For changes in styling, before/after screenshots would be helpful for the reviewer.

2022-10-10 12:22 UTC, FlorianSchepers requested changes

2022-10-10 12:58 UTC, JakobSchubert approved these changes
Looks good. Some small remarks.

2022-10-10 12:58 UTC, JakobSchubert commented on src/Frontend/Components/ProjectStatisticsPopup/PieCharts.tsx
> +            outerRadius="70"
```suggestion
            outerRadius={70}
```
should also work and is more consistent with the other number values like `minAngle`.

2022-10-10 13:15 UTC, JakobSchubert commented on src/Frontend/enums/enums.ts
> +  AttributionCountByCriticalityPieChart = 'Attributions per Criticality',
To be more precise: `AttributionCountByCriticalityPieChart` is unused

2022-10-10 13:19 UTC, JakobSchubert commented
Optional remark: The legend for the pie chart is a bit far away from the actual pie chart. One could think about either moving it closer to the pie chart or adding a box around the whole (pie chart + legend) to make it clear to the viewer that the legend belongs to the pie chart.

2022-10-10 13:28 UTC, vasily-pozdnyakov commented on src/Frontend/Components/ProjectStatisticsPopup/CriticalLicensesTable.tsx
> +                  {columnName}
Actually here it is not really necessary, as there are only two defined columns, which are developer-defined.

2022-10-10 13:55 UTC, vasily-pozdnyakov commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> -export const TOTAL_COLUMN_NAME_IN_TABLE_Key = 'Total';
Honestly, I also do not get it. Will change.

2022-10-11 08:19 UTC, FlorianSchepers approved these changes

2022-10-11 08:26 UTC, merged