Highlight resources with critical licenses
opossum-tool/OpossumUI pull request #1065
Opened 2022-10-11 13:25 UTC by vasily-pozdnyakov

### Summary of changes

The icons indicating presence of signals are colored based on highest criticality for resources with critical signals and also their tooltip texts are modified.
Part of #1012

Before:
![image](https://user-images.githubusercontent.com/85183359/195102967-bb387adf-446d-45cc-b011-b7d8cea418e5.png)

After:
![image](https://user-images.githubusercontent.com/85183359/195103200-b1be83ed-affb-47ff-90a9-e952e29d067f.png)

2022-10-11 14:17 UTC, MarkusObendrauf requested changes

2022-10-11 14:17 UTC, MarkusObendrauf commented on src/Frontend/Components/Icons/Icons.tsx
> +      ? 'has highly critical signals'
imo 'has high criticality signals' would be clearer here (and below: 'has medium criticality signals')

2022-10-11 14:17 UTC, MarkusObendrauf commented on src/Frontend/Components/ResourceBrowser/get-tree-item-label.tsx
> +    for (const attribution of attributionsForResource) {
I find this a bit hard to follow. Suggestion:
```
for (const attribution of attributionsForResource) {
  if (externalAttributions[attribution].criticality === Criticality.High) {
    return Criticality.High
  }
}
```
followed by a similar loop for medium

2022-10-11 14:20 UTC, leslielazzarino requested changes

2022-10-11 14:20 UTC, leslielazzarino commented on src/Frontend/Components/Icons/Icons.tsx
> +    props.criticality === Criticality.High
I would replace this if with an object, it would be cleaner.

2022-10-11 14:20 UTC, leslielazzarino commented on src/Frontend/Components/Icons/Icons.tsx
> +            props.criticality === Criticality.High
Same here.

2022-10-11 14:20 UTC, leslielazzarino commented on src/Frontend/Components/ResourceBrowser/get-tree-item-label.tsx
> +function getCriticality(
This should be tested thoroughly.

2022-10-11 14:20 UTC, leslielazzarino commented on src/Frontend/Components/Icons/Icons.tsx
> +export function SignalIcon(props: SignalIconProps): ReactElement {
The behavior of this component should be tested.

2022-10-12 09:43 UTC, vasily-pozdnyakov commented on src/Frontend/Components/ResourceBrowser/get-tree-item-label.tsx
> +    for (const attribution of attributionsForResource) {
I got your point now, will do it.

2022-10-12 10:43 UTC, MarkusObendrauf approved these changes

2022-10-12 11:21 UTC, leslielazzarino approved these changes

2022-10-12 11:21 UTC, merged