Add Pie chart for signal numbers clustered by criticality
opossum-tool/OpossumUI pull request #1066
Opened 2022-10-11 14:20 UTC by someshkhandelia

### Summary of changes

Add Pie chart for signal numbers clustered by criticality

### Context and reason for change

- Use Accordion for better utilization of space, compactness, and prevent overcrowding of visual data.
- Accordion will permit addition of Pie charts to the popup in future without having to change the page styles or layout. Thus, it should be future-proof.
- Add expansion icon to Accordion to indicate when accordion is expanded. Better UX.
- Add function that provides the data needed by the new Pie chart.

Fix: #945

Signed-off-by: someshkhandelia <someshkhandelia@gmail.com>

2022-10-11 14:22 UTC, someshkhandelia commented
### Previously, the popup looked like this:
![image](https://user-images.githubusercontent.com/9270691/195051664-07cadee6-5a21-4242-a820-470c6a90950e.png)

### Now, the popup looks like this:
![image](https://user-images.githubusercontent.com/9270691/195113713-dea9d088-fadb-411f-8b6f-595034904eab.png)

![image](https://user-images.githubusercontent.com/9270691/195114172-673dd824-35b8-456d-9ce6-6e2e4a2686ac.png)

![image](https://user-images.githubusercontent.com/9270691/195114402-1e68dd28-968c-40c8-aa02-5d627fd22500.png)

![image](https://user-images.githubusercontent.com/9270691/195114652-041aac8a-fd2d-4b6e-8586-9d8f18bc56f0.png)

2022-10-12 07:57 UTC, someshkhandelia commented
Interesting to note, that the following test is failing:
![image](https://user-images.githubusercontent.com/9270691/195283312-6509acee-a64f-407b-9eaf-b4b9d3d6826b.png)

with the error:
![image](https://user-images.githubusercontent.com/9270691/195283799-cfd475e0-d795-461c-8e30-303f2498ee91.png)

However, commenting out the Accordion components in statistics popup, makes the test pass:
![image](https://user-images.githubusercontent.com/9270691/195284229-3ff3aaca-ea83-4637-b259-2f2ad01b1686.png)

2022-10-12 08:26 UTC, someshkhandelia commented
Checking https://github.com/maslianok/react-resize-detector/issues/217 for https://github.com/opossum-tool/OpossumUI/pull/1066#issuecomment-1275748639

2022-10-12 14:21 UTC, vasily-pozdnyakov commented
Some design points:
* "Other" color is not really good on this background
* Critical signals pie chart has no highly critical signals, but the legend has.
* Both pie charts should have equal margin on left
* The both pie charts (especially critical signals) have too big margins on top and bottom.
* Pie charts title bars have different height when accordeon is opened and closed. Probably it should be equal to table headers.
* Accordeons are too wide on wide screens
* It will unlikely be the case, but when there are no signals Critical signals pie chart (empty) still exists (see picture 2)

![image](https://user-images.githubusercontent.com/85183359/195364406-bb76978f-cd64-44e0-bd50-781709e1747b.png)
**Picture 2**
![image](https://user-images.githubusercontent.com/85183359/195367559-e9648f8a-19ae-43be-9d93-5ebeb1875068.png)

2022-10-12 14:26 UTC, someshkhandelia commented
Regarding https://github.com/opossum-tool/OpossumUI/pull/1066#issuecomment-1276262826, @vasily-pozdnyakov can you please tell which input files have you used for generating the two pictures?

2022-10-12 15:07 UTC, leslielazzarino requested changes
Tests are missing.
**Answer by someshkhandelia** : Tests have been added.

2022-10-12 16:08 UTC, vasily-pozdnyakov requested changes

2022-10-12 16:08 UTC, vasily-pozdnyakov commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +  }
Please unify it with the lines 147-153, where we also count critical licenses, and extract into a separate function.

2022-10-12 16:08 UTC, vasily-pozdnyakov commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +  let countNoCriticalitySignals = 0;
You can replace all of them with one object
`const criticalityData = [{ name: 'High', count: 0 }, { name: 'Medium', count: 0 }, { name: 'Not critical', count: 0 }]`

2022-10-13 09:19 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +  const noCriticalitySectionName = 'Not Critical';
Done.

2022-10-13 09:20 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +  let countNoCriticalitySignals = 0;
Combined with https://github.com/opossum-tool/OpossumUI/pull/1066#discussion_r993465586.
Done.

2022-10-13 09:21 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +      if (licenseNamesWithCriticality[license] === Criticality.High) {
Combined with https://github.com/opossum-tool/OpossumUI/pull/1066#discussion_r993650984
Done.

2022-10-13 09:21 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +  }
Combined with https://github.com/opossum-tool/OpossumUI/pull/1066#discussion_r993464251
Done.

2022-10-13 09:24 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/ProjectStatisticsPopup.tsx
> +              </MuiTypography>
Keeping the title for two reasons:
- All other sections have a title (uniformity)
- Tells the user, what the section is about (e.g. the content below is all pie charts)

2022-10-13 09:52 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/AccordionWithPieChart.tsx
> +  props: PieChartProps
Done.

2022-10-13 09:52 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/PieCharts.tsx
>            <Pie
Done.

2022-10-13 09:52 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/AccordionWithPieChart.tsx
> +        <CustomizedPieChart data={props.data} title={props.title} />
Done.

2022-10-13 09:54 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/PieCharts.tsx
>    title: string;
Fixed.

2022-10-13 12:29 UTC, someshkhandelia commented on setupTests.ts
> +window.ResizeObserver = require('resize-observer-polyfill')
Fixed.

2022-10-14 09:52 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +export function getCriticalSignalsCount(
Added tests.

2022-10-14 11:32 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/AccordionWithPieChart.tsx
> +export function AccordionWithPieChart(
Added tests.

2022-10-14 12:28 UTC, vasily-pozdnyakov commented
* I would keep legends on right side, because it is more readable if we have long license names.
* Red and orange colors on Most Frequent Licenses can be confusing as we use the colors for criticality as well.
* Critical signals should be colored consistently (I guess high = orange, medium=lighOrange, none=darkBlue) - see Critical Licenses table.
![image](https://user-images.githubusercontent.com/85183359/195846142-1a8a2623-bd1b-44a4-8bec-d2ced8943077.png)

2022-10-14 13:12 UTC, vasily-pozdnyakov commented on src/Frontend/Components/ProjectStatisticsPopup/PieCharts.tsx
>    title: string;
now we need it again:)

2022-10-14 14:06 UTC, vasily-pozdnyakov reviewed
Good job, just small comments.
**Answer by someshkhandelia** : Thanks!

2022-10-14 14:06 UTC, vasily-pozdnyakov commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +function signalCountIncrementor(
Propose to rename it to something like "criticalSignals..."

2022-10-14 14:06 UTC, vasily-pozdnyakov commented on src/Frontend/Components/ProjectStatisticsPopup/AccordionWithPieChart.tsx
> +import { projectStatisticsPopupClasses } from './shared-project-statistics-popup-styles';
move it down, after the components import.

2022-10-14 14:41 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +function signalCountIncrementor(
Fixed.

2022-10-14 14:42 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/AccordionWithPieChart.tsx
> +import { projectStatisticsPopupClasses } from './shared-project-statistics-popup-styles';
Fixed.

2022-10-14 15:54 UTC, vasily-pozdnyakov requested changes

2022-10-14 15:54 UTC, vasily-pozdnyakov commented on src/Frontend/Components/ProjectStatisticsPopup/PieCharts.tsx
> +const mostFrequentLicensesPieChartColors = [
Propose to use it as default values. Propose the following color schema:
`const defaultPieChartColors = [
  'purple',
  OpossumColors.brown,
  OpossumColors.green,
  OpossumColors.darkBlue,
  OpossumColors.pastelRed,
  OpossumColors.disabledGrey,
];`

2022-10-14 15:54 UTC, vasily-pozdnyakov commented on src/Frontend/Components/ProjectStatisticsPopup/PieCharts.tsx
> +const defaultPieChartColors = [
Use this structure instead
`const criticalColors: { [criticality: string]: string } = {
  High: OpossumColors.orange,
  Medium: OpossumColors.mediumOrange,
  'Not critical': OpossumColors.darkBlue,
};`

2022-10-14 15:54 UTC, vasily-pozdnyakov commented on src/Frontend/Components/ProjectStatisticsPopup/PieCharts.tsx
> +              <Cell key={`cell-${index}`} fill={colorsForPieChart[index]} />
Use this
`fill={
                  props.title ===
                  ProjectStatisticsPopupTitle.CriticalSignalsCountPieChart
                    ? criticalColors[record.name]
                    : defaultPieChartColors[index]
                }`

2022-10-14 15:54 UTC, vasily-pozdnyakov commented on src/Frontend/Components/ProjectStatisticsPopup/PieCharts.tsx
>    }
Made a proposal how to get rid of this logic.

2022-10-14 15:54 UTC, vasily-pozdnyakov commented on src/Frontend/Components/ProjectStatisticsPopup/PieCharts.tsx
>            <Tooltip />
<Legend verticalAlign="middle" align="right" layout="vertical" width={200}/>

2022-10-14 15:54 UTC, vasily-pozdnyakov commented on src/Frontend/Components/ProjectStatisticsPopup/shared-project-statistics-popup-styles.ts
> +    maxWidth: '500px',
Make it 600

2022-10-17 10:13 UTC, leslielazzarino requested changes

2022-10-17 10:13 UTC, leslielazzarino commented on src/Frontend/Components/ProjectStatisticsPopup/__tests__/project-statistics-popup-helpers.test.tsx
> +  it('counts number of critical signals across all licenses - testAttributions_3', () => {
However, I see this all testing file is filled with anti-patterns. Further fixes shouldn't be done in this RP, it is already too big, I will create new issues for that

2022-10-17 10:13 UTC, leslielazzarino commented on src/Frontend/Components/ProjectStatisticsPopup/PieCharts.tsx
> +export function CustomizedPieChart(props: PieChartProps): ReactElement {
File and component should have the same name. Rename the file.

2022-10-17 11:06 UTC, benedikt-richter commented
> ### Failing test case - solved
> 
> [#1066 (comment)](https://github.com/opossum-tool/OpossumUI/pull/1066#issuecomment-1275748639) was solved by adding the ResizeObserver package(https://yarnpkg.com/package/resize-observer-polyfill): `yarn add resize-observer-polyfill`
> 
> and then including the following line in `setupTests.ts`: ![image](https://user-images.githubusercontent.com/9270691/195296650-7bffe516-43fc-4818-aae9-70cced8ee85e.png)

From https://developer.mozilla.org/en-US/docs/Glossary/Polyfill?retiredLocale=de : A polyfill is a piece of code (usually JavaScript on the Web) used to provide modern functionality on older browsers that do not natively support it.

We are not in this case (we are using a quite recent version of chromium).

Please, check `mockResizeObserver` in `src/Frontend/test-helpers/popup-test-helpers.ts` for a different (already existing solution).

2022-10-18 07:50 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/PieCharts.tsx
> +const mostFrequentLicensesPieChartColors = [
Done.

2022-10-18 07:50 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/PieCharts.tsx
> +const defaultPieChartColors = [
Done. Thanks.

2022-10-18 07:50 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/PieCharts.tsx
> +              <Cell key={`cell-${index}`} fill={colorsForPieChart[index]} />
Done. Thanks.

2022-10-18 07:51 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/PieCharts.tsx
>    }
Followed proposal. Thanks.

2022-10-18 07:52 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/shared-project-statistics-popup-styles.ts
> +    maxWidth: '500px',
Done.

2022-10-18 07:54 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/PieCharts.tsx
> +        switch (criticalityNameAndCount['name']) {
Yes. Fixed.

2022-10-18 07:56 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/PieCharts.tsx
>            <Tooltip />
Done.

2022-10-18 07:58 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/__tests__/project-statistics-popup-helpers.test.tsx
> +  it('counts number of critical signals across all licenses - testAttributions_3', () => {
Removed the two previous tests. Thank you for explanation.

2022-10-18 07:58 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +    }
Done. Understood.

2022-10-18 07:59 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/PieCharts.tsx
> +export function CustomizedPieChart(props: PieChartProps): ReactElement {
Done.

2022-10-18 09:12 UTC, vasily-pozdnyakov approved these changes
Just one small thing. The rest looks fine.

2022-10-18 09:12 UTC, vasily-pozdnyakov commented on src/Frontend/Components/ProjectStatisticsPopup/CustomizedPieChart.tsx
> +            width={200}
If it is possible, please slightly increase the size of the legend (width=250 maybe), because 200px is not enough for "Apache License Version 2.0".=)

2022-10-18 09:30 UTC, leslielazzarino requested changes

2022-10-18 09:30 UTC, leslielazzarino commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +      licenseCriticalityCounts = criticalSignalsCountingHelper(
I think this helper function just makes the code more difficult to understand. You should just replace it with:
`licenseCriticalityCounts[attributions[attributionId].criticality || 'none']++`

2022-10-18 09:30 UTC, leslielazzarino commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +      licenseCriticalityCounts = criticalSignalsCountingHelper(
Same here.

2022-10-18 09:30 UTC, leslielazzarino commented on src/Frontend/Components/ProjectStatisticsPopup/AccordionWithPieChart.tsx
> +    <MuiAccordion sx={projectStatisticsPopupClasses.accordion} disableGutters>
As there is now enough space for both of them to be open set them as expanded from the beginning.

2022-10-18 09:48 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +      licenseCriticalityCounts = criticalSignalsCountingHelper(
Minor correction to your suggestion, in this case:
`licenseCriticalityCounts[licenseNamesWithCriticality[license] || 'none'] += attributionCountPerSourcePerLicense[license][SOURCE_TOTAL]`

since we are not incrementing by 1 like previous case.

2022-10-18 09:56 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/CustomizedPieChart.tsx
> +            width={200}
Done.

2022-10-18 09:56 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +      licenseCriticalityCounts = criticalSignalsCountingHelper(
Done.

2022-10-18 09:57 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +      licenseCriticalityCounts = criticalSignalsCountingHelper(
Done.

2022-10-18 10:03 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/AccordionWithPieChart.tsx
> +    <MuiAccordion sx={projectStatisticsPopupClasses.accordion} disableGutters>
As per verbal discussion, keeping it same for now.

2022-10-18 11:33 UTC, leslielazzarino approved these changes

2022-10-18 11:35 UTC, merged