Refactor Customized Pie Chart
opossum-tool/OpossumUI pull request #1094
Opened 2022-10-20 11:10 UTC by someshkhandelia

### Summary of changes

Refactor Customized Pie Chart

### Context and reason for change

- Make pie chart a top level component.
- Keep color logic outside component.

Fix: #1078

Signed-off-by: someshkhandelia <someshkhandelia@gmail.com>

2022-10-20 11:34 UTC, someshkhandelia commented
Currently the tests for the top level core component are missing. Will add those later.
Please review other changes.

2022-10-20 14:55 UTC, benedikt-richter requested changes
Consider the review comments for a more strict separation of data and color.

**Answered by someshkhandelia**: Done.

2022-10-20 14:55 UTC, benedikt-richter commented on src/Frontend/Components/CustomizedPieChart/CustomizedPieChart.tsx
> +export interface PieChartDataWithColor {
here we mix data and representation (in particular, in the location where this data(with colors) is calculated.

2022-10-20 14:55 UTC, benedikt-richter commented on src/Frontend/Components/CustomizedPieChart/CustomizedPieChart.tsx
>  interface PieChartProps {
I'd suggest the following interface for the pie chart:

```
interface PieChartProps {
segments: Array<{  
  name: string;
  count: number;
  }>;
colors?: { [name: string]: string }
}
```

This had the advantage that data `segements` and representation/display `colors` is separated. `colors`establishes a map between the names of the segments and their colors. If none is provided the default colors are used.
The `colors` would then be configured in e.g. `AccordionWithPieChart`.

2022-10-20 14:55 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
>  export function getMostFrequentLicenses(
Here getting the data and their appearance (color) is intertwined. The colors for the individual segaments should be kept as configuration (as suggested above). Here it is difficult to see which data gets which color, as it depends on the relative ordering of two arrays.

2022-10-20 15:36 UTC, vasily-pozdnyakov requested changes

2022-10-20 15:36 UTC, vasily-pozdnyakov commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +  return criticalityData.filter(
Good idea.

2022-10-20 15:36 UTC, vasily-pozdnyakov commented on src/Frontend/Components/CustomizedPieChart/customized-pie-chart-helpers.ts
> +export function addColorToPieChartData(
Not sure that we need the helper and the function. It can be done as a part of getMostFrequentLicenses.

2022-10-25 08:26 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/AccordionWithPieChart.tsx
> +        <CustomizedPieChart data={props.data} />
The original component from recharts is also called PieChart. We import that and create our component on top of it. Thus, this name is creating errors.

2022-10-25 08:50 UTC, someshkhandelia commented on src/Frontend/Components/CustomizedPieChart/CustomizedPieChart.tsx
>  interface PieChartProps {
Cannot use "colors?" since this will be used for mapping colors in the pie chart, and a variable that can be None, cannot be iterated upon.

2022-10-25 09:12 UTC, someshkhandelia commented on src/Frontend/Components/CustomizedPieChart/CustomizedPieChart.tsx
>  interface PieChartProps {
Using slightly different.

2022-10-25 09:12 UTC, someshkhandelia commented on src/Frontend/Components/CustomizedPieChart/CustomizedPieChart.tsx
> +export interface PieChartDataWithColor {
changed.

2022-10-25 09:13 UTC, someshkhandelia commented on src/Frontend/Components/CustomizedPieChart/CustomizedPieChart.tsx
>  interface PieChartProps {
![image](https://user-images.githubusercontent.com/9270691/197734166-e568537f-6196-411c-a9e3-760cb1ea1257.png)

2022-10-25 09:18 UTC, someshkhandelia commented on src/Frontend/Components/CustomizedPieChart/customized-pie-chart-helpers.ts
> +export function addColorToPieChartData(
Keeping the helper as it was suggested to not add color logic in the data function. Will use helper to add colours.

2022-10-25 09:20 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
>  export function getMostFrequentLicenses(
The data varies, and therefore having a manual config. (map) from license name -> color is not possible...in some cases we have over 100s of licenses that are merged to form "Others" segment in PieChart.

2022-10-25 09:27 UTC, someshkhandelia commented on src/Frontend/Components/CustomizedPieChart/CustomizedPieChart.tsx
>  interface PieChartProps {
Colors are now being configured in `AccordionWithPieChart` as suggested by you.

2022-10-25 09:33 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
>  export function getMostFrequentLicenses(
WIll have a helper function that 'colorises' the data.

2022-10-25 11:13 UTC, someshkhandelia commented on src/Frontend/Components/CustomizedPieChart/CustomizedPieChart.tsx
>  interface PieChartProps {
Had verbal discussion with @benedikt-richter. Marking resolved.

2022-10-25 12:33 UTC, benedikt-richter requested changes

2022-10-25 12:33 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +    (criticalityDataWithCountAndColor) =>
`...AndColor`?

2022-10-25 12:33 UTC, benedikt-richter commented on src/Frontend/Components/PieChart/pie-chart-helpers.ts
> +import { defaultPieChartColors, PieChartData } from './PieChart';
as `defaultPieChartColors ` is only used here it should be defined here and not imported

2022-10-25 12:33 UTC, benedikt-richter commented on src/Frontend/Components/PieChart/pie-chart-helpers.ts
> +  pieChartColorScheme: string | undefined
`pieChartColorScheme` should take values in an enum.

2022-10-25 12:33 UTC, benedikt-richter commented on src/Frontend/Components/PieChart/pie-chart-helpers.ts
> +  pieChartColorScheme: string | undefined
use a default value here. E.g. `pieChartColorScheme = PieChartColorScheme.Default`

2022-10-25 12:33 UTC, benedikt-richter commented on src/Frontend/Components/PieChart/pie-chart-helpers.ts
> +          case 'High':
where does is magic string `'High'` come from?

2022-10-25 12:33 UTC, benedikt-richter commented on src/Frontend/Components/PieChart/pie-chart-helpers.ts
> +    case 'critical':
as suggested above, this should be an enum

2022-10-25 12:33 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/AccordionWithPieChart.tsx
> +import { getColorsForPieChart } from '../PieChart/pie-chart-helpers';
the helpers of a component should not importend in another component

2022-10-25 12:33 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/AccordionWithPieChart.tsx
> +  colorScheme?: string;
having this here, there can never be piecharts with different schemes...

2022-10-25 13:01 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +    (criticalityDataWithCountAndColor) =>
fixed.

2022-10-25 13:04 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +import { PieChartData } from '../PieChart/PieChart';
No, it is used by functions that return data for the PieChart.

2022-10-25 13:05 UTC, someshkhandelia commented on src/Frontend/Components/PieChart/pie-chart-helpers.ts
> +import { defaultPieChartColors, PieChartData } from './PieChart';
Fixed.

2022-10-25 13:10 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/AccordionWithPieChart.tsx
> +  colorScheme?: string;
For a pie chart, there are two things:
1. data
2. colors

color scheme is not for a pie chart to understand. It understands only the data and color you provide it. 

color scheme is for Pie charts specifically in statisitics popup -> accoordions (because here you have critical pie chart etc.)

2022-10-25 13:26 UTC, someshkhandelia commented on src/Frontend/Components/PieChart/pie-chart-helpers.ts
> +  pieChartColorScheme: string | undefined
schemes not used anymore.

2022-10-25 13:26 UTC, someshkhandelia commented on src/Frontend/Components/PieChart/pie-chart-helpers.ts
> +    case 'critical':
schemes not used anymore.

2022-10-25 13:29 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/AccordionWithPieChart.tsx
> +  colorScheme?: string;
schemes not used anymore.

2022-10-25 13:35 UTC, someshkhandelia commented on src/Frontend/Components/PieChart/pie-chart-helpers.ts
> +          case 'High':
Fixed.

2022-10-25 15:00 UTC, vasily-pozdnyakov requested changes
Should we also extract AccordionWithPieChart into a separate top-level component?

2022-10-25 15:00 UTC, vasily-pozdnyakov commented on src/Frontend/enums/enums.ts
> +export enum CriticalityTypes {
We have Criticality in shared-types (src\shared\shared-types.ts), can we use that one (maybe with some modifications)?

2022-10-25 15:00 UTC, vasily-pozdnyakov commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +export function getColorsForPieChart(
Should test the function.

2022-10-25 15:00 UTC, vasily-pozdnyakov commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +  switch (pieChartTitle) {
We do not really need the outer switch, as there are only two options. Use if-statement.

2022-10-25 15:00 UTC, vasily-pozdnyakov commented on src/Frontend/Components/PieChart/PieChart.tsx
> +export function PieChart(props: PieChartProps): ReactElement {
Should test the component separately, see #1078, point 2.

2022-10-25 15:09 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +export function getColorsForPieChart(
https://github.com/opossum-tool/OpossumUI/pull/1094#issuecomment-1285374089

2022-10-25 15:09 UTC, someshkhandelia commented on src/Frontend/Components/PieChart/PieChart.tsx
> +export function PieChart(props: PieChartProps): ReactElement {
https://github.com/opossum-tool/OpossumUI/pull/1094#issuecomment-1285374089

2022-10-26 06:31 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/AccordionWithPieChart.tsx
> +  colorScheme?: string;
> having this here, there can never be piecharts with different schemes...

Actually I misunderstund the accordion. It is always a single one with a single pie chart. So the comment does not apply.

2022-10-26 06:56 UTC, benedikt-richter requested changes

2022-10-26 06:56 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +export const defaultPieChartColors = [
The default colors should be defined and used in the pie chart component. The property `color`should be optional and if no colors are provided the default ones are used.

2022-10-26 06:56 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +      break;
This case is not needed anymore when default colors are applied by component by default

2022-10-26 06:56 UTC, benedikt-richter commented on src/Frontend/enums/enums.ts
> +export enum CriticalityTypes {
Here the enum is actually used to store the values displayed to the user. Therefore, it is different from the other enum we use to store values of criticality.

2022-10-26 10:59 UTC, benedikt-richter approved these changes
Actually, this pr does already get quite some things done. THe remaining points are not too crucial for me.

2022-10-26 12:14 UTC, benedikt-richter requested changes
Tests missing

**Answered by someshkhandelia**: Added tests for the new function. Need help in writing tests for the component since it might need Redux.

2022-10-31 08:54 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +  switch (pieChartTitle) {
Fixed.

2022-10-31 08:54 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +export const defaultPieChartColors = [
Fixed.

2022-10-31 08:56 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +      break;
Fixed.

2022-11-02 07:06 UTC, benedikt-richter requested changes
Just added two comments regarding the tests.
I think the test coverage is ok. I don't think a test involving the state (redux) is required here.

**Answered by someshkhandelia**: Do we want to add tests for the new component "PieChart"? I thought that might need Redux.

**Answered by someshkhandelia**: [EDIT] as per verbal discussions with @benedikt-richter and @vasily-pozdnyakov, it was agreed upon that this component can be left without any explicit tests for now. Reason being complications with ResizeObserver and that the component itself doesn't have too much logic in it.

2022-11-02 08:29 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/__tests__/project-statistics-popup-helpers.test.tsx
> +    );
Fixed.

2022-11-02 08:29 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/__tests__/project-statistics-popup-helpers.test.tsx
> +    );
Fixed.

2022-11-02 08:45 UTC, vasily-pozdnyakov requested changes

2022-11-02 08:45 UTC, vasily-pozdnyakov commented on src/Frontend/Components/PieChart/__tests__/PieChart.test.tsx
> +  });
You are missing some assertion (expect) part here, see ProjectStatisticsPopup.test.tsx for example.

2022-11-02 08:45 UTC, vasily-pozdnyakov commented on src/Frontend/Components/PieChart/PieChart.tsx
> +            outerRadius={70}
I would turn off animation, as the accordion is initially collapsed.

2022-11-02 08:51 UTC, someshkhandelia commented on src/Frontend/Components/PieChart/PieChart.tsx
> +            outerRadius={70}
I had removed the `isAnimationActive={true}` flag so that there won't be any animation. Guess I will just try to explicitly set it to `false`.

2022-11-02 08:58 UTC, someshkhandelia commented on src/Frontend/Components/PieChart/PieChart.tsx
> +            outerRadius={70}
Fixed.

2022-11-02 09:29 UTC, someshkhandelia commented on src/Frontend/Components/PieChart/__tests__/PieChart.test.tsx
> +  });
As discussed verbally, we are removing the tests for the component.

2022-11-02 09:52 UTC, benedikt-richter approved these changes

2022-11-02 10:00 UTC, vasily-pozdnyakov approved these changes

2022-11-02 10:03 UTC, merged