Include pie chart with incomplete attributions
opossum-tool/OpossumUI pull request #1097
Opened 2022-10-22 13:55 UTC by vasily-pozdnyakov

### Summary of changes
Included pie chart and corresponding tests.
Fix #946

2022-10-25 06:35 UTC, benedikt-richter commented
Please fill all required fields of the pull request description

2022-10-25 07:44 UTC, benedikt-richter requested changes

2022-10-25 07:44 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +  if (numberOfAttributions - numberOfIncompleteAttributions !== 0) {
why do we need this? Can't we just put the number 0 in the data?

2022-10-25 07:44 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +export function getIncompleteAttributions(
This function should be renamed as it does not return attributions

2022-10-25 07:44 UTC, benedikt-richter commented on src/Frontend/enums/enums.ts
> +  IncompleteLicensesPieChart = 'Incomplete attributions',
`'Incomplete attributions'` -> `'Incomplete Attributions'`

2022-10-25 07:44 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/ProjectStatisticsPopup.tsx
> +  ).length;
This should go into `getIncompleteAttributions`

2022-10-25 07:44 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/ProjectStatisticsPopup.tsx
> +  const manualAttributionValues = Object.values(attributions);
I'd suggest to only use `attributions` and not have a second constant next to it that contains parts of the other one.

2022-10-25 07:44 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/ProjectStatisticsPopup.tsx
> +  const manualAttributionValues = Object.values(attributions);
`aggregateAttributionPropertiesFromAttributions` should accept attributions

2022-10-25 07:44 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/__tests__/ProjectStatisticsPopup.test.tsx
> +          externalAttributions: testAttributions,
better to have `testExternalAttributions` and `testManualAttributions` separately.

2022-10-25 07:44 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/__tests__/ProjectStatisticsPopup.test.tsx
> +  it('does not render pie charts when there are no attributions', () => {
I guess there should be the pie charts related to signals even if there are not attributions

2022-10-25 07:44 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/__tests__/ProjectStatisticsPopup.test.tsx
> -  it('renders the Critical Signals pie chart when there are attributions', () => {
why are these tests removed?

2022-10-25 07:45 UTC, benedikt-richter commented on src/Frontend/enums/enums.ts
> +  PieChartsSectionHeader = 'View Pie Charts',
why does the header contain the word "View"?

2022-10-25 08:04 UTC, vasily-pozdnyakov commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +  if (numberOfAttributions - numberOfIncompleteAttributions !== 0) {
In this case the pie chart will be not good: there will be no sector with this data, but the field will still be in the legend.

2022-10-25 08:09 UTC, vasily-pozdnyakov commented on src/Frontend/Components/ProjectStatisticsPopup/__tests__/ProjectStatisticsPopup.test.tsx
> -  it('renders the Critical Signals pie chart when there are attributions', () => {
This is because all the pie chart tests are exactly the same, so I merged them into one (see line 54).

2022-10-25 16:29 UTC, alexzurbonsen commented on src/Frontend/enums/enums.ts
> +  PieChartsSectionHeader = 'Pie Charts',
Not important, just wondering: was the section header changed on purpose or should it still be "View Pie Charts" as in the screen shot shown in the summary?

2022-10-26 06:02 UTC, benedikt-richter approved these changes

2022-10-26 10:19 UTC, vasily-pozdnyakov commented on src/Frontend/enums/enums.ts
> +  PieChartsSectionHeader = 'Pie Charts',
It was one of the comments of the second reviewer, decided to change it.

2022-10-26 14:20 UTC, merged