Improve styling of PieChart
opossum-tool/OpossumUI pull request #1121
Opened 2022-11-02 16:07 UTC by someshkhandelia

### Summary of changes

Improve styling of PieChart

### Context and reason for change

- Updated overall colors.
- Updated tooltip.

Fix: #1092

Signed-off-by: someshkhandelia <someshkhandelia@gmail.com>

2022-11-02 16:10 UTC, someshkhandelia commented
### Previously
![Screenshot 2022-10-19 at 11 38 10](https://user-images.githubusercontent.com/46576389/196655615-ebbc3571-d3c6-4b85-bc39-381854896ed4.png)

### Now
After the recent changes, it looks like this:
(P.S. The font of the legend cannot be changed. There is no way to specify it in the 3rd party API call.)

![image](https://user-images.githubusercontent.com/9270691/199539192-42be52ac-42f8-445a-a828-f8b90d1b2218.png)

2022-11-03 15:24 UTC, vasily-pozdnyakov commented
In my opinion the colors are too bright. Also not sure that it is a good idea to use criticality colors (opossum.orange) for other pie charts.

2022-11-04 08:57 UTC, someshkhandelia commented on src/Frontend/Components/PieChart/PieChart.tsx
> +            iconSize={5}
Thanks @alexzurbonsen. I missed that, will change.

2022-11-07 07:48 UTC, leslielazzarino commented
The orange is almost inpossible to read on my screen, it should be replaced.

2022-11-07 07:50 UTC, leslielazzarino requested changes
Replace hard to read color.

**Answered by @someshkhandelia**: Fixed.

2022-11-07 19:45 UTC, alexzurbonsen commented on src/Frontend/Components/PieChart/PieChart.tsx
> +            iconSize={5}
Thank you :)

2022-11-08 07:10 UTC, benedikt-richter requested changes
Looks much more consistent with other components now 👍 
As Alex pointed out the font of the legend is to be changed

2022-11-09 09:42 UTC, someshkhandelia commented
After the latest changes, the PieCharts look like this:

![image](https://user-images.githubusercontent.com/9270691/200795418-d5af0f64-6f00-4972-a05f-03b3ad27c4a2.png)

![image](https://user-images.githubusercontent.com/9270691/200795756-9fdd43f0-c26c-4789-8a66-e4ad4300d704.png)

2022-11-09 10:55 UTC, benedikt-richter approved these changes

2022-11-09 14:52 UTC, alexzurbonsen approved these changes

2022-11-10 06:57 UTC, leslielazzarino approved these changes

2022-11-10 06:57 UTC, merged