Refactor Tests for statistics popup helpers
opossum-tool/OpossumUI pull request #1165
Opened 2022-11-17 12:13 UTC by someshkhandelia

### Summary of changes

Refactor Tests for statistics popup helpers

### Context and reason for change

 - Have separate tests to check different behaviours of a function.
 - Refactor existing tests to have a more clear workflow.
 - Add dedicated tests for all functions that exist in the helper file. 

Fix: #1079

Signed-off-by: someshkhandelia <someshkhandelia@gmail.com>

2022-11-17 12:23 UTC, benedikt-richter requested changes
This is a first round of review. Will look at the actual test implementations later.

2022-11-17 12:23 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +export const UNKNOWN_SOURCE_PLACEHOLDER = '-';
This constant should not be exported for testing. Better to hardcode it in tests.

2022-11-17 12:23 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +export function getSourceDisplayNameFromId(
We should not export functions only to test them (except there are really good reasons). 
Functions that are not exported can be considered implementation details. These functions are tested implicitly in the tests of the functions that are exported.

2022-11-17 12:23 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/__tests__/project-statistics-popup-helpers.test.tsx
> +  it('counts only incomplete attributions', () => {
Typically we have empty lines between tests

2022-11-17 12:23 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/ProjectStatisticsPopup.tsx
> -  const sortedManualAttributionPropertyCountsEntries =
👍

2022-11-17 12:23 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/__tests__/project-statistics-popup-helpers.test.tsx
>  const attributionSources = {
All constants in tests should have an explicit type: `const attributionSources: Type = {`
This helps a lot during refactorings.

2022-11-21 14:30 UTC, MarkusObendrauf requested changes
Looks a lot better!

**Answered by @someshkhandelia**: Thank you @MarkusObendrauf

2022-11-21 14:30 UTC, MarkusObendrauf commented on src/Frontend/Components/ProjectStatisticsPopup/__tests__/project-statistics-popup-helpers.test.tsx
> +      'themitlicense(mit)': ['uuid2', 'uuid5'],
There should definitely be a test the grouping though. Eg. test that "Apache License 2.0" is the same as "aPaChE lIcEnSe 2.0" but not "Apache License 3.0"

2022-11-21 14:30 UTC, MarkusObendrauf commented on src/Frontend/Components/ProjectStatisticsPopup/__tests__/project-statistics-popup-helpers.test.tsx
> +  it('get valid display name, for example firstParty', () => {
remove "for example firstParty"

2022-11-23 08:10 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +export const UNKNOWN_SOURCE_PLACEHOLDER = '-';
Had not hardcoded it and reused it so that if the value is changed, the test is auto-updated. But I understand your point, the test should then fail and we should not mask any changes done in the code.

2022-11-23 08:22 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +export const UNKNOWN_SOURCE_PLACEHOLDER = '-';
Fixed.

2022-11-23 08:22 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/__tests__/project-statistics-popup-helpers.test.tsx
> +  it('counts only incomplete attributions', () => {
Fixed.

2022-11-23 08:23 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/ProjectStatisticsPopup.tsx
> -  const sortedManualAttributionPropertyCountsEntries =
Thanks.

2022-11-23 08:25 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> -
Yeah. Thanks.

2022-11-23 08:32 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +export function getSourceDisplayNameFromId(
Do not completely agree with you here. It may go against the spirit of unit testing where every function should be tested.
What can be done is to follow a convention (like we do in Python), whereby we can begin a function name with underscore '_' to indicate it is private and should never be exported. If this is not the case, all other functions should be part of unit testing.

2022-11-23 08:54 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/__tests__/project-statistics-popup-helpers.test.tsx
> +  it('Obtain license information from attribution id', () => {
Makes sense. Good point. Fixed. Thanks.

2022-11-23 08:58 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/__tests__/project-statistics-popup-helpers.test.tsx
> +  it('counts only incomplete attributions', () => {
Further improved: kept separation between between 3 distinct parts of a test, namely "test data", "call to tested function", and the "expect statements". All tests now follow the same structure.

2022-11-23 09:07 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +export function getSourceDisplayNameFromId(
I do not agree that testing ALL functions is the best way to write tests. Actually testing implementation details has serious drawbacks. Maybe you can convince me that I'm wrong and that the advantages outweight the disadvantages. Otherwise, I would like to stick to the typical pattern for writing tests that we use (almost) consistently in the project.

2022-11-23 09:08 UTC, benedikt-richter requested changes
see comment on testing

**Answered by @someshkhandelia**: can appreciate the point made by you. Will find some optimal solution instead of extreme one (don't test any/ test ALL). Please see reply to comment as well.

2022-11-23 09:28 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +export function getSourceDisplayNameFromId(
Ok. I agree with you. Maybe ALL functions is not a good idea. Will try to find an optimal solution (test some and not test others). I think some functions might need to be tested (even if they are not being explicitly exported)

2022-11-23 09:38 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/__tests__/project-statistics-popup-helpers.test.tsx
> +  it('obtain ScanCode display name', () => {
Fixed.

2022-11-23 09:45 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/__tests__/project-statistics-popup-helpers.test.tsx
> +  it('get valid display name, for example firstParty', () => {
Fixed.

2022-11-23 09:56 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/__tests__/project-statistics-popup-helpers.test.tsx
> +      'themitlicense(mit)': ['uuid2', 'uuid5'],
That is already being tested I think.

"Apache License 2.0" is different from "Apache License 3.0" in the same way as "Apache License 2.0" is different from "The MIT License" : the difference in characters basically, **which is tested in different keys of the test data**.

"Apache License 2.0" is the same as "aPaChE lIcEnSe 2.0": **tested in the same key of the test data, with different uuid**

2022-11-23 10:48 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +): Array<Array<string | number>> {
Actually there wasn't a type change. There used to be a function that took in some values and sorted them and returned them. However, the input used to be sorted already, and so the need for the function vanished. The function was therefore removed.

However the removed function's output was used as a prop in a component, and therefore to keep the API usage as it is, this function's output type was modified to be the same as the removed function's output type.

2022-11-23 10:55 UTC, benedikt-richter requested changes

2022-11-23 10:55 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +export function getLicenseDataFromAttributionsAndSources(
This function has no branches. It will always be tested in the tests of the function that uses it. It seems not necessary to export it.

2022-11-23 10:55 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +export function getLicenseDataFromVariants(
This function has almost no branches. It will always be tested in the tests of the function that uses it. It seems not necessary to export it.

2022-11-23 10:55 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +export function getLicenseCriticality(licenseCriticalityCounts: {
it would be good to add a comment that the function is exported only for testing

2022-11-23 10:55 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +export function getSourceDisplayNameFromId(
I think this one should not be exported for testing. Actually, part of it's logic is "hidden" at the place it is invoked...

```

const sourceName = getSourceDisplayNameFromId(
        attributions[attributionId].source?.name ?? UNKNOWN_SOURCE_PLACEHOLDER,
        attributionSources
);

```

To be honest, I think this function should not exist and be inlined or at least it should take `attributions[attributionId].source` as input insterad of `attributions[attributionId].source?.name ?? UNKNOWN_SOURCE_PLACEHOLDER`

2022-11-23 11:01 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/__tests__/project-statistics-popup-helpers.test.tsx
> +      'themitlicense(mit)': ['uuid2', 'uuid5'],
Test removed, as per discussion, since it is an implementation detail and is being tested elsewhere.

2022-11-23 12:09 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +): Array<Array<string | number>> {
Fixed as per verbal discussion.

2022-11-23 12:17 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +export function getLicenseDataFromAttributionsAndSources(
Fixed.

2022-11-23 12:18 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +export function getLicenseDataFromVariants(
Fixed.

2022-11-23 12:22 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +export function getLicenseCriticality(licenseCriticalityCounts: {
Done.

2022-11-23 12:27 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +export function getSourceDisplayNameFromId(
Removed export.

2022-11-23 12:57 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +export function getSourceDisplayNameFromId(
Inlined the function behaviour where it was being called.

2022-11-23 12:57 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +export function getSourceDisplayNameFromId(
Fixed.

2022-11-23 13:23 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/__tests__/project-statistics-popup-helpers.test.tsx
>  const attributionSources = {
Fixed.

2022-11-23 14:16 UTC, MarkusObendrauf approved these changes
Nice. I personally think that some more tests could have been kept, lets see what Benedikt thinks.

**Answered by @someshkhandelia**: yes, it was a little painful for me to have written so many new tests for functions and then to have deleted them. More so, because of our single commit squashing policy, all that work is now lost and cannot be recovered in future :(  
But on the other hand it is also true that those functions were implementation details and are being tested as part of other functions. So I guess it's ok in a way.

2022-11-23 15:22 UTC, benedikt-richter requested changes
some last comments.

Tests look much better now 👍

2022-11-23 15:22 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/__tests__/project-statistics-popup-helpers.test.tsx
> +    const expectedAttributionCountPerSourcePerLicense = {
there should be type annotations for all constants used in the tests, whenever there exist defined types that we can use.

2022-11-23 15:22 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/ProjectStatisticsPopup.tsx
> +                attributionPropertyCountsEntries={Object.entries(
This should be done in `aggregateAttributionPropertiesFromAttributions`.

2022-11-23 15:22 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/__tests__/project-statistics-popup-helpers.test.tsx
>      };
why was the return type changed from Array?

2022-11-23 15:22 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/__tests__/project-statistics-popup-helpers.test.tsx
> +  it('obtains most frequent licenses without Other accumulation', () => {
"Other" -> "other"

2022-11-23 15:22 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/__tests__/project-statistics-popup-helpers.test.tsx
> +  it('obtains most frequent licenses with Other accumulation', () => {
"Other" -> "other"

2022-11-23 16:38 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/ProjectStatisticsPopup.tsx
> +                attributionPropertyCountsEntries={Object.entries(
Had made changes as per: https://github.com/opossum-tool/OpossumUI/pull/1165#discussion_r1028080961 and a following verbal discussion with @MarkusObendrauf

2022-11-23 16:38 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/__tests__/project-statistics-popup-helpers.test.tsx
>      };
Had made changes as per: https://github.com/opossum-tool/OpossumUI/pull/1165#discussion_r1028080961 and a following verbal discussion with @MarkusObendrauf

2022-11-24 06:54 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/__tests__/project-statistics-popup-helpers.test.tsx
>      };
It would be great to test at some place that the order (that is important for the display) is correct. Currently there is no test verifying that the order is correct.

2022-11-24 08:55 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/__tests__/project-statistics-popup-helpers.test.tsx
> +  it('obtains most frequent licenses without Other accumulation', () => {
Fixed.

2022-11-24 08:55 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/__tests__/project-statistics-popup-helpers.test.tsx
> +  it('obtains most frequent licenses with Other accumulation', () => {
Fixed.

2022-11-24 09:20 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/ProjectStatisticsPopup.tsx
> +                attributionPropertyCountsEntries={Object.entries(
Made changes according to verbal discussion today.

2022-11-24 09:20 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/__tests__/project-statistics-popup-helpers.test.tsx
>      };
Made changes according to verbal discussion today.

2022-11-24 09:59 UTC, someshkhandelia commented on src/Frontend/Components/ProjectStatisticsPopup/__tests__/project-statistics-popup-helpers.test.tsx
> +    const expectedAttributionCountPerSourcePerLicense = {
Fixed.

2022-11-24 10:08 UTC, benedikt-richter approved these changes

2022-11-24 10:13 UTC, MarkusObendrauf approved these changes

2022-11-24 10:34 UTC, merged