match project metadata popup style with project statistics popup style
opossum-tool/OpossumUI pull request #1185
Opened 2022-11-24 14:53 UTC by lennartclaas

### Summary of changes

The project metadata popup table style was adjusted according to the project statistics popup table style. 

### Context and reason for change

Before the changes, the project metadata popup table style was quite plain. Now, both tables have the same style, which improves visual consistency.

### How can the changes be tested

Open both tables with the "File" button and take a look.

### Comments

Added maxWidth to NotificationPopupProps in order to enable different widths for the project metadata popup (use value 'sm') and the project statistics popup (use value 'xl').
projectMetadataPopupClasses were defined to remove any dependencies from the project statistics popup style. Later on, both popup tables can depend on a single style (other ticket).

Issue: #1010

2022-11-24 14:55 UTC, vasily-pozdnyakov commented
It would be nice to add screenshots of the component before and after the changes.

2022-11-24 16:45 UTC, vasily-pozdnyakov commented
The popup is not flexible, if you open it for a bigger file (e.g. opossum_ui_scan_input.json.gz) with a lot of content:
![image](https://user-images.githubusercontent.com/85183359/203833490-7472adbf-7ac7-4a6c-98e6-a9d9fccf6f44.png)

2022-11-25 07:28 UTC, benedikt-richter requested changes

2022-11-25 07:28 UTC, benedikt-richter commented on src/Frontend/Components/ProjectMetadataPopup/ProjectMetadataPopup.tsx
> +      maxWidth="sm"
why was this changed?

2022-11-25 07:28 UTC, benedikt-richter commented on src/Frontend/Components/ProjectMetadataPopup/ProjectMetadataPopup.tsx
> +        <>
the fragment `<>`is not needed

2022-11-25 07:28 UTC, benedikt-richter commented on src/Frontend/Components/ProjectMetadataPopup/ProjectMetadataTable.tsx
> +// SPDX-FileCopyrightText: Meta Platforms, Inc. and its affiliates
This component should have its own folder directly under `components/`

2022-11-25 07:28 UTC, benedikt-richter commented on src/Frontend/Components/ProjectMetadataPopup/ProjectMetadataTable.tsx
> +import { projectMetadataPopupClasses } from './../ProjectMetadataPopup/shared-project-metadata-popup-styles';
these styles seem not shared and should be moved into this file. Even Though I understand that @FlorianSchepers might also touch the styling. Not sure how to coordinate here best.

2022-11-25 07:28 UTC, benedikt-richter commented on src/Frontend/Components/ProjectMetadataPopup/ProjectMetadataTable.tsx
> +  const metadata: ProjectMetadata = useAppSelector(getProjectMetadata);
The type does not have to be provided here

2022-11-25 07:28 UTC, benedikt-richter commented on src/Frontend/Components/ProjectMetadataPopup/ProjectMetadataTable.tsx
> +  function mapKeyToString(key: string): string {
`mapKeyToString` -> `mapKeyToDisplayName`

2022-11-25 07:28 UTC, benedikt-richter commented on src/Frontend/Components/ProjectMetadataPopup/ProjectMetadataTable.tsx
> +    const keyToDisplayName: { [key: string]: string } = {
move to beginning of file

2022-11-25 07:28 UTC, benedikt-richter commented on src/Frontend/Components/ProjectMetadataPopup/ProjectMetadataTable.tsx
> +    }
might be `return key in keyToDisplayName ? keyToDisplayName[key] : key`

2022-11-25 07:28 UTC, benedikt-richter commented on src/Frontend/Components/ProjectMetadataPopup/ProjectMetadataTable.tsx
> +  function getMuiTableRow(key: string): ReactElement {
`getMuiTableRow` -> `getTableRow`

The prefix "Mui" we only use for components imported from material-ui

2022-11-25 07:28 UTC, benedikt-richter commented on src/Frontend/Components/ProjectMetadataPopup/ProjectMetadataTable.tsx
> +      {/* <MuiTypography variant="subtitle1">{'Test'}</MuiTypography> */}
remove

2022-11-25 07:28 UTC, benedikt-richter commented on src/Frontend/Components/ProjectMetadataPopup/ProjectMetadataTable.tsx
> +  const metadata: ProjectMetadata = useAppSelector(getProjectMetadata);
also metadata is verty generic. Might be called `projectMetadata`

2022-11-25 07:28 UTC, benedikt-richter commented on src/Frontend/Components/ProjectMetadataPopup/shared-project-metadata-popup-styles.ts
> +// SPDX-FileCopyrightText: TNG Technology Consulting GmbH <https://www.tngtech.com>
There is no need for a file containing shared styles here, see above.

2022-11-25 07:29 UTC, benedikt-richter commented on src/Frontend/Components/ProjectMetadataPopup/ProjectMetadataPopup.tsx
> +      maxWidth="sm"
It seems this change leads to the behavior documented in https://github.com/opossum-tool/OpossumUI/pull/1185#issuecomment-1326672960

2022-11-25 07:43 UTC, lennartclaas commented on src/Frontend/Components/ProjectMetadataPopup/ProjectMetadataPopup.tsx
> +      maxWidth="sm"
Previously, maxWidth was hardcoded with value 'xl'. This led to smaller tables looking like this:
![2_opossumui_project_metadata_new_wide](https://user-images.githubusercontent.com/83081698/203926797-059ac524-08b7-4ea8-892e-ad51be03633c.png)

I guess the best solution would be to employ a flexible table, as proposed in [#1185 (comment)](https://github.com/opossum-tool/OpossumUI/pull/1185#issuecomment-1326672960)

2022-11-25 07:48 UTC, benedikt-richter commented
Regarding the commit message, I'd like to refer to `https://github.com/opossum-tool/OpossumUI/blob/main/CONTRIBUTING.md`. A good example is given there:

```

Short summary of changes (72 characters or less)

More detailed explanatory text, if necessary. This text can have 
several lines.

Issue: #123  (this line is optional)

```

In case you replace "Issue" by "Fix" the corresponding issue will be automatically closed, when this PR is merged.

2022-11-25 13:17 UTC, benedikt-richter approved these changes
Looks good! 

Nice solution for the issue of various width 👍 

Just rebase on the latest `main` before merging

2022-11-25 13:57 UTC, FlorianSchepers reviewed
lgtm

2022-11-25 13:57 UTC, FlorianSchepers commented on src/Frontend/Components/ProjectMetadataTable/ProjectMetadataTable.tsx
> +};
Seems you made some changes to these styles, so a refactoring with my pull request is no longer necessary.

2022-11-25 14:49 UTC, merged