Refactor Statistics Popup tables
opossum-tool/OpossumUI pull request #1193
Opened 2022-11-25 16:42 UTC by FlorianSchepers

### Summary of changes

1.  Moved the components `AccordionWithPieChart`, `AttributionPropertyCountTable`, `AttributionCountPerSourcePerLicenseTable` and `CriticalLicensesTable`. 
2. Reduced boiler plate code by refactored `AttributionCountPerSourcePerLicenseTable` and `CriticalLicensesTable` to use the newly introduced `ProjectLicensesTable` component. 

### Context and reason for change

Remove technical debt.

Fix: #1080 

Signed-off-by: Florian Schepers <florian.schepers@tngtech.com>

2022-11-28 07:34 UTC, benedikt-richter requested changes
Added first round of comments. Mainly on imports and structure.

2022-11-28 07:34 UTC, benedikt-richter commented on src/Frontend/Components/AccordionWithPieChart/AccordionWithPieChart.tsx
> +    maxWidth: '600px',
Using `px` in line 19 is inconsitent with line 18 where it is not used

2022-11-28 07:34 UTC, benedikt-richter commented on src/Frontend/Components/AccordionWithPieChart/AccordionWithPieChart.tsx
> +export const accordionWithPieChartClasses = {
this should not be exported

2022-11-28 07:34 UTC, benedikt-richter commented on src/Frontend/Components/AccordionWithPieChart/accordion-with-pie-chart-helpers.test.tsx
> +// SPDX-FileCopyrightText: Meta Platforms, Inc. and its affiliates
Tests should go into a dedicated `__tests__`folder

2022-11-28 07:34 UTC, benedikt-richter commented on src/Frontend/Components/AccordionWithPieChart/accordion-with-pie-chart-helpers.test.tsx
> +import { PieChartData } from '../PieChart/PieChart';
if we use `PieChartData`here the interface should go into shared types

2022-11-28 07:34 UTC, benedikt-richter commented on src/Frontend/Components/AccordionWithPieChart/accordion-with-pie-chart-helpers.ts
> +export function getColorsForPieChart(
as this is a single function it should go into the component itself. No need for separate file.

2022-11-28 07:34 UTC, benedikt-richter commented on src/Frontend/Components/AttributionCountPerSourcePerLicenseTable/AttributionCountPerSourcePerLicenseTable.tsx
> +} from '../ProjectStatisticsPopup/project-statistics-popup-helpers';
we should not import from these helpers

2022-11-28 07:34 UTC, benedikt-richter commented on src/Frontend/Components/AttributionCountPerSourcePerLicenseTable/AttributionCountPerSourcePerLicenseTable.tsx
> +export const attributionCountPerSourcePerLicenseTableClasses = {
should not be exported

2022-11-28 07:34 UTC, benedikt-richter commented on src/Frontend/Components/AttributionCountPerSourcePerLicenseTable/AttributionCountPerSourcePerLicenseTable.tsx
> +    marginBottom: 3,
as above

2022-11-28 07:34 UTC, benedikt-richter commented on src/Frontend/Components/AttributionCountPerSourcePerLicenseTable/AttributionCountPerSourcePerLicenseTable.tsx
> +export interface AttributionCountPerSourcePerLicenseTableProps {
why is this exported?

2022-11-28 07:34 UTC, benedikt-richter commented on src/Frontend/Components/AttributionPropertyCountTable/AttributionPropertyCountTable.tsx
> +    marginBottom: 3,
as above

2022-11-28 07:34 UTC, benedikt-richter commented on src/Frontend/Components/AttributionPropertyCountTable/attribution-property-count-table-helpers.ts
> +// SPDX-FileCopyrightText: Meta Platforms, Inc. and its affiliates
This helper should go into the component

2022-11-28 07:34 UTC, benedikt-richter commented on src/Frontend/Components/AttributionPropertyCountTable/attribution-property-count-table-helpers.test.tsx
> +// SPDX-FileCopyrightText: Meta Platforms, Inc. and its affiliates
Tests should be in dedicated folder

2022-11-28 07:34 UTC, benedikt-richter commented on src/Frontend/Components/CriticalLicensesTable/CriticalLicensesTable.tsx
> +} from '../ProjectStatisticsPopup/project-statistics-popup-helpers';
we should not import from these helpers

2022-11-28 07:34 UTC, benedikt-richter commented on src/Frontend/Components/CriticalLicensesTable/CriticalLicensesTable.tsx
> +    marginBottom: 3,
as above

2022-11-28 07:34 UTC, benedikt-richter commented on src/Frontend/Components/ProjectLicensesTable/ProjectLicensesTable.tsx
> +} from '../ProjectStatisticsPopup/project-statistics-popup-helpers';
as above

2022-11-28 07:34 UTC, benedikt-richter commented on src/Frontend/Components/ProjectLicensesTable/ProjectLicensesTable.tsx
> +export interface ProjectLicensesTableProps {
why is this exported?

2022-11-28 07:34 UTC, benedikt-richter commented on src/Frontend/Components/ProjectLicensesTable/ProjectLicensesTable.tsx
> +  tableFooter?: string[];
`string[]` -> `Array<string>`

2022-11-28 07:34 UTC, benedikt-richter commented on src/Frontend/shared-styles.ts
> +export const projectStatisticsTableClasses = {
This name is very specific for a shared style

2022-11-28 12:16 UTC, benedikt-richter commented on src/Frontend/Components/CriticalLicensesTable/CriticalLicensesTable.tsx
> +  ];
Instead of defining `LICENSE_COLUMN_NAME_IN_TABLE`and `AMOUNT_COLUMN_NAME_IN_TABLE`on top define `TABLE_COLUMN_NAMES`

2022-11-28 12:16 UTC, benedikt-richter commented on src/Frontend/Components/CriticalLicensesTable/CriticalLicensesTable.tsx
> +export const criticalLicensesTableClasses = {
just call `classes`and do not export

2022-11-28 12:16 UTC, benedikt-richter commented on src/Frontend/Components/CriticalLicensesTable/CriticalLicensesTable.tsx
> +            { Amount: totalNumberOfAttributions },
`Amount` has to be `AMOUNT_COLUMN_NAME_IN_TABLE`

2022-11-28 12:16 UTC, benedikt-richter commented on src/Frontend/Components/AttributionPropertyCountTable/AttributionPropertyCountTable.tsx
> +export function getAttributionPropertyDisplayNameFromId(
add comment that it is exported only for testing

2022-11-28 12:22 UTC, benedikt-richter commented on src/Frontend/Components/AttributionCountPerSourcePerLicenseTable/AttributionCountPerSourcePerLicenseTable.tsx
> +} from '../ProjectStatisticsPopup/project-statistics-popup-helpers';
This coupling to the project statistics popup will be removed in #1194

2022-11-29 06:40 UTC, leslielazzarino requested changes

2022-11-29 13:25 UTC, FlorianSchepers commented on src/Frontend/Components/CriticalLicensesTable/CriticalLicensesTable.tsx
> +}
Moved them under the component.

2022-11-29 13:40 UTC, benedikt-richter approved these changes
👍

2022-11-29 13:46 UTC, leslielazzarino approved these changes

2022-11-29 16:00 UTC, merged