Use worker for top progress bar
opossum-tool/OpossumUI pull request #1195
Opened 2022-11-28 16:27 UTC by MarkusObendrauf

### Summary of changes

Adapt the worker for the folder progress bar and use it for the top progress bar.

### Context and reason for change

See https://github.com/opossum-tool/OpossumUI/issues/1110

This PR aims to speed up saving. The following two functions were identified as taking up most of the time when saving a large file:
1. `getUpdatedProgressBarData` (~1300ms on my setup)
2. `saveManualAndResolvedAttributionsToFile` (~300ms on my setup)
`getUpdatedProgressBarData` is a function that calculates data for the progress bar at the top of the UI. Since it takes up a lot of time and doesn't need to be blocking, it was moved to a worker where it can be executed asynchronously.

### How can the changes be tested

Save changes to a large OpossumUI input file. Use the Performance tab to check how long it takes (or just feel the difference).

From my test (~600,000 files)
Before: 1.55s
After: 0.51s

2022-11-29 06:26 UTC, benedikt-richter commented
The file`package-lock.json` should not be checked in

2022-11-30 08:19 UTC, alexzurbonsen commented
How do we handle sign offs? There are a couple of them missing, but I guess it is fine if the merge commit is signed?

2022-11-30 08:39 UTC, MarkusObendrauf commented
> How do we handle sign offs? There are a couple of them missing, but I guess it is fine if the merge commit is signed?

I will squash it into a single commit before merging, that will be signed

2022-11-30 14:07 UTC, alexzurbonsen commented on src/ElectronBackend/input/OpossumOutputFileSchema.json
> +      }
Seem like these are all format changes, except for this one. Necessary?

2022-11-30 14:11 UTC, alexzurbonsen commented on src/Frontend/Components/ProgressBar/ProgressBar.tsx
> +  isFolderProgressBar: boolean; // was optional before
remove comment?

2022-11-30 14:25 UTC, leslielazzarino requested changes

2022-11-30 14:25 UTC, leslielazzarino commented on src/Frontend/Components/ProgressBar/ProgressBar.tsx
> +  isFolderProgressBar: boolean; // was optional before
I would rather make it an union of two litteral strings, and call it "type"

2022-11-30 14:25 UTC, leslielazzarino commented on src/Frontend/Components/ProgressBar/TopProgressBar.tsx
> +      worker.onmessage = (messageEvent): void => {
deconstruct it like in the WorkerAccordionPanel, it makes it more readable. Plus in js you do not write ['key'], but just .key ;)

2022-11-30 14:25 UTC, leslielazzarino commented on src/Frontend/Components/TopBar/TopBar.tsx
> +      {showTopProgressBar ? <TopProgressBar /> : null}
Put a placeholder here instead of null, just a MuiBox with flex: 1 will do the trick.

2022-11-30 14:26 UTC, leslielazzarino commented on src/Frontend/Components/TopBar/TopBar.tsx
> +      {showTopProgressBar ? <TopProgressBar /> : null}
The purpose is to have the buttons always at the sdame place.

2022-11-30 14:26 UTC, leslielazzarino commented
Ad sign your commit.

2022-12-01 08:08 UTC, alexzurbonsen commented on src/Frontend/state/actions/resource-actions/__tests__/all-views-simple-actions.test.ts
> -  it('sets and gets progressBarData', () => {
It seems to me, that we are deleting a lot of tests related to the old progress bar (here and in other files). Don't we need similar things for the new worker progress bar? Or is it all covered?

2022-12-01 10:50 UTC, MarkusObendrauf commented on src/ElectronBackend/input/OpossumOutputFileSchema.json
> +      }
fixed

2022-12-01 10:51 UTC, MarkusObendrauf commented on src/Frontend/Components/ProgressBar/ProgressBar.tsx
> +  isFolderProgressBar: boolean; // was optional before
done

2022-12-01 10:51 UTC, MarkusObendrauf commented on src/Frontend/Components/ProgressBar/TopProgressBar.tsx
> +      worker.onmessage = (messageEvent): void => {
ok

2022-12-01 11:37 UTC, MarkusObendrauf commented on src/Frontend/state/actions/resource-actions/__tests__/all-views-simple-actions.test.ts
> -  it('sets and gets progressBarData', () => {
I removed this test because it assumes that the state will be updated synchronously - not sure how to write a test that waits for the worker. The function called by the worker is tested, but not the worker itself.

2022-12-05 12:59 UTC, alexzurbonsen commented on src/ElectronBackend/input/OpossumOutputFileSchema.json
> +      }
May be I got this wrong last time, didn't you say the `inputFileMD5Checksum` wasn't necessary and just a residue from a former approach? Or is it still needed?

2022-12-07 06:37 UTC, benedikt-richter commented on src/ElectronBackend/input/OpossumOutputFileSchema.json
> +        "description": "AAAAAAAAAA"
the description should be imporved

2022-12-08 08:59 UTC, MarkusObendrauf commented on src/ElectronBackend/input/OpossumOutputFileSchema.json
> +        "description": "AAAAAAAAAA"
not sure how that one returned lol

2022-12-08 09:01 UTC, MarkusObendrauf commented on src/ElectronBackend/input/OpossumOutputFileSchema.json
> +      }
I changed the description. I think it is necessary, and idk why it doesnt appear in the base commit.

2022-12-08 09:08 UTC, MarkusObendrauf commented on src/ElectronBackend/input/OpossumOutputFileSchema.json
> +      }
nvm, I had that wrong, deleted it again.

2022-12-08 09:10 UTC, MarkusObendrauf commented on src/ElectronBackend/input/OpossumOutputFileSchema.json
> +        "description": "AAAAAAAAAA"
I've deleted those lines, they were not necessary

2022-12-08 10:13 UTC, benedikt-richter commented on src/Frontend/state/reducers/resource-reducer.ts
> +          manualData: {
The new implementation seems not to depend on `action.payload.jumpToUpdatedAttribution`. Was this changed accidentely?

2022-12-08 12:26 UTC, MarkusObendrauf commented on src/Frontend/state/reducers/resource-reducer.ts
> +          manualData: {
Not intended, Ive reverted it.

2022-12-08 14:31 UTC, alexzurbonsen approved these changes

2022-12-08 15:15 UTC, benedikt-richter approved these changes
Nice 👍

2022-12-08 15:17 UTC, merged