[Bug Fix] unknown application version in Windows
opossum-tool/OpossumUI pull request #1209
Opened 2022-11-30 13:25 UTC by someshkhandelia

### Summary of changes

[Bug Fix] unknown application version in Windows

### Context and reason for change

Fix: #776 

Signed-off-by: someshkhandelia <someshkhandelia@gmail.com>

2022-11-30 13:46 UTC, someshkhandelia commented
### Previously in Windows:

![image](https://user-images.githubusercontent.com/85183359/175551224-a25e7373-e66e-4451-9cee-69f7a5aaeda1.png)

### Now: 
![image](https://user-images.githubusercontent.com/9270691/204812268-0e8d9ee4-e402-4b80-8ab1-6d9715ab5b92.png)

2022-11-30 15:01 UTC, someshkhandelia commented on get_app_version_for_windows.bat
> +FOR /F "tokens=*" %%g IN ('call git rev-parse --short HEAD') do (SET VAR=%%g)
Please have a look again.

2022-11-30 15:13 UTC, benedikt-richter commented on get_app_version_for_windows.bat
> +FOR /F "tokens=*" %%g IN ('call git describe --tags') do (SET OPTION1=%%g)
I think `git describe --tags` should be `git describe --exact-match --tags 2> /dev/null`, as for mac it currently looks like the following

![Screenshot 2022-11-30 at 16 11 24](https://user-images.githubusercontent.com/46576389/204835489-567d2b67-cc65-4c4b-8bc8-1d6afd3f8be8.png)

2022-11-30 15:18 UTC, someshkhandelia commented on get_app_version_for_windows.bat
> +FOR /F "tokens=*" %%g IN ('call git describe --tags') do (SET OPTION1=%%g)
That command is throwing errors. Will have to take another route.

2022-11-30 15:35 UTC, someshkhandelia commented on get_app_version_for_windows.bat
> +FOR /F "tokens=*" %%g IN ('call git describe --tags') do (SET OPTION1=%%g)
I was looking through : https://git-scm.com/docs/git-describe

and tried a few things but didn't find a way.

2022-11-30 16:34 UTC, benedikt-richter approved these changes
nice 👍 
Great to have that feature now in place also for windows!
Didn't test manually, but code looks good. 

**Answered by someshkhandelia**: Thank you! How to test? Answer-> https://github.com/opossum-tool/OpossumUI/pull/1209#issue-1469635084

2022-12-01 15:57 UTC, leslielazzarino requested changes
It gives me always the tag, even when I've created a new commit.

2022-12-07 10:09 UTC, leslielazzarino approved these changes

2022-12-07 10:13 UTC, merged