[Preliminary] Replace resource popup list with a tree.
opossum-tool/OpossumUI pull request #1224
Opened 2022-12-05 09:47 UTC by lennartclaas

### Summary of changes
The resource popup list was replaced with a tree. 

### Context and reason for change
The list shown when opening the resource popup looked quite unappealing. The new tree view provides improved navigation. By default, the tree opens with all affected nodes expanded. A future ticket could improve the appearance of the node icons.

### Further comments
There is still an issue with an unnecessary second scroll bar appearing when reducing the window size. Therefore, this is a preliminary pull request. Suggestions regarding the scroll bar issue are welcome.

The icon design is still rather sparse and could be improved in another ticket, if necessary.

By default, all nodes in the tree are expanded when the popup is opened. This strategy has been chosen to minimize clicking work. Therefore, the tree can become very large if many resources are affected by the underlying signal/attribution. However, the whole tree can be contracted by clicking the arrow of the root node. Afterwards, the tree can be expanded manually.

Before:
![0_opossumui_resources_popup_list](https://user-images.githubusercontent.com/83081698/205599770-e24a9d90-8ac3-4afd-b71d-f970068a1bc8.png)

After:
![0_opossumui_resources_popup_tree_final](https://user-images.githubusercontent.com/83081698/205599822-40b2b4fe-af3e-4ff6-8fca-4e8ccd0dca85.png)

Second scroll bar issue:
![0_opossumui_resources_popup_tree_scroll_bar_problem](https://user-images.githubusercontent.com/83081698/205599920-e70a5c05-3a07-41cd-888f-d637fac04937.png)

Sorry for the large number of changed lines. However, some stuff was just copied from ResourceBrowser.tsx to create the VistualizedTree.

Fix: #993

2022-12-05 09:55 UTC, lennartclaas commented on src/Frontend/Components/ResourcePathPopup/ResourcePathPopup.tsx
> +  console.timeEnd('convertResourcesList');
Already removed the time measurements.

2022-12-05 10:37 UTC, lennartclaas commented on src/Frontend/shared-styles.ts
> +export const resourceBrowserWidthInPixels = 640;
This does not seem to be very elegant. I will make a workaround for this and leave the value at 420.

2022-12-05 11:50 UTC, vasily-pozdnyakov commented on src/Frontend/shared-styles.ts
> +export const resourceBrowserWidthInPixels = 640;
It also influences resource browser in Audit view.

2022-12-05 17:38 UTC, lennartclaas commented on src/Frontend/Components/ResourcePathPopup/ResourcePathPopup.tsx
> +    maxHeight: 'calc(100vh - 220px)',
Fix by Vasily to remove the unintended second vertical scroll bar when extremely reducing the window size.

2022-12-06 09:46 UTC, vasily-pozdnyakov requested changes
Why do we have files "/" there?
![image](https://user-images.githubusercontent.com/85183359/205870613-24885151-e1ae-4aba-be52-6ed113c42b82.png)

2022-12-06 09:46 UTC, vasily-pozdnyakov commented on src/Frontend/Components/ResourcePathPopup/ResourcePathPopup.tsx
Delete the line

2022-12-06 09:46 UTC, vasily-pozdnyakov commented on src/Frontend/Components/ResourcePathPopup/ResourcePathPopup.tsx
> +const ROOT_FOLDER_LABEL = '';
Please move the constants above the styling classes.

2022-12-06 09:46 UTC, vasily-pozdnyakov commented on src/Frontend/Components/ResourcePathPopup/ResourcePathPopup.tsx
>    const externalAttributionsToResources = useAppSelector(
It is very difficult to follow, could you please group the constants maybe? Like all useAppSelector next to each other, etc.

2022-12-06 09:46 UTC, vasily-pozdnyakov commented on src/Frontend/Components/ResourcePathPopup/__tests__/ResourcePathPopup.test.tsx
> +  test('check structure of returned Resources object', () => {
test -> it

2022-12-06 09:46 UTC, vasily-pozdnyakov commented on src/Frontend/Components/ResourcePathPopup/__tests__/ResourcePathPopup.test.tsx
> +  test('check type of returned Resources object', () => {
You can merge the tests in one test.

2022-12-06 09:46 UTC, vasily-pozdnyakov commented on src/Frontend/test-helpers/popup-test-helpers.ts
I guess you do not use the function clickOnPathInPopupWithResources anymore and therefore do not need it.

2022-12-06 09:54 UTC, lennartclaas commented on .gitignore
> +/.vscode
To prevent that auto-generated stuff from VSCode is considered for commits.

2022-12-06 10:14 UTC, lennartclaas commented on src/Frontend/Components/ResourcePathPopup/ResourcePathPopup.tsx
>    const externalAttributionsToResources = useAppSelector(
I feel that grouping into functional chunks is more meaningful. This means that the values that we get from invoking useAppSelector should be used directly afterwards, if possible, to not "lose" the underlying functional logic / the process. However, I adjusted the order a little bit.

2022-12-06 10:16 UTC, lennartclaas commented on src/Frontend/test-helpers/popup-test-helpers.ts
It felt a little bit unpleasant to remove entire functions. :D But yeah, we don't need it anymore.

2022-12-06 10:23 UTC, lennartclaas commented
@vasily-pozdnyakov I cannot reproduce the tree with "/"-files. What was your approach?

2022-12-06 12:17 UTC, benedikt-richter commented on src/Frontend/Components/ResourcePathPopup/ResourcePathPopup.tsx
> +    maxHeight: 'calc(100vh - 220px)',
What is the meaning of `220px`? Is it the size of something? Would be good not to have magic numbers.

2022-12-06 12:17 UTC, benedikt-richter commented on src/Frontend/Components/ResourcePathPopup/ResourcePathPopup.tsx
> +    width: resourceBrowserWidthInPixels + 220,
as above

2022-12-06 12:18 UTC, benedikt-richter commented on src/Frontend/Components/ResourcePathPopup/ResourcePathPopup.tsx
> +    backgroundColor: `${OpossumColors.lightestBlue} !important`,
If possible avoid "!important"

2022-12-06 12:18 UTC, benedikt-richter commented on src/Frontend/Components/ResourcePathPopup/ResourcePathPopup.tsx
> +  const attributionBreakpoints = useAppSelector(getAttributionBreakpoints); // vielleicht
remove comment

2022-12-06 12:19 UTC, benedikt-richter commented on src/Frontend/Components/ResourcePathPopup/ResourcePathPopup.tsx
> +  const resolvedExternalAttributions = new Set<string>();
what going on here?

2022-12-06 12:20 UTC, benedikt-richter commented on src/Frontend/Components/ResourcePathPopup/ResourcePathPopup.tsx
> +  const externalData = {} as AttributionData;
why do we do this?

2022-12-06 12:20 UTC, benedikt-richter commented on src/Frontend/Components/ResourcePathPopup/ResourcePathPopup.tsx
> +  const maxTreeHeight: number = useWindowHeight() - topBarHeight - 200;
what does the magic number `200`stand for?

2022-12-06 12:22 UTC, benedikt-richter commented on src/Frontend/Components/ResourcePathPopup/__tests__/ResourcePathPopup.test.tsx
> +  test('check type of returned Resources object', () => {
Remove this test. We should not test types.

Furthermore, this test is green for `desiredResources = {}` and `getResourcesFromResourcePaths(testResourcesList) = null` ...

2022-12-06 12:24 UTC, benedikt-richter commented on src/Frontend/Components/ResourcePathPopup/resource-path-popup-helpers.ts
> +      return parent[childName] as Resources;
avoid type casts. There is alonst no case where we should use `as`. Why is it required here?

2022-12-06 12:27 UTC, benedikt-richter commented on src/Frontend/test-helpers/popup-test-helpers.ts
If it is not used, it should die :)

2022-12-06 13:34 UTC, vasily-pozdnyakov commented on src/Frontend/Components/ResourcePathPopup/ResourcePathPopup.tsx
> +    maxHeight: 'calc(100vh - 220px)',
I think it should be somehow synchronized with maxTreeHeight

2022-12-06 13:36 UTC, vasily-pozdnyakov commented on src/Frontend/Components/ResourcePathPopup/ResourcePathPopup.tsx
> +  const resolvedExternalAttributions = new Set<string>();
All of them are empty and used in getTreeItemLabel. Why?

2022-12-07 08:26 UTC, leslielazzarino commented on src/Frontend/Components/ResourcePathPopup/ResourcePathPopup.tsx
> +    maxHeight: 'calc(100vh - 220px)',
This number should just be extracted to a constant, in order not to be a magic number. The name of the constant should explain what it is.

2022-12-07 09:58 UTC, leslielazzarino requested changes

2022-12-07 09:58 UTC, leslielazzarino commented on src/Frontend/Components/ResourcePathPopup/ResourcePathPopup.tsx
> +  const externalData = {} as AttributionData;
This is and will always be not what you want to do. Casting can be used, sparringly, to help the compiler when it doesn't understand what's happening with the types in your code. Never to circumvent the typing.

2022-12-07 13:57 UTC, lennartclaas commented
> Why do we have files "/" there? ![image](https://user-images.githubusercontent.com/85183359/205870613-24885151-e1ae-4aba-be52-6ed113c42b82.png)

Resolved. Now, it looks like this:
![res_tree_folders_correct](https://user-images.githubusercontent.com/83081698/206197937-f627e2e4-dbc6-4beb-9d53-957faf2572f4.png)

2022-12-08 09:11 UTC, lennartclaas commented on src/Frontend/Components/ResourcePathPopup/ResourcePathPopup.tsx
> +    },
Done in latest commit.

2022-12-08 10:27 UTC, vasily-pozdnyakov commented
I see different resources lists for e.g. /OpossumUI/build/index.html. Not sure which one is correct.
![image](https://user-images.githubusercontent.com/85183359/206422862-5e901d42-f489-4c60-887e-5b051f315971.png)
![image](https://user-images.githubusercontent.com/85183359/206422668-d3f19890-df07-4e24-ac62-7caa406254ff.png)

2022-12-08 10:46 UTC, leslielazzarino commented
![Screen_Capture_-_Dec_8__11_43_AM](https://user-images.githubusercontent.com/62446606/206426995-b3c3a43b-8321-4eb2-97ce-397c50e0b835.png)
I don't like this behavior, the tree should use all the horizontal space it can before the need to scroll horizontally arises.

2022-12-08 10:57 UTC, vasily-pozdnyakov approved these changes
Just minor things. Well done!

2022-12-08 10:57 UTC, vasily-pozdnyakov commented on src/Frontend/shared-styles.ts
> +interface TreeStyleBrowserVars {
Can the interfaces be merged?

2022-12-08 10:57 UTC, vasily-pozdnyakov commented on src/Frontend/test-helpers/popup-test-helpers.ts
> +  node: string
is it nodeId? Would be nice to be more specific.

2022-12-08 10:57 UTC, vasily-pozdnyakov commented on src/Frontend/Components/ResourcePathPopup/resource-path-popup-helpers.ts
> +        parent[childName] = isFolder ? {} : 1;
Why can it be 1?

2022-12-08 12:09 UTC, benedikt-richter commented on src/Frontend/Components/ResourcePathPopup/resource-path-popup-helpers.ts
> +      return parent[childName] as Resources;
Actually, this function can return `1`. Typescript is right. To reproduce, execute the following: `getResourcesFromResourcePaths(testResourcesList)`

2022-12-08 12:10 UTC, benedikt-richter commented on src/Frontend/Components/ResourcePathPopup/resource-path-popup-helpers.ts
> +      return parent[childName] as Resources;
`  return parent[childName] as Resources;` could be

```
      const returnValue = parent[childName];
      return returnValue !== 1 ? returnValue : {};
```

2022-12-08 12:12 UTC, benedikt-richter commented on src/Frontend/Components/ResourcePathPopup/__tests__/ResourcePathPopup.test.tsx
> +it('correctly converts a list of resource ids (paths) into a Resources object', () => {
helpers should be tested in a different file (to be created): `resource-path-popup-heklpers.test.ts`

2022-12-08 14:53 UTC, lennartclaas commented on src/Frontend/test-helpers/popup-test-helpers.ts
> +  node: string
It's not the nodeId, i.e., the full path to a node. It's just the label (or name) of a node. I changed it to `nodeLabel`.

2022-12-08 14:56 UTC, lennartclaas commented on src/Frontend/Components/ResourcePathPopup/resource-path-popup-helpers.ts
> +        parent[childName] = isFolder ? {} : 1;
This is a characteristic of the Resources interface. An objects indicates a folder, and a 1 indicates a file.

2022-12-08 14:58 UTC, lennartclaas commented on src/Frontend/shared-styles.ts
> +interface TreeStyleBrowserVars {
I found the SxProps type and used this instead. Looks way better.

2022-12-08 15:18 UTC, lennartclaas commented on src/Frontend/Components/ResourcePathPopup/resource-path-popup-helpers.ts
> +      return parent[childName] as Resources;
Nice solution. Thanks. 👍

2022-12-09 09:56 UTC, leslielazzarino requested changes

2022-12-09 09:56 UTC, leslielazzarino commented on src/Frontend/shared-styles.ts
> +            width: `calc(100vw - ${horizontalSpaceBetweenTreeAndViewportEdges}px)`,
Doesn't work properly with wide form factors, as the popup has a max width. Either remove the max width from the popup or introduce it here too.

2022-12-09 15:35 UTC, leslielazzarino approved these changes

2022-12-09 16:15 UTC, merged