Adjust buttons of URL field in attribution column.
opossum-tool/OpossumUI pull request #1237
Opened 2022-12-07 10:56 UTC by lennartclaas

### Summary of changes
If disabled, the fetch button is not clickable. The fetch button and the open button do show a tooltip if they are disabled. The tooltips indicate that fetching or opening is not possible because the URL is missing or unsuitable.

### Context and reason for change
Previously, the fetch button was clickable, although disabled. Furthermore, disabled buttons did not show a tooltip. However, a tooltip with information on why the buttons are disabled is helpful for unexperienced users of the app.

Tooltip of the enabled fetch button:
![url_tooltip_fetch_enabled](https://user-images.githubusercontent.com/83081698/206160458-dacd7a5a-c382-4220-8e03-205f74b5c75f.png)

Tooltip of the enabled open button:
![url_tooltip_open_enabled](https://user-images.githubusercontent.com/83081698/206160637-69204f92-4412-449d-8457-e61850a34715.png)

Tooltip of the disabled fetch button:
![fetch](https://user-images.githubusercontent.com/83081698/208462033-4cdee2ab-deff-4a12-a9f5-551b3041eebe.png)

Tooltip of the disabled open button:
![open](https://user-images.githubusercontent.com/83081698/208462091-fe45a145-077e-4fbe-a180-9f6d5101bdf8.png)

Fix: #1217

2022-12-07 12:22 UTC, benedikt-richter requested changes

2022-12-07 12:22 UTC, benedikt-richter commented on src/Frontend/Components/IconButton/IconButton.tsx
> +      <MuiTooltip
the function `wrapInTooltip`seems to be no longer required. The return value is in case of `props.disabled` being `true`or `false`the same (modulo unimportant `span`).

2022-12-07 12:22 UTC, benedikt-richter commented on src/Frontend/Components/FetchLicenseInformationButton/FetchLicenseInformationButton.tsx
> +      tooltipTitle={
Would be nice to extract the tooltip text as a constant like it was the case before for `FETCH_DATA_TOOLTIP`

2022-12-07 12:22 UTC, benedikt-richter commented on src/Frontend/Components/FetchLicenseInformationButton/FetchLicenseInformationButton.tsx
> +        'Fetching data is not possible. Please enter a suitable URL.'
not sure "suitable" is the correct term here.

2022-12-07 12:23 UTC, benedikt-richter requested changes
Nice 👍 Just some minor comments

2022-12-07 13:13 UTC, vasily-pozdnyakov commented
Could you please attach screenshots of how it looks now?

2022-12-07 14:23 UTC, someshkhandelia commented
Looks nice! One small comment about the tests.

For the disabled Fetch button, you have a test to check the text of the tooltip, but the same is not true for the enabled button. Also there is a switch case for the enabled button depending on the state of loading URL. Maybe that can be tested?

2022-12-07 14:25 UTC, someshkhandelia commented on src/Frontend/Components/FetchLicenseInformationButton/__tests__/FetchLicenseInformationButton.test.tsx
>    it('renders enabled button', () => {
Looks nice! One small comment about the tests.

For the disabled Fetch button, you have a test to check the text of the tooltip, but the same is not true for the enabled button. Also there is a switch case for the enabled button depending on the state of loading URL. Maybe that can be tested?

2022-12-08 09:26 UTC, lennartclaas commented on src/Frontend/Components/IconButton/IconButton.tsx
> +      <MuiTooltip
In fact, the span tag is necessary. It facilitates tooltips for disabled buttons.

2022-12-08 09:38 UTC, lennartclaas commented on src/Frontend/Components/FetchLicenseInformationButton/FetchLicenseInformationButton.tsx
> +        'Fetching data is not possible. Please enter a suitable URL.'
Suitable means, that the URL links to pypi, npm, or github. Otherwise, the button is disabled. This more specific information could also be given in the tooltip. But it would get quite lengthy.

2022-12-13 16:41 UTC, lennartclaas commented
Regarding the tests: Any idea how `setTimeout()` can be avoided? `async`, `await` and `find` instead of `get` queries do not seem to help.

2022-12-13 16:47 UTC, lennartclaas commented
The tooltip of the disabled fetch data button now looks like this:
![tooltip_disabled_new](https://user-images.githubusercontent.com/83081698/207393680-ced94954-7609-4887-b6cf-bef3119bf7a2.png)

2022-12-14 07:50 UTC, benedikt-richter commented
> Regarding the tests: Any idea how `setTimeout()` can be avoided? `async`, `await` and `find` instead of `get` queries do not seem to help.

Jest fake timers might be helpful: https://jestjs.io/docs/timer-mocks

2022-12-19 15:28 UTC, lennartclaas commented on src/Frontend/Components/FetchLicenseInformationButton/__tests__/FetchLicenseInformationButton.test.tsx
>    it('renders enabled button', () => {
I added multiple tests for different tooltips.

2022-12-20 07:24 UTC, benedikt-richter requested changes

2022-12-20 07:24 UTC, benedikt-richter commented on src/Frontend/Components/IconButton/IconButton.tsx
> +      <MuiTooltip
Good point! In this case, I'd suggest to always include the span in order to reduce complexity. The component could be something like:

```
export function IconButton(props: IconButtonProps): ReactElement {
  return (
    <MuiTooltip
      sx={tooltipStyle}
      title={props.tooltipTitle}
      placement={props.tooltipPlacement}
    >
      <span>
        {
          // this span enables tooltips for disabled buttons
        }
        <MuiButtonBase
          sx={props.sx}
          onClick={(event): void => {
            event.stopPropagation();
            props.onClick();
          }}
          disabled={props.disabled}
        >
          {props.icon}
        </MuiButtonBase>
      </span>
    </MuiTooltip>
  );
}
```

2022-12-21 07:05 UTC, benedikt-richter approved these changes
👍

2022-12-21 08:19 UTC, vasily-pozdnyakov commented
See failed tests.

2022-12-21 09:30 UTC, someshkhandelia approved these changes

2022-12-21 10:39 UTC, merged