Decouple project statistics popup helper
opossum-tool/OpossumUI pull request #1238
Opened 2022-12-07 11:02 UTC by someshkhandelia

### Summary of changes

Decouple project statistics popup helper

### Context and reason for change

Issue: #1194

Signed-off-by: someshkhandelia <someshkhandelia@gmail.com>

2022-12-07 11:11 UTC, benedikt-richter requested changes
Actually, these components and the helpers for the project statistics popup are still coupled (not technically anymore but logically).
If you change the value of one of the constants in one of the files the logic breaks. The logic currently relies on these constants to have equal value. E.g. in `src/Frontend/Components/AttributionCountPerSourcePerLicenseTable/AttributionCountPerSourcePerLicenseTable.tsx` in line 37 and 38 the sorting of the sources relies on this fact.

**Answered by @someshkhandelia**: The logic won't break now, since the constants are shared now.  I would also draw attention to the fact that `ProjectLicensesTable` is the generic table which is already decoupled from data logic of the statistic helper. The tables `AttributionCountPerSourcePerLicenseTable` and `CriticalLicensesTable` are specific to statistics popup and therefore don't seem to have the need to be decoupled.

2022-12-08 06:26 UTC, benedikt-richter commented
Regarding the reply made as an edit to https://github.com/opossum-tool/OpossumUI/pull/1238#pullrequestreview-1208228482.
Let's discuss the question whether to decouple these components in the respective issue https://github.com/opossum-tool/OpossumUI/issues/1194 and reserve the space here for discussions on the actual implementation.

2022-12-14 10:43 UTC, benedikt-richter approved these changes

2022-12-14 12:12 UTC, leslielazzarino approved these changes

2022-12-14 12:17 UTC, merged