Replace attribution view resource list with a tree.
opossum-tool/OpossumUI pull request #1245
Opened 2022-12-12 13:56 UTC by MarkusObendrauf

### Summary of changes

The attribution view list was replaced with a tree, [similar to the recent changes done to the resources popup.
](https://github.com/opossum-tool/OpossumUI/pull/1224)
### Context and reason for change

The list shown in the attribution view looked quite unappealing. The new tree view provides improved navigation. By default, the tree opens with all affected nodes expanded.

See https://github.com/opossum-tool/OpossumUI/issues/962

Before:
![image](https://user-images.githubusercontent.com/107913663/207063189-85960c79-ab35-43dc-93c8-dbc4010e466c.png)

After:
![image](https://user-images.githubusercontent.com/107913663/207063104-9acb3e16-d9bb-4096-8554-f5ded6264083.png)

2022-12-13 08:40 UTC, lennartclaas commented on src/Frontend/Components/AttributionDetailsViewer/AttributionDetailsViewer.tsx
> +  const maxTreeHeight: number = useWindowHeight() - 120;
Same as above regarding the 120. This value has some kind of origin (usually padding or margins). Would make sense to define a constant, so that this value can be comprehended in the future.

2022-12-13 08:52 UTC, lennartclaas commented on src/Frontend/shared-styles.ts
> +  ): TreeContainerStyleVars => {
Although I get the idea, I don't quite understand why this is necessary. If one would be consistent, corresponding interfaces should also be defined for the functions returning the SxProps for header and tree.  Since the tree function can return three different objects, this would be quite a mess. However, this is more like an opinion rather than a change request.

2022-12-13 12:27 UTC, MarkusObendrauf commented on src/Frontend/Components/AttributionDetailsViewer/AttributionDetailsViewer.tsx
> +  const maxTreeHeight: number = useWindowHeight() - 120;
extracted it to VERTICAL_SPACE_OF_LINKED_RESOURCE_HEADER_AND_FOOTER

2022-12-13 12:28 UTC, MarkusObendrauf commented on src/Frontend/shared-styles.ts
> +  ): TreeContainerStyleVars => {
you are right, reverted it

2022-12-13 12:48 UTC, MarkusObendrauf commented on src/Frontend/Components/AttributionDetailsViewer/AttributionDetailsViewer.tsx
> +    height: 'calc(100% - 48px)',
deined two consts:
`const VERTICAL_RESOURCE_COLUMN_PADDING = 48;
const VERTICAL_RESOURCE_HEADER_AND_FOOTER_SIZE = 72;`

The const `VERTICAL_RESOURCE_COLUMN_PADDING` is used for the `resourceColumn` class, while `VERTICAL_RESOURCE_COLUMN_PADDING + VERTICAL_RESOURCE_HEADER_AND_FOOTER_SIZE ` is used for the height of the graph itself. I think it makes sense to add these two variables together, because the graph size is dependant on both - this way you can increase `VERTICAL_RESOURCE_COLUMN_PADDING` and the graph height will change appropriately.

2022-12-13 13:17 UTC, lennartclaas approved these changes

2022-12-14 10:05 UTC, leslielazzarino requested changes
The white field should not leave an extra wide margin at the bottom, just the same the buttons in the right column.

2022-12-14 10:49 UTC, leslielazzarino requested changes

2022-12-14 10:49 UTC, leslielazzarino commented on src/Frontend/Components/AttributionView/__tests__/AttributionView.test.tsx
> +          resources: { ['/test resource']: 1 },
This change is wrong, wer do not write the slash in Resources

2022-12-14 10:49 UTC, leslielazzarino commented on src/Frontend/Components/AttributionView/__tests__/AttributionView.test.tsx
> +          resources: { ['/test resource']: 1 },
Same for the othewr three here

2022-12-14 10:49 UTC, leslielazzarino commented on src/Frontend/Components/ResourcesTree/ResourcesTree.tsx
> +const TREE_ROW_HEIGHT = 20;
These two constants should be extracted to shared constants, as they are also used in the other tree.

2022-12-14 10:49 UTC, leslielazzarino commented on src/Frontend/Components/ResourcesTree/ResourcesTree.tsx
> +  const initialExpandedIds = getInitialExpandedIds(props.resourcePaths);
Thinking more about this issue, I think you should remove this line. The calculation in the useMemo will be triggered anyhow on the first time, and as only a shallow comparison happens a rerender will also be triggered, even if the two objects are the same. Just use an empty array as initial state.

2022-12-14 10:49 UTC, leslielazzarino commented on src/Frontend/Components/ResourcesTree/__tests__/ResourcesTree.test.tsx
> +  });
You do not need this test, as you already have the next one checking the initial state.

2022-12-14 11:51 UTC, MarkusObendrauf commented
> The white field should not leave an extra wide margin at the bottom, just the same the buttons in the right column.

Adjusted the vertical spacing to match the height of the "CONFIRM" button

2022-12-14 11:55 UTC, MarkusObendrauf commented on src/Frontend/Components/ResourcesTree/ResourcesTree.tsx
> +const TREE_ROW_HEIGHT = 20;
done

2022-12-14 11:56 UTC, MarkusObendrauf commented on src/Frontend/Components/ResourcesTree/ResourcesTree.tsx
> +  const initialExpandedIds = getInitialExpandedIds(props.resourcePaths);
done

2022-12-14 12:03 UTC, MarkusObendrauf commented on src/Frontend/Components/AttributionView/__tests__/AttributionView.test.tsx
> +          resources: { ['/test resource']: 1 },
a resource is a path, so it should contain a leading slash

2022-12-14 14:16 UTC, MarkusObendrauf commented on src/Frontend/Components/AttributionView/__tests__/AttributionView.test.tsx
> +          resources: { ['/test resource']: 1 },
ok, I see the issue now. Fixed.

2022-12-19 06:38 UTC, benedikt-richter commented
Please, also test with a real world example before merging to ensure huge trees are rendered correctly.

2022-12-19 15:13 UTC, benedikt-richter requested changes
Please, sqash before merging

2022-12-19 15:13 UTC, leslielazzarino commented
The selected resource on audit view should not cause resources in the panel in attribution view to be highlighted. In the resource popup it is ok though.

2022-12-19 15:14 UTC, leslielazzarino approved these changes

2022-12-20 10:40 UTC, lennartclaas commented
Highlighting of selected resources is now disabled in the attribution view tree.

2022-12-20 12:10 UTC, benedikt-richter requested changes

2022-12-20 12:44 UTC, lennartclaas commented on src/Frontend/shared-constants.ts
> +export const TREE_ROW_HEIGHT = 20;
Then, I think, the same is true for the last 4 constants in this file.

2022-12-21 06:49 UTC, benedikt-richter requested changes
We now have `SimpleTreeItemLabel` and `StyledTreeItemLabel`. Both of which are styled. Would be good to clarify naming a bit more. Maybe:
`ResourceBrowserTreeItemLabel` and `GeneralResourceTreeItemLabel`?

2022-12-21 06:49 UTC, benedikt-richter commented on src/Frontend/Components/SimpleTreeItemLabel/SimpleTreeItemLabel.tsx
> +export function SimpleTreeItemLabel(props: StyledTreeItemProps): ReactElement {
By convention the properties of a component are named `ComponentNameProps`.

2022-12-21 06:49 UTC, benedikt-richter commented on src/Frontend/Components/ResourcesTree/get-tree-item-label-simple.tsx
> +export function getTreeItemLabelSimple(
Why not call it `getSimpleTreeItemLabel`. In my opinion that would make more sense.

2022-12-21 07:47 UTC, benedikt-richter approved these changes

2022-12-21 11:20 UTC, merged