Remove improper selector returns
opossum-tool/OpossumUI pull request #1256
Opened 2022-12-16 09:43 UTC by leslielazzarino

### Summary of changes

Selectors have been rewritten to return null instead of {} or [] created in the selector itself.

### Context and reason for change

Empty object or arrays created in the selector themselves should never be returned. They cause unnecessary re-renders and degraded performances. For examplle by navigation in the resource tree.

2022-12-16 09:46 UTC, leslielazzarino commented on src/Frontend/Components/AttributionDetailsViewer/AttributionDetailsViewer.tsx
> -    isEqual
This is expensive, it should be avoided.

2022-12-16 09:46 UTC, leslielazzarino commented on src/Frontend/state/selectors/all-views-resource-selectors.ts
> -    return {};
We should have caugth these arrors during reviews.

2022-12-16 11:55 UTC, benedikt-richter commented on src/Frontend/state/selectors/all-views-resource-selectors.ts
> +export function getManualAttributions(state: State): Attributions | null {
this function will never return `null`. The type can be removed and a lot of the `|| {}`else where can be removed

2022-12-16 11:57 UTC, benedikt-richter commented on src/Frontend/state/selectors/view-selector.ts
> +  return (popup.length === 1 && popup[0].attributionId) || null;
👍

2022-12-16 13:30 UTC, benedikt-richter requested changes
Nice catch! 👍 

There is one more to fix: `getAttributionIdsOfSelectedResource`. Also see comment.

2022-12-19 09:16 UTC, lennartclaas approved these changes

2022-12-19 12:57 UTC, benedikt-richter requested changes

2022-12-19 12:57 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/ProjectStatisticsPopup.tsx
> +  const manualAttributions: Attributions = useAppSelector(
why do we always specify the type explicitly? Would be better to stay consistent with other cases, e.g. `const externalAttributions = useAppSelector(getExternalAttributions);`

2022-12-19 14:58 UTC, benedikt-richter approved these changes

2022-12-19 15:34 UTC, merged