Make URLs in ReportView clickable
opossum-tool/OpossumUI pull request #1270
Opened 2022-12-21 15:09 UTC by someshkhandelia

### Summary of changes

Make URLs in ReportView clickable

### Context and reason for change

Fix: #1222

Signed-off-by: someshkhandelia <someshkhandelia@gmail.com>

### How can the changes be tested

If no URLs are present in the ReportView, click on button to edit the table row and add a URL, and then click on it to test it.

2022-12-21 15:25 UTC, benedikt-richter requested changes

2022-12-21 15:25 UTC, benedikt-richter commented on src/Frontend/Components/ReportTableItem/ReportTableItem.tsx
> +              }
Instead of copying the functionality from `PackageSubPanel.tsx` it should be extracted to a utility and be tested and reused.

2022-12-21 15:37 UTC, benedikt-richter commented on src/Frontend/Components/ReportTableItem/ReportTableItem.tsx
> +              let urlString = cellData.toString();
Even though not introduced in this diff, it would be good to replace the deprecated input type `ReactText` by `string | number`.

2022-12-21 15:38 UTC, someshkhandelia commented on src/Frontend/Components/ReportTableItem/ReportTableItem.tsx
> +              }
adding the function to utils and adding tests by mocking the `window.electronAPI.openLink` call

2022-12-22 09:21 UTC, someshkhandelia commented on src/Frontend/Components/ReportTableItem/ReportTableItem.tsx
> +              }
Done.

2022-12-22 09:28 UTC, vasily-pozdnyakov commented on src/Frontend/Components/ReportTableItem/ReportTableItem.tsx
> +              let urlString = cellData.toString();
Also in the `report-table-item-helpers.ts`

2022-12-22 09:32 UTC, benedikt-richter requested changes

2022-12-22 09:32 UTC, benedikt-richter commented on src/Frontend/util/open-url.ts
> +export function openUrl(urlString: string | undefined): void {
The input `urlString` should be of type`string`. We should make sure the function is only called if there is a url to open, i.e. the `urlString`is of type `string`.

2022-12-22 09:32 UTC, benedikt-richter commented on src/Frontend/util/__tests__/open-url.test.ts
> +    const urlString: string | undefined = 'www.google.com';
The type does not have to be provided explicitly. Here typescript can infer the type.

2022-12-22 09:32 UTC, benedikt-richter commented on src/Frontend/util/__tests__/open-url.test.ts
> +describe('openUrl', () => {
nice tests!

2022-12-22 09:57 UTC, someshkhandelia commented on src/Frontend/Components/ReportTableItem/ReportTableItem.tsx
> +              let urlString = cellData.toString();
I changed all occurences of ReactText to string | number.

2022-12-22 09:58 UTC, someshkhandelia commented on src/Frontend/util/__tests__/open-url.test.ts
> +describe('openUrl', () => {
Thanks!

2022-12-22 10:03 UTC, someshkhandelia commented on src/Frontend/util/__tests__/open-url.test.ts
> +    const urlString: string | undefined = 'www.google.com';
Ah, my bad. I thought we always wanted to provide types, but that's for defined types and not primitive types provided by the language itself.

Fixed.

2022-12-22 10:24 UTC, someshkhandelia commented on src/Frontend/util/open-url.ts
> +export function openUrl(urlString: string | undefined): void {
Fixed as per verbal discussion

2022-12-22 10:35 UTC, vasily-pozdnyakov approved these changes

2022-12-22 12:03 UTC, benedikt-richter approved these changes

2022-12-22 12:03 UTC, merged