Add criticality bar with toggle
opossum-tool/OpossumUI pull request #1272
Opened 2022-12-22 08:26 UTC by FlorianSchepers

### Summary of changes

Introduce a second clickable progress bar for critical licenses:
 - there are three colors for no, high, and low criticality (only resources that have a signal but no attribution should be included)
 - there should be a nice on hover message incl the number of resources with critical (high and low separately) signal
 - there is a toggle (right next to existing bar; maybe use https://mui.com/material-ui/react-switch/) to switch between the new progress bar and the current one

fix: #1029
Signed-off-by: Florian Schepers <florian.schepers@tngtech.com>

2022-12-22 09:15 UTC, lennartclaas requested changes
There seems to be a bug when adding an attribution. The criticality bar only updates after triggering the switch (I added MIT to OpossumUI folder):

![criticality_bar_no_update](https://user-images.githubusercontent.com/83081698/209099597-e08b2346-b6e2-4b92-a5f9-50ce758726ce.png)

The tooltip is updated correctly. When I remove the attribute again, the criticality bar updates as expected, without needing to hit the switch.

2022-12-22 10:29 UTC, benedikt-richter commented on src/Frontend/Components/ProgressBar/TopProgressBar.tsx
> +import { Switch } from '@mui/material';
By convention: `import MuiSwitch from '@mui/materia/Switch';` and `import MuiTooltip from '@mui/material/Tooltip';`

2022-12-22 10:30 UTC, benedikt-richter commented on src/Frontend/Components/ProgressBar/TopProgressBar.tsx
> +      </Tooltip>
could be extracted to new component

2022-12-22 11:18 UTC, vasily-pozdnyakov requested changes
Is it intended that when you click the bar it does not go through all the resources with critical signals, but only with the highest available criticality?
The rest looks fine for me, just minor comments.

2022-12-22 11:29 UTC, vasily-pozdnyakov commented
Please suppress console.log messages about "Error in rendering top progress bar"  during testing by including this text into `setupTests.ts`

2022-12-22 11:35 UTC, lennartclaas commented on src/Frontend/Components/ProgressBar/__tests__/TopProgressBar.test.tsx
> +    console.log(prettyDOM(criticalityViewSwitch));
A small remnant from testing the test. 😄

2022-12-22 12:18 UTC, benedikt-richter commented on src/Frontend/Components/ProgressBar/TopProgressBar.tsx
> +          sx={classes.tooltip}
it's unexpected to see the class `tooltip`on the switch conponent. Better create a new class. Also the default colors of the switch should not be used, as these do not fit in our color schema.

2022-12-22 12:48 UTC, benedikt-richter commented on src/Frontend/Components/ProgressBar/FolderProgressBar.tsx
> +  const externalAttributions = useAppSelector(getExternalAttributions);
The `FolderProgressBar` was not changed. Why do we add externalAttributions now?

2022-12-22 13:49 UTC, FlorianSchepers commented
> Is it intended that when you click the bar it does not go through all the resources with critical signals, but only with the highest available criticality? The rest looks fine for me, just minor comments.

Yes it was intended. However, after our discussion I will change it so that it will circle through all resources with a signal that has some criticality (i.e. high or medium).

2022-12-22 13:49 UTC, FlorianSchepers commented on src/Frontend/Components/ProgressBar/progress-bar-helpers.tsx
> +  );
It is now ;)

2022-12-22 13:56 UTC, FlorianSchepers commented on src/Frontend/Components/ProgressBar/TopProgressBar.tsx
> +    ? 'Critical license view is switched on'
How do you like `criticalityBarState`?

2022-12-22 16:22 UTC, FlorianSchepers commented
> There seems to be a bug when adding an attribution. The criticality bar only updates after triggering the switch (I added MIT to OpossumUI folder):
> 
> ![criticality_bar_no_update](https://user-images.githubusercontent.com/83081698/209099597-e08b2346-b6e2-4b92-a5f9-50ce758726ce.png)
> 
> The tooltip is updated correctly. When I remove the attribute again, the criticality bar updates as expected, without needing to hit the switch.

Nice catch!

2022-12-22 17:05 UTC, FlorianSchepers commented on src/Frontend/Components/ProgressBar/TopProgressBar.tsx
> +      </Tooltip>
Extracted it as `SwitchWithTooltip`

2022-12-22 17:10 UTC, FlorianSchepers commented on src/Frontend/Components/ProgressBar/TopProgressBar.tsx
> +          sx={classes.tooltip}
Which color style would you prefere for the switch?
https://mui.com/material-ui/react-switch/#color

2022-12-23 07:54 UTC, benedikt-richter commented on src/Frontend/Components/ProgressBar/TopProgressBar.tsx
> +          sx={classes.tooltip}
I think we should use one of our `OpossumColors`

2022-12-23 09:07 UTC, vasily-pozdnyakov commented on src/Frontend/Components/ProgressBar/TopProgressBar.tsx
> +    ? 'Critical license view is switched on'
I propose 'Critical license bar is switched on' instead of 'Critical license view is switched on'

2022-12-23 09:09 UTC, FlorianSchepers commented on src/Frontend/Components/ProgressBar/FolderProgressBar.tsx
> +  const externalAttributions = useAppSelector(getExternalAttributions);
Otherwise the `externalAttributions` would have to be optional in the `ProgressBarWorkerArgs` and this would have introduced a lot of logical overhead when loading the data. Futhermore, we might want to add the criticality bar also for the folders. In that case we would need it anyway. 

I will check if getting the externalAttributions in the folder bar has a significant impact on the performance.

2022-12-23 09:22 UTC, vasily-pozdnyakov approved these changes
Well done! I just do not like to use the word "view" for the bar. It is a bit misleading, as I thought that the views are Attribution, Audit and Report.

2022-12-23 09:24 UTC, benedikt-richter commented on src/Frontend/Components/SwitchWithTooltip/SwitchWithTooltip.tsx
> +  progressBarCriticalityState: boolean;
should have a generic name, e.g. `progressBarCriticalityState` -> `isChecked`

2022-12-23 09:25 UTC, benedikt-richter commented on src/Frontend/Components/SwitchWithTooltip/SwitchWithTooltip.tsx
> +        aria-label="CriticalityViewSwitch"
Should not be hardcoded but be handed over as property

2023-01-02 09:38 UTC, benedikt-richter approved these changes
Works 👍 

Just change the color to one of our standard colors and rename the tooltip text to not use the word "view" as this word is typically used in the context of "audit view", "attribution view" and "report view"


![Screenshot 2023-01-02 at 10 37 15](https://user-images.githubusercontent.com/46576389/210214566-d1e0056e-8679-4c61-958b-18aee8284b9a.png)

2023-01-02 09:43 UTC, lennartclaas approved these changes
👍

2023-01-02 16:35 UTC, merged