Attribution Wizard: Add package card context menu and wizard popup skeleton
opossum-tool/OpossumUI pull request #1289
Opened 2022-12-28 10:39 UTC by lennartclaas

This PR is part of the story [Attribution wizard - proof of concept](https://github.com/opossum-tool/OpossumUI/issues/1275).

### Summary of changes

Rightclicking a package card (manual attributions only) and clicking 'Open attribution wizard' opens the popup. The skeleton comprises a header, the ID (path) of the current resource, and buttons to cancel and switch to the next view (only a dummy so far).

### Context and reason for change

The Attribution Wizard is meant to streamline the editing of attributions. 

### Images

Package card context menu:
![att_wiz_context_menu](https://user-images.githubusercontent.com/83081698/209799019-227021cb-1e0a-403a-b0dd-510652db02ae.png)

Wizard skeleton:
![att_wiz_skeleton](https://user-images.githubusercontent.com/83081698/209799061-3950f156-fc7d-4255-b708-a54801d42f6a.png)

### Comments
I think it makes sense to not focus on stylistic details at this stage of development since the style will certainly change when adding more components to the wizard later.

2022-12-28 11:51 UTC, vasily-pozdnyakov requested changes

2022-12-28 11:51 UTC, vasily-pozdnyakov commented on src/Frontend/Components/PackageCard/PackageCard.tsx
> +            disabled: false,
The menu item should be disabled by default.

2022-12-28 11:51 UTC, vasily-pozdnyakov commented on src/Frontend/Components/PackageCard/__tests__/PackageCard.test.tsx
> +    expect(screen.getByText(attributionWizardHeader)).toBeInTheDocument();
Please get rid of empty lines.
Would be nice to also check that the file path shown in the wizard is correct.

2022-12-28 11:51 UTC, vasily-pozdnyakov commented on src/Frontend/Components/AttributionWizard/__tests__/AttributionWizard.test.tsx
> +  });
Would be nice to also test clicking buttons in the popup.

2022-12-28 11:51 UTC, vasily-pozdnyakov commented on src/Frontend/Components/AttributionWizard/AttributionWizard.tsx
> +              <bdi>{selectedResourceId}</bdi>
Can PathBar component be reused here?

2022-12-28 11:51 UTC, vasily-pozdnyakov commented on src/Frontend/Components/AttributionWizard/AttributionWizard.tsx
> +    buttonText: 'Cancel',
There is enum with button texts, please use it here. (src\Frontend\enums\enums.ts)

2022-12-28 11:51 UTC, vasily-pozdnyakov commented on src/Frontend/Components/AttributionWizard/AttributionWizard.tsx
> +    isDisabled: false,
Make it disabled or hidden if it is currently unused.

2022-12-28 11:51 UTC, vasily-pozdnyakov commented on src/Frontend/Components/AttributionWizard/AttributionWizard.tsx
> +      <MuiBox sx={classes.pathBox}>
Not sure that we need so many boxes.

2022-12-28 12:25 UTC, lennartclaas commented on package.json
> +    "test:single": "react-scripts test src/Frontend/Components/AttributionWizard/__tests__/AttributionWizard.test.tsx --watchAll=false --setupFilesAfterEnv=./setupTests.ts",
It is the easiest way to run only a single specific test. But that's only for me. I will delete this line before merging.

2022-12-28 12:29 UTC, lennartclaas commented on src/Frontend/enums/enums.ts
> +  AttributionWizard = 'AttributionWizard',
I used 'popup' initially. But I think it is more than that since it will have multiple steps/views. To be precise, one should name it AttributionWizardPopup as the wizard lives in the popup. 😄 But that sounds a little odd.

2022-12-28 12:30 UTC, lennartclaas commented on src/Frontend/Components/PackageCard/PackageCard.tsx
> +            disabled: false,
Yes, I will change that before merging.

2022-12-28 12:31 UTC, lennartclaas commented on src/Frontend/Components/PackageCard/__tests__/PackageCard.test.tsx
> +    expect(screen.getByText(attributionWizardHeader)).toBeInTheDocument();
This is done in `AttributionWizard.test.tsx`.

2022-12-28 12:32 UTC, lennartclaas commented on src/Frontend/Components/AttributionWizard/__tests__/AttributionWizard.test.tsx
> +  });
This is done in `PackageCard.test.tsx` because the PackageCard component needs to be rendered to open and close the popup.

2022-12-28 12:34 UTC, lennartclaas commented on src/Frontend/Components/AttributionWizard/AttributionWizard.tsx
> +              <bdi>{selectedResourceId}</bdi>
Not really because it needs different styling and other stuff. I think reusing it would be quite cumbersome and unnecessarily inflate the Pathbar component.

2022-12-28 12:39 UTC, lennartclaas commented on src/Frontend/Components/AttributionWizard/AttributionWizard.tsx
> +      <MuiBox sx={classes.pathBox}>
It's just a test content. But in this case, all boxes are actually needed to facilitate the current style. The outmost box is needed because the content prop of the notification popup can only be a single component.

2022-12-28 13:36 UTC, vasily-pozdnyakov commented on src/Frontend/Components/PackageCard/__tests__/PackageCard.test.tsx
> +    expect(screen.getByText(attributionWizardHeader)).toBeInTheDocument();
But here it is more like integration test, where the popup gets the path not from the test settings, but from another component - PackageCard.

2022-12-28 13:38 UTC, vasily-pozdnyakov commented on src/Frontend/Components/AttributionWizard/__tests__/AttributionWizard.test.tsx
> +  });
At least you can check if the expected buttons are there.

2022-12-28 13:41 UTC, vasily-pozdnyakov commented on src/Frontend/Components/AttributionWizard/AttributionWizard.tsx
> +      <MuiBox sx={classes.pathBox}>
Btw, it is not 100% test content, e.g. the path bar is actual component which will be used there.

2022-12-28 13:42 UTC, vasily-pozdnyakov commented on src/Frontend/Components/AttributionWizard/AttributionWizard.tsx
> +      <MuiBox sx={classes.pathBox}>
I propose to make it (path field) a separate component.

2022-12-28 13:56 UTC, lennartclaas commented on src/Frontend/Components/PackageCard/__tests__/PackageCard.test.tsx
> +    expect(screen.getByText(attributionWizardHeader)).toBeInTheDocument();
Okay, I can move this to the integration-test folder.

2023-01-02 07:12 UTC, benedikt-richter requested changes
The infrastructure around `GlobalPopup` should be used instead of adding a new popup to the `PackageCard`.

2023-01-02 07:12 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizard/AttributionWizard.tsx
> +export const attributionWizardHeader = 'Attribution Wizard';
I would not export it, if it is not used elsewhere in production code.

2023-01-02 07:12 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizard/AttributionWizard.tsx
> +    width: `calc(100% - ${POPUP_CONTENT_PADDING}px)`,
It seems removing this line does not change styling.

2023-01-02 07:12 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizard/AttributionWizard.tsx
> +    borderRadius: 2,
This styling seems inconsistent with the rest of the app. Typically we use a border radius of `0`

2023-01-02 07:12 UTC, benedikt-richter commented on src/Frontend/Components/PackageCard/PackageCard.tsx
> +          <AttributionWizard
Instead of including the popup here, we should use the mechanism utilized by `GlobalPopup`. This would allow us to access the `attributionId` from the redux state and to add additional/different ways to open the wizard. We also would not need a new local state and there would be no need to pass the function to close the popup.

2023-01-02 07:14 UTC, benedikt-richter commented on src/Frontend/enums/enums.ts
> +  AttributionWizard = 'AttributionWizard',
I'm for the more consistent one including the word "Popup".

2023-01-02 07:14 UTC, benedikt-richter commented on package.json
> +    "test:single": "react-scripts test src/Frontend/Components/AttributionWizard/__tests__/AttributionWizard.test.tsx --watchAll=false --setupFilesAfterEnv=./setupTests.ts",
> It is the easiest way to run only a single specific test.

I would disagree here ;)

2023-01-02 13:48 UTC, benedikt-richter requested changes

2023-01-02 13:48 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardPopup/AttributionWizardPopup.tsx
> +// const POPUP_CONTENT_PADDING = 48; monitored in upcoming tickets
Would be good to make these todos ( `// TODO:`) in order not to forget at the end

2023-01-02 13:48 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardPopup/__tests__/AttributionWizardPopup.test.tsx
> +  it('opens via package card context menu and closes by hitting "Cancel")', () => {
Here we should test that the popup's close button works.

2023-01-02 13:48 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardPopup/__tests__/AttributionWizardPopup.test.tsx
> +    renderComponentWithStore(<GlobalPopup />, { store: testStore });
Why do we have two renders? Seems to be accidental.

2023-01-02 13:48 UTC, benedikt-richter commented on src/Frontend/Components/GlobalPopup/GlobalPopup.tsx
> +    case PopupType.AttributionWizardPopup:
A respective test should be added.

2023-01-02 13:48 UTC, benedikt-richter commented on src/Frontend/Components/PathBar/PathBar.tsx
> +  additionalRootSx?: SxProps;
In all other components, we call this `sx?: SxProps;`

2023-01-02 13:48 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardPopup/__tests__/AttributionWizardPopup.test.tsx
> +    renderComponentWithStore(
The integration of the popup and the `PackageCard` should be tested in the `PackageCard`tests.

2023-01-02 13:57 UTC, lennartclaas commented on src/Frontend/Components/AttributionWizardPopup/__tests__/AttributionWizardPopup.test.tsx
> +  it('opens via package card context menu and closes by hitting "Cancel")', () => {
What exactly do you mean? In the second test (line 39 ff.), the closing behavior is tested in line 77. Or do you mean to shif this into the first test?

2023-01-02 14:00 UTC, lennartclaas commented on src/Frontend/Components/AttributionWizardPopup/__tests__/AttributionWizardPopup.test.tsx
> +    renderComponentWithStore(<GlobalPopup />, { store: testStore });
I need to render the `GlobalPopup` in order to open it via dispatch. Or do you mean to render the package card and the global popup inside a `React.Fragment` component with only a single call of `renderComponentWithStore?`

2023-01-02 14:02 UTC, lennartclaas commented on src/Frontend/Components/PathBar/PathBar.tsx
> +  additionalRootSx?: SxProps;
But this seems to be inaccurate as this naming would hide the fact that other styling is predefined.

2023-01-02 14:50 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardPopup/__tests__/AttributionWizardPopup.test.tsx
> +  it('opens via package card context menu and closes by hitting "Cancel")', () => {
As discussed, here the PackageCard should play no role.

2023-01-02 15:48 UTC, vasily-pozdnyakov approved these changes
Looks nice, just finalize the comments from the second reviewer.

2023-01-02 15:48 UTC, vasily-pozdnyakov commented on src/Frontend/Components/PackageCard/PackageCard.tsx
> +            disabled: false,
Please do not forget to disable that before merging.

2023-01-02 15:52 UTC, lennartclaas commented on src/Frontend/Components/AttributionWizardPopup/__tests__/AttributionWizardPopup.test.tsx
> +  it('opens via package card context menu and closes by hitting "Cancel")', () => {
👍

2023-01-02 16:08 UTC, benedikt-richter approved these changes

2023-01-02 16:26 UTC, merged