Attribution Wizard: Implement navigation
opossum-tool/OpossumUI pull request #1307
Opened 2023-01-05 13:22 UTC by lennartclaas

### Summary of changes

Breadcrumbs as well as next and back buttons are implemented to switch between the two steps of the wizard. Additional components for the individual wizard steps are added. Switching to the second step is only possible if both lists of the first step have an item selected. Breadcrumbs are only displayed up to the current step. Alternatively, all breadcrumbs could be displayed but disabled if the corresponding steps are not already reached.

### Additional Comments

Testing the navigation is hardly possible without a working business logic that gets redux state data. Testing the navigation will therefore be done in an upcoming ticket.

2023-01-09 07:02 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardBreadcrumbs/AttributionWizardBreadcrumbs.tsx
> +  onClick: (breadcrumbsIndex: number) => void;
We can modify the properties as follows:
```
  selectedId: string;
  onClick: (breadcrumbsId: string) => void;
  selectedIdToDisplayValue: {[selectedId: string]: string}
```

To make the component reusable

2023-01-09 07:05 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardPopup/AttributionWizardPopup.tsx
> +  const [selectedWizardStep, setSelectedWizardStep] = useState<number>(0);
Instead of numbers we can use strings to identify the "steps". This helps the readability

2023-01-09 07:06 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardPopup/AttributionWizardPopup.tsx
> +  const maxStep = 1;
This would then be obsolete

2023-01-09 07:07 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardPopup/AttributionWizardPopup.tsx
> +  };
This code is duplicated three times and should be refactored to take `selectedIdPackageVersionList` etc as input in order to not to have to duplicate the code

2023-01-09 07:10 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardStepPackageNamespaceAndName/AttributionWizardStepPackageNamespaceAndName.tsx
> +export function AttributionWizardStepPackageNamespaceAndName(
Suggestion for shorter naming: `AttributionWizardPackageStep`

2023-01-09 07:11 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardStepPackageNamespaceAndName/AttributionWizardStepPackageNamespaceAndName.tsx
> +  selectedIdPackageNamespaceList: string;
I'd prefer `selectedPackageNamespaceId`. It feels more like a proper word. Also below

2023-01-09 07:12 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardStepPackageNamespaceAndName/AttributionWizardStepPackageNamespaceAndName.tsx
> +        listTitle={'Dummy title list 1'}
I'd suggest to already use the "proper" title. It makes it easier to already envision the future functionality

2023-01-09 07:13 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardStepPackageVersion/AttributionWizardStepPackageVersion.tsx
> +export function AttributionWizardStepPackageVersion(
Suggestion for shorter naming: `AttributionWizardVersionStep`

2023-01-09 07:13 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardStepPackageVersion/AttributionWizardStepPackageVersion.tsx
> +  selectedIdPackageVersionList: string;
AS above, the naming could be improved

2023-01-09 07:14 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardStepPackageVersion/AttributionWizardStepPackageVersion.tsx
> +      listTitle={'Dummy title list 3'}
Also here, consider using the proper title

2023-01-09 07:15 UTC, benedikt-richter commented on src/Frontend/Components/ListWithAttributes/ListWithAttributes.tsx
> +  listTitle?: string;
Here, the name `title` should be sufficient, as the component is a list. Therefore, I'd expect an attribute with name "title" to be the "listTitle"

2023-01-09 07:17 UTC, benedikt-richter commented on src/Frontend/Components/NotificationPopup/NotificationPopup.tsx
> +            isDark={false}
Why do we change this here? Did we check that none of the other popups is effected?

2023-01-09 07:19 UTC, benedikt-richter commented on src/shared/shared-types.ts
> +}
These seem to be unused. Please, remove these.

2023-01-09 09:18 UTC, vasily-pozdnyakov requested changes
Few suggestions:
- Test AttributionWizardBreadcrumbs component
- Do we really need separate components for the first and second steps? Maybe they can be parts of the popup.
- I would propose to use more realistic titles and names in the UI. They will be surely changed later, but currently it is quite difficult to follow the logic.
-  I would like to see the complete Breadcrumbs all the time with highlighted current step.
- Would be nice to show some informative tooltip over disabled Next button (e.g. "Please choose both namespace and name to navigate to the next step")

2023-01-09 10:38 UTC, lennartclaas commented on src/Frontend/Components/AttributionWizardBreadcrumbs/AttributionWizardBreadcrumbs.tsx
> +  onClick: (breadcrumbsIndex: number) => void;
👍 but needs discussion

2023-01-10 09:20 UTC, benedikt-richter requested changes

2023-01-10 09:20 UTC, benedikt-richter commented on src/Frontend/Components/Button/__tests__/Button.test.tsx
> +        tooltip={'test_tooltip'}
`'test_tooltip'` is a very strange tooltip title. Please choose more realistic one.

2023-01-10 09:20 UTC, benedikt-richter commented on src/Frontend/Components/Button/__tests__/Button.test.tsx
> +        tooltip={'test_tooltip'}
Also extract it into a constant, as it is also used in line 41

2023-01-10 09:20 UTC, benedikt-richter commented on src/Frontend/Components/ListWithAttributes/__tests__/ListWithAttributes.test.tsx
> +    const testListTitle = 'testTitle';
Consider using a more realistic title

2023-01-10 09:20 UTC, benedikt-richter commented on src/Frontend/Components/ListWithAttributes/__tests__/ListWithAttributes.test.tsx
> +    expect(screen.getByText('testTitle')).toBeInTheDocument();
Use the constant defined in line 35 here

2023-01-10 09:20 UTC, benedikt-richter commented on src/Frontend/types/types.ts
> +  tooltip?: string;
Also here `tooltipText` would be more appropriate

2023-01-10 09:20 UTC, benedikt-richter commented on src/Frontend/Components/NotificationPopup/NotificationPopup.tsx
> +            tooltip={props.centerRightButtonConfig.tooltip || ''}
This is inconsistent with line 93 and others.

Furthermore, it could be `props.centerRightButtonConfig?.tooltip`.

2023-01-10 09:20 UTC, benedikt-richter commented on src/Frontend/Components/NotificationPopup/NotificationPopup.tsx
> +            isDark={props.centerLeftButtonConfig.isDark ?? false}
this is inconsistent with line 82

2023-01-10 09:20 UTC, benedikt-richter commented on src/Frontend/Components/NotificationPopup/NotificationPopup.tsx
> +            isDark={props.centerRightButtonConfig.isDark ?? false}
could be `Boolean(props.centerRightButtonConfig.isDark)`

2023-01-10 09:20 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardPopup/AttributionWizardPopup.tsx
> +  // redundancy with disabled next button necessary?
remove comment

2023-01-10 09:20 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardPopup/AttributionWizardPopup.tsx
> +  const numberOfSteps = wizardStepIds.length;
There is no need for this number. It makes the code less radable. 
For the logic it should be sufficient to know the id of the first breadcumb and of the last one. This would also improve readibility in e.g. line 69

2023-01-10 09:20 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardPopup/AttributionWizardPopup.tsx
> +  function handleBreadcrumbsClick(breadcrumbsId: string): void {
This function could be inlined

2023-01-10 09:20 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardPopup/AttributionWizardPopup.tsx
> +    setSelectedWizardStepId(breadcrumbsId);
`breadcrumbsId` actually is `wizardStepId`

2023-01-10 09:20 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardPopup/AttributionWizardPopup.tsx
> +      selectedPackageNamespaceId === '' || selectedPackageNameId === '',
could be `!selectedPackageNamespaceId || !selectedPackageNameId` and be extracted as it is also used below

2023-01-10 09:20 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardPopup/AttributionWizardPopup.tsx
> +    tooltip:
The tooltip should be placed left or above. Currently it is outside of the popup.

2023-01-10 11:16 UTC, lennartclaas commented on src/Frontend/Components/NotificationPopup/NotificationPopup.tsx
> +            isDark={props.centerRightButtonConfig.isDark ?? false}
At least for me, Boolean is harder to understand. With the current implementation, one can clearly see that the default value is false if the prop is undfined. In Boolean, this information is "hidden".

2023-01-10 11:45 UTC, lennartclaas commented on src/Frontend/Components/AttributionWizardPopup/AttributionWizardPopup.tsx
> +      selectedPackageNamespaceId === '' || selectedPackageNameId === '',
I swapped the boolean: `const packageNamespaceAndNameSelected: boolean = selectedPackageNamespaceId !== '' && selectedPackageNameId !== '';`

2023-01-10 11:47 UTC, benedikt-richter commented on src/Frontend/Components/NotificationPopup/NotificationPopup.tsx
> +            isDark={props.centerLeftButtonConfig.isDark ?? false}
The current implementation is not very intuitive as there are different defaults based on the placement of the button. BEtter to always have the same default and to overwrite where necessary.

2023-01-10 14:19 UTC, lennartclaas commented on src/Frontend/Components/NotificationPopup/NotificationPopup.tsx
> +            isDark={props.centerRightButtonConfig.isDark ?? false}
Used `Boolean `now.

2023-01-10 14:20 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardPopup/AttributionWizardPopup.tsx
> +      selectedPackageNamespaceId === '' || selectedPackageNameId === '',
I'd prefer the first one, as it's easier to read

2023-01-11 09:07 UTC, vasily-pozdnyakov commented
When the Next button is disabled (e.g. no package chosen), user can still navigate to the next screen by clicking the breadcrumbs.

2023-01-11 10:22 UTC, benedikt-richter requested changes
Some last minor points

2023-01-11 10:22 UTC, benedikt-richter commented on package.json
> +    "test:single": "react-scripts test src/Frontend/integration-tests/audit-view-tests/__tests-ci__/save-attributions.test.tsx --watchAll=false --setupFilesAfterEnv=./setupTests.ts",
has to be removed before merging

2023-01-11 10:22 UTC, benedikt-richter commented on src/Frontend/Components/AttributionColumn/PackageSubPanel.tsx
> +              disabled={!props.isEditable}
👍

2023-01-11 10:22 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardPopup/AttributionWizardPopup.tsx
> +        selectedWizardStepId !== wizardStepIds[wizardStepIds.length - 1]
above we used `wizardStepIds[-1]`instead of `wizardStepIds[wizardStepIds.length - 1]`

2023-01-11 10:22 UTC, benedikt-richter commented on src/Frontend/Components/Breadcrumbs/Breadcrumbs.tsx
> +    ([id, ,]) => id
optional: `([id, ,]) => id` could be `(selectedIdToDisplayValue) => selectedIdToDisplayValue[0]`

2023-01-11 10:22 UTC, benedikt-richter commented on src/Frontend/Components/Breadcrumbs/Breadcrumbs.tsx
> +  selectedIdToDisplayValue: Array<[string, string]>;
Just realized `selectedIdToDisplayValue` should be `selectedIdsToDisplayValues` as it's multiple

2023-01-11 10:22 UTC, benedikt-richter commented on src/Frontend/Components/Button/Button.tsx
> +type ButtonProps = ButtonConfig;
👍

2023-01-11 10:22 UTC, benedikt-richter commented on src/Frontend/Components/FetchLicenseInformationButton/FetchLicenseInformationButton.tsx
> +  disabled: boolean;
awesome!

2023-01-11 10:22 UTC, benedikt-richter commented on src/Frontend/Components/PackageCard/PackageCard.tsx
> +            hidden: isExternalAttribution || hideResourceSpecificButtons,
to be reverted before merging

2023-01-11 10:45 UTC, lennartclaas commented on src/Frontend/Components/AttributionWizardPopup/AttributionWizardPopup.tsx
> +        selectedWizardStepId !== wizardStepIds[wizardStepIds.length - 1]
Good point. That's a bug. Negative array indices return `undefined` in javascript. Hard for me as a person used to Python. :D

2023-01-11 12:06 UTC, benedikt-richter approved these changes

2023-01-11 12:44 UTC, vasily-pozdnyakov approved these changes
Looks nice, well done!

2023-01-11 12:45 UTC, merged