[BugFix] Do not show tooltip for hidden button
opossum-tool/OpossumUI pull request #1318
Opened 2023-01-12 11:59 UTC by someshkhandelia

### Summary of changes

[BugFix] Do not show tooltip for hidden button

### Context and reason for change

- We keep the text shown in tooltip as empty to not let the tooltip render, when IconButton has visibility:hidden.
- The approach of keeping visibility:hidden for tooltip did not work.

Fix: #1290

### How can the changes be tested

- Load the large_opossum_input.json.gz file in the application
- In the right corner of PathBar of AuditView, the tooltip is no longer visible since the button is hidden. 

Signed-off-by: someshkhandelia <someshkhandelia@gmail.com>

2023-01-12 12:01 UTC, someshkhandelia commented
I still have to add tests. I can add them if the implementation of the bug-fix is considered satisfactory by the reviewers.

2023-01-12 12:12 UTC, benedikt-richter requested changes

2023-01-12 12:12 UTC, benedikt-richter commented on src/Frontend/Components/IconButton/IconButton.tsx
> +  });
It is not a good practice to parse styling in order to set variables in code. If we provide styling to a component it should just be applied and not have other effects.

Better: set the tooltip title to an empty string where it is used, i.e. in `GoToLinkButton`.

2023-01-12 12:46 UTC, lennartclaas commented on src/Frontend/Components/IconButton/IconButton.tsx
> +  });
@benedikt-richter What about adding a new prop `hidden` instead of hiding the `IconButton` via sx?

2023-01-12 12:51 UTC, benedikt-richter commented on src/Frontend/Components/IconButton/IconButton.tsx
> +  });
That's a good idea!

2023-01-12 13:03 UTC, someshkhandelia commented on src/Frontend/Components/IconButton/IconButton.tsx
> +  });
Working on adding a new prop `hidden`. Thanks for the comments guys!

2023-01-12 13:36 UTC, benedikt-richter commented on src/Frontend/Components/IconButton/IconButton.tsx
> +
Please, remove empty lines

2023-01-12 13:36 UTC, benedikt-richter commented on src/Frontend/Components/IconButton/IconButton.tsx
> +          sx={props.hidden ? { visibility: 'hidden', ...props.sx } : props.sx}
Would be good to extract the styling like 
```

const classes = {
  hidden: {
    visibility: 'hidden',
  }
};
```

2023-01-12 13:38 UTC, benedikt-richter commented
Works nicely 👍 
Just two minor points

2023-01-12 13:53 UTC, lennartclaas requested changes
Elegant solution. 👍

2023-01-12 14:00 UTC, someshkhandelia commented on src/Frontend/Components/IconButton/IconButton.tsx
> +
I actually did not touch those parts of the code. I just added the last line `hidden?: boolean`. Maybe the pre-commit hook added it or something. I will remove it manually now and create a commit, but not sure if the hook will re-add it.

2023-01-12 15:13 UTC, someshkhandelia commented on src/Frontend/Components/IconButton/IconButton.tsx
> +
Linter is not allowing me to do this. If I push without running pre-commit hooks, the tests in the online GIT CLI fail.

2023-01-12 15:14 UTC, someshkhandelia commented on src/Frontend/Components/IconButton/IconButton.tsx
> +          sx={props.hidden ? { visibility: 'hidden', ...props.sx } : props.sx}
Me, Leslie and Lennart found a weird thing. For `visibility` it only works inline. The `classes` approach works for everything except `visibility`

2023-01-12 15:24 UTC, someshkhandelia commented on src/Frontend/Components/IconButton/IconButton.tsx
> +
I committed without running pre-commit hooks. But I think if someone touches those lines, those blank lines will come back again from the Linter.

2023-01-12 15:52 UTC, benedikt-richter commented on src/Frontend/Components/IconButton/IconButton.tsx
> +          sx={props.hidden ? { visibility: 'hidden', ...props.sx } : props.sx}
Interesting. In this case it is fine. However, I would add a comment in code, as otherwise somebody will refactor it and thus introduce a bug.

2023-01-13 06:54 UTC, benedikt-richter commented on src/Frontend/Components/IconButton/IconButton.tsx
> +          sx={props.hidden ? { visibility: 'hidden', ...props.sx } : props.sx}
Or better: In this special situation we could have a test testing in particular the styling, i.e. that the hidden flag works.

2023-01-13 13:19 UTC, someshkhandelia commented on src/Frontend/Components/IconButton/IconButton.tsx
> +          sx={props.hidden ? { visibility: 'hidden', ...props.sx } : props.sx}
Done.

2023-01-13 13:33 UTC, benedikt-richter requested changes
Add a test for the styling (element being hidden), see https://github.com/opossum-tool/OpossumUI/pull/1318/files#r1068995740

2023-01-13 13:33 UTC, benedikt-richter commented on src/Frontend/Components/IconButton/__tests__/IconButton.test.tsx
> +  it('does not render tooltip when hidden flag is active', () => {
here we should also check that the styling `visibility: 'hidden'` is applied.

2023-01-13 13:33 UTC, benedikt-richter commented on src/Frontend/Components/IconButton/__tests__/IconButton.test.tsx
> +    expect(screen.getByTitle('Test'));
-> `expect(screen.getByTitle('Test')).toBeInTheDocument();`

2023-01-13 13:33 UTC, benedikt-richter commented on src/Frontend/Components/IconButton/__tests__/IconButton.test.tsx
> +    expect(() => screen.getByTitle('Test')).toThrow();
-> `expect(() => screen.queryByTitle('Test')).toBeInTheDocument()`

2023-01-13 13:33 UTC, benedikt-richter commented on src/Frontend/Components/IconButton/IconButton.tsx
> +          // TypeScript issue:
not sure this is a typescript issue. Might be a MUI issue as well...

2023-01-13 13:46 UTC, someshkhandelia commented on src/Frontend/Components/IconButton/IconButton.tsx
> +          // TypeScript issue:
True.

2023-01-13 13:50 UTC, someshkhandelia commented on src/Frontend/Components/IconButton/__tests__/IconButton.test.tsx
> +    expect(screen.getByTitle('Test'));
Fixed.

2023-01-13 13:58 UTC, someshkhandelia commented on src/Frontend/Components/IconButton/__tests__/IconButton.test.tsx
> +    expect(() => screen.getByTitle('Test')).toThrow();
This command wasn't working. (This is a negative test, we are not supposed to find the element with title "Test")

Used this instead:
`expect(screen.queryByTitle('Test')).toBeNull();`

2023-01-13 14:12 UTC, benedikt-richter commented on src/Frontend/Components/IconButton/IconButton.tsx
> +          sx={props.hidden ? { visibility: 'hidden', ...props.sx } : props.sx}
Just remembered. Maybe try using our util function `getSxFromPropsAndClasses`

2023-01-13 14:38 UTC, benedikt-richter commented on src/Frontend/Components/IconButton/__tests__/IconButton.test.tsx
> +    expect(screen.getByLabelText('Test')).toHaveStyle('visibility: hidden');
👍

2023-01-13 14:38 UTC, benedikt-richter approved these changes

2023-01-13 15:07 UTC, someshkhandelia commented on src/Frontend/Components/IconButton/IconButton.tsx
> +          sx={props.hidden ? { visibility: 'hidden', ...props.sx } : props.sx}
Fixed.

2023-01-13 15:12 UTC, lennartclaas commented on src/Frontend/Components/IconButton/IconButton.tsx
> +          }
Nice. 👍

2023-01-13 15:12 UTC, lennartclaas approved these changes

2023-01-13 15:52 UTC, merged