Attribution Wizard: Finalize first wizard step
opossum-tool/OpossumUI pull request #1319
Opened 2023-01-12 13:00 UTC by lennartclaas

### Summary of changes

Relevant data is taken from the redux state and processed in order to fill the lists of the first wizard step (package namespace and version). The second wizard step isn't touched. 

### Further comments
Only the large `input_from_ort.json.gz` provides reasonable data for the wizard but the performance is poor. Maybe we should create a new more appropriate file.

Example image captured with `input_from_ort.json.gz` and resource `package.json`
![Unbenannt](https://user-images.githubusercontent.com/83081698/212072797-c960e134-e6f2-441d-a934-8a13c0b2f460.PNG)

Fix: #1281

2023-01-12 16:53 UTC, MarkusObendrauf requested changes
I would guess the performance issues you described are caused by `localeCompare` and are trivial to fix :)

2023-01-12 16:53 UTC, MarkusObendrauf commented on src/Frontend/Components/AttributionWizardPopup/attribution-wizard-popup-helpers.tsx
> +      containedExternalPackage['childrenWithAttributionCount'] ?? 0;
functional might be nicer, but its a matter of taste. something like
```
let totalCountAttributions = containedExternalPackages
  .map(containedExternalPackage => containedExternalPackage['childrenWithAttributionCount'] ?? 0)
  .reduce((accumulator, current) => accumulator + current, 0);
```

2023-01-12 16:53 UTC, MarkusObendrauf commented on src/Frontend/Components/AttributionWizardPopup/attribution-wizard-popup-helpers.tsx
> +    return a.text.localeCompare(b.text, undefined, {
localeCompare is extremely slow and has led to performance issues in the past, see https://github.com/opossum-tool/OpossumUI/pull/889. dont use it.

2023-01-12 16:53 UTC, MarkusObendrauf commented on src/Frontend/Components/AttributionWizardPopup/attribution-wizard-popup-helpers.tsx
> +    return 1;
there is nothing special about returning -1 or 1, all that matters is if the number is greater than 0, less than 0, or equal to 0. So you can write
`if (a.count != b.count) return b.count - a.count`

2023-01-12 16:53 UTC, MarkusObendrauf commented on src/Frontend/Components/AttributionWizardPopup/attribution-wizard-popup-helpers.tsx
> +}
this function just does the same thing twice. can you instead make a function that you call two times?

2023-01-12 16:53 UTC, MarkusObendrauf commented on src/Frontend/Components/ListWithAttributes/ListWithAttributes.tsx
> +    // TODO: Now: Single scroll bar for each list item.
assuming this one is left intentionally

2023-01-12 16:53 UTC, MarkusObendrauf commented on src/shared/shared-types.ts
> +export interface AttributionWizardListItemAttribute {
please come up with a better name

2023-01-12 16:53 UTC, MarkusObendrauf commented on src/shared/shared-types.ts
> +export interface AttributionWizardListItemAttribute {
are these used anywhere?

2023-01-13 07:15 UTC, benedikt-richter requested changes
Still have to review the new helper functions

2023-01-13 07:15 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardPackageStep/AttributionWizardPackageStep.tsx
> +  packageNameListItems: Array<ListWithAttributesItem>;
maybe the "ListItem" part could be removed in all. It is technical and does not provide a lot of information. Suggestion "packageNameListItems" -> "attributedPackageNames" and also others

2023-01-13 07:15 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardPackageStep/AttributionWizardPackageStep.tsx
> +        title={'Package namespaces'}
I'd leave the singular, as we are only looking for a single one and we expect a single one for a package. Alternatively "Package namespace options".

2023-01-13 07:15 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardPopup/AttributionWizardPopup.tsx
>  // const POPUP_CONTENT_PADDING = 48; // TODO: monitored in upcoming tickets
is there a result of monitoring?

2023-01-13 07:15 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardPopup/AttributionWizardPopup.tsx
>    const packageNamespaceAndNameSelected: boolean =
`: boolean` is not necessary

2023-01-13 07:15 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardPopup/AttributionWizardPopup.tsx
> +  const externalAttributions = externalData['attributions'];
this can be inlined. Just use `externalData.attributions` instead of `externalAttributions` or move this line up to the selectors to have the "data fetching" at one place.

2023-01-13 07:15 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardPopup/__tests__/AttributionWizardPopup.test.tsx
> +  const testStore = createTestAppStore();
This is very very dangerous! All tests use the same store and thus there can be side effects that are very difficult to debug. Use a different store for each test.

2023-01-13 07:15 UTC, benedikt-richter commented on src/Frontend/Components/ListWithAttributes/ListWithAttributes.tsx
> +    // whiteSpace: 'nowrap',
remove comment

2023-01-13 07:15 UTC, benedikt-richter commented on src/Frontend/Components/ListWithAttributes/ListWithAttributes.tsx
> +              sx={Object.assign(classes.listItem, props.sx)}
Typically we use `{...classes.listItem, ...props.sx}` instead of `Object.assign(classes.listItem, props.sx)`

2023-01-13 07:15 UTC, benedikt-richter commented on src/Frontend/Components/ListWithAttributes/ListWithAttributes.tsx
> +  sx?: SxProps;
As this does not get attached to the root element of this component, I'd prefer a more descriptive name like e..g `listItemSx`

2023-01-13 09:16 UTC, benedikt-richter requested changes

2023-01-13 09:16 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardPopup/attribution-wizard-popup-helpers.tsx
> +function sortPackageData(packageDataAndCounts: {
Why is this called `sortPackageData`? 
If I look at the function I do not see `packageData` and  `Counts`.

2023-01-13 09:16 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardPopup/attribution-wizard-popup-helpers.tsx
> +    .map(([dataName, count]) => ({
in my opinion `dataName` is too abstact. It is almost never good to have `Data` as part of a variable name.

2023-01-13 09:16 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardPopup/attribution-wizard-popup-helpers.tsx
> +  const packageNamesAndCountsArray = sortPackageData(packageNamesAndCounts);
as above

2023-01-13 09:16 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardPopup/attribution-wizard-popup-helpers.tsx
> +  return Object.entries(packageDataAndCounts)
this seems very expensive for a huge number of attributed children.

2023-01-13 09:16 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardPopup/attribution-wizard-popup-helpers.tsx
> +  return packageAttributesListItems;
Could be something like the following with much improved naming

```
function getWizardListItems(
  packageAttributesAndCountsArray: Array<TextAndCount>,
  totalCountAttributes: number,
  idPrefix: string
): Array<ListWithAttributesItem> {
  return packageAttributesAndCountsArray.map((packageAttributeAndCount) =>
    getWizardListItem(packageAttributeAndCount, totalCountAttributes, idPrefix)
  );
}

function getWizardListItem(
  packageAttributeAndCount: TextAndCount,
  totalCountAttributes: number,
  idPrefix: string
): ListWithAttributesItem {
  const count = packageAttributeAndCount.count;
  const packageAttribute = packageAttributeAndCount.text;
  return {
    text: packageAttribute,
    id: `${idPrefix}-${packageAttribute}`,
    attributes: [
      {
        text: `count: ${count} (${(
          (count / totalCountAttributes) *
          100
        ).toFixed(1)}%)`,
        id: `${idPrefix}-attribute-${packageAttribute}`,
      },
    ],
  };
}

```

2023-01-13 09:36 UTC, lennartclaas commented on src/Frontend/Components/AttributionWizardPopup/AttributionWizardPopup.tsx
> +  // const popupAttributionId = useAppSelector(getPopupAttributionId);  // TODO: required later
In an upcoming ticket, we need the current attribution id to update the package info in the redux state. This is just a reminder.

2023-01-13 09:46 UTC, lennartclaas commented on src/Frontend/Components/AttributionWizardPopup/attribution-wizard-popup-helpers.tsx
> +      containedExternalPackage['childrenWithAttributionCount'] ?? 0;
I like it. Although `reduce `usually decreases readability. But in this case, it is quite clear.

2023-01-13 10:05 UTC, lennartclaas commented on src/Frontend/Components/AttributionWizardPopup/attribution-wizard-popup-helpers.tsx
> +    return 1;
Nice.

2023-01-13 10:11 UTC, lennartclaas commented on src/Frontend/Components/AttributionWizardPopup/attribution-wizard-popup-helpers.tsx
> +    return a.text.localeCompare(b.text, undefined, {
I did some logging and `localCompare`  seems not to be the issue. It's the rendering process itself, if we have long lists. However, replacing `localCompare` with a simple `return a.text.toLowerCase() < b.text.toLowerCase() ? -1 : 1;` reduced sorting time from about 20ms down to 0.8ms for the large ort file. 👍

2023-01-13 10:13 UTC, lennartclaas commented on src/Frontend/Components/AttributionWizardPopup/attribution-wizard-popup-helpers.tsx
> +    return a.text.localeCompare(b.text, undefined, {
It could make sense to add a new ticket for checking whether `localeCompare` can be replaced with a simpler expression at other locations of the project.

2023-01-13 10:20 UTC, lennartclaas commented on src/Frontend/Components/AttributionWizardPopup/attribution-wizard-popup-helpers.tsx
> +}
That would be possible. But in this case, we would have two `for` loops instead of just a single one. Since containedExternalPackages could become quite large, it could affect the performance.

2023-01-13 10:21 UTC, lennartclaas commented on src/Frontend/Components/ListWithAttributes/ListWithAttributes.tsx
> +    // TODO: Now: Single scroll bar for each list item.
Yes. Each comment that is marked with `TODO` is intentional.

2023-01-13 10:22 UTC, lennartclaas commented on src/shared/shared-types.ts
> +export interface AttributionWizardListItemAttribute {
We discussed a long time about this naming. :D I would not like to change it again unless there is a really convincing reason.

2023-01-13 10:25 UTC, lennartclaas commented on src/shared/shared-types.ts
> +export interface AttributionWizardListItemAttribute {
Good point. Strange remnant... The interfaces are defined in `src/Frontend/types/types.ts`.

2023-01-13 10:27 UTC, lennartclaas commented on package.json
> +    "test:single": "react-scripts test src/Frontend/Components/AttributionWizardPopup/__tests__/AttributionWizardPopup.test.tsx --watchAll=false --setupFilesAfterEnv=./setupTests.ts",
It's hard to remember. 😄

2023-01-13 10:28 UTC, lennartclaas commented on src/Frontend/Components/AttributionWizardPopup/AttributionWizardPopup.tsx
>  // const POPUP_CONTENT_PADDING = 48; // TODO: monitored in upcoming tickets
After having populated the list of the second step with real data (next ticket).

2023-01-13 10:36 UTC, lennartclaas commented on src/Frontend/Components/ListWithAttributes/ListWithAttributes.tsx
> +              sx={Object.assign(classes.listItem, props.sx)}
This produces an error "No overload matches this call.". `{ ...classes.listItem, ...props.sx } as SxProps` does the trick but we don't like castings.

2023-01-13 10:50 UTC, lennartclaas commented on src/Frontend/Components/AttributionWizardPopup/attribution-wizard-popup-helpers.tsx
> +      containedExternalPackage['childrenWithAttributionCount'] ?? 0;
Very good point. Haven't thought about this yet. I also changed this at other locations.

2023-01-13 11:00 UTC, lennartclaas commented on src/Frontend/Components/AttributionWizardPopup/attribution-wizard-popup-helpers.tsx
> +  return Object.entries(packageDataAndCounts)
Sorting does take less than 1ms for the large ort file.

2023-01-13 11:03 UTC, lennartclaas commented on src/Frontend/Components/AttributionWizardPopup/attribution-wizard-popup-helpers.tsx
> +function sortPackageData(packageDataAndCounts: {
This function can be used to sort `packageNamespacesAndCounts` and `packageNamesAndCounts`. We therefore need an expression that includes namespaces and names and counts. But it's true that data is rather generic. WHat about `sortPackageAttributesAndCounts`?

2023-01-13 11:04 UTC, lennartclaas commented on src/Frontend/Components/AttributionWizardPopup/attribution-wizard-popup-helpers.tsx
> +function sortPackageData(packageDataAndCounts: {
But when I think about it, this could lead to confusion with the `attributes` in the `ListWithAttributesItem`.

2023-01-13 11:06 UTC, lennartclaas commented on src/Frontend/Components/AttributionWizardPopup/attribution-wizard-popup-helpers.tsx
> +  const packageNamesAndCountsArray = sortPackageData(packageNamesAndCounts);
see above

2023-01-13 14:34 UTC, lennartclaas commented on src/Frontend/Components/AttributionWizardPopup/attribution-wizard-popup-helpers.tsx
> +        : 'empty'; // for monitoring during development
I see. I experienced that namespaces and names in the `PackageInfo` of our test files are sometimes undefined (read as 'none') or just empty strings (read as 'empty'). So far, I can only guess if this can also happen with real data.

2023-01-13 14:36 UTC, lennartclaas commented on src/Frontend/Components/ListWithAttributes/ListWithAttributes.tsx
> +              sx={Object.assign(classes.listItem, props.sx)}
Solved with `getSxFromPropsAndClasses`.

2023-01-13 14:42 UTC, lennartclaas commented on src/Frontend/Components/AttributionWizardPackageStep/AttributionWizardPackageStep.tsx
> +        title={'Package namespaces'}
Used singular.

2023-01-13 15:01 UTC, lennartclaas commented on src/Frontend/Components/AttributionWizardPopup/AttributionWizardPopup.tsx
> +  const [packageNamespaceListItems, packageNameListItems] =
Okay, I changed it to `attributedPackageNamespaces `and `attributedPackageNames`.

2023-01-16 08:42 UTC, MarkusObendrauf commented on src/Frontend/Components/AttributionWizardPopup/attribution-wizard-popup-helpers.tsx
> +}
was this measured?

2023-01-16 08:45 UTC, MarkusObendrauf approved these changes
Looks good, I would still like to see a refactor of `getPackageNamespacesAndNamesWithCounts` but maybe it's not so simple to do.

2023-01-16 09:33 UTC, lennartclaas commented on src/Frontend/Components/AttributionWizardPopup/attribution-wizard-popup-helpers.tsx
> +}
Actually, the difference is just a fracture of a millisecond. I will refactor it.

2023-01-16 16:07 UTC, benedikt-richter approved these changes

2023-01-16 17:07 UTC, merged