Attribution Wizard: Finalize Step 2
opossum-tool/OpossumUI pull request #1329
Opened 2023-01-17 11:20 UTC by lennartclaas

### Summary of changes

In step 2 of the wizard, a package version is selected based on the previously selected package namespace and name in step 1.  The changes include mostly business logic that provides possible versions given the package name. This PR does not include an "apply" functionality. 

Screenshot of the second wizard step with large ort file.
![Unbenannt](https://user-images.githubusercontent.com/83081698/212885959-d8b67b41-a6e5-4c35-98c6-897e79db7189.png)

Fix: #1282

2023-01-17 12:14 UTC, benedikt-richter requested changes
First part of review.

2023-01-17 12:14 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardPopup/AttributionWizardPopup.tsx
> +  const popupPackage =
I think we never use the term "Package".

2023-01-17 12:14 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardPopup/AttributionWizardPopup.tsx
> +                selectedPackageVersion={selectedPackageVersion}
why do we not provide the ids? We should pass the identifiers to the component and not their values.

2023-01-17 12:14 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardPopup/__tests__/AttributionWizardPopup.test.tsx
> +    packageNamespace: 'pkg:npm',
The namespace does not contain `pkg:`

2023-01-17 12:14 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardPopup/__tests__/AttributionWizardPopup.test.tsx
> +    packageNamespace: 'pkg:npm',
also other occurrences

2023-01-17 12:14 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardPopup/__tests__/attribution-wizard-popup-helpers.test.tsx
> +const emptyAttribute = '\u2014';
better to just use `-`

2023-01-17 12:14 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardVersionStep/AttributionWizardVersionStep.tsx
> +      >{`${props.selectedPackageNamespace}/${props.selectedPackageName}@${props.selectedPackageVersion}`}</MuiTypography>
There is a util we use for constructing and paring PURLs: `handle-purl.ts`

2023-01-17 12:14 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardPopup/attribution-wizard-popup-helpers.tsx
> +const emptyAttribute = '\u2014';
better to use `-`.

2023-01-17 12:22 UTC, vasily-pozdnyakov commented
For me it fails almost all the time with `Cannot read properties of undefined (reading 'text')`

2023-01-19 08:51 UTC, vasily-pozdnyakov commented
Why is there "%20" in the full package string?
![image](https://user-images.githubusercontent.com/85183359/213396931-e452d3a8-cc3f-4973-ba2d-061c34a3b995.png)

2023-01-19 09:22 UTC, lennartclaas commented
@vasily-pozdnyakov regarding your [comment](https://github.com/opossum-tool/OpossumUI/pull/1329#issuecomment-1396631861):
This is a property of the PURL. In URL encodings, special characters are encoded by using a percentage sign, e.g., @ --> %40. I assume that %20 means a space.

2023-01-19 11:32 UTC, vasily-pozdnyakov requested changes
Nice. Just few minor changes.

2023-01-19 11:32 UTC, vasily-pozdnyakov commented on src/Frontend/Components/AttributionWizardPopup/AttributionWizardPopup.tsx
> +  const externalAndManualAttributionIdsOfResourceAndChildrenWithCounts =
Can the variable name be shortened? The same like function name.

2023-01-19 11:32 UTC, vasily-pozdnyakov commented on src/Frontend/Components/AttributionWizardPopup/AttributionWizardPopup.tsx
> +      ? attributedPackageNamespaces.filter(
Should maybe the filtering part be extracted into a separate local function? Exactly the same logic is used multiple times.

2023-01-19 11:32 UTC, vasily-pozdnyakov commented on src/Frontend/Components/AttributionWizardPopup/AttributionWizardPopup.tsx
>                  selectedPackageVersionId={selectedPackageVersionId}
Proposal: combine them into one constant? Like 
selectedInfo:{
selectedPackageNamespace: string,
selectedPackageName: string,
selectedPackageVersion: string,
selectedPackageVersionId: string
}

2023-01-19 11:32 UTC, vasily-pozdnyakov commented on src/Frontend/Components/GlobalPopup/__tests__/GlobalPopup.test.tsx
>      expect(screen.getByText('Attribution Wizard')).toBeInTheDocument();
Can we also test that the content of the popup is correctly rendered?

2023-01-19 14:22 UTC, lennartclaas commented on src/Frontend/Components/AttributionWizardPopup/__tests__/attribution-wizard-popup-helpers.test.tsx
> +const emptyAttribute = '-';
I'm not exactly sure what you mean. If attributes like the packageVersion, packageName, or packageNamespace are not given, a dash is displayed in the lists. The same holds if only an empty string is given.

2023-01-19 14:26 UTC, lennartclaas commented on src/Frontend/Components/AttributionWizardPopup/AttributionWizardPopup.tsx
> +  const externalAndManualAttributionIdsOfResourceAndChildrenWithCounts =
Okay, see above.

2023-01-19 14:40 UTC, lennartclaas commented on src/Frontend/Components/AttributionWizardPopup/__tests__/attribution-wizard-popup-helpers.test.tsx
> +const emptyAttribute = '-';
Ah, you mean to import the constant form the attribution-wizard-popup-helpers.tsx. Done. 👍

2023-01-19 14:41 UTC, lennartclaas commented on src/Frontend/Components/AttributionWizardPopup/AttributionWizardPopup.tsx
> +      ? attributedPackageNamespaces.filter(
It is actually used two times. The third one has to be slightly different. I don't think we gain much from refactoring it.

2023-01-19 14:42 UTC, lennartclaas commented on src/Frontend/Components/AttributionWizardPopup/AttributionWizardPopup.tsx
>                  selectedPackageVersionId={selectedPackageVersionId}
Jep. I used the PackageInfo interface. 👍

2023-01-19 14:46 UTC, lennartclaas commented on src/Frontend/Components/GlobalPopup/__tests__/GlobalPopup.test.tsx
>      expect(screen.getByText('Attribution Wizard')).toBeInTheDocument();
Testing the content is done in `AttributionWizardPopup.test.tsx` and `ListWithAttributes.test.tsx`. In `GlobalPopup.test.tsx` we just ensure that the Wizard can be opened via dispatching.

2023-01-19 15:33 UTC, benedikt-richter approved these changes

2023-01-19 16:40 UTC, merged