Attribution Wizard: Add apply functionality.
opossum-tool/OpossumUI pull request #1340
Opened 2023-01-23 12:46 UTC by lennartclaas

### Summary of changes

Choosing package namespace, name, and version in the wizard and clicking 'apply' updates the temporary package info via a corresponding dispatch.

Fix: #1283

2023-01-23 12:47 UTC, lennartclaas commented on src/Frontend/Components/AttributionWizardPopup/AttributionWizardPopup.tsx
> +        packageNamespace: selectedPackageInfo.packageNamespace,
I gues I can shorten that by `...selectedPackageInfo`

2023-01-23 13:03 UTC, benedikt-richter requested changes

2023-01-23 13:03 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardPopup/__tests__/AttributionWizardPopup.test.tsx
> +describe('AttributionWizardPopup apply', () => {
It's strange to have `describe('AttributionWizardPopup apply', () => {` next to `describe('AttributionWizardPopup', () => {`

2023-01-24 12:52 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardPopup/AttributionWizardPopup.tsx
> +  emptyAttribute,
I really dislike this magic string similar to the one treated in #1194. Will have to get rid of this one

2023-01-24 12:55 UTC, MarkusObendrauf requested changes
Nice! Just a few small requests.

2023-01-24 12:55 UTC, MarkusObendrauf commented on src/Frontend/Components/AttributionWizardPackageStep/AttributionWizardPackageStep.tsx
> +  console.log(props.selectedPackageInfo);
remove

2023-01-24 12:55 UTC, MarkusObendrauf commented on src/Frontend/Components/AttributionWizardPopup/AttributionWizardPopup.tsx
> +  const packageVersionSelected = selectedPackageVersionId !== '';
I prefer `isPackageVersionSelected` (and `isPackageNamespaceAndNameSelected`). Otherwise, I might think `packageVersionSelected` refers to the package version that was selected.

2023-01-24 12:55 UTC, MarkusObendrauf commented on src/Frontend/Components/AttributionWizardPopup/AttributionWizardPopup.tsx
> +        : undefined,
please reverse the ternaries i.e.
`selectedPackageName === emptyAttribute ? undefined : selectedPackageName`
to avoid double negatives

2023-01-24 12:55 UTC, MarkusObendrauf commented on src/Frontend/Components/AttributionWizardPopup/AttributionWizardPopup.tsx
> +        : undefined,
also you could reduce the number of ternaries with
`const selectedPackageInfo: PackageInfo = selectedPackageNamespace === emptyAttribute ? { ... } : { ... }`
would be more readable imo

2023-01-24 12:55 UTC, MarkusObendrauf commented on src/Frontend/Components/AttributionWizardPopup/AttributionWizardPopup.tsx
> +      : '',
please reverse

2023-01-24 12:55 UTC, MarkusObendrauf commented on src/Frontend/Components/AttributionWizardPopup/__tests__/AttributionWizardPopup.test.tsx
>      expect(screen.queryByText(versionListTitle)).not.toBeInTheDocument();
please also check that there is no 'back' button on the first page or 'next' button on the last page

2023-01-24 15:09 UTC, lennartclaas commented on src/Frontend/Components/AttributionWizardPopup/__tests__/AttributionWizardPopup.test.tsx
>      expect(screen.queryByText(versionListTitle)).not.toBeInTheDocument();
I added the checks in `it('allows navigation via "next" and "back" buttons' ...`

2023-01-24 15:55 UTC, MarkusObendrauf commented on src/Frontend/Components/AttributionWizardPopup/AttributionWizardPopup.tsx
> +        : undefined,
understandable

2023-01-24 15:56 UTC, MarkusObendrauf approved these changes
Nice

2023-01-25 10:28 UTC, benedikt-richter approved these changes

2023-01-25 13:06 UTC, merged