Attribution Wizard: Improve Styling
opossum-tool/OpossumUI pull request #1357
Opened 2023-01-26 06:52 UTC by lennartclaas

### Summary of changes

Adapt the wizard styling such that it looks cohesive to the rest of the app.

### Test changes

Open the attribution wizard via the context menu of a manual attribution in audit view. Make sure that you select a folder which contains a reasonable amount of signals.

Fix: #1322

2023-01-26 07:07 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardVersionStep/AttributionWizardVersionStep.tsx
> +  },
This seems to be shared styling

2023-01-26 07:07 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardVersionStep/AttributionWizardVersionStep.tsx
>  const PURL_HEIGHT = 45;
This is duplicated

2023-01-26 07:08 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardPopup/AttributionWizardPopup.tsx
> +const BREADCRUMBS_HEIGHT = 42.391;
I'm not sure this is the best way to do it. Extacting all heights and widths into constants does, in my opinion, not make it easier to read and work with.

2023-01-26 07:09 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardPopup/AttributionWizardPopup.tsx
> +const BREADCRUMBS_HEIGHT = 42.391;
This number is precise up to 3 digits after the comma? I guess, it should be integer.

2023-01-26 07:10 UTC, benedikt-richter commented on src/Frontend/Components/ListWithAttributes/ListWithAttributes.tsx
>  const LIST_WITH_ATTRIBUTES_VERTICAL_BORDER_AND_MARGIN = 10; // 10px = margin + border
the comment is not needed

2023-01-26 07:10 UTC, benedikt-richter commented on src/Frontend/Components/ListWithAttributes/ListWithAttributes.tsx
>    showAddNewInput: boolean; // TODO: required later
remove todo

2023-01-26 07:10 UTC, benedikt-richter commented on src/Frontend/Components/ListWithAttributes/ListWithAttributes.tsx
>      // TODO: Now: Single scroll bar for each list item.
still needed?

2023-01-26 07:13 UTC, benedikt-richter commented
Would be ncie to include a screenshot in the description.

2023-01-26 07:22 UTC, benedikt-richter commented
Looks already very good. 
Two further suggestions:
* Remove the word "count" it should be obvious for the user what this number refers to
![Screenshot 2023-01-26 at 08 20 21](https://user-images.githubusercontent.com/46576389/214778985-df997cee-98ed-45d9-ac19-dfa62da159dd.png)
* Use e.g. MuiChips (https://mui.com/material-ui/react-chip/) for the attributes to improve styling

![Screenshot 2023-01-26 at 08 20 39](https://user-images.githubusercontent.com/46576389/214779079-b581ad7c-cf6d-45f8-99d6-f1c4b596056a.png)

2023-01-26 08:35 UTC, lennartclaas commented on src/Frontend/Components/AttributionWizardVersionStep/AttributionWizardVersionStep.tsx
> +  },
moved to shared-styles

2023-01-26 08:35 UTC, lennartclaas commented on src/Frontend/Components/AttributionWizardVersionStep/AttributionWizardVersionStep.tsx
>  const PURL_HEIGHT = 45;
moved to shared-constants

2023-01-26 08:41 UTC, lennartclaas commented on src/Frontend/Components/AttributionWizardPopup/AttributionWizardPopup.tsx
> +const BREADCRUMBS_HEIGHT = 42.391;
I think it's necessary if we want the wizard to be adaptable to the window height and to easily change certain layout quantities. The constants refelct static sizes of the popup like the height of the pathbar or the breadcrumbs whose heights are defined by the font properties. Only if we know these sizes, we can make the height of the main content adaptable without getting unwanted scoll bars.

2023-01-26 08:42 UTC, lennartclaas commented on src/Frontend/Components/AttributionWizardPopup/AttributionWizardPopup.tsx
> +const BREADCRUMBS_HEIGHT = 42.391;
This value is shown in the deveoloper tools. I guess it originates in the font size that is used for the breadcrumb text (defined by MuiTypography).

2023-01-26 08:46 UTC, lennartclaas commented on src/Frontend/Components/ListWithAttributes/ListWithAttributes.tsx
>      // TODO: Now: Single scroll bar for each list item.
So far, we haven't decided whether we want to have horizontal scrollbars for individual list items or for the whole list (even, if only one items exceeds the maximum width). I would be fine with leaving it as it is.

2023-01-26 09:02 UTC, lennartclaas commented
@benedikt-richter regarding your [comment](https://github.com/opossum-tool/OpossumUI/pull/1357#issuecomment-1404636929)

Removing "count" sounds reasonable and looks quite nice. Concerning using MuiChip, I encountered some issues which we should discuss while taking a look at the UI.

2023-01-26 10:16 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardPopup/AttributionWizardPopup.tsx
> +const BREADCRUMBS_HEIGHT = 42.391;
I guess, it is save to use 42

2023-01-27 07:15 UTC, leslielazzarino requested changes
When a card is selected or hovered I would make the border the same color of the background.

2023-01-27 12:54 UTC, leslielazzarino approved these changes

2023-01-27 12:55 UTC, benedikt-richter approved these changes
Styling looks great! Just some minor points

2023-01-27 12:55 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardPackageStep/AttributionWizardPackageStep.tsx
> +import { ATTRIBUTION_WIZARD_PURL_HEIGHT } from '../../shared-constants';
Acutally, this would go into shared styles

2023-01-27 12:55 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardPopup/attribution-wizard-popup-helpers.tsx
> +        text: `${getCountString(count, totalAttributeCount)}`,
-> `getCountString`

Do not include the type of the variable that the getter returns. Further if it is a string why is it contained in a tempalte string?

2023-01-27 12:55 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardPopup/attribution-wizard-popup-helpers.tsx
> +  const percentageValue = (count / totalAttributeCount) * 100;
Why `Value`. This is a generic word that could be added as postfix to any variable we have.

2023-01-27 12:55 UTC, benedikt-richter commented on src/Frontend/Components/ListWithAttributes/ListWithAttributes.tsx
> +    height: `${LIST_TITLE_HEIGHT}px - 8px`,
As we are substracting 8px, this seems not to be the height (other than the naming suggests).

2023-01-27 12:55 UTC, benedikt-richter commented on src/Frontend/Components/ListWithAttributes/list-with-attributes-helpers.tsx
> +      {highlightedAttributeIds === undefined ? (
Suggestion: `highlightedAttributeIds === undefined` -> `highlightedAttributeIds` and returning the order in the ternary

2023-01-27 14:13 UTC, merged