Attribution Wizard: Implement "add new" functionality.
opossum-tool/OpossumUI pull request #1361
Opened 2023-01-30 09:50 UTC by lennartclaas

### Summary of changes

A textbox is placed below each list for adding items manually. After having entered a string, the item can be added by clicking the icon button on the right.

### Context and reason for change

Flexibility for the user.

### Further comments

Inserting the textbox below the list was done for better visual separation.

First wizard step:
<img src="https://user-images.githubusercontent.com/83081698/215442895-06e5c523-a765-4140-8cd0-281d05a859ca.PNG" width="550"/>

Fix: #1280

2023-01-30 10:45 UTC, vasily-pozdnyakov commented
### Comments about styling
* It would be nice to have the labels consistent (e.g. see "manually added" tag at different steps)
![image](https://user-images.githubusercontent.com/85183359/215455223-ac1358ee-f211-45f2-a523-83b9baaab86f.png)
![image](https://user-images.githubusercontent.com/85183359/215455512-64e12546-c3f7-4b1c-80c1-3e504380a286.png)

2023-01-30 11:23 UTC, vasily-pozdnyakov requested changes
Small things.

2023-01-30 11:23 UTC, vasily-pozdnyakov commented on package.json
> +    "test:single": "react-scripts test src/Frontend/Components/ListWithAttributes/__tests__/ListWithAttributes.test.tsx --watchAll=false --setupFilesAfterEnv=./setupTests.ts",
It should not be in the final version.

2023-01-30 11:23 UTC, vasily-pozdnyakov commented on src/Frontend/Components/ListWithAttributes/ListWithAttributes.tsx
> +  function getAddNewInputIcon(): ReactElement {
There is a file with icons: \Frontend\Components\Icons\Icons.tsx
Please move the icon there.

2023-01-30 12:26 UTC, lennartclaas commented
First revision update.

First step:
<img src="https://user-images.githubusercontent.com/83081698/215476170-a2339aff-2199-4489-ac6e-597f706499a1.PNG" width="550" />

Second step:
<img src="https://user-images.githubusercontent.com/83081698/215476378-32b3ca2d-51fe-437e-9200-75619f9d6066.PNG" width="550" />

2023-01-30 13:00 UTC, vasily-pozdnyakov approved these changes
A couple of minor things.

2023-01-30 13:00 UTC, vasily-pozdnyakov commented on src/Frontend/Components/AttributionWizardPopup/attribution-wizard-popup-helpers.tsx
> +        text: 'manually added',
I think "manually added" should be a constant (probably in shared constants?) and also exported to src/Frontend/Components/ListWithAttributes/list-with-attributes-helpers.tsx

2023-01-30 13:00 UTC, vasily-pozdnyakov commented on src/Frontend/Components/ListWithAttributes/list-with-attributes-helpers.tsx
> +  if (attributes?.length === 1 && attributes[0].text === 'manually added') {
why "length===1" ?

2023-01-30 13:57 UTC, lennartclaas commented on src/Frontend/Components/ListWithAttributes/list-with-attributes-helpers.tsx
> +  if (attributes?.length === 1 && attributes[0].text === 'manually added') {
I wasn't sure if the second condition would be enough when we enhance the wizard later. But for now, the second condition should be enough. I'll change it.

2023-01-31 07:23 UTC, benedikt-richter requested changes
Looks good and works nicely. Only some technical comments.

Regarding styling I'd suggest to use some icon to highlight manually added items. That way we do not have to abuse the attributes field and we would not display different information (whether something was added manually vs the package name) in the same spot.

2023-01-31 07:23 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardPopup/attribution-wizard-popup-helpers.tsx
> +export function getManuallyAddedPackageNamesToVersions(
I do not think that there is a lot of value for the user adding a manually added package name to the version field where there is no version...
Why would the user expect that?

2023-01-31 07:23 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardPopup/AttributionWizardPopup.tsx
> +  };
It feels, this should happen in `getAttributionWizardPackageListsItems`

2023-01-31 07:23 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardPopup/AttributionWizardPopup.tsx
> +  console.log(attributedPackageNamespaces);
do not forget to remove

2023-01-31 07:23 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardPopup/AttributionWizardPopup.tsx
> +  // console.log(attributedPackageNames);
do not forget to remove

2023-01-31 07:23 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardPopup/AttributionWizardPopup.tsx
> +  );
It feels this should be one function (as above)

2023-01-31 07:23 UTC, benedikt-richter commented on src/Frontend/Components/ListWithAttributes/list-with-attributes-helpers.tsx
> +  }
This is a very custom logic to handle this edge case. We match the first element of an array (here we relay on the array only having a single entry). Further we match the display name that is exposed to the user.
Feels there should be a better way.

2023-01-31 07:23 UTC, benedikt-richter commented on src/Frontend/shared-styles.ts
> +export const LIST_WITH_ATTRIBUTES_DEFAULT_ATTRIBUTE_WHEN_MANUALLY_ADDED_ITEM =
This should be a shared constant if we want to keep it.

2023-01-31 11:16 UTC, lennartclaas commented on src/Frontend/Components/AttributionWizardPopup/AttributionWizardPopup.tsx
> +  };
Is currently needed to prevent a TypeError. Will get obsolet when showing all versions (next ticket).

2023-01-31 11:27 UTC, lennartclaas commented on src/Frontend/shared-styles.ts
> +export const LIST_WITH_ATTRIBUTES_DEFAULT_ATTRIBUTE_WHEN_MANUALLY_ADDED_ITEM =
Removed because not needed anymore.

2023-01-31 11:28 UTC, lennartclaas commented on src/Frontend/Components/ListWithAttributes/list-with-attributes-helpers.tsx
> +  }
Removed because not needed anymore. Functionality is achieved with new prop in `ListWithAttributesItem`.

2023-01-31 13:13 UTC, lennartclaas commented on src/Frontend/Components/AttributionWizardPopup/attribution-wizard-popup-helpers.tsx
> +export function getManuallyAddedPackageNamesToVersions(
Is currently needed to prevent a TypeError. Will get obsolet when showing all versions (next ticket).

2023-01-31 14:36 UTC, benedikt-richter commented on src/Frontend/Components/ListWithAttributes/list-with-attributes-helpers.tsx
> +  manuallyAddedItem?: boolean
Actually it would be nice to have that function being stupid. We should use `manuallyAddedItem` to calculate `showChipsForAttributes` before invoking this function. I.e. to move the logic of l32-34 out of this function

2023-01-31 14:36 UTC, benedikt-richter commented on src/Frontend/Components/ListWithAttributes/ListWithAttributes.tsx
> +      if (props.setManuallyAddedListItems && props.manuallyAddedListItems) {
these two `if` statements can be merged

2023-01-31 14:36 UTC, benedikt-richter commented on src/Frontend/Components/ListWithAttributes/ListWithAttributes.tsx
> +                      sx={{ display: 'flex', justifyContent: 'space-between' }}
extract that styling as we typically do

2023-01-31 14:36 UTC, benedikt-richter commented on src/Frontend/Components/ListWithAttributes/ListWithAttributes.tsx
> +                      {item.text || (props.emptyTextFallback ?? '-')}
extract `-` as constant

2023-01-31 14:36 UTC, benedikt-richter commented on src/Frontend/Components/ListWithAttributes/ListWithAttributes.tsx
> +                          ...{ color: OpossumColors.darkBlue },
extract that styling as we typically do

2023-01-31 14:36 UTC, benedikt-richter commented on src/Frontend/Components/ListWithAttributes/ListWithAttributes.tsx
> +                    ? { margin: '13px 5px 13px 0px' }
extract that styling as we typically do

2023-01-31 14:36 UTC, benedikt-richter commented on src/Frontend/Components/Icons/Icons.tsx
> +}
Should extend `IconProps` or - as described below  not being required

2023-01-31 14:49 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardPopup/attribution-wizard-popup-helpers.tsx
> +        id: `${packageAttributeId}-attribute-${item}`,
why do we set this?
If there is a reason, then why is `'-'` not the empty attribute?

2023-01-31 14:50 UTC, benedikt-richter requested changes

2023-01-31 14:50 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardPopup/attribution-wizard-popup-helpers.tsx
> +}
do we really want to add a manually created package name to be listed at the emtpy version?

2023-01-31 16:19 UTC, lennartclaas commented on src/Frontend/Components/AttributionWizardPopup/attribution-wizard-popup-helpers.tsx
> +        id: `${packageAttributeId}-attribute-${item}`,
I made attributes optional and removed them here.

2023-02-01 07:43 UTC, benedikt-richter approved these changes
👍

2023-02-01 09:16 UTC, merged