Attribution Wizard: Documentation
opossum-tool/OpossumUI pull request #1379
Opened 2023-02-02 12:13 UTC by lennartclaas

Add section about attribution wizard to USER_GUIDE.md.

Some minor changes in USER_GUIDE.md to reduce oversized images.

Fix: #1299

2023-02-02 16:54 UTC, vasily-pozdnyakov requested changes
Would be nice to update the last three screenshots.

2023-02-02 16:54 UTC, vasily-pozdnyakov commented on USER_GUIDE.md
> +###### Attribution Wizard
Should have a bigger font size.

2023-02-02 16:54 UTC, vasily-pozdnyakov commented on USER_GUIDE.md
> +- Lists of aggregated package attributes (4), e.g., package namespace, name, and version (depending on wizard step).
no comma after "e.g."

2023-02-02 16:54 UTC, vasily-pozdnyakov commented on USER_GUIDE.md
> +In the first step, package namespace and name can be selected. The list entries are sorted by count, i.e., the number of occurrences in the attributions and signals of the current resource and its de
no comma after "i.e."
Propose: "New list items are marked"-> "Manually added items are marked..."

2023-02-06 08:42 UTC, lennartclaas commented on USER_GUIDE.md
> +###### Attribution Wizard
True, however, in a logical sense, `Attribution Wizard` must be a subsection of `Attribution Selection Column`, hence it needs one hash more. But if no one has arguments against using one hash less, I can do it. I agree that is would look nicer this way.

2023-02-06 08:44 UTC, lennartclaas commented on USER_GUIDE.md
> +- Lists of aggregated package attributes (4), e.g., package namespace, name, and version (depending on wizard step).
It depends whether we want to use british (without comma after e.g.) oder american style (with comma after e.g.). I would prefer the american style.

2023-02-06 08:45 UTC, lennartclaas commented on USER_GUIDE.md
> +In the first step, package namespace and name can be selected. The list entries are sorted by count, i.e., the number of occurrences in the attributions and signals of the current resource and its de
Regarding i.e.: see above. 

The proposal is good. I will consider it.

2023-02-06 08:49 UTC, lennartclaas commented
@vasily-pozdnyakov regarding you [comment](https://github.com/opossum-tool/OpossumUI/pull/1379#pullrequestreview-1281425912):

What do you mean by that? The last three screenshots are about the attribution wizard, attribution view, and report view. Do you mean updating the last two because their appearance hast changed?

2023-02-06 09:22 UTC, lennartclaas commented
I created a new ticket for updating other images in `USER_GUIDE.md`.

2023-02-06 09:52 UTC, vasily-pozdnyakov approved these changes

2023-02-06 10:14 UTC, benedikt-richter approved these changes
Nice documentation! Just added two suggestions.

I worry a bit about the images as these will have to be updated repeatedly (including manually adding the respective numbers (that are displayed in red)).

2023-02-06 10:14 UTC, benedikt-richter commented on USER_GUIDE.md
> +The `Attribution Wizard` can be opened via the context menu of an assigned attribution. It aggregates information from attributions and signals of the current resource and its descendents and provide
I'd replace `the context menu of an assigned attribution` by `the context menu of a manual attribution`.

2023-02-06 10:14 UTC, benedikt-richter commented on USER_GUIDE.md
> +- Package URL (3) that reflects the currently selected package attributes.
`that reflects the currently selected package attributes.` -> `that describes the currently selected package.`

2023-02-06 12:44 UTC, merged