AttributionW Wizard: Clean business logic !Draft!
opossum-tool/OpossumUI pull request #1396
Opened 2023-02-09 15:35 UTC by lennartclaas

The `AttributionWizardPopup` state is moved the the redux store. Ids are now UUIDs.

Fix: #1345

2023-02-16 16:46 UTC, benedikt-richter requested changes

2023-02-16 16:46 UTC, benedikt-richter commented on src/Frontend/state/reducers/resource-reducer.ts
> +    packageVersionsToNames: {},
These links should be removed thoughout the code, as discussed.

2023-02-16 16:46 UTC, benedikt-richter commented on src/Frontend/types/types.ts
> +}
The the type's naming - in my opinion - it is not relevant that these are "selected.

I'd suggest:
```
export interface PackageAttributeIds {
  namespaceId: string;
  nameId: string;
  versionId: string;
}

```

2023-02-16 16:46 UTC, benedikt-richter commented on src/Frontend/types/types.ts
> +  id?: string;
To me it seems strange to have the id optional. What is the reason for this change?

2023-02-16 16:46 UTC, benedikt-richter commented on src/Frontend/state/reducers/resource-reducer.ts
> +    popupAttribution: {},
Personally, I'm confused by the name `popupAttribution`. Prefer to refer to it as `originalAttribution` (it is also the one which origin id will be used).

2023-02-16 16:46 UTC, benedikt-richter commented on src/Frontend/state/selectors/attribution-wizard-selectors.ts
> +export function getAttributionWizardSelectedPackageIds(
-> getAttributionWizardSelectedPackageAttributeIds

2023-02-16 16:46 UTC, benedikt-richter commented on src/Frontend/state/actions/popup-actions/popup-actions.ts
> +export function openAttributionWizardPopup(
this action seems untested

2023-02-16 16:46 UTC, benedikt-richter commented on src/Frontend/state/actions/popup-actions/popup-actions.ts
> +    const manualAttributions = getManualAttributions(getState());
`manualAttributions` are contained in `manualData`

2023-02-16 16:46 UTC, benedikt-richter commented on src/Frontend/state/actions/popup-actions/popup-actions.ts
> +      popupAttributionId !== null ? manualAttributions[popupAttributionId] : {};
suggestion `startingAttribution` -> `originAttribution`

2023-02-16 16:46 UTC, benedikt-richter commented on src/Frontend/Components/ListWithAttributesListItem/ListWithAttributesListItem.tsx
> +                            attribute.id || ''
What is happening here?

2023-02-16 16:46 UTC, benedikt-richter commented on src/Frontend/Components/ListWithAttributes/ListWithAttributes.tsx
> +  handleListItemClick(id: string): void;
👍

2023-02-16 16:46 UTC, benedikt-richter commented on src/Frontend/Components/ListWithAttributes/ListWithAttributes.tsx
> +  const listItemsToDisplay =
I'd prefer the name `sortedListItems`

2023-02-16 16:46 UTC, benedikt-richter commented on src/Frontend/Components/ListWithAttributes/ListWithAttributes.tsx
> +          )
This logic is quite involved. The sorting depends on the number of arguments of the sorting function and whether there are highlighted items. Consider to move all logic into the sorting function.

2023-02-16 16:46 UTC, benedikt-richter commented on src/Frontend/Components/GlobalPopup/__tests__/GlobalPopup.test.tsx
> -  it('opens the AttributionWizardPopup', () => {
why is this test removed?

2023-02-16 16:46 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardVersionStep/AttributionWizardVersionStep.tsx
> +import { sortAttributedPackageVersions } from '../AttributionWizardPopup/attribution-wizard-popup-helpers';
We should not import helpers across components

2023-02-16 16:46 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardPackageStep/AttributionWizardPackageStep.tsx
> +import { sortAttributedPackageItems } from '../AttributionWizardPopup/attribution-wizard-popup-helpers';
We should not import helpers across components

2023-02-16 16:46 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardPopup/attribution-wizard-popup-helpers.tsx
>  export function sortAttributedPackageVersions(
consider moving the two sorting functions that are quite different to the different wizard steps where they are used.

2023-02-22 08:39 UTC, lennartclaas commented on src/Frontend/types/types.ts
> +  id?: string;
Namespaces and names have a single attribute: the count (absolute and relative). These are not referenced in other parts of the code. This is in contrast to the versions that can have multiple attributes, i.e., related package names and the ids of these package names. Not providing an id for the attributes of namespaces and names simplifies the creation of the `ListWithAttributes`.

2023-02-22 08:40 UTC, lennartclaas commented on src/Frontend/state/reducers/resource-reducer.ts
> +    popupAttribution: {},
We already agreed on calling it `startingAttribution`.

2023-02-22 08:48 UTC, lennartclaas commented on src/Frontend/Components/GlobalPopup/__tests__/GlobalPopup.test.tsx
> -  it('opens the AttributionWizardPopup', () => {
It is redundant with the ones in `AttributionWizardPopup.test.tsx` because the popup is always invoked with the `GlobalPopup`.

2023-02-23 12:26 UTC, leslielazzarino requested changes

2023-02-23 12:26 UTC, leslielazzarino commented on src/Frontend/Components/AttributionWizardPackageStep/attribution-wizard-package-step-helpers.ts
> +  } else if (manuallyAddedA && manuallyAddedB) {
I would remove the else, as you are returning

2023-02-23 12:26 UTC, leslielazzarino commented on src/Frontend/Components/AttributionWizardPackageStep/attribution-wizard-package-step-helpers.ts
> +  } else {
I would also remove the else here

2023-02-23 12:26 UTC, leslielazzarino commented on src/Frontend/Components/AttributionWizardVersionStep/attribution-wizard-verstion-step-helpers.ts
> +  } else if (manuallyAddedA && manuallyAddedB) {
I would remove this else

2023-02-23 12:26 UTC, leslielazzarino commented on src/Frontend/Components/AttributionWizardVersionStep/attribution-wizard-verstion-step-helpers.ts
> +  } else if (!versionAIsValid || !versionBIsValid) {
Also this one

2023-02-23 12:26 UTC, leslielazzarino commented on src/Frontend/Components/ListWithAttributes/ListWithAttributes.tsx
> +    props.sortList !== undefined
Remove !== undefined, not useful

2023-02-23 12:39 UTC, benedikt-richter requested changes
Some small points. Also there are previous comments not addressed.

2023-02-23 12:39 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardPackageStep/attribution-wizard-package-step-helpers.ts
> +  // eslint-disable-next-line @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any
Why do we have to ignore `no-explicit-any`?

2023-02-23 12:39 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardPackageStep/attribution-wizard-package-step-helpers.ts
> +  // eslint-disable-next-line @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any
Also a comment on why this is done would be helpful

2023-02-23 12:39 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardPopup/__tests__/AttributionWizardPopup.test.tsx
> +import { GlobalPopup } from '../../GlobalPopup/GlobalPopup';
This should not be required here.

2023-02-23 12:39 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardPopup/__tests__/AttributionWizardPopup.test.tsx
> +    // GlobalPopup has to be rendered, otherwise closing is not possible and triggers re-render
This should be an integration test. Also if I remember correctly there is some commented out one?

2023-02-23 12:39 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardPopup/__tests__/AttributionWizardPopup.test.tsx
> +    // GlobalPopup has to be rendered, otherwise closing is not possible and triggers re-render
as above

2023-02-23 12:39 UTC, benedikt-richter commented on src/Frontend/state/actions/popup-actions/popup-actions.ts
> +      popupAttributionId !== null ? manualAttributions[popupAttributionId] : {};
`popupAttributionId` -> `originalAttributionId`

2023-02-23 12:39 UTC, benedikt-richter commented on src/Frontend/state/helpers/open-attribution-wizard-popup-helpers.ts
> +  packageAttributeId: 'namespace' | 'name'
The name `Id` is confusing here. It does not seem to be an id.

2023-02-23 16:01 UTC, lennartclaas commented on src/Frontend/Components/GlobalPopup/__tests__/GlobalPopup.test.tsx
> -  it('opens the AttributionWizardPopup', () => {
Added the test.

2023-02-23 16:02 UTC, lennartclaas commented on src/Frontend/state/reducers/resource-reducer.ts
> +    popupAttribution: {},
Changed according to discussion.

2023-02-23 16:38 UTC, lennartclaas commented on src/Frontend/Components/ListWithAttributes/ListWithAttributes.tsx
> +  const listItemsToDisplay =
But if no `sortList` is provided, the resulting list is not sorted. The suggested naming would in this case be confusing.

2023-02-23 16:54 UTC, lennartclaas commented on src/Frontend/state/helpers/open-attribution-wizard-popup-helpers.ts
> +  packageAttributeId: 'namespace' | 'name'
Changed it to `packageAttributeKey`. Also not perfect. Other names with, e.g., `type` also clash with other usages.

2023-02-24 08:35 UTC, lennartclaas commented on src/Frontend/Components/AttributionWizardPopup/__tests__/AttributionWizardPopup.test.tsx
> +    // GlobalPopup has to be rendered, otherwise closing is not possible and triggers re-render
Moved this one and the other one below to integration tests.  

You are right. It was a `PackageCard` test. Added it again.

2023-03-02 11:08 UTC, leslielazzarino approved these changes

2023-03-02 12:12 UTC, benedikt-richter approved these changes
nice refactoring!

2023-03-02 12:13 UTC, merged