Show more indicators for pre-selected attributions
opossum-tool/OpossumUI pull request #14
Opened 2021-09-23 09:20 UTC by sebathomas

1. Show the new icon in report table view.
(This makes it necessary to increase the row height.)

2. Show a hint in the attribution details column.

Signed-off-by: Sebastian Thomas <sebastian.thomas@tngtech.com>

2021-09-23 12:16 UTC, antonbauhofer commented
When running the app on Mac, the text "Attribution was pre-selected" is not left-aligned with the content above.
<img width="505" alt="Screenshot 2021-09-23 at 14 14 42" src="https://user-images.githubusercontent.com/48415604/134504864-c49f6e42-1a1d-4791-adf1-69317e95ae99.png">

2021-09-23 12:18 UTC, antonbauhofer commented
Why do we have different blue tones for the icons? Should not the blue icons have the same color?
![Screenshot 2021-09-23 at 14 17 25](https://user-images.githubusercontent.com/48415604/134505218-95828cf1-b554-4cbc-8ff5-ca4ba1378d55.png)

2021-09-23 12:32 UTC, antonbauhofer requested changes
See comments

2021-09-23 12:32 UTC, antonbauhofer commented on src/Frontend/Components/AttributionColumn/ButtonRow.tsx
> +    <>
```suggestion
    <div>
```

This fixes the left-alignment (see previous comment) with the content above on Mac.

2021-09-23 12:32 UTC, antonbauhofer commented on src/Frontend/Components/AttributionColumn/ButtonRow.tsx
> +    </>
```suggestion
    </div>
```

2021-09-23 12:59 UTC, sebathomas commented
> When running the app on Mac, the text "Attribution was pre-selected" is not left-aligned with the content above.
> <img alt="Screenshot 2021-09-23 at 14 14 42" width="505" src="https://user-images.githubusercontent.com/48415604/134504864-c49f6e42-1a1d-4791-adf1-69317e95ae99.png">

That one is really strange, I cannot reproduce it on different sizes and zoom levels. Seems to be OS dependent. (See screenshot in description.)

2021-09-23 13:01 UTC, sebathomas commented
> Why do we have different blue tones for the icons? Should not the blue icons have the same color?
> ![Screenshot 2021-09-23 at 14 17 25](https://user-images.githubusercontent.com/48415604/134505218-95828cf1-b554-4cbc-8ff5-ca4ba1378d55.png)

I thought the idea was to have different colors for every icon. Matter of taste though.

2021-09-23 14:36 UTC, sebathomas commented
As discussed in person, we'll make the icon orange.

2021-09-23 15:35 UTC, nicarl approved these changes

2021-09-23 15:35 UTC, nicarl commented on src/Frontend/Components/ReportTableItem/ReportTableItem.tsx
> +    height: reportTableRowHeight - 2 * padding,
:+1: removing magic numbers is always good :mage_man:

2021-09-23 15:35 UTC, nicarl commented
As discussed we agreed to keep the colors as they are

2021-09-27 07:37 UTC, sebathomas commented
> When running the app on Mac, the text "Attribution was pre-selected" is not left-aligned with the content above.
> <img alt="Screenshot 2021-09-23 at 14 14 42" width="505" src="https://user-images.githubusercontent.com/48415604/134504864-c49f6e42-1a1d-4791-adf1-69317e95ae99.png">

Looks like it was a difference between the auto-update version and the built version of the app (weird...). I think I fixed it. Can you try again?

2021-09-27 12:21 UTC, antonbauhofer commented
> > When running the app on Mac, the text "Attribution was pre-selected" is not left-aligned with the content above.
> > <img alt="Screenshot 2021-09-23 at 14 14 42" width="505" src="https://user-images.githubusercontent.com/48415604/134504864-c49f6e42-1a1d-4791-adf1-69317e95ae99.png">
> 
> Looks like it was a difference between the auto-update version and the built version of the app (weird...). I think I fixed it. Can you try again?

Great, it works now as expected.

2021-09-27 12:21 UTC, antonbauhofer approved these changes

2021-09-27 12:23 UTC, merged