Add icon to url text box and enable open valid url
opossum-tool/OpossumUI pull request #141
Opened 2021-10-27 15:13 UTC by mayayunx

Signed-off-by: Ruiyun Xie <ruiyun.xie@tum.de>

### Summary of changes

- Add icon to the URL Textfield for opening a link in browser
- Check if the url is empty, then disable the icon and change the color
- Check if url is valid, otherwise add https protocol to it
- Open link via clicking on the icon if not disabled 

### Context and reason for change

Enable the user open link in browser.

### How can the changes be tested

By entering different links and clicking on the icon.

Note: Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

2021-11-02 12:58 UTC, leslielazzarino requested changes
- The only URL in the opossum_input.json example file has a typo (typescRipt), preventing to directly test this feature on that file
- The icon on the path bar has moved to the left from its expected positon at the extreme right.

2021-11-02 12:58 UTC, leslielazzarino commented on src/Frontend/Components/AttributionColumn/PackageSubPanel.tsx
> +});
Can be written as: `const useStyles = makeStyles({clickableIcon,disabledIcon});`

2021-11-02 14:27 UTC, benedikt-richter approved these changes
consider squashing individual commits before merging

2021-11-02 15:05 UTC, mayayunx commented on src/Frontend/Components/GoToLinkButton/GoToLinkButton.tsx
> +      className={!openLinkArgs.link ? classes.hidden : undefined}
But then it needs to be packed into clsx right? And Leslie commented above that he finds it unclean to use boolean as args in clsx.

2021-11-02 15:52 UTC, benedikt-richter commented on src/Frontend/Components/GoToLinkButton/GoToLinkButton.tsx
> +      className={!openLinkArgs.link ? classes.hidden : undefined}
Ok. is not required

2021-11-03 07:11 UTC, leslielazzarino approved these changes

2021-11-03 09:16 UTC, merged