Add .opossum support: Add script to generate dot opossum files.
opossum-tool/OpossumUI pull request #1423
Opened 2023-02-20 14:38 UTC by lennartclaas

### Summary of changes

`yarn generate-dot-opossum` scans `example-files` and generates `.opossum` files. `.opossum` files are ignored by git.

### Context and reason for change

Needed for dev. 

### How can the changes be tested

Run script and take a look into `example-files`.

2023-02-20 16:04 UTC, lennartclaas commented
@vasily-pozdnyakov regarding your [comment](https://github.com/opossum-tool/OpossumUI/pull/1423#issuecomment-1437162545)

I revised the variable naming. Looks better to me now.

I refactored parts of the logic into functions to improve readability.

For creating a zip archive via node, I needed to install `archiver`, hence the additional lines in yarn.lock.

2023-02-20 16:07 UTC, lennartclaas commented
In general, the location of the script could be changed, as it is not a build script in the narrower sense. Do we have any convention that considers this case?

2023-02-21 09:21 UTC, vasily-pozdnyakov requested changes
I do not know, but should we may be add some logging?

2023-02-21 09:21 UTC, vasily-pozdnyakov commented on build_scripts/generateDotOpossum.js
> +  if (attributionFilePaths.includes(expectedAssociatedAttributionFilePath)) {
`attributionFilePaths` is a global variable which is used in the function, so I think it would be nice to make it the function argument.

2023-02-21 10:06 UTC, lennartclaas commented on build_scripts/generateDotOpossum.js
> +  if (attributionFilePaths.includes(expectedAssociatedAttributionFilePath)) {
I also added logging about the create `.opossum` files.

2023-02-21 10:19 UTC, benedikt-richter requested changes

2023-02-21 10:19 UTC, benedikt-richter commented on build_scripts/generateDotOpossum.js
> +const archiver = require('archiver');
Would be nice to use the same library as we do in the productive code

2023-02-21 10:29 UTC, vasily-pozdnyakov approved these changes
Minor thing.

2023-02-21 11:19 UTC, lennartclaas commented on build_scripts/generateDotOpossum.js
> +const archiver = require('archiver');
Changed it. Now using `JSZip`.

2023-02-21 12:31 UTC, vasily-pozdnyakov requested changes

2023-02-21 12:31 UTC, vasily-pozdnyakov commented on build_scripts/generateDotOpossum.js
> +  console.log('Created ' + dotOpossumFilePath);
If the file already exists, the logging should be like "The file already exists".
Actually, it the ".opossum" file already exists it should not overwrite it.

2023-02-22 07:28 UTC, benedikt-richter commented on package.json
> +    "generate-dot-opossum": "yarn node build_scripts/generateDotOpossum.js",
This won't work on windows, I guess?

2023-02-22 07:29 UTC, benedikt-richter requested changes

2023-02-22 07:29 UTC, benedikt-richter commented on build_scripts/generateDotOpossum.js
> +// SPDX-FileCopyrightText: Meta Platforms, Inc. and its affiliates
The script should not be located in this folder. Could be moved into the folder `example-files`.

2023-02-22 08:21 UTC, lennartclaas commented on package.json
> +    "generate-dot-opossum": "yarn node build_scripts/generateDotOpossum.js",
Yes.

2023-02-22 08:29 UTC, lennartclaas commented on build_scripts/generateDotOpossum.js
> +// SPDX-FileCopyrightText: Meta Platforms, Inc. and its affiliates
moved into `/example-files/scripts/`

2023-02-22 11:22 UTC, vasily-pozdnyakov approved these changes
lgtm

2023-02-23 07:58 UTC, benedikt-richter approved these changes
👍

2023-02-23 07:59 UTC, merged