Opossum format
opossum-tool/OpossumUI pull request #1426
Opened 2023-02-21 07:57 UTC by MarkusObendrauf

### Summary of changes

Add support for a new .opossum file format. This file format combines the old `resources.json` and `resources_attributions.json` by zipping them together.

In the current implementation, if you use the old format, you will save to old format, and if you use the new .opossum format, you will save to .opossum format.

### Context and reason for change

Make it easier for a user to work with OpossumUI by only needed one type of file.

### How can the changes be tested

* Run the new unit tests
* For manual testing, a new file `example-files/example.opossum` is provided. This is a converted version of `example-files/opossum_input`.

2023-02-21 09:33 UTC, lennartclaas requested changes
It seems that opening a `.opossum` file without an` output.json` is currently throwing an error. Apart from that, only minor issues.

2023-02-21 09:33 UTC, lennartclaas commented on src/ElectronBackend/input/parseFile.ts
> +    zip.files['output.json'].async('text').then(function (content) {
It seems we run into trouble here if the `.opossum` file does not include an `output.json` (it is optional).

2023-02-21 09:33 UTC, lennartclaas commented on src/ElectronBackend/input/__tests__/importFromFile.test.ts
> +  it('loads .opossum file and parses jsons successfully', async () => {
I suggest to add a test that checks whether loading a `.opossum` file without an `output.json` works. Could also be done in `parseFiles.test.ts`.

2023-02-21 09:33 UTC, lennartclaas commented on src/ElectronBackend/input/importFromFile.ts
> +  if (path.extname(filePath) == '.opossum') {
I guess using `===` would be cleaner.

2023-02-21 09:33 UTC, lennartclaas commented on src/ElectronBackend/input/importFromFile.ts
> +    [parsedInputData, parsedOutputData] = parsingResult;
I think we mostly use object destructuring for returning multiple variables in OpossumUI. Using an array could potentially lead to mixing both values if further changes are made in the future. Therefore, parsingResult could be made an object.

2023-02-21 09:42 UTC, MarkusObendrauf commented
> It seems that opening a `.opossum` file without an `output.json` is currently throwing an error.

Do we need to support that?

2023-02-21 09:44 UTC, MarkusObendrauf commented on src/ElectronBackend/input/importFromFile.ts
> +  if (path.extname(filePath) == '.opossum') {
fixed

2023-02-21 09:44 UTC, MarkusObendrauf commented on src/ElectronBackend/input/parseFile.ts
> +export function parseOuputJsonFile(
corrected

2023-02-21 09:52 UTC, MarkusObendrauf commented on src/ElectronBackend/input/importFromFile.ts
> +    [parsedInputData, parsedOutputData] = parsingResult;
changed it to return an object

2023-02-21 09:56 UTC, MarkusObendrauf commented
> > It seems that opening a `.opossum` file without an `output.json` is currently throwing an error.
> 
> Do we need to support that?

We do, I will work on changes to allow this

2023-02-21 10:12 UTC, MarkusObendrauf commented on src/ElectronBackend/input/parseFile.ts
> +    zip.files['output.json'].async('text').then(function (content) {
fixed

2023-02-21 10:13 UTC, MarkusObendrauf commented on src/ElectronBackend/input/__tests__/importFromFile.test.ts
> +  it('loads .opossum file and parses jsons successfully', async () => {
I added a new test in `importFromFile.test.ts` and one in `parseFiles.test.ts`

2023-02-21 10:24 UTC, leslielazzarino requested changes

2023-02-21 10:24 UTC, leslielazzarino commented on src/ElectronBackend/input/importFromFile.ts
> +    if (isJsonParsingError(parsingResult)) {
We should extract this if into a function

2023-02-21 10:24 UTC, leslielazzarino commented on src/ElectronBackend/input/importFromFile.ts
> +    createOutputFile(
Should be renamed to createJsonOutputFile imo

2023-02-21 10:24 UTC, leslielazzarino commented on src/ElectronBackend/input/parseFile.ts
> +  await sleep(500);
Why do we have this sleep?

2023-02-21 10:24 UTC, leslielazzarino commented on src/ElectronBackend/output/writeJsonToOpossumFile.ts
> +  await sleep(500);
Here too?

2023-02-21 11:39 UTC, lennartclaas commented
When I open a `test.opossum` file that only contains an `input.json`, a new `test_attributions.json` file is created next to the `test.opossum` file. Furthermore, it could be beneficial to throw a warning (no error) if a `.opossum` file is openend that does not contain JSONs with proper naming. But I guess this is out of the scope of this story.

2023-02-21 12:02 UTC, MarkusObendrauf commented on src/ElectronBackend/input/parseFile.ts
> +  await sleep(500);
We sleep in order to wait for some async stuff to finish. I was unable to write a sync version (JS zip library only supports aasync stuff it seems), and also failed to get the async version working correctly. This is a terrible quick fix so that I unblock other tickets.

2023-02-21 12:12 UTC, MarkusObendrauf commented
> When I open a `test.opossum` file that only contains an `input.json`, a new `test_attributions.json` file is created next to the `test.opossum` file.

Good find, I will work on a fix

2023-02-21 13:15 UTC, MarkusObendrauf commented on src/ElectronBackend/input/importFromFile.ts
> +    if (isJsonParsingError(parsingResult)) {
Not possible because we return early from the function `loadInputAndOutputFromFilePath`.

2023-02-21 13:15 UTC, MarkusObendrauf commented on src/ElectronBackend/output/writeJsonToOpossumFile.ts
> +  await sleep(500);
same as above

2023-02-21 14:08 UTC, MarkusObendrauf commented
I managed to eliminate the `sleep`s by wrapping stuff in promises. I hope that's a reasonable solution.

2023-02-22 09:41 UTC, leslielazzarino approved these changes

2023-02-22 09:41 UTC, leslielazzarino commented on src/ElectronBackend/input/parseFile.ts
> +    fs.readFile(opossumfilePath, function (err, data) {
We usually use arrow functions when inlining functions. Is there a specific reason here not to use them? Otherwise I would prefer to have them here too.

2023-02-22 09:41 UTC, leslielazzarino commented on src/ElectronBackend/input/parseFile.ts
> +    fs.readFile(opossumfilePath, function (err, data) {
Same here.

2023-02-22 10:14 UTC, lennartclaas approved these changes
lgtm

2023-02-22 12:20 UTC, benedikt-richter commented on src/ElectronBackend/input/importFromFile.ts
> -  cleanNonExistentResolvedExternalAttributions,
Why do we no longer use this one?

2023-02-22 12:25 UTC, benedikt-richter commented
Might be a good point to get rid of the namings `input` and `output` :)
Given that we have a single input file that also is the output file, we could consider renaming these to better describe what these are.
E.g. the input might be the "immutable" part, while the output might be the "mutable" part (that's kind of the defining properties of these files)

2023-02-22 14:31 UTC, MarkusObendrauf commented on src/ElectronBackend/input/parseFile.ts
> +    fs.readFile(opossumfilePath, function (err, data) {
Switched them to arrows

2023-02-22 15:52 UTC, MarkusObendrauf commented on src/ElectronBackend/input/importFromFile.ts
> -  cleanNonExistentResolvedExternalAttributions,
Good find. Added it back.

2023-02-22 15:53 UTC, MarkusObendrauf commented
> Might be a good point to get rid of the namings `input` and `output` :) Given that we have a single input file that also is the output file, we could consider renaming these to better describe what these are. E.g. the input might be the "immutable" part, while the output might be the "mutable" part (that's kind of the defining properties of these files)

I personally like this naming, I think it's something we should discuss.

2023-02-23 13:04 UTC, vasily-pozdnyakov commented
When you try to open .opossum file, the opossumUI still checks hash of the input file and compares it with the one from _attribution.json (if it exists next to .opossum file).

2023-02-23 16:30 UTC, benedikt-richter requested changes
Currently, the app always shows a warning when opening a .opossum file.

2023-02-23 16:30 UTC, benedikt-richter commented on src/ElectronBackend/main/listeners.ts
> +    checksums &&
This logic is broken, as it implies that all .opossum files raise an error. This is because the variable `checksum` is always falsy in that case.

2023-02-23 16:30 UTC, benedikt-richter commented on src/ElectronBackend/main/listeners.ts
> +    checksums === undefined ? undefined : checksums.actualInputFileChecksum
suggestion: 
replace
`checksums === undefined ? undefined : checksums.actualInputFileChecksum`
by
`checksums.?actualInputFileChecksum`

2023-02-23 16:35 UTC, benedikt-richter commented
Further observation:
Currently, when opening a .opossum file, we still set the variable `attributionFilePath` in the globalBackendState. The value  '/Users/.../opossum_input_attributions.json' is set in this case. This is confusing (this file does not exist and never will) and instead it should most likely not be set or being explicitly set to `null`.

2023-02-24 09:47 UTC, MarkusObendrauf commented on src/ElectronBackend/main/listeners.ts
> +    checksums &&
I cleaned up this section.

2023-02-24 09:47 UTC, MarkusObendrauf commented
> Further observation: Currently, when opening a .opossum file, we still set the variable `attributionFilePath` in the globalBackendState. The value '/Users/.../opossum_input_attributions.json' is set in this case. This is confusing (this file does not exist and never will) and instead it should most likely not be set or being explicitly set to `null`.

I explicitly set it to `null` now.

2023-02-24 10:04 UTC, benedikt-richter requested changes
Unfortunately, saving fails now:
![Screenshot 2023-02-24 at 11 01 25](https://user-images.githubusercontent.com/46576389/221150670-a31aeb53-95c3-4fd3-a5b0-15e230bafc54.png)


origin: `src/ElectronBackend/main/listeners.ts` approx l.64

2023-02-24 10:30 UTC, MarkusObendrauf commented
> Unfortunately, saving fails now:
> 
> origin: `src/ElectronBackend/main/listeners.ts` approx l.64

Theres an error because `attributionFilePath == null`. Ideally, we should have a different field for this in the backend state, for now I did the quick fix of checking for `undefined` instead of `undefined | null`

2023-02-24 15:14 UTC, benedikt-richter approved these changes
works nicely 👍

2023-02-24 15:14 UTC, merged