Update documentation
opossum-tool/OpossumUI pull request #1428
Opened 2023-02-21 12:25 UTC by vasily-pozdnyakov

### Summary of changes

Update documentation.

### Context and reason for change

We introduce new ".opossum" file extension.

### How can the changes be tested

Check the documentation.

2023-02-22 07:53 UTC, benedikt-richter requested changes

2023-02-22 07:53 UTC, benedikt-richter commented on README.md
> +If you work with `.opossum` file an accompanying output file will be automatically created and added to the archive if there is no such file yet.
For the user, the new file is not visible. I'd prefer to frame it as "the .opossum file is updated".

2023-02-22 07:53 UTC, benedikt-richter commented on USER_GUIDE.md
> +### Archived opossum file format <a name="dot_opossum"></a>
I'd perfer to the new file format simply as "opossum file format" instead of "archived opossum file format"

2023-02-22 07:53 UTC, benedikt-richter commented on USER_GUIDE.md
> +<img src="./docs/user_guide_screenshots/opossum_file_popup.png" width="550"/>
Not sure we need this screenshot. It certainly adds information, however, it has the disadvantage that we have to update the screenshot whenever we update the popup text (which we most likely forget).

2023-02-22 07:53 UTC, benedikt-richter commented on USER_GUIDE.md
> +## Table of contents
Nice 👍

2023-02-22 13:51 UTC, lennartclaas approved these changes
Only very minor fussy stuff.

2023-02-22 13:51 UTC, lennartclaas commented on README.md
> +If you work with `.opossum` file an accompanying output file will be automatically created and added to the archive if there is no such file yet.
Proposal: "If you work with a `.opossum` file, an accompanying ..."

2023-02-22 13:51 UTC, lennartclaas commented on README.md
> +Files with `.opossum` extension are zip-archives which contain `input.json` (must be provided) together with `output.json` (optional).
Proposal: "Files with a `.opossum` extension are zip-archives which contain an `input.json` (must be provided) together with an `output.json` (optional)."

2023-02-22 13:51 UTC, lennartclaas commented on USER_GUIDE.md
> +## Table of contents
😍

2023-02-22 13:51 UTC, lennartclaas commented on USER_GUIDE.md
> +Files with `.opossum` extension are zip-archives which contain _input.json_ (must be provided) together with _output.json_ (optional). An output file will be automatically created and added to the ar
Also here, at least for my feeling, some noun markers could be added, e.g., "Files with a `.opossum` extension are zip-archives which contain an _input.json_ (must be provided) together with an _output.json_ (optional).". But I'm not sure if this is really necessary.

2023-02-22 13:51 UTC, lennartclaas commented on USER_GUIDE.md
> +If you try to open a _.json_ file, a popup will be shown which asks whether you would like to create an `.opossum` file and proceed (recommended) or continue working with the old format (two separate
I would suggest "a `.opossum` file", as you would say "dot opossum file".

2023-02-23 07:48 UTC, benedikt-richter reviewed
Looks good! Just squash commits.

2023-02-23 09:46 UTC, vasily-pozdnyakov commented
> Looks good! Just squash commits.

Done. Should be merged after #1426

2023-02-23 12:10 UTC, benedikt-richter approved these changes

2023-02-24 15:15 UTC, merged