Handle attributions with missing package name in terms of styling
opossum-tool/OpossumUI pull request #1436
Opened 2023-02-23 16:13 UTC by lennartclaas

### Summary of changes

If the package name is missing, the package cards in attribution view are highlighted with dark orange color. The background color of the corresponding text box changes accordingly.

### Context and reason for change

The user gets more feedback and is alerted if the package name is missing.

Screenshot:
![Unbenannt](https://user-images.githubusercontent.com/83081698/220964979-5a2cb513-14cf-43bd-9c12-1dd0eb9715a9.PNG)

2023-02-23 16:37 UTC, benedikt-richter commented on src/Frontend/Components/AttributionCountsPanel/AttributionCountsPanel.tsx
> +  const numberOfAttributionsWithoutPackageName = 1;
;)

2023-02-23 16:37 UTC, benedikt-richter commented on src/Frontend/Components/AttributionCountsPanel/AttributionCountsPanel.tsx
> +      {`, ${numberOfAttributionsWithoutPackageName}`}
as above

2023-02-23 16:40 UTC, benedikt-richter commented on src/Frontend/Components/AttributionCountsPanel/AttributionCountsPanel.tsx
> +      {`, ${numberOfAttributionsWithoutPackageName}`}
Not introduced here and therefore optional.
Can we rename `IncompletePackagesIcon` above to `IncompleteAttributionsIcon`

2023-02-23 16:42 UTC, benedikt-richter commented on src/Frontend/Components/InputElements/TextBox.tsx
> +function getTextBoxSx(
should be a constant instead of a function

2023-02-23 16:42 UTC, benedikt-richter commented on src/Frontend/Components/InputElements/TextBox.tsx
> +function getHighlighting(color: HighlightingColor | undefined): SxProps {
as above

2023-02-23 16:48 UTC, benedikt-richter commented on src/Frontend/Components/ListCard/ListCard.tsx
> +  highlighting?: HighlightingColor | false;
typically, we refer to it as `isHighlighted`

2023-02-24 07:38 UTC, benedikt-richter requested changes

2023-02-24 07:38 UTC, benedikt-richter commented on src/Frontend/Components/InputElements/shared.ts
> +  highlightedTextFieldLightOrange: {
I'm not a fan of adding the actual color to the name of the class, as this means we have to rename the class in several files once we decide to simply change the color. Or even worse, we change the color and do not rename...
Better use semantic naming: `defaultHighlightedTextField` and below `strongHighlightedTextField`

2023-02-24 07:38 UTC, benedikt-richter commented on src/Frontend/util/is-important-attribution-information-missing.ts
> +): HighlightingColor | false {
Why does this function return `false`? This is surprising.

2023-02-24 09:31 UTC, lennartclaas commented on src/Frontend/Components/AttributionCountsPanel/AttributionCountsPanel.tsx
> +  const numberOfAttributionsWithoutPackageName = 1;
Oops... Changed that part and adapted the corresponding test.

2023-02-24 09:34 UTC, lennartclaas commented on src/Frontend/Components/AttributionCountsPanel/AttributionCountsPanel.tsx
> +      {`, ${numberOfAttributionsWithoutPackageName}`}
Not sure what the first part means. Why should it be optional? 

I renamed the icon component.

2023-02-24 09:37 UTC, lennartclaas commented on src/Frontend/Components/InputElements/TextBox.tsx
> +function getTextBoxSx(
Why? I remember that the convention is to use functions whenever possible. However, I changed it.

2023-02-24 09:38 UTC, lennartclaas commented on src/Frontend/Components/InputElements/TextBox.tsx
> +function getHighlighting(color: HighlightingColor | undefined): SxProps {
see above

2023-02-24 09:47 UTC, lennartclaas commented on src/Frontend/Components/ListCard/ListCard.tsx
> +  highlighting?: HighlightingColor | false;
`isHighlighted` is not an appropriate name anymore, as it refers to a boolean. The new prop speciefies the highlighting color if highlighting should be applied, or is false if no highlighting should be applied. Alternatively, HighlightinhColor could have an entry like `None`. However, this would introduce a lot of logic to handle these cases.

2023-02-24 09:51 UTC, lennartclaas commented on src/Frontend/util/is-important-attribution-information-missing.ts
> +): HighlightingColor | false {
As above.

2023-02-24 16:10 UTC, benedikt-richter requested changes

2023-02-24 16:10 UTC, benedikt-richter commented on src/Frontend/Components/AttributionCountsPanel/AttributionCountsPanel.tsx
> +      {`, ${numberOfAttributionsWithoutPackageName}`}
"optional" had the meaning that you could do it if you want. Thanks for doing it!

2023-02-27 08:43 UTC, lennartclaas commented on src/Frontend/Components/InputElements/TextBox.tsx
> +const getHighlighting = (color: HighlightingColor | undefined): SxProps => {
Why? By convention or just simplicity? However, I changed it. But now, this constant is computed each time the component renders, even if it is not highlighted. Not a big deal in terms of performance, I think, but still unnecassary.

2023-02-27 08:43 UTC, lennartclaas commented on src/Frontend/Components/InputElements/TextBox.tsx
> +};
Why? By convention or just simplicity? However, I changed it.

2023-02-27 09:14 UTC, lennartclaas commented
@benedikt-richter regarding your [comment](https://github.com/opossum-tool/OpossumUI/pull/1436#discussion_r1117246552)

> What is the difference between the values undefined and false?

It was intended for compatibility. However, using it turned out to be not necessary. I therefore removed `false`.

2023-02-27 09:14 UTC, lennartclaas commented on src/Frontend/Components/ListCard/ListCard.tsx
> +  highlighting?: HighlightingColor | false;
see below

2023-02-27 09:28 UTC, benedikt-richter commented on src/Frontend/Components/InputElements/TextBox.tsx
> +  const HIGHLIGHTED_STYLING =
Why is this ALL_CAPS?

2023-02-27 09:28 UTC, benedikt-richter commented on src/Frontend/Components/InputElements/TextBox.tsx
> +function getTextBoxSx(
Sorry for that confusion. If we can write something as a constant it is preferred to do so instead of writing a function returning that constant.

2023-02-27 09:32 UTC, benedikt-richter commented on src/Frontend/Components/InputElements/TextBox.tsx
> +};
This is just for simplicity

2023-02-27 09:32 UTC, benedikt-richter commented on src/Frontend/Components/InputElements/TextBox.tsx
> +const getHighlighting = (color: HighlightingColor | undefined): SxProps => {
This is just for simplicity

2023-02-27 09:38 UTC, benedikt-richter approved these changes

2023-02-27 10:12 UTC, MarkusObendrauf requested changes

2023-02-27 10:12 UTC, MarkusObendrauf commented on src/Frontend/Components/ListCard/ListCard.tsx
> +        packageBorder
I would prefer if the parameters were in some kind of object, so that we have 
`highlightColor: 'OpossumColors.lightOrange',
backgroundColor: 'OpossumColors.lightOrange'`
etc. Because currently, I just see four colors but can't see what they're used for without scrolling to the function definition of `getHighlightedStyleClass`

2023-02-27 10:12 UTC, MarkusObendrauf commented on src/Frontend/Components/ListCard/ListCard.tsx
> +        packageBorder
also, can we just write
```
getHighlightedStyleClass(
        useLightOrange ? OpossumColors.lightOrange : OpossumColors.darkOrange,
        selected ? OpossumColors.middleBlue : defaultBackgroundColor,
        useLightOrange  ? OpossumColors.lightOrangeOnHover : OpossumColors.darkOrangeOnHover,
        selected ? hoveredSelectedBackgroundColor : hoveredBackgroundColor,
        packageBorder
```

2023-02-27 10:12 UTC, MarkusObendrauf commented on src/Frontend/Components/ListCard/ListCard.tsx
> +        packageBorder
another idea: create 4 variables
```
const highlightColor = useLightOrange ? OpossumColors.lightOrange : OpossumColors.darkOrange;
const backgroundColor = selected ? OpossumColors.middleBlue : defaultBackgroundColor;
```
etc. and then just use one call
```
return getHighlightedStyleClass(
        highlightColor ,
        backgroundColor ,
        highlightColorHover,
        backgroundColorHover,
        packageBorder
      );
```
this also clarifies which color is used for which purpose

2023-02-27 18:00 UTC, lennartclaas commented on src/Frontend/Components/InputElements/TextBox.tsx
> +      : props.highlightingColor === HighlightingColor.DarkOrange
I could imagine that `HighlightingColor` is extended in the future and used in other parts of the code. In this case, we are safe.

2023-02-27 18:18 UTC, lennartclaas commented on src/Frontend/Components/ListCard/ListCard.tsx
> +        packageBorder
Good idea. I implemented the last approach.

2023-02-28 08:37 UTC, MarkusObendrauf commented on src/Frontend/Components/InputElements/TextBox.tsx
> +      : {};
a boolean variable needs to have a name like `useDefaultHighlighting`, making it clear that its a boolean. the current name suggests it is a color.

2023-02-28 08:52 UTC, MarkusObendrauf commented on src/Frontend/Components/ListCard/ListCard.tsx
> +        packageBorder
the code seems to be written with a non-existent third color in mind, turning 4 lines of code into 30, and i dont like it. (premature optimization?)
and actually, if more colors need to be added, id expect it to be implemented via a map `highlighting style -> (highlightColor, highlightColorOnHover)`. i think it would be fine to use that approach now, but imo its also ok to write code like theres only two colors.

2023-02-28 09:12 UTC, lennartclaas commented on src/Frontend/Components/InputElements/TextBox.tsx
> +      : {};
Seems reasonable, however, I would not call such a variable `use...` as use is reserved for hooks. I have chosen `isDefaultHighlighting`.

2023-02-28 09:12 UTC, lennartclaas commented on src/Frontend/Components/ListCard/ListCard.tsx
> +        packageBorder
Okay, I changed it. But I still think this is dangerous. However, in `PackageCard` the possible colors are restricted to `lightOrange` and `darkOrange`.

2023-02-28 09:41 UTC, MarkusObendrauf approved these changes

2023-02-28 09:42 UTC, merged