Add .opossum support: Wire FileSupportPopup
opossum-tool/OpossumUI pull request #1444
Opened 2023-02-28 08:19 UTC by lennartclaas

### Summary of changes

Based on the user input in the `FileSupportPopup`, data loading is handled in different ways. Either converting the outdated format into `.opossum` or keeping the old format and proceed. Another popup is shown if a file with an outdated format is opened but a `.opossum` file with the same name is in the same folder.

### How can the changes be tested

Open files from `example-files` folder.

### Screenshots
Create `.opossum` file popup:
![Unbenannt](https://user-images.githubusercontent.com/83081698/221794117-2ceda28b-45be-40e5-970d-5cf3b36d78aa.PNG)

Open .opossum file that is already existent:
![Unbenannt2](https://user-images.githubusercontent.com/83081698/221794206-fba5b27e-f33c-414a-99ea-cc878b00bb67.PNG)

2023-02-28 10:00 UTC, MarkusObendrauf requested changes

2023-02-28 11:22 UTC, MarkusObendrauf requested changes

2023-02-28 11:22 UTC, MarkusObendrauf commented on src/Frontend/Components/FileSupportPopupDotOpossumAlreadyExists/FileSupportPopupDotOpossumAlreadyExists.tsx
> +  'You are trying to open a file with an outdated extension (".json" or ".json.gz"). \
i think we usually use `\n'` and `+` (not sure)

2023-02-28 11:22 UTC, MarkusObendrauf commented on src/Frontend/Components/FileSupportPopupDotOpossumAlreadyExists/FileSupportPopupDotOpossumAlreadyExists.tsx
> +export function FileSupportPopupDotOpossumAlreadyExists(): ReactElement {
i would find `FileSupportDotOpossumAlreadyExistsPopup` easier to understand

2023-02-28 11:22 UTC, MarkusObendrauf commented on src/Frontend/enums/enums.ts
> +  FileSupportPopupDotOpossumAlreadyExists = 'FileSupportPopupDotOpossumAlreadyExists',
if you rename as suggested, dont forget to update this string too

2023-02-28 12:15 UTC, benedikt-richter commented on src/Frontend/Components/FileSupportPopupDotOpossumAlreadyExists/FileSupportPopupDotOpossumAlreadyExists.tsx
> +    ></NotificationPopup>
`></NotificationPopup>` -> `/>`

2023-02-28 12:15 UTC, benedikt-richter commented on src/Frontend/Components/FileSupportPopupDotOpossumAlreadyExists/FileSupportPopupDotOpossumAlreadyExists.tsx
> +    ></NotificationPopup>
same in other popup

2023-02-28 12:15 UTC, benedikt-richter commented on src/Frontend/Components/FileSupportPopupDotOpossumAlreadyExists/FileSupportPopupDotOpossumAlreadyExists.tsx
> +const INFO_TEXT_PART_1 =
this string is similar but still different from the one in the other popup. This should not be the case.

2023-02-28 12:15 UTC, benedikt-richter commented on src/Frontend/Components/FileSupportPopupDotOpossumAlreadyExists/FileSupportPopupDotOpossumAlreadyExists.tsx
> +export const HEADER = 'Warning: Outdated input file format';
This one should not be exported

2023-02-28 12:15 UTC, benedikt-richter commented on src/Frontend/Components/FileSupportPopupDotOpossumAlreadyExists/FileSupportPopupDotOpossumAlreadyExists.tsx
> +export function FileSupportPopupDotOpossumAlreadyExists(): ReactElement {
or just `DotOpossumFileAlreadyExistsPopup`

2023-02-28 12:15 UTC, benedikt-richter commented on src/Frontend/Components/FileSupportPopupDotOpossumAlreadyExists/FileSupportPopupDotOpossumAlreadyExists.tsx
> +export function FileSupportPopupDotOpossumAlreadyExists(): ReactElement {
This component should be tested.

2023-02-28 12:15 UTC, benedikt-richter commented on src/Frontend/Components/FileSupportPopupDotOpossumAlreadyExists/FileSupportPopupDotOpossumAlreadyExists.tsx
> +export const HEADER = 'Warning: Outdated input file format';
same in other popup

2023-02-28 12:15 UTC, benedikt-richter commented on src/Frontend/Components/FileSupportPopup/FileSupportPopup.tsx
> +  const handleCreateAndProceedButtonClick = (): void => {
component should be tested.

2023-02-28 12:15 UTC, benedikt-richter commented on src/Frontend/Components/GlobalPopup/GlobalPopup.tsx
> +    case PopupType.FileSupportPopupDotOpossumAlreadyExists:
This case should be tested

2023-02-28 12:15 UTC, benedikt-richter commented on src/shared/ipc-channels.ts
> +  ConvertInputFileToDotOpossum = 'convert-input-file-to-dot-opossum',
The other names are all very short. Can we use `ConvertInputFile` and so on?

2023-02-28 12:15 UTC, benedikt-richter commented on src/shared/shared-types.ts
> +  openDotOpossumFile: () => Promise<void>;
Why do these return a promise?

2023-02-28 12:15 UTC, benedikt-richter commented on src/ElectronBackend/main/main.ts
> +      getUseOutdatedInpuFileFormatListener(mainWindow)
typo

2023-02-28 12:15 UTC, benedikt-richter commented on src/ElectronBackend/main/main.ts
>      ipcMain.handle(IpcChannel.OpenFile, getOpenFileListener(mainWindow));
Confusing to have `OpenFile` and `OpenDotOpossumFile`

2023-02-28 12:15 UTC, benedikt-richter commented on src/ElectronBackend/main/listeners.ts
> +        throw new Error(`Resource file path is falsy: ${resourceFilePath}`);
This error message should be rewritten to expose less technical information. The issue is not that the variable is falsy, but that there is an invalid path.

2023-02-28 12:15 UTC, benedikt-richter commented on src/ElectronBackend/main/listeners.ts
> +      const resourceFilePath = globalBackendState.resourceFilePath;
What is going on here?
If we are opening a .opossum file here, then we should not use `resourceFilePath`

2023-02-28 12:15 UTC, benedikt-richter commented on src/ElectronBackend/main/listeners.ts
> +        throw new Error(`Resource file path is falsy: ${resourceFilePath}`);
please, improve error message

2023-02-28 12:21 UTC, benedikt-richter commented on src/ElectronBackend/main/listeners.ts
> +export function getConvertInputFileToDotOpossumListener(
This is a long function. Please, extract parts that belong together into smaller functions. Inparticular, there is a lot of magic happening with paths and file names. Also extract that logic and extract the relevant "magic strings" that are used in that context.

2023-02-28 12:24 UTC, benedikt-richter commented on src/ElectronBackend/main/listeners.ts
> +const outputFileEnding = '_attributions.json';
should also be used in line 168

2023-02-28 14:17 UTC, lennartclaas commented on src/ElectronBackend/main/listeners.ts
> +const dotOpossumFileCompressionLevel = 1; // TODO: which level?
I created a new constant and set it to 5.

2023-02-28 14:20 UTC, lennartclaas commented on src/ElectronBackend/main/listeners.ts
> +      await openFile(mainWindow, dotOpossumFilePath);
Changed name to `getConvertInputFileToDotOpossumAndOpenListener`.

2023-02-28 14:27 UTC, lennartclaas commented on src/Frontend/Components/FileSupportPopupDotOpossumAlreadyExists/FileSupportPopupDotOpossumAlreadyExists.tsx
> +const INFO_TEXT_PART_1 =
I don't see the problem. What solution do you propose?

2023-02-28 14:30 UTC, lennartclaas commented on src/Frontend/Components/FileSupportPopupDotOpossumAlreadyExists/FileSupportPopupDotOpossumAlreadyExists.tsx
> +export const HEADER = 'Warning: Outdated input file format';
It's only for testing. I could rename it more specifically to the underlying component, I could move it to `shared-constants`, or I could just copy it to the test. For now, I have chosen the last option.

2023-02-28 14:42 UTC, lennartclaas commented on src/shared/shared-types.ts
> +  openDotOpossumFile: () => Promise<void>;
Because the invoked listeners return promises. Maybe I misunderstood that. We should discuss it.

2023-02-28 14:49 UTC, lennartclaas commented on src/ElectronBackend/main/listeners.ts
> +      const resourceFilePath = globalBackendState.resourceFilePath;
Good point. Was a remnant from before the previous ticket was commited.

2023-02-28 15:10 UTC, lennartclaas commented on src/ElectronBackend/main/listeners.ts
> +export function getConvertInputFileToDotOpossumListener(
I changed some stuff. We should discuss these changes.

2023-02-28 16:16 UTC, lennartclaas commented on src/ElectronBackend/main/listeners.ts
> +export function getConvertInputFileToDotOpossumListener(
👍

2023-02-28 16:39 UTC, lennartclaas commented on src/Frontend/Components/FileSupportPopupDotOpossumAlreadyExists/FileSupportPopupDotOpossumAlreadyExists.tsx
> +const INFO_TEXT_PART_1 =
👍

2023-02-28 16:39 UTC, lennartclaas commented on src/shared/shared-types.ts
> +  openDotOpossumFile: () => Promise<void>;
Removed promise. Not needed.

2023-03-01 10:07 UTC, MarkusObendrauf requested changes

2023-03-01 10:07 UTC, MarkusObendrauf commented on src/ElectronBackend/main/__tests__/listeners.test.ts
> +  it('sends signal for opening FileSupportPopupDotOpossumExistent to frontend when .opossum file is existent', async () => {
`is existent` -> `exists`

2023-03-01 10:07 UTC, MarkusObendrauf commented on src/ElectronBackend/main/__tests__/listeners.test.ts
> +  });
add newlines between tests

2023-03-01 10:07 UTC, MarkusObendrauf commented on src/ElectronBackend/main/__tests__/listeners.test.ts
> +    });
this should be reused from the non-test code

2023-03-01 11:53 UTC, leslielazzarino commented
When opening an old file format, with the new format version already existing, I get an error when I click on opening the new format file instead. Reloading the file fixes the issue, but this shouldn't happen.

2023-03-01 11:53 UTC, leslielazzarino requested changes
See comment

2023-03-01 12:03 UTC, lennartclaas commented on src/ElectronBackend/main/listeners.ts
> +}
Nice idea. I like that.

2023-03-01 12:14 UTC, lennartclaas commented on src/ElectronBackend/main/__tests__/listeners.test.ts
> +    });
`parseOpossumFile` returns parsed objects. I don't want that in this case because the file contents are just one-line-strings. Mocking a real input file just blows up the test and the code to unzip the opossum file is quite easy to read. Therefore, I would keep it as it is.

2023-03-02 08:33 UTC, MarkusObendrauf commented on src/e2e-tests/test-helpers/test-helpers.ts
> +export async function getButtonWithName(
i like this a lot

2023-03-02 08:35 UTC, leslielazzarino approved these changes

2023-03-02 08:43 UTC, MarkusObendrauf commented
If I open a .json.gz and an opossum file already exists, it is not detected.

2023-03-02 09:28 UTC, MarkusObendrauf requested changes

2023-03-02 09:28 UTC, MarkusObendrauf commented on src/ElectronBackend/main/listeners.ts
> +      filePathWithoutFileExtension + OPOSSUM_FILE_EXTENSION;
isn't this exactly what the function `getDotOpossumFilePath` does?

2023-03-02 13:13 UTC, merged