Remove unused devDependencies
opossum-tool/OpossumUI pull request #146
Opened 2021-10-29 14:45 UTC by benedikt-richter

### Summary of changes

* Unused dependencies are removed
* the package is renamed to only consist of valid characters

2021-11-01 07:52 UTC, nicarl approved these changes

2021-11-02 08:12 UTC, nicarl requested changes
Can you also modify the release github action?

2021-11-02 08:19 UTC, benedikt-richter commented
The github action does not have to be modified as we rename the files when shipping. These internals are encapsulated in the ship scripts :)

2021-11-02 08:24 UTC, nicarl approved these changes

2021-11-02 09:50 UTC, antonbauhofer requested changes

2021-11-02 09:50 UTC, antonbauhofer commented on package.json
> +  "name": "opossum-ui",
This changes the shown name of the app (i.e. for Mac, the name shown in the top left of the screen and in the applications bar at the bottom). I am not sure about the other systems, but in Mac it is common, to have the name shown including capitalization.
I think I would rather have the warning than changing the name of the app. Or is there another fix for this?

2021-11-02 11:54 UTC, benedikt-richter commented on package.json
> +  "name": "opossum-ui",
Good catch! I agree that we want to show the name "OpossumUI". The config for the builder is adapted to make sure that's the case even though we use a different name here.

2021-11-02 15:19 UTC, antonbauhofer approved these changes
Looks good now.

2021-11-02 16:09 UTC, merged