Attribution Wizard: Prevent empty attributions
opossum-tool/OpossumUI pull request #1465
Opened 2023-03-07 10:11 UTC by lennartclaas

### Summary of changes

The apply button is disabled as long as the generated purl is invalid. This includes empty attributions but also ensures that a truthy package name is given. Additionally, booleans indicating whether a package name, namespace, or version is selected are removed since these are always true due to pre-selection. 

### Context and reason for change

Empty attributions are forbidden and should be avoided.

### How can the changes be tested

Open the attribution wizard and select empty package name.

Fix: #1451

2023-03-07 15:49 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardPopup/AttributionWizardPopup.tsx
> +      ? 'Please generate valid purl to apply changes'
I think, for some users it is difficult to know what is a valid PURL. This tooltip might be confusing, as it requires an understanding of the spec for PURLs.

2023-03-07 15:51 UTC, benedikt-richter commented on src/Frontend/Components/AttributionWizardPopup/AttributionWizardPopup.tsx
>      buttonText: ButtonText.Next,
Why do we now allow to navigate to the second step? Once in the second step with mit having selected a package name, the user has no way to make the `apply` button clickable.

2023-03-07 16:46 UTC, lennartclaas commented on src/Frontend/Components/AttributionWizardPopup/AttributionWizardPopup.tsx
> +      ? 'Please generate valid purl to apply changes'
Changed the tooltip.

2023-03-10 09:03 UTC, antonbauhofer reviewed
In the summary, you write that version etc. are always true due to pre-selection. Can you elaborate on that?

2023-03-10 09:12 UTC, antonbauhofer approved these changes

2023-03-10 10:43 UTC, lennartclaas commented on src/Frontend/Components/AttributionWizardPopup/AttributionWizardPopup.tsx
> -    tooltipPlacement: 'top',
It is not possible that no item in the version list is selected. In an older version this was possible but not anymore.

2023-03-10 10:49 UTC, lennartclaas commented
@antonbauhofer regarding your [comment](https://github.com/opossum-tool/OpossumUI/pull/1465#pullrequestreview-1334406278).

> In the summary, you write that version etc. are always true due to pre-selection. Can you elaborate on that?

The wizard is opened via the context menu of a manual attribution. The package attributes of this manual attribution like name, namespace, and version are pre-selected in the corresponding lists in the wizard (the - entry if the attribute is empty). Therefore, it is not possible that no item in a list is selected. The corresponding flags are therefore always true and hence unnecessary.

2023-03-13 12:37 UTC, leslielazzarino requested changes
Yous should write a test for the behavior.

2023-03-13 15:55 UTC, leslielazzarino approved these changes

2023-03-13 17:19 UTC, merged