Add comment text field array
opossum-tool/OpossumUI pull request #1477
Opened 2023-03-13 15:39 UTC by FlorianSchepers

### Summary of changes

Introduced new component that accepts an array of comments and displays them as an array of text fields for signals and attributions.

### Context and reason for change

We want to enable a signal or attribution to have multiple comments (i.e. if two identical signals with different comments are merged).

### How can the changes be tested

- Checkout PR
- Run tests in: `src/Frontend/Components/CommentTextFieldArray/__tests__/CommentTextFieldArray.test.tsx`
- In `src/Frontend/Components/AttributionColumn/AuditingSubPanel.tsx` replace the value for `comments` in the call of the `CommentTextFieldArray` by an hard coded array of strings and check the result in the app.

2023-03-13 17:15 UTC, lennartclaas requested changes
Looks good so far, but I think some features could be added to make this new component more useful.

2023-03-13 17:15 UTC, lennartclaas commented on src/Frontend/Components/CommentTextFieldArray/__tests__/CommentTextFieldArray.test.tsx
> +  it('renders number of comments if collapsed', () => {
Extreme nit: empty line between tests.

2023-03-13 17:15 UTC, lennartclaas commented on src/Frontend/Components/CommentTextFieldArray/__tests__/CommentTextFieldArray.test.tsx
> +    renderComponentWithStore(
Nit: render() should also work.

2023-03-13 17:17 UTC, lennartclaas commented
Could the distance indicated by the arrow be decreased before introducing the vertical scroll bar?

![Screenshot 2023-03-13 181037](https://user-images.githubusercontent.com/83081698/224777232-b28d89ca-9fb2-45c9-8b1f-bbfa140e3887.png)

2023-03-14 13:06 UTC, MarkusObendrauf requested changes

2023-03-14 13:06 UTC, MarkusObendrauf commented on src/Frontend/Components/CommentTextFieldArray/__tests__/CommentTextFieldArray.test.tsx
> +      'This ist the first comment',
same as above

2023-03-14 13:06 UTC, MarkusObendrauf commented on src/Frontend/Components/CommentTextFieldArray/__tests__/CommentTextFieldArray.test.tsx
> +    const comments = ['This ist the first comment'];
as above

2023-03-14 16:35 UTC, FlorianSchepers commented on src/Frontend/Components/AttributionColumn/AuditingSubPanel.tsx
> +      <CommentTextFieldArray
Ok, i will rename it to `TextFieldStack`

2023-03-15 08:26 UTC, FlorianSchepers commented
> Could the distance indicated by the arrow be decreased before introducing the vertical scroll bar?
> 
> ![Screenshot 2023-03-13 181037](https://user-images.githubusercontent.com/83081698/224777232-b28d89ca-9fb2-45c9-8b1f-bbfa140e3887.png)

2023-03-15 08:48 UTC, FlorianSchepers commented
> Could the distance indicated by the arrow be decreased before introducing the vertical scroll bar?
> 
> ![Screenshot 2023-03-13 181037](https://user-images.githubusercontent.com/83081698/224777232-b28d89ca-9fb2-45c9-8b1f-bbfa140e3887.png)

There is a hard coded size for the whole attribution panel. So the size of the comment section is calculated based on the remaining size below the other components.

2023-03-15 09:28 UTC, MarkusObendrauf requested changes
I tried adding a comment to a component which had none, and it didn't work well.

- Firstly, the comments box is now called "No comments". Instead, "Comments" would be more sensible.
- After typing one letter, the text box height changed, and was deselected. I can't just continue typing, instead I need to select the box a second time.
- The text box is named "Comment 1". This suggests that it is possible to have multiple comments. But this is not actually possible for a user from the outside world. If we do not allow a user to create multiple comments, then it should be named "Comment".  But I think we should support users adding new comments, otherwise it's impossible to undo a comment merge.
- Also, performance on adding text is unbelievably bad. Really hurts the user experiences, it feels necessary to improve that. (Not related to this PR)

2023-03-16 09:19 UTC, lennartclaas commented on src/Frontend/Components/CommentTextFieldArray/CommentTextFieldArray.tsx
> +    width: '100%',
👍

2023-03-16 09:19 UTC, lennartclaas commented on src/Frontend/Components/CommentTextFieldArray/CommentTextFieldArray.tsx
> +export function CommentTextFieldArray(
👍

2023-03-16 09:20 UTC, lennartclaas approved these changes
👍

2023-03-16 12:19 UTC, FlorianSchepers commented
> I tried adding a comment to a component which had none, and it didn't work well.
> 
>     * Firstly, the comments box is now called "No comments". Instead, "Comments" would be more sensible.
> 
>     * After typing one letter, the text box height changed, and was deselected. I can't just continue typing, instead I need to select the box a second time.
> 
>     * The text box is named "Comment 1". This suggests that it is possible to have multiple comments. But this is not actually possible for a user from the outside world. If we do not allow a user to create multiple comments, then it should be named "Comment".  But I think we should support users adding new comments, otherwise it's impossible to undo a comment merge.
> 
>     * Also, performance on adding text is unbelievably bad. Really hurts the user experiences, it feels necessary to improve that. (Not related to this PR)

I have fixed your issues as follows:

- If there is no comment an empty comment with the title 'comment' will be shown. 
- Text can be added to this comment without the neet to reselect this comment box.
- Only if there are more than one comment the title of the comment boxes will be numbered, e.g., 'comment 1', 'comment 2' ...
- In case the comment section is collapsed (i.e., extended license text) a non editable text box is shown whichs tates the number of non empty comments.

2023-03-16 13:49 UTC, MarkusObendrauf approved these changes

2023-03-16 15:54 UTC, merged