Show popup when clicking on the go-to-link button for an invalid link
opossum-tool/OpossumUI pull request #149
Opened 2021-11-02 09:08 UTC by antonbauhofer

### Summary of changes

Show error popup when clicking on the go-to-link button for an invalid link

### Context and reason for change

Before this fix, an error was thrown in the backend that was not caught. There was no feedback for the user in the OpossumUI.

### How can the changes be tested

Run `yarn test`

2021-11-02 12:12 UTC, benedikt-richter commented on src/Frontend/Components/ErrorPopup/ErrorPopup.tsx
> +  content: string;
could be the same type as `content` in `NotificationPopup`

2021-11-02 12:15 UTC, benedikt-richter commented on src/e2e-tests/__tests__/e2e.test.ts
> +describe('Open link from path bar', () => {
cool 👍

2021-11-02 12:20 UTC, benedikt-richter commented on src/ElectronBackend/main/listeners.ts
> +      return new Error('Invalid path');
could be `'Invalid link'`

2021-11-02 12:55 UTC, nicarl commented on example-files/opossum_input.json
> +    "test.txt": 1,
Why was this added?

2021-11-02 13:02 UTC, nicarl requested changes
I get an error popup from the file system, this is not how it should look like? The end-2-end test fails under linux.
The branch seems not up to date with master (no opossum logo under linux available), branch should be rebased

2021-11-03 08:42 UTC, nicarl commented
Rebasing will give you CI feedback for the e2e-tests

2021-11-03 12:35 UTC, benedikt-richter commented on src/Frontend/Components/GoToLinkButton/GoToLinkButton.tsx
> +          });
couzld be extracted into a function

2021-11-03 12:44 UTC, benedikt-richter commented on src/Frontend/Components/Icons/Icons.tsx
> +
should be deleted.

also the class 'robotArmIcon' is now unused and can be removed

2021-11-04 14:23 UTC, nicarl reviewed
There does not seem to be a solution for linux for now (see comments)

2021-11-04 14:23 UTC, nicarl commented on src/ElectronBackend/errorHandling/errorHandling.ts
> +        log.info('Failed executing callback function.\n' + error.message);
Consider using `${}` template strings (similar to f strings in python)

2021-11-04 14:23 UTC, nicarl commented on src/ElectronBackend/main/listeners.ts
> +      return await shell.openExternal(args.link);
The problem on linux is the following:
- it uses xdg-open for `openExternal`
- apparently any errors thrown from xdg-open are not communicated back to electron so `shell.openExternal` currently never throws on linux (https://github.com/electron/electron/issues/28183)
- If I set the link to a non existing path I get a system popup which is created from my file explorer
- If I set an invalid link (like in e2e test) I `xdg-open` just logs its help

2021-11-04 14:23 UTC, nicarl commented on src/e2e-tests/test-resources/opossum_input_e2e.json
> +    "/ElectronBackend/": "invalid/link"
This is only one of the error cases. The other error case is a local file/folder which does not exist. Both cases behave differently on linux.

2021-11-04 15:10 UTC, antonbauhofer commented on src/ElectronBackend/errorHandling/errorHandling.ts
> +        log.info('Failed executing callback function.\n' + error.message);
Actually, I did use template strings at first, but thought it was more readable the way it is now.

2021-11-04 15:10 UTC, antonbauhofer commented on src/ElectronBackend/main/listeners.ts
> +      return await shell.openExternal(args.link);
That's unfortunate. So, the feature will not work in Linux for now. We'll add a comment for that.

2021-11-04 15:10 UTC, antonbauhofer commented on src/e2e-tests/test-resources/opossum_input_e2e.json
> +    "/ElectronBackend/": "invalid/link"
I added a second end-to-end test to cover this.

2021-11-04 15:33 UTC, nicarl approved these changes
Skips the test locally for linux

2021-11-04 15:44 UTC, merged