Added functionality to check for newer release
opossum-tool/OpossumUI pull request #1524
Opened 2023-03-30 13:47 UTC by vasily-pozdnyakov

### Summary of changes

There is a new top bar menu item to check for OpossumUI latest release.

### Context and reason for change

Part of #1472

### How can the changes be tested

There are some tests.
Check in the UI: "help" - "check for updates"

2023-03-30 14:53 UTC, leslielazzarino approved these changes
Cool. It would be even cooler if it checked for a new version when the app is started.

2023-03-31 08:37 UTC, benedikt-richter requested changes
![Screenshot 2023-03-31 at 10 30 39](https://user-images.githubusercontent.com/46576389/229069829-29124b43-de43-4575-8fbc-d75c50801128.png)
![Screenshot 2023-03-31 at 10 33 06](https://user-images.githubusercontent.com/46576389/229069842-f4ab8e9d-192e-43d2-8925-17db5ee7afed.png)

works nicely!

Some UI observations: (see screenshots)
* The spinner is too big in my opinion.
* The font is different in the link

2023-03-31 08:37 UTC, benedikt-richter commented on src/Frontend/Components/GlobalPopup/__tests__/GlobalPopup.test.tsx
> +  it('opens the UpdateAppPopup', () => {
We should also test the query.

2023-03-31 08:37 UTC, benedikt-richter commented on src/Frontend/Components/UpdateAppPopup/__tests__/UpdateAppPopup.test.tsx
> +describe('UpdateAppPopup', () => {
Nice tests! 👍

2023-03-31 10:55 UTC, vasily-pozdnyakov commented on src/Frontend/Components/UpdateAppPopup/__tests__/UpdateAppPopup.test.tsx
> +// SPDX-FileCopyrightText: Nico Carl <nicocarl@protonmail.com>
Copied from some other component

2023-03-31 11:41 UTC, vasily-pozdnyakov commented
> ![Screenshot 2023-03-31 at 10 30 39](https://user-images.githubusercontent.com/46576389/229069829-29124b43-de43-4575-8fbc-d75c50801128.png) ![Screenshot 2023-03-31 at 10 33 06](https://user-images.githubusercontent.com/46576389/229069842-f4ab8e9d-192e-43d2-8925-17db5ee7afed.png)
> 
> works nicely!
> 
> Some UI observations: (see screenshots)
> 
> * The spinner is too big in my opinion.
> * The font is different in the link

I am ok with the spinner size - anyway it is usually shown just for a second.
I corrected the font.

2023-03-31 12:17 UTC, benedikt-richter approved these changes

2023-03-31 12:17 UTC, merged