Deduplicate Signals: Add originIds to PackageInfo
opossum-tool/OpossumUI pull request #1527
Opened 2023-03-31 10:36 UTC by lennartclaas

### Summary of changes

In PackageInfo, replace originId (string) with originIds (Array<string>). If the input file contains originId, write it into originIds. Same when loading output files. When saving, the output file only contains originIds.

### Context and reason for change

Part of the story 'Deduplicate reused signals that are identical'.

### How can the changes be tested

Run newly added tests or open test files.

2023-03-31 12:12 UTC, MarkusObendrauf requested changes

2023-03-31 12:12 UTC, MarkusObendrauf commented on src/ElectronBackend/input/OpossumOutputFileSchema.json
> +            }
i *really* dont think we should be changing the output schema. this would break tools that read opossum output files

2023-03-31 12:12 UTC, MarkusObendrauf commented on src/ElectronBackend/input/OpossumInputFileSchema.json
> +            }
i don't think we should be changing the input file schema (does not seem to be in the ticket)

2023-03-31 12:25 UTC, MarkusObendrauf requested changes

2023-03-31 12:25 UTC, MarkusObendrauf commented on src/ElectronBackend/input/__tests__/parseInputData.test.ts
> +        originIds: ['def', 'ghi'],
i would expect 'abc' to be added to this list

2023-03-31 12:25 UTC, MarkusObendrauf commented on src/ElectronBackend/input/importFromFile.ts
> +  console.log(
remove (+other `console.log`s in this file)

2023-03-31 13:41 UTC, lennartclaas commented on src/ElectronBackend/input/__tests__/parseInputData.test.ts
> +        originIds: ['def', 'ghi'],
We decided to drop `originId` in case `originIds`  exists as well, since `originId` should be outdated in that case. However, in practice, it should not be possible to have both fields set, unless someone adds it manually.

2023-03-31 13:48 UTC, benedikt-richter commented on src/ElectronBackend/input/parseInputData.ts
> +        rawAttributions[attributionId].originIds = new Array<string>(
Would prefer not to use the constructor for the array, as we typically do not do this

2023-03-31 14:19 UTC, lennartclaas commented on src/ElectronBackend/input/parseInputData.ts
> +          rawAttributions[attributionId].originId ?? ''
Changed as discussed. Execution time changed from 0.7 ms to 0.85 ms for the ort file... 😅

2023-03-31 14:20 UTC, lennartclaas commented on src/Frontend/Components/ReportTableItem/report-table-item-helpers.ts
> +  let cellData: string | number = '';
Just for typing reasons. We should discuss this in more detail.

2023-04-03 09:19 UTC, lennartclaas commented on src/Frontend/Components/ReportTableItem/report-table-item-helpers.ts
> +  let cellData: string | number = '';
Changed according to discussion.

2023-04-03 09:28 UTC, benedikt-richter approved these changes

2023-04-03 09:54 UTC, MarkusObendrauf requested changes
just some minor comments

2023-04-03 09:54 UTC, MarkusObendrauf commented on src/ElectronBackend/input/importFromFile.ts
> -
i would keep the line break (looks like an accident)

2023-04-03 09:54 UTC, MarkusObendrauf commented on src/ElectronBackend/input/parseInputData.ts
> +      rawAttributions[attributionId].originIds = originIds
i had to do a double take when reading this line. the `= originIds` looks like an assignment but is actually a condition for a ternary. i would find this easier to read:
```
const originIds = rawAttributions[attributionId].originIds ?? [];
originIds.push(originId);
rawAttributions[attributionId].originIds = originIds;
```
although here we still change `originIds` in place which isnt perfect

2023-04-03 09:57 UTC, benedikt-richter commented on src/ElectronBackend/input/parseInputData.ts
> +      rawAttributions[attributionId].originIds = originIds
The `= originIds` actually is an assignment. The ternary is `originIds ? [...originIds, originId] : [originId];`

However, I agree that this part of the code was not the easiest to read.

2023-04-03 09:59 UTC, lennartclaas commented on src/ElectronBackend/input/__tests__/parseInputData.test.ts
> +      expectedParsedRawAttributions,
Why? To not having a red test when the implementation with respect to order is changed? I think it would be nice to know if changes like this happen. Maybe it is important in the future.

2023-04-03 10:18 UTC, lennartclaas commented on src/ElectronBackend/input/parseInputData.ts
> +      rawAttributions[attributionId].originIds = originIds
I agree that you need to take a glance at the next line to realize it is a ternary.  I changed the implementation according to Markus' suggestion. It's even slightly faster this way. :)

2023-04-03 10:26 UTC, MarkusObendrauf approved these changes
Nice

2023-04-03 11:04 UTC, merged