Group signals by hash
opossum-tool/OpossumUI pull request #1530
Opened 2023-03-31 15:28 UTC by leslielazzarino

### Summary of changes

### Context and reason for change

### How can the changes be tested

Note: Please review the [guidelines for contributing](https://github.com/opossum-tool/OpossumUI/blob/main/CONTRIBUTING.md) to this repository.

2023-04-04 05:56 UTC, benedikt-richter commented on src/Frontend/Components/PackagePanel/PackagePanel.tsx
> +    );
What is going on here?

2023-04-04 05:58 UTC, benedikt-richter commented on src/Frontend/state/selectors/all-views-resource-selectors.ts
> +  }
why do we need this "hack"?

2023-04-04 06:00 UTC, benedikt-richter commented on src/shared/shared-types.ts
> +interface PackageInfoCore {
we could also have a comments array always. This would avoid introducing this new almost identical type

2023-04-04 08:21 UTC, lennartclaas requested changes

2023-04-04 08:21 UTC, lennartclaas commented on src/Frontend/Components/AggregatedAttributionsPanel/accordion-panel-helpers.ts
> +  const mergedPackageInfo = <MergedPackageInfo>packageInfoWithoutComment;
To prevent the type cast, one could do something like this:
`const comments = attribution.comment ? [attribution.comment] : [];`
`const mergedPackageInfo: MergedPackageInfo = {...packageInfoWithoutComment, comments};`

2023-04-04 08:21 UTC, lennartclaas commented on src/Frontend/Components/AggregatedAttributionsPanel/accordion-panel-helpers.ts
> +      (attributionsWithId): number =>
I would call it `attributionWithId`.

2023-04-04 08:21 UTC, lennartclaas commented on src/Frontend/Components/AggregatedAttributionsPanel/accordion-panel-helpers.ts
> +    .map((attributionsWithId) => attributionsWithId[1].comment)
Same here.

2023-04-04 08:21 UTC, lennartclaas commented on src/Frontend/Components/AggregatedAttributionsPanel/accordion-panel-helpers.ts
> +    attributionId: attributionsWithIds[0][0],
It would make sense to generate a new uuid for a merged signal.

2023-04-05 06:40 UTC, leslielazzarino commented on src/shared/shared-types.ts
> +interface PackageInfoCore {
This would change the input/output file format and not be backwards compatible.

2023-04-05 06:47 UTC, leslielazzarino commented on src/Frontend/Components/AggregatedAttributionsPanel/accordion-panel-helpers.ts
> +    attributionId: attributionsWithIds[0][0],
It will break everything we haven't fixed yet. It should probably be done, but at the end of the story.

2023-04-05 06:53 UTC, leslielazzarino commented on src/Frontend/Components/AggregatedAttributionsPanel/accordion-panel-helpers.ts
> +  const mergedPackageInfo = <MergedPackageInfo>packageInfoWithoutComment;
I removed the casting, now it works correctly without, but left the current logic, as a copy operation is somewhat expensive.

2023-04-05 08:22 UTC, vasily-pozdnyakov requested changes
Why do we need to change opossum_input.json?
UI question: do we plan to show some info at the signal card indicating that it is a merged signal?

2023-04-05 08:22 UTC, vasily-pozdnyakov commented on src/Frontend/Components/AggregatedAttributionsPanel/accordion-panel-helpers.ts
> +function getMergedAttributionWithCountFromAttributions(
Just my feeling: I do not like having two functions with very long names which differ only by the last letter, but with very different implementations.
Maybe rename like: getMergedAttributionWithCountFromSingleAttribution and getMergedAttributionWithCountFromMultipleAttributions

2023-04-05 08:22 UTC, vasily-pozdnyakov commented on src/Frontend/Components/PackagePanel/PackagePanel.tsx
> +    );
Honestly, I do not get this part.

2023-04-05 08:27 UTC, leslielazzarino commented on .gitignore
> +/.run
I need it to ignore some config files on IntelliJ

2023-04-05 08:30 UTC, leslielazzarino commented on src/Frontend/Components/AggregatedAttributionsPanel/accordion-panel-helpers.ts
> +    if (!savedHash) {
I've inverted it

2023-04-05 08:37 UTC, leslielazzarino commented on src/Frontend/Components/AggregatedAttributionsPanel/accordion-panel-helpers.ts
> +function getMergedAttributionWithCountFromAttributions(
The two fuction do the same thing, strating from different inputs. I could turn them into a single function with two different prototypes, if you prefer it.

2023-04-05 08:38 UTC, leslielazzarino commented on src/Frontend/Components/PackagePanel/PackagePanel.tsx
> +    );
Ignore the typing, then it becomes clear. The typing is weird, because I could not find a way to make TS understand what i'm doing.

2023-04-05 08:39 UTC, leslielazzarino commented on src/Frontend/state/selectors/all-views-resource-selectors.ts
> +  }
Actually I think it is much cleaner than before. It tells you explicitly "if you are on a read-only panel, nothing was changed".

2023-04-05 09:03 UTC, lennartclaas approved these changes
lgtm

2023-04-05 09:11 UTC, benedikt-richter commented on src/Frontend/Components/PackagePanel/PackagePanel.tsx
> +    );
The following properly handles types:
```
    const attributionIdOrMergedAttributionWithCount =
      props.attributionIdsWithCount.find(
        (attributionIdWithCount) =>
          attributionIdWithCount.attributionId === attributionId
      );
    if (!attributionIdOrMergedAttributionWithCount) {
      return undefined;
    }

    function isMergedAttribution(
      attributionIdOrMergedAttributionWithCount:
        | AttributionIdWithCount
        | MergedAttributionWithCount
    ): attributionIdOrMergedAttributionWithCount is MergedAttributionWithCount {
      return 'attribution' in attributionIdOrMergedAttributionWithCount;
    }

    return isMergedAttribution(attributionIdOrMergedAttributionWithCount)
      ? attributionIdOrMergedAttributionWithCount?.attribution
      : undefined;
```

2023-04-05 09:31 UTC, benedikt-richter requested changes

2023-04-05 09:31 UTC, benedikt-richter commented on src/Frontend/Components/AggregatedAttributionsPanel/accordion-panel-helpers.ts
> +    .map((attributionWithId) => attributionWithId[1].comment)
`|| ""` then you can drop the type cast

2023-04-05 09:31 UTC, benedikt-richter commented on src/Frontend/Components/AttributionColumn/AuditingSubPanel.tsx
> +          (props.displayPackageInfo as MergedPackageInfo).comments ||
Also use type guard here

2023-04-05 10:37 UTC, benedikt-richter commented on src/Frontend/Components/ResourceDetailsAttributionColumn/resource-details-attribution-column-helpers.ts
> +    // TODO: PackagePanelTitle.ContainedExternalPackages should use the same logic
When do we do that?

2023-04-05 10:38 UTC, benedikt-richter commented on src/Frontend/types/types.ts
> +  attributionIdOrMergedAttributionWithCount:
the variable name sounds a bit odd

2023-04-05 12:27 UTC, leslielazzarino commented on src/Frontend/Components/ResourceDetailsAttributionColumn/resource-details-attribution-column-helpers.ts
> +    // TODO: PackagePanelTitle.ContainedExternalPackages should use the same logic
The one where we take care of the PackagePanelTitle.ContainedExternalPackages panel.

2023-04-05 12:39 UTC, benedikt-richter requested changes

2023-04-05 12:39 UTC, benedikt-richter commented on src/Frontend/Components/AggregatedAttributionsPanel/AccordionPanel.tsx
> +  return attributionIdsWithCount && attributionIdsWithCount?.length === 0;
Why do we do `attributionIdsWithCount && ...`? As `attributionIdsWithCount` is an array it is always truthy.

2023-04-05 12:45 UTC, benedikt-richter commented on src/Frontend/state/actions/resource-actions/navigation-actions.ts
> +        : resetTemporaryPackageInfo()
maybe change `resetTemporaryPackageInfo` instead

2023-04-05 13:20 UTC, leslielazzarino commented on src/Frontend/state/selectors/all-views-resource-selectors.ts
> +  }
4+ tests become red removing these lines

2023-04-05 13:46 UTC, benedikt-richter approved these changes
👍

2023-04-05 14:01 UTC, merged