Deduplicate Signals: Populate externalAttributionsToHashes
opossum-tool/OpossumUI pull request #1533
Opened 2023-04-03 11:34 UTC by lennartclaas

### Summary of changes

After the parsed input data is sent to the frontend, calculate externalAttributionsToHashes and write it to the redux state. The following fields are ignored when hashing attributions: 'comment', 'attributionConfidence',  'originIds', and 'preSelected'. Furthermore, the following values are considered equal: null, undefined, and ''.

### Context and reason for change

Part of the story 'Deduplicate reused signals that are identical'.

### How can the changes be tested

Run new test in `action-and-reducer-helpers.test.ts` or log the data when opening a new file.

2023-04-03 12:29 UTC, benedikt-richter requested changes

2023-04-03 12:29 UTC, benedikt-richter commented on src/Frontend/state/helpers/action-and-reducer-helpers.ts
> +export function createExternalAttributionsToHashes(
`create` sounds a bit odd. Why not e.g. `get`?

2023-04-03 12:29 UTC, benedikt-richter commented on src/Frontend/state/helpers/action-and-reducer-helpers.ts
> +    ].includes(key);
This config should be extracted into a constant

2023-04-03 12:29 UTC, benedikt-richter commented on src/Frontend/state/helpers/action-and-reducer-helpers.ts
> +  const excludeKeys = function (key: string): boolean {
We typically write `function excludeKeys(...`

2023-04-03 12:29 UTC, benedikt-richter commented on src/Frontend/state/actions/resource-actions/load-actions.ts
> +    dispatch(setExternalAttributionsToHashes(externalAttributionsToHashes));
this code should be tested

2023-04-03 12:29 UTC, benedikt-richter commented on src/Frontend/state/helpers/action-and-reducer-helpers.ts
> +          (attribution[key] == null || attribution[key] === '') &&
which attribution[key] can actually be `null`?

2023-04-03 12:29 UTC, benedikt-richter commented on src/Frontend/state/helpers/action-and-reducer-helpers.ts
> +          (attribution[key] == null || attribution[key] === '') &&
btw using `==` is unsafe

2023-04-03 12:29 UTC, benedikt-richter commented on src/Frontend/state/helpers/action-and-reducer-helpers.ts
> +export function createExternalAttributionsToHashes(
In this function we loop two times over the in general very huge object `Object.entries(externalAttributions)`. Performance might be a real issue here.

2023-04-03 13:18 UTC, lennartclaas commented on src/Frontend/state/helpers/action-and-reducer-helpers.ts
> +export function createExternalAttributionsToHashes(
`getExternalAttributionsToHashes` is already used for the corresponding selector. Here, it's more about calculation. 

2nd comment as discusses.

2023-04-03 13:31 UTC, lennartclaas commented on src/Frontend/state/actions/resource-actions/load-actions.ts
> +    dispatch(setExternalAttributionsToHashes(externalAttributionsToHashes));
It is tested in `all-views-simple-actions.test.ts`. I noticed that in this file, actions and corresponding selectors are tested jointly.

2023-04-03 13:34 UTC, lennartclaas commented on src/Frontend/state/helpers/action-and-reducer-helpers.ts
> +          (attribution[key] == null || attribution[key] === '') &&
We used `attribution[key] == null` to consider both `(attribution[key] === null || attribution[key] === undefined)`. The reason is to consider `null`, `undefined`, and `''` the same with respect to hashing.

2023-04-03 14:07 UTC, benedikt-richter commented on src/Frontend/state/actions/resource-actions/load-actions.ts
> +    dispatch(setExternalAttributionsToHashes(externalAttributionsToHashes));
You added the present code, but did not modify the test. How is the new functionality tested?

2023-04-03 17:09 UTC, benedikt-richter commented on src/Frontend/state/helpers/load-action-helpers.ts
> +const FIELDS_TO_IGNORE_WHEN_HASHING_ATTRIBUTIONS = new Set<string>([
`string` could be `KeysOfPackageInfo`.

2023-04-03 17:09 UTC, benedikt-richter approved these changes

2023-04-04 06:42 UTC, lennartclaas commented on src/Frontend/state/helpers/load-action-helpers.ts
> +const FIELDS_TO_IGNORE_WHEN_HASHING_ATTRIBUTIONS = new Set<string>([
This leads to typing problems since the `excludeKeys` function in `hashOptions` requires a string type.

2023-04-04 12:30 UTC, vasily-pozdnyakov approved these changes
Please do not forget to squash the commits.

2023-04-04 13:43 UTC, merged