DRAFT! Deduplicate Signals: Create attribution from merged signal
opossum-tool/OpossumUI pull request #1542
Opened 2023-04-05 06:56 UTC by lennartclaas

### Summary of changes

### Context and reason for change

### How can the changes be tested

Note: Please review the [guidelines for contributing](https://github.com/opossum-tool/OpossumUI/blob/main/CONTRIBUTING.md) to this repository.

2023-04-06 09:19 UTC, MarkusObendrauf requested changes

2023-04-06 09:19 UTC, MarkusObendrauf commented on src/Frontend/Components/PackagePanel/PackagePanel.tsx
> +          ? removeCommentsFromMergedPackageInfo(packageInfo)
function should be called `convertMergedPackageInfoToPackageInfo`

2023-04-06 09:19 UTC, MarkusObendrauf commented on src/Frontend/Components/PackagePanel/package-panel-helpers.ts
> +  if (packageInfoWithoutComments.originalAttributionIds) {
i dont understand what is happening here. isnt `MergedPackageInfo.originalAttributionIds` non-optional?

2023-04-06 09:19 UTC, MarkusObendrauf commented on src/Frontend/integration-tests/audit-view-tests/__tests-ci__/add-to-attribution.test.tsx
> +  it('works correctly when adding a merged signal', () => {
`'adds a merged signal correctly'` or just `'adds a merged signal'`

2023-04-06 09:19 UTC, MarkusObendrauf commented on src/Frontend/Components/PackagePanel/package-panel-helpers.ts
> +export function removeCommentsFromMergedPackageInfo(
should be unit tested

2023-04-06 09:24 UTC, benedikt-richter requested changes

2023-04-06 09:24 UTC, benedikt-richter commented on src/Frontend/Components/PackagePanel/PackagePanel.tsx
> +        dispatch(addToSelectedResource(packageInfo));
Instead of initiating a constant of type `PackageInfo | MergedPackageInfo` and then transforming it to something of type `PackageInfo`, we should be more explicit.

I'd suggest to create a function that given an input of type `PackageInfo | MergedPackageInfo` returns a new instance of type `PackageInfo`.

2023-04-06 09:26 UTC, benedikt-richter commented on src/Frontend/Components/PackagePanel/package-panel-helpers.ts
> +  if (packageInfoWithoutComments.originalAttributionIds) {
Good point. It should be non-optional.

2023-04-06 09:32 UTC, lennartclaas commented on src/Frontend/Components/PackagePanel/package-panel-helpers.ts
> +  if (packageInfoWithoutComments.originalAttributionIds) {
The problem is that due to the current design, all packages in the package panel are `MergedPackageInfo`. So, `originalAttributionIds` are the only way to differentiate between merged signals and ordinary signals.

2023-04-06 09:33 UTC, lennartclaas commented on example-files/opossum_input.json
> -      "packageName": "Should Be Merged"
I have no strong opinion here.

2023-04-06 09:39 UTC, benedikt-richter commented on src/Frontend/Components/PackagePanel/package-panel-helpers.ts
> +  if (packageInfoWithoutComments.originalAttributionIds) {
To differentiate between these two types, we should always use the respective type guard.

2023-04-06 09:39 UTC, benedikt-richter commented on src/shared/shared-types.ts
> +  originalAttributionIds?: Array<string>;
this property should be non-optional

2023-04-06 09:40 UTC, lennartclaas commented on src/Frontend/Components/AggregatedAttributionsPanel/accordion-panel-helpers.ts
> +    attributionToShow.originalAttributionIds = originalAttributionIds;
I don't see why this should improve anything.

2023-04-06 09:46 UTC, lennartclaas commented on src/Frontend/Components/PackagePanel/PackagePanel.tsx
> +        dispatch(addToSelectedResource(packageInfo));
This is basically done by `removeCommentsFromMergedPackageInfo`. I renamed this function to `convertMergedPackageInfoToPackageInfo` as also suggested by Markus.

2023-04-06 10:02 UTC, lennartclaas commented on src/shared/shared-types.ts
> +  originalAttributionIds?: Array<string>;
Needs discussion.

2023-04-06 10:40 UTC, benedikt-richter commented on src/Frontend/Components/PackagePanel/PackagePanel.tsx
> +        dispatch(addToSelectedResource(packageInfo));
`removeCommentsFromMergedPackageInfo` does just remove the comments and does not return a new object. Further, the "`PackageInfo`" at the end also has fields from `mergedPackageInfo`(e.g. the `type`). A proper parsing would be more save here.

2023-04-06 13:03 UTC, lennartclaas commented on src/Frontend/Components/AggregatedAttributionsPanel/accordion-panel-helpers.ts
> +    attributionToShow.originalAttributionIds = originalAttributionIds;
Changed as discusses.

2023-04-06 13:05 UTC, lennartclaas commented on src/shared/shared-types.ts
> +  originalAttributionIds?: Array<string>;
Changed according to discussion.

2023-04-11 08:03 UTC, lennartclaas commented on src/Frontend/Components/PackagePanel/PackagePanel.tsx
> +        dispatch(addToSelectedResource(packageInfo));
Done as discusses.

2023-04-11 08:57 UTC, MarkusObendrauf requested changes

2023-04-11 08:57 UTC, MarkusObendrauf commented on src/Frontend/Components/PackagePanel/PackagePanel.tsx
> +        console.log(isDisplayPackageInfo(packageInfo));
please remove debug statements

2023-04-11 08:57 UTC, MarkusObendrauf commented on src/Frontend/Components/PackagePanel/PackagePanel.tsx
> +        console.log(packageInfoToAdd);
here too

2023-04-11 08:57 UTC, MarkusObendrauf commented on src/Frontend/Components/PackagePanel/PackagePanel.tsx
> +          props.attributions[attributionId];
i find the mixing of `packageInfo` and `attribution` here confusing

2023-04-11 08:57 UTC, MarkusObendrauf commented on src/Frontend/Components/PackagePanel/package-panel-helpers.ts
> +      switch (packageInfoKey) {
do we need this switch?

2023-04-11 08:57 UTC, MarkusObendrauf commented on src/Frontend/Components/PackagePanel/package-panel-helpers.ts
> +  mergedPackageInfo: DisplayPackageInfo
`mergedPackageInfo` -> `displayPackageInfo`

2023-04-11 08:57 UTC, MarkusObendrauf commented on src/Frontend/Components/PackagePanel/__tests__/package-panel-helpers.test.ts
> +    const testMergedPackageInfoA: DisplayPackageInfo = {
`testMergedPackageInfoA` -> `testDisplayPackageInfoA`
`testMergedPackageInfoB` -> `testDisplayPackageInfoB`

2023-04-11 08:57 UTC, MarkusObendrauf commented on src/Frontend/Components/PackagePanel/package-panel-helpers.ts
> +    }
please handle the `else` case explicitly by setting `packageInfo['comment']` to `''`. i believe the current code works only because of the fact that comments are removed when the `mergedPackageInfo` is constructed, which is not obvious and could break later.

2023-04-11 09:14 UTC, lennartclaas commented on src/Frontend/Components/PackagePanel/PackagePanel.tsx
> +          props.attributions[attributionId];
What do you mean exactly?

2023-04-11 09:14 UTC, lennartclaas commented on src/Frontend/Components/PackagePanel/package-panel-helpers.ts
> +      switch (packageInfoKey) {
Yes, due to typing issues and clean parsing. Was discussed with Benedikt.

2023-04-11 11:09 UTC, lennartclaas commented on src/Frontend/Components/PackagePanel/PackagePanel.tsx
> +          props.attributions[attributionId];
The differentiation between `PackageInfo` and `DisplayPackageInfo` will be obsolet after the refactoring.

2023-04-11 12:10 UTC, merged