Group signals in folder content by hash
opossum-tool/OpossumUI pull request #1543
Opened 2023-04-05 12:44 UTC by MarkusObendrauf

### Summary of changes

Group "Signals in Folder Content" by hash

### Context and reason for change

Currently, it is possible that there are many identical signals that only differ by the comment. This should be fixed. In this PR, the "Signals in Folder Content" section of the attribution view is updated to only show one signal per hash.

2023-04-05 14:07 UTC, lennartclaas approved these changes
👍 Looks very nice. Just some nits.

2023-04-05 14:11 UTC, leslielazzarino requested changes

2023-04-05 14:11 UTC, leslielazzarino commented on src/Frontend/Components/AggregatedAttributionsPanel/accordion-panel-helpers.ts
> +export function getMergedPackageInfoFromPackageInfo(
Not used, left-over from a rebase.

2023-04-05 14:21 UTC, MarkusObendrauf commented on src/Frontend/Components/AggregatedAttributionsPanel/__tests__/AggregatedAttributionsPanel.test.tsx
> +      comment: 'ManualPackage',
same as the other tests - but like you said its not important

2023-04-05 14:27 UTC, MarkusObendrauf commented on src/Frontend/Components/AggregatedAttributionsPanel/AggregatedAttributionsPanel.tsx
> +export interface externalAttributionData {
removed it

2023-04-06 06:57 UTC, MarkusObendrauf commented on src/Frontend/Components/AggregatedAttributionsPanel/accordion-panel-helpers.ts
> +export function getMergedPackageInfoFromPackageInfo(
removed it

2023-04-06 06:59 UTC, MarkusObendrauf commented on src/Frontend/Components/WorkersContextProvider/WorkersContextProvider.tsx
> +  const memoizedAttributionsToHashes = useMemo(
removed it

2023-04-06 07:32 UTC, MarkusObendrauf commented on src/Frontend/Components/WorkersContextProvider/WorkersContextProvider.tsx
> +      resourceDetailsTabsWorkers.containedExternalAttributionsAccordionWorker.postMessage(
done

2023-04-06 07:47 UTC, MarkusObendrauf commented on src/Frontend/Components/AggregatedAttributionsPanel/__tests__/AggregatedAttributionsPanel.test.tsx
> +      // eslint-disable-next-line testing-library/prefer-screen-queries, jest-dom/prefer-in-document, testing-library/prefer-presence-queries
it seems like the second one could be removed. very confused by this

2023-04-06 11:23 UTC, leslielazzarino commented on src/Frontend/Components/AggregatedAttributionsPanel/__tests__/AggregatedAttributionsPanel.test.tsx
>    it('does not merge signals without n hash', () => {
Typo

2023-04-06 11:29 UTC, leslielazzarino approved these changes

2023-04-06 12:18 UTC, merged