Show resources for merged signals
opossum-tool/OpossumUI pull request #1551
Opened 2023-04-06 13:20 UTC by MarkusObendrauf

### Summary of changes

The resource path popup shows resources for all attributions of a merged package.

### Context and reason for change

Currently, it is possible that there are many identical signals that only differ by the comment. This should be fixed. In this PR, the resource path popup is updated to display resource paths for all attributions of a merged package, instead of just one.

2023-04-06 15:21 UTC, lennartclaas requested changes

2023-04-06 15:21 UTC, lennartclaas commented on src/Frontend/Components/ResourcePathPopup/ResourcePathPopup.tsx
> +    props.isExternalAttribution
👍

2023-04-06 15:21 UTC, lennartclaas commented on src/Frontend/Components/PackageCard/PackageCard.tsx
> +  const attributionIdsForResourcePathPopup = isMergedPackageInfo(
In `PackageCardProps`, only `PackageInfo` is allowed as a type for `props.packageInfo`. `isMergedPackageInfo` should therefore only yield `false`.

2023-04-06 15:35 UTC, lennartclaas commented on src/Frontend/Components/PackageCard/PackageCard.tsx
> +  const attributionIdsForResourcePathPopup = isMergedPackageInfo(
But is works anyway. I'm confused.

2023-04-11 07:58 UTC, MarkusObendrauf commented on src/Frontend/Components/PackageCard/PackageCard.tsx
> +  const attributionIdsForResourcePathPopup = isMergedPackageInfo(
`MergedPackageInfo` is a subclass of `PackageInfo`, so the props allowed it. changed the type signature of `props.packageInfo` to `PackageInfo | MergedPackageInfo` to make it explicit.

2023-04-11 11:42 UTC, merged