Deprecate originId field in input files
opossum-tool/OpossumUI pull request #1579
Opened 2023-04-14 09:05 UTC by MarkusObendrauf

### Summary of changes

Deprecate the originId filed in input files

### Context and reason for change

In #1561, identical signals are merged in OpossumUI. This means that one signal may have multiple origins. In order to support this, the field `originIds` was introduced, and now `originId` is deprecated.

2023-04-17 06:03 UTC, benedikt-richter requested changes

2023-04-17 06:03 UTC, benedikt-richter commented on src/ElectronBackend/input/OpossumInputFileSchema.json
> +            "description": "Can be set to track a signal from the tooling that generated the input file. Will be copied into the output when the signal is converted into an attribution.",
We could add the information that the new field `originIds` should be used instead of the deprecated one.

2023-04-18 07:44 UTC, MarkusObendrauf commented on src/ElectronBackend/input/OpossumInputFileSchema.json
> +            "description": "Can be set to track a signal from the tooling that generated the input file. Will be copied into the output when the signal is converted into an attribution.",
Added `Deprecated - originIds should be used instead. ` to the front of the description

2023-04-18 07:55 UTC, benedikt-richter approved these changes

2023-04-18 11:39 UTC, merged