Refactor DisplayPackageInfo: `temporaryPackageInfo`
opossum-tool/OpossumUI pull request #1637
Opened 2023-05-02 12:29 UTC by lennartclaas

### Summary of changes

Apply the refactoring regarding `DisplayPackageInfo` to `temporaryPackageInfo`. This change entails changes to many components that get or set `temporaryPackageInfo`.

### Context and reason for change

Improve separation of display and business logic by introducing `DisplayPackageInfo` in all components that display attributions.

2023-05-04 14:07 UTC, benedikt-richter requested changes

2023-05-04 14:07 UTC, benedikt-richter commented on src/Frontend/state/selectors/all-views-resource-selectors.ts
> +  // TODO: Will this retrigger renderings if the state has not changed? (New object is created with convert function)
When will this comment be resolved?

2023-05-04 14:07 UTC, benedikt-richter commented on src/Frontend/util/convert-package-info.ts
> +  attributionIds?: Array<string>
Why are these arguments optional?
ALso, what is the use case of converting `null`?

2023-05-04 14:07 UTC, benedikt-richter commented on src/Frontend/util/get-stripped-package-info.ts
> +export function getStrippedDisplayPackageInfo(
This function is used to calculate a variable `temporaryPackageInfoWithoutConfidence`. This seems not to fit the actual implementation

2023-05-04 14:07 UTC, benedikt-richter commented on src/Frontend/util/get-stripped-package-info.ts
> +export function getStrippedDisplayPackageInfo(
This function is untested

2023-05-05 08:53 UTC, lennartclaas commented on src/Frontend/Components/AttributionColumn/AttributionColumn.tsx
> +        updatePurl(initialDisplayPackageInfo);
Will be done in next PR.

2023-05-05 09:30 UTC, lennartclaas commented on src/Frontend/Components/ReplaceAttributionPopup/ReplaceAttributionPopup.tsx
> +        displayAttributions
I thought it was cleaner (according to our principal 'DisplayPackageInfo as early as possible'. But in terms of performance, it does not make sense, I guess. I reverted the changes.

2023-05-05 12:20 UTC, lennartclaas commented on src/Frontend/state/actions/resource-actions/__tests__/save-actions.test.ts
> +      convertDisplayPackageInfoToPackageInfo(expectedTemporaryPackageInfo)
It's to ignore random uuids as attributioIds, but I changed it to a clearer version.

2023-05-05 12:23 UTC, lennartclaas commented on src/Frontend/state/selectors/all-views-resource-selectors.ts
> +  // TODO: Will this retrigger renderings if the state has not changed? (New object is created with convert function)
Can you test with real data whether this leads to performance drops?

2023-05-05 12:23 UTC, lennartclaas commented on src/Frontend/state/selectors/audit-view-resource-selectors.ts
> +    // TODO: Will this retrigger renderings if the state has not changed? (New object is created with convert function)
See above.

2023-05-05 12:23 UTC, lennartclaas commented on src/Frontend/util/convert-package-info.ts
> +  attributionIds?: Array<string>
For making things easier in other parts of the code. However, I reverted the changes to make things clearer.

2023-05-05 12:23 UTC, lennartclaas commented on src/Frontend/util/convert-package-info.ts
> +  displayPackageInfo?: DisplayPackageInfo | null
See above.

2023-05-08 05:55 UTC, benedikt-richter commented
In attributionColumn the following code still has to be adapted:
```
  const attributionIdsToResolveOrUnresolve = isDisplayPackageInfo(
    temporaryPackageInfo
  )
    ? temporaryPackageInfo.attributionIds
    : []; // TODO: remove when refactoring

```

2023-05-08 05:58 UTC, benedikt-richter commented
The subpanels of the AttributionColumn still expect `PackageInfo`. This should be ``DisplayPackageInfo`.

2023-05-08 10:51 UTC, benedikt-richter approved these changes

2023-05-08 10:51 UTC, merged