Add checkbox for needsReview
opossum-tool/OpossumUI pull request #1638
Opened 2023-05-02 13:46 UTC by antonbauhofer

### Summary of changes

This adds a checkbox next to the buttons on the attribution view to signal that an attribution needs further review.

### Context and reason for change

We are adding a checkbox to OpossumUI to signal if a review is required for an attribution.

### How can the changes be tested

- Run the tests in `AttributionColumn.test.tsx`.
- Open a file in OpossumUI and verify that the new checkbox shows up and works.

2023-05-02 14:22 UTC, lennartclaas requested changes
The implementations look nice. However, the styling in the `EditAttributionPopup` should be considered as well:

![Screenshot 2023-05-02 161859](https://user-images.githubusercontent.com/83081698/235694813-980e39ab-ea26-4551-9ae7-326ad619305c.png)

2023-05-02 16:50 UTC, antonbauhofer commented
> The implementations look nice. However, the styling in the `EditAttributionPopup` should be considered as well:
> 

Nice catch!
I fixed it in `ButtonRow.tsx`. 
![Screenshot 2023-05-02 at 18 47 01](https://user-images.githubusercontent.com/48415604/235732214-a706f449-976c-4ea5-9c4e-49d764864699.png)

2023-05-03 05:48 UTC, lennartclaas requested changes
Only some nits I have overlooked in the first review. Sorry for that. We should discuss whether the position of the checkbox is suitable in the case of attributions in the `Global` tab or the `ContainedManualPackages` panel. I looks a bit lost as no other buttons are displayed.

![Screenshot 2023-05-03 073919](https://user-images.githubusercontent.com/83081698/235840592-9b5fe079-39ef-465b-b7b5-c5f93042020e.png)

2023-05-03 05:48 UTC, lennartclaas commented on src/Frontend/Components/AttributionColumn/ButtonRow.tsx
> +  extraPadding: {
I would choose a more meaningful name. First, only margins are set and not padding. Second, one could name it according to for which component and why it is used, e.g., 'checkboxWithHiddenButtons'. But that's only a suggestion.

2023-05-03 05:48 UTC, lennartclaas commented on src/Frontend/Components/AttributionColumn/ButtonRow.tsx
> +  const largerPaddingForNeedsReviewCheckbox = props.areButtonsHidden
Naming as above.

2023-05-03 08:11 UTC, lennartclaas approved these changes
lgtm

2023-05-03 09:24 UTC, merged