Needs review icon
opossum-tool/OpossumUI pull request #1644
Opened 2023-05-03 09:23 UTC by antonbauhofer

### Summary of changes

Adds a new icon to signal that an attribution needs review.
Note that in the cards in attribution view, there should be a maximum of 4 icons shown at the same time, since pre-selected attributions cannot have the needs-preview attribute.
Also, the color of the follow-up icon was adjusted in the attribution view to make it consistent with the report view.

### Context and reason for change

We are adding a checkbox to OpossumUI to signal if a review is required for an attribution.

### How can the changes be tested

- Run the tests in `Icons.test.tsx` and `ReportTableItem.test.tsx`
- Open a file in OpossumUI and verify that the new icon shows up in the report- and attribution view (twice).

2023-05-03 15:11 UTC, vasily-pozdnyakov requested changes

2023-05-03 15:11 UTC, vasily-pozdnyakov commented on src/e2e-tests/__tests__/e2e-deprecated-file-format.test.ts
> -  test('should open FileSupportPopup when .json file is provided as command line arg', async () => {
why?

2023-05-03 15:11 UTC, vasily-pozdnyakov commented on src/e2e-tests/test-helpers/test-helpers.ts
> -export const EXPECT_TIMEOUT = 30000;
why?

2023-05-03 15:11 UTC, vasily-pozdnyakov commented on src/Frontend/Components/ProjectStatisticsPopup/__tests__/project-statistics-popup-helpers.test.tsx
> +      needsReview: 1,
is it the only test where needsReview>0? Would be nice to have more, e.g. with more items which needReview

2023-05-04 08:25 UTC, antonbauhofer commented on src/e2e-tests/__tests__/e2e-deprecated-file-format.test.ts
> -  test('should open FileSupportPopup when .json file is provided as command line arg', async () => {
This test was redundant with the test below which implicitly also tests that the popup is shown (with `await getButtonWithName(window, 'Keep');`)

2023-05-04 08:25 UTC, antonbauhofer commented on src/e2e-tests/test-helpers/test-helpers.ts
> -export const EXPECT_TIMEOUT = 30000;
The CI repeatedly ran into this timeout. So, we decided to increase it. The value of `30000` was kind of arbitrarily chosen anyway.

2023-05-04 08:25 UTC, antonbauhofer commented on src/Frontend/Components/ProjectStatisticsPopup/__tests__/project-statistics-popup-helpers.test.tsx
> +      needsReview: 1,
I added the property to another one of the test attributions. I would not add a separate test for that, since the logic is trivial and the same as for follow-ups.
Is that ok for you?

2023-05-04 09:02 UTC, vasily-pozdnyakov commented on src/Frontend/Components/ProjectStatisticsPopup/__tests__/project-statistics-popup-helpers.test.tsx
> +      needsReview: 1,
fine, thx

2023-05-04 09:08 UTC, antonbauhofer commented
> well done. The failing CI - not good.

We ran the CI on a separate branch and locally. In both cases it was green. So, we decided to ignore the failing tests and still land this diff (hoping that the CI will be green when we make a PR into the main branch).

2023-05-04 09:09 UTC, merged