DRAFT: Refactor lookup of 'DisplayPackageInfos' in displaying components.
opossum-tool/OpossumUI pull request #1676
Opened 2023-05-15 12:47 UTC by lennartclaas

### Summary of changes

Instead of 'attributionId', which is closely related to attributions in the state, 'packageCardId' is used to look up 'DisplayPackageInfos' via 'PackageCards'. 'DisplayPackageInfo' is saved in 'PanelPackage'. Tests have yet to be added.

### Context and reason for change

Improve separation between business and display logic. With introducing merged signals, 'attributionId' is not suitable anymore to identify both 'PackageCard' (display logic) and 'Attribution' in the redux state (business logic).

2023-05-15 15:26 UTC, benedikt-richter requested changes

2023-05-15 15:26 UTC, benedikt-richter commented on src/Frontend/Components/AttributionColumn/AttributionColumn.tsx
> +      : '';
this seems more complicated than necessary

2023-05-15 15:26 UTC, benedikt-richter commented on src/Frontend/Components/AttributionView/AttributionView.tsx
> +      filteredDisplayPackageInfos[packageCardId].attributionIds[0];
Doesn't `attributionId` = `packageCardId` hold?

2023-05-15 15:26 UTC, benedikt-richter commented on src/Frontend/Components/ManualAttributionList/ManualAttributionList.tsx
> +  const extendedSortedPackageCardIds = props.isAddNewAttributionItemShown
`extendedSortedPackageCardIds` sounds a bit odd

2023-05-15 15:26 UTC, benedikt-richter commented on src/Frontend/Components/ManualPackagePanel/ManualPackagePanel.tsx
> +  });
could be extracted

2023-05-15 15:26 UTC, benedikt-richter commented on src/Frontend/Components/ManualPackagePanel/ManualPackagePanel.tsx
> +        selectedPackageCardId={selectedPackage?.packageCardId ?? null}
what is the meaning of `null`here?

2023-05-15 15:26 UTC, benedikt-richter commented on src/Frontend/Components/PackagePanel/PackagePanel.tsx
> +    // );
remove comment

2023-05-15 15:26 UTC, benedikt-richter commented on src/Frontend/shared-constants.ts
> +export const ATTRIBUTION_LIST_TITLE_FOR_PACKAGE_CARD_ID = 'Attribution List';
Why do these constants have the postfix `FOR_PACKAGE_CARD_ID`?

2023-05-15 15:26 UTC, benedikt-richter commented on src/Frontend/state/actions/resource-actions/navigation-actions.ts
> +    const attributionIdsOfResource: Array<string> =
👍

2023-05-15 15:26 UTC, benedikt-richter commented on src/Frontend/state/reducers/resource-reducer.ts
> +              : EMPTY_DISPLAY_PACKAGE_INFO,
this could be extracted as it is reused in line 275

2023-05-16 06:46 UTC, benedikt-richter commented
There is the following bug:
* give a resource an attribution
* give the same attribution to a child
* error is raised

2023-05-16 11:14 UTC, benedikt-richter commented on src/Frontend/util/create-package-card-id.ts
> +export function createPackageCardId(
Here it would be nice to have default values for `panelTitle` and `sourceName`. In that case we would not have to expose `ATTRIBUTION_LIST_TITLE_FOR_PACKAGE_CARD_ID` and the other constant.

2023-05-17 05:32 UTC, lennartclaas commented on src/Frontend/Components/AggregatedAttributionsPanel/accordion-panel-helpers.ts
> +  const displayAttributionIdsWithCount: Array<DisplayPackageInfoWithCount> = [];
I used `gatheredDisplayPackageInfosWithCount` now because `displayPackageInfosWithCount` is reserved for objects of the interface `DisplayPackageInfosWithCount`.

2023-05-17 05:35 UTC, lennartclaas commented on src/Frontend/Components/AttributionColumn/AttributionColumn.tsx
> +      : '';
Let's discuss.

2023-05-17 05:36 UTC, lennartclaas commented on src/Frontend/Components/AttributionView/AttributionView.tsx
> +      filteredDisplayPackageInfos[packageCardId].attributionIds[0];
Nice catch!

2023-05-17 05:38 UTC, lennartclaas commented on src/Frontend/Components/ManualAttributionList/ManualAttributionList.tsx
> +  const extendedSortedPackageCardIds = props.isAddNewAttributionItemShown
Any suggestions? I could call it `sortedPackageCardIdsToDisplay` although the Ids are technically not displayed themselves.

2023-05-17 06:42 UTC, benedikt-richter commented on src/Frontend/Components/ManualAttributionList/ManualAttributionList.tsx
> +  const extendedSortedPackageCardIds = props.isAddNewAttributionItemShown
Could be `sortedPackageCardIdsWithNewAttributionButton`

2023-05-17 06:45 UTC, lennartclaas commented on src/Frontend/Components/ManualPackagePanel/ManualPackagePanel.tsx
> +  });
I did the same in `AttributionView` and `ResourceDetailsTabs`.

2023-05-17 06:48 UTC, lennartclaas commented on src/Frontend/Components/ManualPackagePanel/ManualPackagePanel.tsx
> +        selectedPackageCardId={selectedPackage?.packageCardId ?? null}
Let's discuss.

2023-05-17 06:50 UTC, lennartclaas commented on src/Frontend/shared-constants.ts
> +export const ATTRIBUTION_LIST_TITLE_FOR_PACKAGE_CARD_ID = 'Attribution List';
Already clarified.

2023-05-17 06:52 UTC, lennartclaas commented on src/Frontend/state/helpers/action-and-reducer-helpers.ts
> +  if (attributionIds) {
Nice catch!

2023-05-17 06:59 UTC, lennartclaas commented on src/Frontend/Components/ManualAttributionList/ManualAttributionList.tsx
> +  const extendedSortedPackageCardIds = props.isAddNewAttributionItemShown
But the name is misleading if the button is not added.

2023-05-17 07:32 UTC, lennartclaas commented on src/Frontend/Components/AttributionColumn/AttributionColumn.tsx
> +      : '';
Extracted in function.

2023-05-17 07:40 UTC, lennartclaas commented on src/Frontend/Components/ManualAttributionList/ManualAttributionList.tsx
> +  const extendedSortedPackageCardIds = props.isAddNewAttributionItemShown
Used `sortedPackageCardIdsPotentiallyWithAddNewAttributionButton` now. ;)

2023-05-17 14:16 UTC, lennartclaas commented on src/Frontend/Components/AggregatedAttributionsPanel/__tests__/accordion-panel-helper.test.ts
> +    const expectedPackageCardIds = [`${testPackagePanelTitle}--0`];
as discussed

2023-05-17 14:41 UTC, benedikt-richter commented on src/Frontend/state/helpers/action-and-reducer-helpers.ts
> +export function getAttributionIdOfFirstPackageCardInManualPackagePanel(
should be tested

2023-05-17 14:42 UTC, benedikt-richter commented on src/Frontend/state/helpers/action-and-reducer-helpers.ts
> +export function getIndexOfAttributionInManualPackagePanel(
should be tested as it is used in the reducer that is at the core of our system

2023-05-17 14:44 UTC, benedikt-richter commented on src/Frontend/state/reducers/resource-reducer.ts
> +                ),
could be extracxted into a constant

2023-05-17 14:46 UTC, benedikt-richter requested changes
Lgtm. Just some minor points

2023-05-17 15:10 UTC, lennartclaas commented on src/Frontend/Components/AggregatedAttributionsPanel/accordion-panel-helpers.ts
> +  gatheredDisplayPackageInfosWithCount.forEach(
Changed it to one loop.

2023-05-22 07:31 UTC, lennartclaas commented on src/Frontend/Components/AttributionView/AttributionView.tsx
> +function getFilteredAndSortedPackageCardIdsAndDisplayPackageInfos(
I would keep it as it as because combining both functions into a new one would introduce unnecessary complexity.

2023-05-23 06:09 UTC, benedikt-richter approved these changes
Played around with the app and everything still seems to work as expected.
Also tested performance. There is no significant difference (maybe the refactored version is even faster).
Thanks for your effort and perseverance performing this huge rafactor!

2023-05-23 07:11 UTC, merged