Add hide button to context menu
opossum-tool/OpossumUI pull request #173
Opened 2021-11-09 14:22 UTC by jonas-tai

### Summary of changes

Adds the implementation for using the hide / unhide function to the context menu for external attributions.

### Context and reason for change

The hide functionality was missing in the context menu for external attributions in the previous version of the context menu. 

### How can the changes be tested

Run the integration tests in package-card-context-menu.test.tsx and / or try it out in the app with example file.

2021-11-09 15:02 UTC, benedikt-richter commented
Works nicely!

We could think of icons for hide and unhide :)
E.g. 
import VisibilityOffIcon from '@mui/icons-material/VisibilityOff';
import VisibilityIcon from '@mui/icons-material/Visibility';

2021-11-10 07:31 UTC, leslielazzarino requested changes
Attributions in folder content created from signals get hidden too: that should not happen.

2021-11-10 08:36 UTC, leslielazzarino approved these changes

2021-11-10 08:38 UTC, jonas-tai commented
> 
> 
> Attributions in folder content created from signals get hidden too: that should not happen.

This seems to be the normal hide logic at the moment, no conjunction with this branch.

2021-11-10 08:39 UTC, merged