Change state for filtering
opossum-tool/OpossumUI pull request #174
Opened 2021-11-09 15:22 UTC by mayayunx

### Summary of changes
- create 3 filters as enum: only 1st party , hide 1st party, only follow-up 
- save active filters in state
- update the follow-up action and selector
- add logic enforces only 1st party or hide 1st party filter can be active at once
- fix follow up filtering logic, to use the new state

### Context and reason for change
- new filters for show only first party and hide first party are required

### How can the changes be tested
run `yarn test:unit`

2021-11-09 15:43 UTC, benedikt-richter commented
The commits should be squashed before merging

2021-11-09 15:45 UTC, benedikt-richter commented on src/Frontend/Components/AttributionView/AttributionView.tsx
> +  const filterForFollowUp = activeFilters.has(FilterEnum.OnlyFollowUp);
The name `FilterEnum` should not contain `Enum`

2021-11-09 15:53 UTC, benedikt-richter commented on src/Frontend/enums/enums.ts
> +export enum FilterEnum {
couzld be `FilterType`

2021-11-09 15:53 UTC, benedikt-richter commented on src/Frontend/state/actions/view-actions/__tests__/view-actions.test.ts
> +    ).toBe(false);
we could check the case of having two filters set at the same time

2021-11-09 15:53 UTC, benedikt-richter commented on src/Frontend/state/reducers/view-reducer.ts
> +    case ACTION_SET_FILTER:
actually it is more a `ACTION_TOGGLE_FILTER`, as the action might lead to a removed filter. In this case the name would be missleading

2021-11-09 15:58 UTC, benedikt-richter commented on src/Frontend/state/helpers/set-filters.ts
> +}
It would be nice to have a configuration like:
{mutuallyExclusiveFilters: [filterA, filterB]} or similar.

In this case adding a new filter would be trivial.

2021-11-09 15:58 UTC, benedikt-richter requested changes
see comments

2021-11-10 10:23 UTC, benedikt-richter commented on src/Frontend/state/actions/view-actions/types.ts
> +export interface SetFilter {
The Interface should also reflect that it is not a simple set (also the name of the action and all other occurences).

I just realized that it's also not a simple toggle...

Maybe it could be: `ACTION_ADD_ACTIVE_FILTER`, `AddActiveFilter`, ...

2021-11-10 12:00 UTC, benedikt-richter requested changes

2021-11-10 12:00 UTC, benedikt-richter commented on src/Frontend/state/helpers/set-filters.ts
> +]);
This implementation seems to be more complex than necessary. Could be

```

import { FilterType } from '../../enums/enums';

const mutuallyExclusiveFilters = [
  [FilterType.OnlyFirstParty, FilterType.HideFirstParty],
];

export function getUpdatedFilters(
  activeFilters: Set<FilterType>,
  newFilter: FilterType
): Set<FilterType> {
  const currentFilters = new Set(activeFilters);

  if (currentFilters.has(newFilter)) {
    currentFilters.delete(newFilter);
  } else {
    const filtersToRemove = getFiltersToRemove(currentFilters, newFilter);
    if (filtersToRemove.size !== 0) {
      filtersToRemove.forEach((element) => currentFilters.delete(element));
    }
    currentFilters.add(newFilter);
  }

  return currentFilters;
}

export function getFiltersToRemove(
  activeFilters: Set<FilterType>,
  newFilter: FilterType
): Set<FilterType> {
  return new Set(
    mutuallyExclusiveFilters
      .filter((filterPair) => filterPair.includes(newFilter))
      .map((filterPair) =>
        filterPair.indexOf(newFilter) ? filterPair[0] : filterPair[1]
      )
  );
}


```

2021-11-10 13:39 UTC, benedikt-richter approved these changes
nice 👍 

just squash commits before merging

2021-11-10 14:19 UTC, antonbauhofer approved these changes
Just one comment regarding renaming. The rest looks good.

2021-11-10 14:19 UTC, antonbauhofer commented on src/Frontend/state/actions/view-actions/types.ts
> +export const ACTION_ADD_ACTIVE_FILTER = 'ACTION_ADD_ACTIVE_FILTER';
I think the action and the types should be called "...SET..." instead of "...ADD..." since they not only add, but also remove the respective filter.

2021-11-10 14:29 UTC, benedikt-richter commented on src/Frontend/state/actions/view-actions/types.ts
> +export const ACTION_ADD_ACTIVE_FILTER = 'ACTION_ADD_ACTIVE_FILTER';
I understand your point. `Add` is not perfect. However, if I'd use an action called `set...`, I'd expect the value to be the value I've set. This is, however, not the case, as it could also remove other values...

2021-11-10 14:41 UTC, antonbauhofer commented on src/Frontend/state/actions/view-actions/types.ts
> +export const ACTION_ADD_ACTIVE_FILTER = 'ACTION_ADD_ACTIVE_FILTER';
Maybe `add_or_delete` would fit

2021-11-10 15:01 UTC, benedikt-richter commented on src/Frontend/state/actions/view-actions/types.ts
> +export const ACTION_ADD_ACTIVE_FILTER = 'ACTION_ADD_ACTIVE_FILTER';
Maybe more generic `update`

2021-11-10 16:50 UTC, merged