Show project statistics popup after new file was loaded. Fix: 1711
opossum-tool/OpossumUI pull request #1774
Opened 2023-06-30 15:25 UTC by FlorianSchepers

### Summary of changes

In `src\Frontend\Components\BackendCommunication\BackendCommunication.tsx` in `fileLoadedListener()`  the `ProjectStatisticsPopup` is now dispatched right after the `parsedFileContent`. Thus, the `ProjectStatisticsPopup` will open once a new file is loaded.
Some tests had to be addapted.

### Context and reason for change

As an OpossumUI user, I want to get a quick overview of the project when opening a new file.
In order to achieve this the project statistics popup should automatically open when a new file is opened.

Fix: #1711 

### How can the changes be tested
Start OpossumUI and open a non empty opossum file. 

Note: Please review the [guidelines for contributing](https://github.com/opossum-tool/OpossumUI/blob/main/CONTRIBUTING.md) to this repository.

2023-07-03 06:18 UTC, benedikt-richter commented on setupTests.ts
> +      default: {
instead of handling this in default, it would be better to have an explicit case.

2023-07-03 06:47 UTC, benedikt-richter requested changes

2023-07-03 06:47 UTC, benedikt-richter commented on setupTests.ts
> +const SUBSTRINGS_TO_SUPPRESS_IN_CONSOLE_WARN = [
we could add a comment here explaining, why we do suppress these warnings

2023-07-03 06:47 UTC, benedikt-richter commented on setupTests.ts
> +function mockResizeObserver(): void {
We should remove the old definition of that function that we had before.

2023-07-03 06:47 UTC, benedikt-richter commented on src/Frontend/Components/EditAttributionPopup/__tests__/EditAttributionPopup.test.tsx
> +    store.dispatch(
why was this test changed?

2023-08-10 13:04 UTC, FlorianSchepers commented on src/Frontend/Components/EditAttributionPopup/__tests__/EditAttributionPopup.test.tsx
> +    store.dispatch(
Must have been a mistake. I removed it.

2023-09-18 09:47 UTC, benedikt-richter commented on setupTests.ts
> +const SUBSTRINGS_TO_SUPPRESS_IN_CONSOLE_WARN = [
This comment could read something like "We supress recharts warning that is due to our mocking in tests."

2023-09-18 09:49 UTC, benedikt-richter approved these changes
lgtm

Just consider adding the comment

2023-09-18 11:36 UTC, benedikt-richter approved these changes
Times for CI vary a lot. This probably also depends on the actual machine utilized. Should be ok to merge and to improve if necessary.

2023-09-18 11:36 UTC, merged