Adapt documentation now that releases are available
opossum-tool/OpossumUI pull request #18
Opened 2021-09-23 12:03 UTC by sebathomas

README and USER GUIDE just mention the pre-built releases, only
CONTRIBUTING explains how to build the app yourself.

Signed-off-by: Sebastian Thomas <sebastian.thomas@tngtech.com>

2021-09-23 12:04 UTC, sebathomas commented
Sorry for the noise in the commit, VS Code always applies an autoformat to the markdown.

2021-09-23 12:15 UTC, benedikt-richter commented on USER_GUIDE.md
> +Run _opossum-ui_ in _opossum-ui-darwin-x64/_.
will conflict with https://github.com/opossum-tool/OpossumUI/pull/17/files

2021-09-23 12:16 UTC, benedikt-richter approved these changes

2021-09-23 12:58 UTC, antonbauhofer requested changes

2021-09-23 12:58 UTC, antonbauhofer commented on CONTRIBUTING.md
> +To install dependencies and set up the working environment, run:
Navigating into the OpossumUI directory could also be named here

2021-09-23 12:58 UTC, antonbauhofer commented on README.md
> +"[INPUT NAME]\_attributions.json" is created in the same directory as the input file.
Why did you add this?

2021-09-23 12:58 UTC, antonbauhofer commented on README.md
> -- [wine](https://www.winehq.org/) (only to build the Windows version on a Unix-based OS).
Don't we want to keep this? It could be moved before the building sections.

2021-09-23 14:19 UTC, sebathomas commented on README.md
> +"[INPUT NAME]\_attributions.json" is created in the same directory as the input file.
It was added by the autoformatter. I think it's escaped because `_` normally starts an italic section.

2021-09-23 14:22 UTC, sebathomas commented on README.md
> -- [wine](https://www.winehq.org/) (only to build the Windows version on a Unix-based OS).
It's already in the contributor documentation.

2021-09-23 14:35 UTC, nicarl commented on CONTRIBUTING.md
> +To build a Windows installer run `yarn win-ship-win`. Building of non-Windows version on Windows is currently not
`win-ship-win` does not exist anymore. It actually is the same command as under windows and macOS

2021-09-23 14:35 UTC, nicarl commented on CONTRIBUTING.md
> +_WARNING: The repo has to be cloned with `lf` unix-style line ending._
`.gitattributes` takes care of this now, I think we can rewrite that `lf` line endings should be used or we drop the sentence completely.

2021-09-23 14:42 UTC, sebathomas commented
I'll remove the "Building on Windows" section then.

2021-09-23 15:24 UTC, nicarl approved these changes

2021-09-27 07:01 UTC, antonbauhofer approved these changes

2021-09-27 07:10 UTC, merged