Replace jszip with fflate async
opossum-tool/OpossumUI pull request #1872
Opened 2023-08-11 13:02 UTC by leslielazzarino

The result is better speed and possibly better reliability.

### Summary of changes

Replace jszip with fflate async in the functions writing the .opossum files.

### Context and reason for change

Users have complained that sporadically .opossum files get corrupted after saving.

### How can the changes be tested

Speed: Compare with the Chrome performance profiler the speed with tha latest release and this brunch (after building it). Reliability: unless we notice something before, we can gather feedback only after releasing it, as the previous error could not be reproduced by me in a short ammount of time.

2023-08-18 06:25 UTC, benedikt-richter requested changes
When opening a corrupt zip file, the loading spinner is shown forever with no user facing message displayed to inform what is going on.

2023-08-21 09:33 UTC, leslielazzarino commented on src/ElectronBackend/output/writeJsonToOpossumFile.ts
> +// just used in tests
Actually, it isn't used in production any longer.

2023-08-21 09:43 UTC, leslielazzarino commented on src/ElectronBackend/input/parseFile.ts
> +function convertUint8ArrayToString(fileData: Uint8Array): string {
Test that this function works with unicode.

2023-08-21 09:44 UTC, leslielazzarino commented on src/ElectronBackend/input/parseFile.ts
> +function convertUint8ArrayToString(fileData: Uint8Array): string {
write unit test for unicode chars

2023-08-21 09:57 UTC, leslielazzarino commented on src/ElectronBackend/output/writeJsonToOpossumFile.ts
> +// just used in tests
I will move it to test helpers.

2023-08-21 14:13 UTC, benedikt-richter requested changes
The app is stuck when attempting to open broken zip files. There should be an error instead displayed to the user. Currently, there is a never ending spinner.

2023-08-22 11:52 UTC, leslielazzarino commented
> The app is stuck when attempting to open broken zip files. There should be an error instead displayed to the user. Currently, there is a never ending spinner.

It isn't when further testing.

2023-08-22 11:54 UTC, leslielazzarino commented on src/ElectronBackend/input/__tests__/parseFile.test.ts
> +instance requires property \"metadata\"`,
Improved.

2023-08-22 13:28 UTC, benedikt-richter commented on src/ElectronBackend/input/parseFile.ts
> +  if (!zip['input.json']) {
Here, the shared constants should be used

2023-08-22 13:28 UTC, benedikt-richter commented on src/ElectronBackend/input/parseFile.ts
> +    if (zip['output.json']) {
Here, the shared constants should be used

2023-08-22 13:39 UTC, benedikt-richter commented
> > The app is stuck when attempting to open broken zip files. There should be an error instead displayed to the user. Currently, there is a never ending spinner.
> 
> It isn't when further testing.

Could reproduce. Must have had an older version. It is now working. 

Not sure only showing "OK" button with no other choice is perfect, as clicking the button leads the user to infinite loading. However, better as before and can be improved later.

2023-08-22 14:06 UTC, benedikt-richter requested changes
While working with the app, I get the zip warnings repeatedly.

In particular, when adding signals to resources in quick succession, I get the warning popup.

2023-08-23 11:04 UTC, benedikt-richter reviewed
It seems the library `jszip` is still used in some places

2023-08-23 11:17 UTC, benedikt-richter commented on src/ElectronBackend/types/types.ts
> +  inputFileUint8Array?: Uint8Array;
I would not name the variable after its type. We typically do not do that and the type is there if anyone wonders about its type.

2023-08-23 11:21 UTC, benedikt-richter reviewed
Retested it. The error popup does no longer show up.

2023-08-23 13:06 UTC, leslielazzarino commented
> jszip

True, in some scripts and in the backwards-compatibility code. As we are not entirely sure which library we will be using in the future (see https://github.com/opossum-tool/OpossumUI/issues/1893), and it takes quite some work to remove it, I would postpone it.

2023-08-23 13:37 UTC, benedikt-richter commented
> [> jszip](https://github.com/opossum-tool/OpossumUI/pull/1872#pullrequestreview-1591340297)
> 
> True, in some scripts and in the backwards-compatibility code. As we are not entirely sure which library we will be using in the future (see #1893), and it takes quite some work to remove it, I would postpone it.

In this case, we should create an issue for it.

2023-08-23 13:38 UTC, benedikt-richter approved these changes

2023-08-23 13:46 UTC, merged