improve table styling
opossum-tool/OpossumUI pull request #189
Opened 2021-11-12 12:06 UTC by benedikt-richter

### Summary of changes

Do not break on white spaces in table cells.

### Context and reason for change

Do not break on white spaces in table cells.

2021-11-15 08:42 UTC, antonbauhofer requested changes
Why do we want this?
I personally don't like the horizontal scrolling in the table cells and would prefer to leave it as is.

2021-11-15 08:59 UTC, nicarl reviewed
Let's discuss together, I am not sure if it looks better

2021-11-29 16:02 UTC, antonbauhofer approved these changes
Looks good. I looked at it in the app and it works.

2021-11-30 08:29 UTC, nicarl approved these changes

2021-11-30 08:29 UTC, merged