Add license selector to popup
opossum-tool/OpossumUI pull request #1961
Opened 2023-09-12 14:39 UTC by meretp

### Summary of changes

This commit adds an auto-completion input field with a dropdown to the locator popup. The dropdown contains all licenses found in any external attribution and does not aggregate licenses. If a license is selected and the apply button is pressed the corresponding state is set. If the clear button is pressed the state will be reset. Fixes #1941.
### Context and reason for change
We want to imlement a new feature to be able to locate signals based on criticality and certain licenses.
### How can the changes be tested
Check out the commit, open an .opossum file and open the popup. Observe the license field and the dropdown when clicking into the field, the dropdown should contain all license names of all external attributions (see the screenshot below).
If you start to type anything the dropdown will filter for those licenses matching your text. Click apply to set the state for this selected license. If you close the popup and reopen it your selected license will be shown in the corresponding field.
If you click the clean button the field will be cleared and the state is reset.

![Screenshot from 2023-09-12 16-09-44](https://github.com/opossum-tool/OpossumUI/assets/50019307/e6691f9f-932b-4408-9f84-53c3e53f9ed0)

2023-09-13 06:46 UTC, benedikt-richter requested changes

2023-09-13 06:46 UTC, benedikt-richter commented on src/Frontend/Components/LocatorPopup/LocatorPopup.tsx
> +export function getLicenseNamesFromExternalAttributions(
If it is exported only for testing, please, add a respetice comment.

2023-09-13 06:46 UTC, benedikt-richter commented on src/Frontend/Components/LocatorPopup/LocatorPopup.tsx
> +  const licenseNamesInSignals =
Is the performance sufficient to do it on every render? Did you try with a realistic example?

2023-09-13 06:46 UTC, benedikt-richter commented on src/Frontend/Components/LocatorPopup/LocatorPopup.tsx
> +      sx={{ padding: 2 }}
Please, avoid inline styling

2023-09-13 06:46 UTC, benedikt-richter commented on src/Frontend/Components/LocatorPopup/LocatorPopup.tsx
> +      options={Array.from(licenseNamesInSignals.values())}
Why do we transform the return value of `getLicenseNamesFromExternalAttributions` instead of returning a different value. I.e. moving the logic into `getLicenseNamesFromExternalAttributions`

2023-09-13 06:46 UTC, benedikt-richter commented on src/Frontend/Components/LocatorPopup/LocatorPopup.tsx
> +      }}
could be 
```
  formatOptionForDisplay={(option: string): string => option}
```

2023-09-13 06:46 UTC, benedikt-richter commented on src/Frontend/state/selectors/locate-popup-selectors.ts
> +export function getFirstLocatePopupSelectedLicense(state: State): string {
I'd suggest to still use `getLocatePopupSelectedLicenses` and to handle the return (i.e. taking first value) in the component.
The danger of the current approach is that e.g. the case size = 0 is handled separately such that if replacing `getFirstLocatePopupSelectedLicense` in the component in the future by `getLocatePopupSelectedLicenses` one might forget to also include such handling in`getLocatePopupSelectedLicenses`.

2023-09-13 06:46 UTC, benedikt-richter commented on src/Frontend/Components/LocatorPopup/LocatorPopup.tsx
> +  const licenseNamesInSignals =
btw we should never use `signals` in variable names. We always refer to these as `externalAttributions`. The variable might just be called `licenseNameOptions`

2023-09-13 06:46 UTC, benedikt-richter commented on src/Frontend/Components/LocatorPopup/LocatorPopup.tsx
> +export function getLicenseNamesFromExternalAttributions(
The function might be called `getLicenseNames`. The fact that it uses "ExternalAttributions" is not required in the name. From the sginature it should be clear that attributions are used. (btw it would also work for manual attributions)

2023-09-13 06:46 UTC, benedikt-richter commented on src/Frontend/Components/LocatorPopup/__tests__/LocatorPopup.test.tsx
> +  });
typically, we have empty lines between tests

2023-09-13 06:46 UTC, benedikt-richter commented on src/Frontend/Components/LocatorPopup/__tests__/LocatorPopup.test.tsx
> +  it('shows license if selected beforehand', () => {
typically, we have empty lines between tests

2023-09-13 06:46 UTC, benedikt-richter commented on src/Frontend/Components/LocatorPopup/__tests__/LocatorPopup.test.tsx
> +    const testExternalAttribution_2: PackageInfo = {
If possible avoid `_2` or similar. For readability, it would be nice to have e.g. `testExternalApacheAttribution` and `testExternalMITAttribution` or similar

2023-09-13 07:27 UTC, meretp commented on src/Frontend/Components/LocatorPopup/LocatorPopup.tsx
> +  const licenseNamesInSignals =
I tried with the provided example file from ort and didn't observe any performance issues.

2023-09-13 13:08 UTC, benedikt-richter approved these changes
Looks good 👍 

just two minor comments.

2023-09-13 13:08 UTC, benedikt-richter commented on src/Frontend/Components/LocatorPopup/LocatorPopup.tsx
> +  const classes = { autocomplete: { padding: 2 } };
typically, we do define these `classes` right after the imports.

2023-09-14 06:08 UTC, meretp commented
After the rebase the popup now looks like this:  
![Screenshot from 2023-09-14 08-03-56](https://github.com/opossum-tool/OpossumUI/assets/50019307/42f04d36-b1dc-4247-b1ea-54db90e855c6)

2023-09-14 07:32 UTC, merged