Introduce icon indicating that there are filters selected
opossum-tool/OpossumUI pull request #1969
Opened 2023-09-13 15:41 UTC by MarkusObendrauf

### Summary of changes

Display a locator icon on the virtualized tree whenever locator popup filters are active. Clicking on it opens the locator popup.
![image](https://github.com/opossum-tool/OpossumUI/assets/107913663/4d6fa015-11ee-4f57-9a3d-2539818d1e58)

### Context and reason for change

This allows a user to see that they have filters active, and gives another way to open the popup.

### How can the changes be tested

Open the popup with Ctrl+L, then select some filters.

2023-09-14 11:01 UTC, benedikt-richter requested changes

2023-09-14 11:01 UTC, benedikt-richter commented on src/Frontend/extracted/VirtualisedTree/VirtualizedTree.tsx
>  export function VirtualizedTree(
This component currently has only dependencies to external libraries and code contained in the `/extracted` folder. The reason is that it is planned to extract it into a library.
Also it only contains display logic and no application logic. The `onClick` function would introduce application logic.
Therefore, I'd suggest to move the new code into the ResourceBrowser that is a wrapper containing the application logic.

2023-09-14 13:49 UTC, MarkusObendrauf commented on src/e2e-tests/vite-e2e-config.ts
> +  },
done

2023-09-14 14:05 UTC, MarkusObendrauf commented on src/Frontend/Components/ResourceBrowser/ResourceBrowser.tsx
> +    locatePopupSelectedLicenses.size > 0;
nice idea 👍

2023-09-14 14:12 UTC, MarkusObendrauf commented on src/Frontend/extracted/VirtualisedTree/VirtualizedTree.tsx
>  export function VirtualizedTree(
between this and the next ticket, i feel that the interface of this component is basically specific to our application logic. but ill change it

2023-09-14 14:27 UTC, MarkusObendrauf commented on src/Frontend/extracted/VirtualisedTree/VirtualizedTree.tsx
>  export function VirtualizedTree(
done

2023-09-15 05:15 UTC, benedikt-richter approved these changes
👍

2023-09-18 07:45 UTC, merged