Add search icons to `CriticalLicensesTable` in `ProjectStatisticsPopup`
opossum-tool/OpossumUI pull request #1997
Opened 2023-09-18 11:35 UTC by lennartclaas

### Summary of changes
This commit adds icons for searching licenses to the `CriticalLicensesTable` in `ProjectStatisticsPopup`. The logic is implemented in an upcoming PR.

### Context and reason for change
We want the user to be able to search for resources with specific licenses via the `ProjectStatisticsPopup`. The new search icons allow for searching licenses in the `ResourceBrowser` according to the functionality of the `LocatorPopup`.

### How can the changes be tested
**Automatic testing:**
Run `ProjectStatisticsPopup.test.tsx`.
**Manual testing:**
Load test file, open `ProjectStatisticsPopup`, and hover over the icons in the third column of the `CriticalLicensesTable`.

Fix: #1984

2023-09-18 12:00 UTC, benedikt-richter commented on src/Frontend/Components/CriticalLicensesTable/CriticalLicensesTable.tsx
> +    ? `search for "${licenseName}" in resource browser`
It's not a "search" but a "locate" in our terms

2023-09-18 12:05 UTC, benedikt-richter commented
Maybe it would be more consistent to use the "locate" icon instead of the search icon

2023-09-18 13:41 UTC, vasily-pozdnyakov requested changes
Honestly, I do not like the appearance (not sure that new column is required, also Total looks not good in this case)
![image](https://github.com/opossum-tool/OpossumUI/assets/85183359/fb6d0d0f-415c-44a3-ad3f-b1fbe9a63d9e)

2023-09-18 13:41 UTC, vasily-pozdnyakov commented on src/Frontend/Components/CriticalLicensesTable/CriticalLicensesTable.tsx
> +              [SEARCH_COLUMN_NAME_IN_TABLE]: getSearchLicenseIconButton(
I do not think that it should be a new column, maybe just place it next to the license names.

2023-09-18 13:41 UTC, vasily-pozdnyakov commented on src/Frontend/Components/CriticalLicensesTable/CriticalLicensesTable.tsx
> +  const buttonIsEnabled = Boolean(totalNumberOfAttributions);
why do we need this?

2023-09-18 13:41 UTC, vasily-pozdnyakov commented on src/Frontend/Components/CriticalLicensesTable/CriticalLicensesTable.tsx
> +    ? `search for "${licenseName}" in resource browser`
and I am not sure that every user knows what resource browser is. Propose something like: "locate resources with 'some license' "

2023-09-18 13:47 UTC, lennartclaas commented on src/Frontend/Components/Icons/Icons.tsx
> +interface SearchLicenseIconProps extends IconProps {
I renamed everything according to `LocatorPopup`. In particular, it is searching for `attributions` (see button label). I guess to keep everything as generic as possible (one could think about searching for attributions via licenses and other properties).

2023-09-18 13:53 UTC, lennartclaas commented on src/Frontend/Components/CriticalLicensesTable/CriticalLicensesTable.tsx
> +  const buttonIsEnabled = Boolean(totalNumberOfAttributions);
Just for security. I wasn't sure whether situations are possible in which a license points to zero attributions (maybe some edge case). But if that's not possible I can remove it and expect the buttons to be always enabled.

2023-09-18 13:56 UTC, lennartclaas commented on src/Frontend/Components/CriticalLicensesTable/CriticalLicensesTable.tsx
> +              [SEARCH_COLUMN_NAME_IN_TABLE]: getSearchLicenseIconButton(
I found that having the button after the license name looks quite oddly when the lenghts of licenses names vary a lot. Before the names looks kind of confusing. However, I have no strong opinion. I will place the icons after the license name.

2023-09-18 13:57 UTC, vasily-pozdnyakov commented
![image](https://github.com/opossum-tool/OpossumUI/assets/85183359/434d1349-34cd-4e9c-85e4-e0f80c337592)
or
![image](https://github.com/opossum-tool/OpossumUI/assets/85183359/e22d35b9-88fc-4024-b707-628ef4d7f1f7)

2023-09-18 16:19 UTC, lennartclaas commented
I decided to place the icons after the license name because I want to preserve text alignment on the left side of the first column.

![Screenshot 2023-09-18 181741](https://github.com/opossum-tool/OpossumUI/assets/83081698/4aa91fef-e93b-47fe-9f6f-a656b8294bc3)

2023-09-19 10:37 UTC, benedikt-richter commented on src/Frontend/Components/ProjectLicensesTable/ProjectLicensesTable.tsx
> +    marginRight: '8px',
I'd attach the margin to the button instead. The butten itself should take care of it.

2023-09-19 10:44 UTC, benedikt-richter approved these changes
just minor comment

2023-09-20 07:29 UTC, vasily-pozdnyakov approved these changes
Just a minor thing about naming:
do we locate attributions or resources?

2023-09-20 07:29 UTC, vasily-pozdnyakov commented on src/Frontend/Components/CriticalLicensesTable/CriticalLicensesTable.tsx
> +      tooltipTitle={`locate attributions with "${licenseName}"`}
why attributions? should it be resources?

2023-09-20 09:32 UTC, benedikt-richter commented on src/Frontend/Components/CriticalLicensesTable/CriticalLicensesTable.tsx
> +      tooltipTitle={`locate attributions with "${licenseName}"`}
I, personally, would argue that it is signals that we are locating.

2023-09-20 09:33 UTC, lennartclaas commented on src/Frontend/Components/CriticalLicensesTable/CriticalLicensesTable.tsx
> +      tooltipTitle={`locate attributions with "${licenseName}"`}
To my understanding, we locate attributions (license is a property of an attribution). As attributions are attached to resources, we locate resources at the same time. It's correct that the visual hints (arrows) point to resources, but I see that as some kind of incompleteness of the location approach we employ. Ideally, we would mark the located attributions, not only the resources. But that would be overkill as the user can easily identify the attribution of interest given the correct resource. Regarding the tooltip, a correct title would be something like 'locate resources that have attributions with <licenseName> attached'. But I don't like that.

2023-09-20 09:58 UTC, merged