Extend packageinfo and schema for preferred attributions
opossum-tool/OpossumUI pull request #1999
Opened 2023-09-18 14:55 UTC by davidmundelius

### Summary of changes

We add two new fields "preferred" and "prefferedOverOriginIds" to the PackageInfo and the manual attributions in the schema for the output file.

### Context and reason for change

We want to support preferred attributions marked as such by the user. For this, the two new fields are necessary.

### How can the changes be tested

Run the updated unit tests.

Fixes #1987

2023-09-18 15:04 UTC, benedikt-richter commented
Seems the DCO check fails. You have to sign your commits: https://github.com/opossum-tool/OpossumUI/pull/1999/checks?check_run_id=16892129931

2023-09-18 15:06 UTC, benedikt-richter commented on src/ElectronBackend/output/writeCsvToFile.ts
> +    preferredOverOriginIds: 'preferred-over-origin-ids',
I think, we do not have to expose this - very technical - data in this csv export.

2023-09-18 15:19 UTC, benedikt-richter requested changes
The input schema should also be adapted accordingly. Currently, the app fails, when adding the new fields to the inpit (see screenshot)


![Screenshot 2023-09-18 at 17 17 16](https://github.com/opossum-tool/OpossumUI/assets/46576389/e02e4f3b-cecb-4976-aaa6-597115ff651a)

2023-09-19 07:29 UTC, davidmundelius commented
Fixed the DCO and input file schema. The csv part is fine as we choose columns explicitly when creating them.

2023-09-19 07:31 UTC, benedikt-richter commented on src/ElectronBackend/output/writeCsvToFile.ts
> +    preferredOverOriginIds: 'preferred-over-origin-ids',
Noted that we have an additional config that specifies the columns going into csvs. Therefore it is fine to keep

2023-09-19 07:36 UTC, benedikt-richter approved these changes
lgtm

2023-09-19 10:34 UTC, merged