Calculate located resources
opossum-tool/OpossumUI pull request #2005
Opened 2023-09-18 16:23 UTC by antonbauhofer

### Summary of changes

Calculate located resources and resources with located children
- Introduce conditions to check the entries in the locate popup
- Adjust the state to only store paths for resources with located children
- Consider short- and full names of frequent licenses
- Fix and add tests
- code style improvements

### Context and reason for change

We are introducing a feature to "locate" resources that have or contain attributions with criteria that can be set in a new popup.

### How can the changes be tested

Run the tests

Note: Please review the [guidelines for contributing](https://github.com/opossum-tool/OpossumUI/blob/main/CONTRIBUTING.md) to this repository.

2023-09-18 17:39 UTC, MarkusObendrauf commented on src/Frontend/state/helpers/action-and-reducer-helpers.ts
> +import { State } from '../../types/types';
I really dont think we should be importing this stuff here.

2023-09-18 17:39 UTC, MarkusObendrauf commented on src/Frontend/state/helpers/action-and-reducer-helpers.ts
> +export function locateResourcesByCriticalityAndLicense(
Not sure about this structure. Here's how I understand these helpers:

In `resource-reducer.ts` we have a bunch of 'setters' and 'updaters'. These are all mostly a couple of lines - they take an input and write it to the state. If some processing is needed to get the data into the right form, that is done in a helper function here, so that the `resource-reducer.ts` function remains concise.

With that in mind, I think the structure should be the following:
* In `resource-reducers.ts`, replace the function `setResourcesWithLocatedAttributions` with a new function `updateResourcesWithLocatedAttributions`.
* The new function takes as input criticality and licenseNames
* Inside action-and-reducer-helpers, we have a function with signature `(criticality, licensenames, state) -> (resourcesWithLocatedChildren, locatedResources)`. It does pretty much what this function does but doesnt update state. (not 100% sure about passing state here, but it seems reasonable an is done elsewhere.)
* Then `updateResourcesWithLocatedAttributions` just calls the helper function and updates the state with the return value.

2023-09-18 17:39 UTC, MarkusObendrauf commented on src/Frontend/state/helpers/action-and-reducer-helpers.ts
> +export function locateResourcesByCriticalityAndLicense(
more generally, imo, when your code does `read -> calculate -> write` then its nice (and very unit-testable) to have the calculations independent of the reading & writing.

2023-09-18 17:39 UTC, MarkusObendrauf commented on src/Frontend/state/helpers/action-and-reducer-helpers.ts
> +          !licenseIsDifferent(licenseNames, attribution)) ||
i dont like double negatives, and i  dont understand what is happening here.

2023-09-18 17:51 UTC, MarkusObendrauf commented on src/Frontend/state/helpers/action-and-reducer-helpers.ts
> +    criticality != SelectedCriticality.Any &&
might be clearer if written as
`criticality != initialResourceState.locatePopup.selectedCriticality`

2023-09-18 17:57 UTC, MarkusObendrauf requested changes
.

2023-09-18 19:06 UTC, antonbauhofer commented on src/Frontend/state/helpers/action-and-reducer-helpers.ts
> +          !licenseIsDifferent(licenseNames, attribution)) ||
I was playing with the same ideas, but actually, the logic you are suggesting is not correct, since it would pass if neither the license, nor the criticality is set.

The point is that there are three possible states for each variable: Matching, not matching and not set. This will also be true when we introduce additional criteria. We want to evaluate as true, if any one of the criteria is matching and none of the other is not matching. With that in mind, I still think the way it is currently written is good.
But I can add a comment to clarify things.

2023-09-18 19:07 UTC, antonbauhofer commented on src/Frontend/state/helpers/action-and-reducer-helpers.ts
> +import { State } from '../../types/types';
Yes, I agree with you. Actually, I had kind of a similar comment on the original diff. I will change the structure to avoid this.

2023-09-18 19:08 UTC, antonbauhofer commented on src/Frontend/state/helpers/action-and-reducer-helpers.ts
> +export function locateResourcesByCriticalityAndLicense(
Yes, I am with you here. I had the same thought, but just didn't fix it yet. I will change the structure as you suggested.

2023-09-18 19:11 UTC, antonbauhofer commented on src/Frontend/state/helpers/action-and-reducer-helpers.ts
> +    criticality != SelectedCriticality.Any &&
Not sure if I agree. We could also have `SelectedCriticality.Any` as a constant with a meaningful name like `unspecifiedCriticality` or similar.

2023-09-20 07:47 UTC, MarkusObendrauf requested changes

2023-09-20 07:47 UTC, MarkusObendrauf commented on src/Frontend/Components/LocatorPopup/__tests__/LocatorPopup.test.tsx
> +      resourcesWithLocatedChildren: new Set(['pathToMITHigh/']),
in the real world, all paths begin with a `/`, and we expect the path `'/'` to be in `resourceWithLocatedChildren`. could you add this to the test?

2023-09-20 07:47 UTC, MarkusObendrauf commented on src/Frontend/Components/LocatorPopup/__tests__/LocatorPopup.test.tsx
> +    pathToApacheHigh: ['ApacheHighAttribution'],
can we add quotation marks around all of these?

2023-09-20 08:34 UTC, MarkusObendrauf approved these changes
lgtm

2023-09-20 08:53 UTC, merged