Add logic to license locator icons in `ProjectStatisticsPopup`
opossum-tool/OpossumUI pull request #2006
Opened 2023-09-19 08:57 UTC by lennartclaas

### Summary of changes

Clicking on an icon initiates the location process. All attributions that contain the underlying license are highlighted in the resource browser. The view changes to Audit View and the resource browser navigates to a resource with a located attribution.

### Context and reason for change

The new search icons allow for searching licenses in the `ResourceBrowser` according to the functionality of the `LocatorPopup`. 

### How can the changes be tested

Manually by using a test file.

### Comment
Meanwhile, this PR has accumulated some refactorings.

Fix: #1985

2023-09-20 14:31 UTC, leslielazzarino requested changes

2023-09-20 14:31 UTC, leslielazzarino commented on src/Frontend/Components/CriticalLicensesTable/CriticalLicensesTable.tsx
>    const onLocateAttributionButtonClick = function (): void {
This is not how you want to do this. The best pattern for selectors and actions in the components is as follows:
- get from the state only what is relevant for visualisation: the component will then re-render only if something it is displaying (or a derivate thereof) changes
- get everything else needed for an action in the action itself: this will not cause re-renders and better separate action and component dependencies.

2023-09-20 14:32 UTC, leslielazzarino commented
I will have a deeper look after the selectors have been migrated.

2023-09-20 15:08 UTC, lennartclaas commented on src/Frontend/Components/CriticalLicensesTable/CriticalLicensesTable.tsx
>    const onLocateAttributionButtonClick = function (): void {
I created a new action that handles all this stuff. Thanks for pointing that out.

2023-09-21 06:36 UTC, leslielazzarino requested changes

2023-09-21 06:36 UTC, leslielazzarino commented on src/Frontend/state/actions/popup-actions/popup-actions.ts
> +    dispatch(setLocatePopupSelectedLicenses(new Set([licenseName])));
Why are these two separate actions? It will potentially cause unwanted re-renders, as the dispatches in a thunk action are applied one after the other, causing re-renders (and calculations) after each. I would prefer to have a new extra action "setLocatePopupFilters" that allows to set all filters at once.

2023-09-22 11:51 UTC, MarkusObendrauf commented on src/Frontend/Components/ProjectStatisticsPopup/__tests__/ProjectStatisticsPopup.test.tsx
> +      name: 'locate attributions with "MIT"',
not sure this is the right place, but shouldn't we call it 'signals' instead of 'attributions'?

2023-09-22 15:11 UTC, lennartclaas commented
I refactored the two individual actions for setting and getting `selectedCriticality` and `selectedLicenses`. Now, both are always set and got at once via `locatePopupFilters`. This prevents unnecessary re-renderings.

2023-09-25 05:56 UTC, benedikt-richter commented on src/Frontend/util/locate-attributions.ts
> +export function calculateResourcesWithLocatedAttributions(
Did not look into it in detail. However, this is very specific for the locate feature and should not be in the `util` folder. Probably, move to component helpers (that's what we typically do to extract specific helpers.

2023-09-25 08:24 UTC, lennartclaas commented on src/Frontend/util/locate-attributions.ts
> +export function calculateResourcesWithLocatedAttributions(
This stuff is used in `LocatorPopup` and `popup-actions`. To me it seems a little bit unconventional to import component helpers to an action.

2023-09-25 14:41 UTC, benedikt-richter commented on src/Frontend/util/locate-attributions.ts
> +export function calculateResourcesWithLocatedAttributions(
We discussed to actually move it to the reducer.

2023-09-25 15:40 UTC, vasily-pozdnyakov commented
I found an issue: statistics popup contains invalid pairs of license name (the most frequent one is taken) and criticality (there is some heuristics) and it fails when no results are found. In this case the locator popup informs user that there are no signals.
I do not know what is the best way to handle this at statistics popup.

2023-09-26 06:01 UTC, lennartclaas commented
@vasily-pozdnyakov concerning your [comment](https://github.com/opossum-tool/OpossumUI/pull/2006#issuecomment-1733982024). Nice catch! To really fix this properly, I would argue that substantial changes in the logic of the statistics popup are required. I would therefore create a new ticket for that. For now, I would say that this issue is quite an edge case and does not introduce major obstacles for the users.

2023-09-26 06:07 UTC, lennartclaas commented on src/Frontend/Components/LocatorPopup/LocatorPopup.tsx
> +      setApplyWasClicked(false);
I don't appreciate this approach, but I could not think of any other way to set `showNoSignalsLocatedMessage` without writing it to the redux state (which I would also consider bad practice).

2023-09-26 11:13 UTC, benedikt-richter commented on src/Frontend/state/helpers/action-and-reducer-helpers.ts
> +  const criticalityIsSet = selectedCriticality != SelectedCriticality.Any;
Do not use `!=` and use `!==` instead as we want to avoid type coercion

2023-09-26 11:18 UTC, benedikt-richter commented on src/Frontend/state/actions/popup-actions/popup-actions.ts
> +      dispatch(closePopup());
Why don't we include 
```
    dispatch(
      openResourceInResourceBrowser(locatedResources.values().next().value),
    );
```

here?

2023-09-26 11:20 UTC, benedikt-richter commented
Thanks for your effort to refactor the code base! The code is much improved now 👍

2023-09-26 14:29 UTC, leslielazzarino requested changes

2023-09-26 14:29 UTC, leslielazzarino commented on src/Frontend/state/helpers/action-and-reducer-helpers.ts
> +  completeFrequentLicenseNamesIfPresent(licenseNames, frequentLicenseNames);
do we really whant to mutate such a small set? We are mutating the input of the parent function, it is error-prone

2023-09-26 15:13 UTC, merged