Add replace attribution to context menu and audit view
opossum-tool/OpossumUI pull request #201
Opened 2021-11-17 09:31 UTC by jonas-tai

### Summary of changes

This commit adds the replace attribution function to the context menu and to the hamburger menu in audit view.

### Context and reason for change

Replacing attributions was only possible in attribution view so far and not available in the context menu. This adds these functionalities and allows the user to replace attributions with the context of the file tree and to switch between views while replacing attributions.

### How can the changes be tested

Run the context menu integration tests (part of the frontend ci integration tests) and / or test replace attributions with example file with context menu and in audit view.

2021-11-17 16:53 UTC, leslielazzarino requested changes

2021-11-17 16:53 UTC, leslielazzarino commented on src/Frontend/Components/AttributionColumn/AttributionColumn.tsx
> +    false
This function has a huge number of parameters, and I do not see a meaningful way of breaking the function into parts. To make the code more readable, I would suggest the following js/ts pattern: the function takes a single object as input, where the keys are the names of the variables. Therefore when you are using the function you can see which input is what.

2021-11-18 08:39 UTC, antonbauhofer commented
When selecting replace attribution from the context menu, the popup says `...to the current attribution`. This might be misleading, since the `current attribution` might not be the one selected (see screenshot). So, I suggest to remove `current` from the popup tex
<img width="1440" alt="Screenshot 2021-11-18 at 09 39 00" src="https://user-images.githubusercontent.com/48415604/142380767-b0fade71-7341-406c-9959-13c013a6362c.png">
t.

2021-11-18 08:55 UTC, antonbauhofer reviewed
Looks good.
Just a few minor comments.

2021-11-18 08:55 UTC, antonbauhofer commented on src/Frontend/Components/ResourceDetailsTabs/ResourceDetailsTabs.tsx
> +      after every save click.
This sentence is very long and hard to read. Can you break it down into simpler sentences?

2021-11-18 08:55 UTC, antonbauhofer commented on src/Frontend/Components/AttributionColumn/attribution-column-helpers.ts
> +  const isTableView = currentView === View.Report;
Let's call it `isReportView` to keep it consistent

2021-11-18 09:50 UTC, leslielazzarino requested changes
Too many integration tests. One should not test every bit of the feature through integration tests, as they are long to write/read and slow. My suggestion would be:
- a single integration test, that tests a complex enough case, e.g. that you can mark for replacement an attribution on attribution view and replace it with another on audit view
- everything else you can test through unit tests, where you just test that each component interacts correctly with the state, writing what it should or being updated correctly when something changes.

2021-11-18 09:50 UTC, leslielazzarino commented on src/Frontend/Components/AttributionColumn/attribution-column-helpers.ts
> +  const isTableView = currentView === View.Report;
Is it at all possible to have the context menu on ReportView? I do not think so, as we have no cards there.

2021-11-18 09:50 UTC, leslielazzarino commented on src/Frontend/Components/PackageCard/PackageCard.tsx
> +          hidden: mergeButtonDisplayState.hideOnReplaceMarkedByButton,
Why "On" in the eneum name? I would remove it.

2021-11-18 09:50 UTC, leslielazzarino commented on src/Frontend/Components/AttributionColumn/attribution-column-helpers.ts
>      hideOnReplaceMarkedByButton:
Why "On" in the name? I would remove it.

2021-11-18 09:50 UTC, leslielazzarino commented on src/Frontend/integration-tests/all-views-tests/__tests-ci__/context-menu-all-views.test.tsx
> +  test('replace attributions buttons are synced with hamburger menu buttons', () => {
I do not think we need such an integration test. It is enough to test with unit tests that all buttons read/write correctly in the state. We do not need to test that Redux works with React.

2021-11-18 09:50 UTC, leslielazzarino commented on src/Frontend/integration-tests/attribution-view-tests/__tests-ci__/context-menu-attribution-view.test.tsx
> +  describe('replace attribution buttons', () => {
"replaces", the subject is the context menu. Same in the following row.

2021-11-18 09:50 UTC, leslielazzarino commented on src/Frontend/integration-tests/audit-view-tests/__tests-ci__/context-menu-audit-view.test.tsx
> +  describe('replace attribution buttons', () => {
"replaces"

2021-11-18 09:50 UTC, leslielazzarino commented on src/Frontend/integration-tests/audit-view-tests/__tests-ci__/context-menu-audit-view.test.tsx
> +    test('replace attributions in Package panel', () => {
"replaces"

2021-11-23 13:44 UTC, jonas-tai commented on src/Frontend/Components/AttributionColumn/AttributionColumn.tsx
> +    false
I changed the paramters of the function to a single object👍

2021-11-23 13:45 UTC, jonas-tai commented on src/Frontend/Components/AttributionColumn/attribution-column-helpers.ts
> +  const isTableView = currentView === View.Report;
Removed the parameter, because it is currently not necessary.

2021-11-23 13:45 UTC, jonas-tai commented on src/Frontend/Components/AttributionColumn/attribution-column-helpers.ts
> +  const isTableView = currentView === View.Report;
Removed the parameter, because it is currently not necessary👍

2021-11-23 13:57 UTC, jonas-tai commented on src/Frontend/integration-tests/attribution-view-tests/__tests-ci__/context-menu-attribution-view.test.tsx
> +  describe('replace attribution buttons', () => {
I think the whole naming was confusing to read, so I simplified the naming of these tests.

2021-11-23 13:58 UTC, jonas-tai commented on src/Frontend/integration-tests/all-views-tests/__tests-ci__/context-menu-all-views.test.tsx
> +  test('replace attributions buttons are synced with hamburger menu buttons', () => {
Removed this test as part of the test refactoring.

2021-11-23 14:08 UTC, jonas-tai commented
> Too many integration tests. One should not test every bit of the feature through integration tests, as they are long to write/read and slow. My suggestion would be:
> 
>     * a single integration test, that tests a complex enough case, e.g. that you can mark for replacement an attribution on attribution view and replace it with another on audit view
> 
>     * everything else you can test through unit tests, where you just test that each component interacts correctly with the state, writing what it should or being updated correctly when something changes.

Testing the replace attribution feature requires opening the corresponding replace attribution pop-up. The pop-up is opened at the top-level of the app, so it is not possible to test the feature in unit tests for each component. To make the integration tests easier to read, I removed the correct context menu configuration check from the integration tests. For that, I added separate unit tests for each component that verify the correct context menu configuration for the replace attribution buttons.

2021-11-24 15:47 UTC, antonbauhofer approved these changes

2021-11-26 10:14 UTC, leslielazzarino approved these changes

2021-11-26 10:22 UTC, merged