Locator popup does not fail when a signal is not linked to any resource
opossum-tool/OpossumUI pull request #2026
Opened 2023-09-21 10:09 UTC by leslielazzarino

As that should not happen anyhow, such a signal has been removed from the example file.

### Summary of changes

Locator popup does not fail when a signal is not linked to any resource. As that should not happen anyhow, such a signal has been removed from the example file.

### Context and reason for change

See linked issue.

### How can the changes be tested

1. Test that the bug does not exist any longer: build the app and try to reproduce the bug, using the example file from the main branch
2. Test that the example file does not contain that attribution any longer: open the new example file and check that there is only one MIT license at the end.

2023-09-21 13:43 UTC, vasily-pozdnyakov approved these changes

2023-09-25 05:23 UTC, benedikt-richter commented
I personally find it strange to argue that it cannot happen but still modify the code to handle it... If we have that code why do we modify the example file?

2023-09-25 06:17 UTC, benedikt-richter commented
Don't we ave the issue that licenses from signals that are not linked to resources still show up in the auto-complete of locate popup?

2023-09-25 08:01 UTC, benedikt-richter requested changes
see https://github.com/opossum-tool/OpossumUI/issues/2021#issuecomment-1733119479

2023-09-26 12:00 UTC, vasily-pozdnyakov approved these changes

2023-09-26 15:02 UTC, merged