Save list of 'preferred over' origin IDs
opossum-tool/OpossumUI pull request #2029
Opened 2023-09-21 13:37 UTC by MarkusObendrauf

### Summary of changes

### Context and reason for change

### How can the changes be tested

Note: Please review the [guidelines for contributing](https://github.com/opossum-tool/OpossumUI/blob/main/CONTRIBUTING.md) to this repository.

2023-09-22 08:16 UTC, davidmundelius commented on src/Frontend/Components/AttributionColumn/attribution-column-helpers.ts
> +      resources.push(pathToChildResource);
Why do we need this? It seems like you did this already two lines before.

2023-09-22 08:18 UTC, lennartclaas requested changes
Would it make sense to add an e2e-test that checks whether `output.json` really contains all required data?

2023-09-22 08:18 UTC, lennartclaas commented on src/Frontend/Components/AttributionColumn/attribution-column-helpers.ts
> +      resources.push(pathToChildResource);
Why is `pathToChildResource` added twice?

2023-09-22 08:26 UTC, MarkusObendrauf commented on src/Frontend/Components/AttributionColumn/attribution-column-helpers.ts
> +      resources.push(pathToChildResource);
good point! removed the first call. it turns out that later deduplicating meant that nothing was broken, but its nicer to have this function return exactly what we need.

2023-09-22 08:28 UTC, MarkusObendrauf commented
> Would it make sense to add an e2e-test that checks whether `output.json` really contains all required data?

seperate issue: https://github.com/opossum-tool/OpossumUI/issues/1995

2023-09-22 08:30 UTC, MarkusObendrauf commented on src/Frontend/Components/AttributionColumn/attribution-column-helpers.ts
> +      resources.push(pathToChildResource);
fixed

2023-09-22 11:00 UTC, MarkusObendrauf commented on src/Frontend/Components/AttributionColumn/AttributionColumn.tsx
> +  );
ok, moved this function to a custom action

2023-09-22 12:31 UTC, lennartclaas requested changes

2023-09-22 12:31 UTC, lennartclaas commented on src/Frontend/state/actions/resource-actions/preference-actions.ts
> +          allViewsState.externalAttributionSources,
So far, I haven't seen this approach of getting state data. Seems a bit like bad practice to me. Usually, we call already existing selectors like
```
const state = getState();
const resourceId = getSelectedResourceId(state);
```

2023-09-22 12:47 UTC, MarkusObendrauf commented on src/Frontend/state/actions/resource-actions/preference-actions.ts
> +          allViewsState.externalAttributionSources,
good point, thanks. it should now look like the other actions.

2023-09-22 12:57 UTC, lennartclaas approved these changes
lgtm

2023-09-22 13:08 UTC, MarkusObendrauf commented
ive rebased onto https://github.com/opossum-tool/OpossumUI/pull/2033 to incorporate those changed. i'd like to wait for that to be finalized before merging anything

2023-09-25 06:02 UTC, benedikt-richter commented
Would it be safer to convert this one to a draft to avoid it being merged accidentaly, as it is based on a draft?

2023-09-25 11:44 UTC, MarkusObendrauf commented
rebased

2023-09-25 14:04 UTC, merged