Add menu item for QA mode
opossum-tool/OpossumUI pull request #2090
Opened 2023-10-04 09:22 UTC by meretp

### Summary of changes

This commit adds a new entry to the menu to select the new QA mode. If the mode is selected the icon will be a checked checkbox if not an unchecked one.

### Context and reason for change

Selecting preferred attributions should only be possible in the new QA mode. As a first step this commit adds the respective menu item.

### How can the changes be tested

Check out the changes of the PR, open OpossumUI observe the unchecked checkbox next to the QA menu item as below
![image](https://github.com/opossum-tool/OpossumUI/assets/50019307/da7005a6-8669-47f4-80f2-a8c60e3ec5ce)
Change the boolean [qaMode](https://github.com/opossum-tool/OpossumUI/compare/main...meretp:OpossumUI:introduce-qa-menu-item?expand=1#diff-8a5869f04d6d5648a750bfeae7fd8a80a86af696c24ef65321c716ecfb00965cR25) to `true`, restart the app and observe the checked icon as below
![image](https://github.com/opossum-tool/OpossumUI/assets/50019307/06e6b62a-67ab-49f0-aa7f-d96ac6895122)

2023-10-04 16:02 UTC, vasily-pozdnyakov requested changes
Just a couple of small comments.

2023-10-05 06:30 UTC, meretp commented
After renaming the label 
![Screenshot from 2023-10-05 08-29-46](https://github.com/opossum-tool/OpossumUI/assets/50019307/3f9444e4-1a00-49d3-b1d5-3a109fb87f79)

![image](https://github.com/opossum-tool/OpossumUI/assets/50019307/bc08ded4-f71f-4ceb-a789-53a75e2c394a)

2023-10-05 08:36 UTC, vasily-pozdnyakov approved these changes

2023-10-05 08:50 UTC, meretp commented on src/ElectronBackend/main/__tests__/iconHelpers.test.ts
> +  });
No, good point, moved it to the test.

2023-10-05 09:16 UTC, merged