Fix: Context menu does not check for disabled
opossum-tool/OpossumUI pull request #2134
Opened 2023-10-11 16:05 UTC by mstykow

### Summary of changes

- add disabled check to ContextMenu
- add new unit tests and fix some integration tests that were failing as a result

### Context and reason for change

Closes #2016.

### How can the changes be tested

See task description: you won't be able to reproduce the bug anymore.

2023-10-11 16:06 UTC, mstykow commented on src/Frontend/test-helpers/attribution-column-test-helpers.ts
> -  if (screen.queryByRole('presentation')) {
a method named `expectButtonInHamburgerMenuIsNotShown` should not contain unrelated side-effects. these side-effects were causing other tests to fail.

2023-10-11 16:06 UTC, mstykow commented on src/Frontend/integration-tests/audit-view-tests/__tests__/audit-view.test.tsx
> +    fireEvent.click(screen.getByRole('presentation').firstChild as Element);
only place where the side effect from `expectButtonInHamburgerMenuIsNotShown` was actually needed to clear the context menu.

2023-10-12 08:45 UTC, leslielazzarino requested changes

2023-10-12 08:45 UTC, leslielazzarino commented on src/Frontend/Components/ContextMenu/__tests__/ContextMenu.test.tsx
> +    // given
As a convention, we do not write given/when/then. Exceptions are possible, but in this case I do no think that they make the tests easier to understand, as they are pretty short and simple already.

2023-10-12 08:45 UTC, leslielazzarino commented on src/Frontend/Components/ContextMenu/__tests__/ContextMenu.test.tsx
> +    const trigger = 'Test Element';
Why are you calling this "trigger"?

2023-10-12 08:45 UTC, leslielazzarino commented on src/Frontend/integration-tests/audit-view-tests/__tests__/audit-view.test.tsx
> +    fireEvent.click(screen.getByRole('presentation').firstChild as Element);
I find this line quite obscure. Can we pack it in a function, whose name explains what we are doing?

2023-10-12 11:53 UTC, mstykow commented on src/Frontend/integration-tests/audit-view-tests/__tests__/audit-view.test.tsx
> +    fireEvent.click(screen.getByRole('presentation').firstChild as Element);
done

2023-10-12 11:58 UTC, mstykow commented on src/Frontend/Components/ContextMenu/__tests__/ContextMenu.test.tsx
> +    // given
removed since such annotations are not commonly current practice

2023-10-12 11:59 UTC, mstykow commented on src/Frontend/Components/ContextMenu/__tests__/ContextMenu.test.tsx
> +    const trigger = 'Test Element';
because this is the button label that, when clicked, triggers opening the menu. i find this more helpful as a variable name than "testElementText" which is what the other tests are using.

2023-10-12 13:58 UTC, leslielazzarino approved these changes

2023-10-12 13:58 UTC, leslielazzarino commented on src/Frontend/test-helpers/context-menu-test-helpers.ts
> +export function clearPopover(screen: Screen): void {
nice

2023-10-12 13:59 UTC, merged