Fix hidden signals in Signals in Folder Content tab
opossum-tool/OpossumUI pull request #215
Opened 2021-11-24 16:41 UTC by jonas-tai

### Summary of changes

Add filter for resolved attributions to 'Signals in Folder Content' tab.

### Context and reason for change

Hiding a signal should remove it from the 'Signals in Folder Content' tab and make it only visible through the 'Signals' tab of the resources, the signal is attached to. So far, the signal stayed greyed out in the 'Signals in Folder Content' tab, if at least one resource, to which the signal was attached to, had one or more other non-hidden signals. This commit fixes this behavior by adding a filter for resolved attributions to the 'Signals in Folder Content' tab.

### How can the changes be tested

Run tests and / or use example file to hide a signal that is attached to a resource with at least one other non-hidden signal. Verify that the signal is not visible in the 'Signals in Folder Content' tab after hiding it

2021-11-25 10:45 UTC, nicarl requested changes

2021-11-25 10:45 UTC, nicarl commented on src/Frontend/Components/ResourceDetailsTabs/resource-details-tabs-helpers.ts
> +  resolvedExternalAttributions = new Set<string>()
I prefer to make `resolvedExternalAttributions` nullable with default null instead of creating a new set every time the function gets called.

2021-11-29 10:23 UTC, benedikt-richter approved these changes
works smoothly 👍

2021-11-29 12:29 UTC, nicarl commented
One test is still failing, let's have a look together.

2021-11-29 14:30 UTC, nicarl commented on src/Frontend/Components/ResourceDetailsTabs/ResourceDetailsTabs.tsx
> +    [selectedResourceId, externalData, resolvedExternalAttributions]
@benedikt-richter

2021-11-29 15:35 UTC, merged