Add feature to directly open a file via ENV variable
opossum-tool/OpossumUI pull request #2207
Opened 2023-10-26 14:30 UTC by meretp

### Summary of changes

In addition to opening a file from a cli argument this commit adds the function to open a file by setting an environment variable. If the ENV variable OPOSSUM_FILE is set, the app will try to open this file directly when starting.

### Context and reason for change

With these changes the app can be started with `yarn start` (using vite) and directly open an opossum input file.
### How can the changes be tested

See the additional tests. Alternatively, set the environment variable by running `export OPOSSUM_FILE=<input_file>` where `<input_file>` is the absolute path to an opossum input file and run `yarn start`. The app is now started and directly opens the provided file.

2023-11-02 07:35 UTC, leslielazzarino commented on src/ElectronBackend/main/__tests__/openFileFromCliOrEnvVariableIfProvided.test.ts
> +    process.argv = [...oldProcessArgv];
A deep copy with lodash would be safer here.

2023-11-02 07:37 UTC, leslielazzarino commented on src/ElectronBackend/main/__tests__/openFileFromCliOrEnvVariableIfProvided.test.ts
> +    if (inputFileName) {
This is always true

2023-11-02 07:42 UTC, leslielazzarino commented on src/ElectronBackend/main/__tests__/openFileFromCliOrEnvVariableIfProvided.test.ts
> +    process.argv = oldProcessArgv;
No longer needed

2023-11-02 07:43 UTC, leslielazzarino commented on src/ElectronBackend/main/__tests__/openFileFromCliOrEnvVariableIfProvided.test.ts
> +      inputFileName,
I think the result of the test is the opposite of what is stated in the test description: the CLI arg is getting used.

2023-11-02 07:44 UTC, leslielazzarino commented on src/ElectronBackend/main/openFileFromCliOrEnvVariableIfProvided.ts
> +  if (!inputFileName && inputFileFromEnvVariable) {
Here the CLI gets priority over the env variable, therefore I assume the test description is wrong.

2023-11-02 08:33 UTC, leslielazzarino commented
It does not work on Windows.

2023-11-02 09:07 UTC, meretp commented on src/ElectronBackend/main/__tests__/openFileFromCliOrEnvVariableIfProvided.test.ts
> +      inputFileName,
True, I changed the description.

2023-11-02 09:07 UTC, meretp commented on src/ElectronBackend/main/__tests__/openFileFromCliOrEnvVariableIfProvided.test.ts
> +    process.argv = [...oldProcessArgv];
done

2023-11-02 09:08 UTC, meretp commented
I fixed the minor comments and will have a look at why it does not work on windows.

2023-11-16 11:20 UTC, maxhbr reviewed
some comments

2023-11-16 11:20 UTC, maxhbr commented on scripts/start.sh
start.sh is a very short name. Especially as it is just used in the yarn context and not in production

2023-11-16 11:20 UTC, maxhbr commented on src/ElectronBackend/main/openFileFromCliOrEnvVariableIfProvided.ts
> +      inputFileFromEnvVariable.endsWith('.json') ||
this is duplicated code

2023-11-16 11:20 UTC, maxhbr commented on scripts/start.sh
maybe it would be better if the folder would be called `yarn_scripts`

2023-11-16 11:20 UTC, maxhbr commented on scripts/start.sh
A description would help to explain what that script is intended for

2023-11-16 11:20 UTC, maxhbr commented on src/ElectronBackend/main/openFileFromCliOrEnvVariableIfProvided.ts
> +      log.info(
could be warning or error?

2023-11-16 14:43 UTC, meretp commented on src/ElectronBackend/main/openFileFromCliOrEnvVariableIfProvided.ts
> +      log.info(
changed it to a warning

2023-11-16 14:43 UTC, meretp commented on src/ElectronBackend/main/openFileFromCliOrEnvVariableIfProvided.ts
> +      inputFileFromEnvVariable.endsWith('.json') ||
extracted a method for this

2023-11-16 15:22 UTC, leslielazzarino requested changes

2023-11-16 15:22 UTC, leslielazzarino commented on package.json
> +    "start": "yarn_scripts/start.sh",
This is never gonna work in Windows.

2023-11-16 15:22 UTC, leslielazzarino commented on yarn_scripts/start.sh
> +yarn generate-notice && yarn tsc -p src/ElectronBackend && cross-env OPOSSUM_FILE=$FILE_PATH yarn vite
This needs a Windows version, that gets called for windows.

2023-11-16 16:05 UTC, leslielazzarino requested changes

2023-11-16 16:05 UTC, leslielazzarino commented on yarn_scripts/start_windows.bat
> +# SPDX-FileCopyrightText: Meta Platforms, Inc. and its affiliates
This is not how comments are written in batch. Use REM instead of #. Also move line 9 to the top, to avoid printing the comments to the console.

2023-11-16 16:05 UTC, leslielazzarino commented on yarn_scripts/start_windows.bat
> +# SPDX-FileCopyrightText: Meta Platforms, Inc. and its affiliates
With those changes, it works fine on windows.

2023-11-17 07:09 UTC, meretp commented on yarn_scripts/start_windows.bat
> +# SPDX-FileCopyrightText: Meta Platforms, Inc. and its affiliates
Thanks for testing! I adapted the script, should be fine now.

2023-11-22 07:35 UTC, leslielazzarino approved these changes

2023-11-22 08:55 UTC, merged