fix: issues with multiple vertical scroll bars
opossum-tool/OpossumUI pull request #2208
Opened 2023-10-27 14:41 UTC by mstykow

### Summary of changes

- replace react-window with virtuoso
- virtuoso comes with built-in full-height sizing which obviates the need for complicated height calculations based on window height and paddings in multiple components
- removing the height calculations and instead using flex-box design with flex grow factor removes the vertical scroll bar issues

### Context and reason for change

Closes #2076.

### How can the changes be tested

These videos demo that first of all no existing functionality has been broken, and second, that small UI bugs such as the doubled vertical scroll bars have been fixed.

https://github.com/opossum-tool/OpossumUI/assets/46091730/08071f7b-39ed-4dc0-9b63-a8a290009ac3
https://github.com/opossum-tool/OpossumUI/assets/46091730/b997cb49-e450-4241-a643-2d263d2d46b8

2023-10-27 14:46 UTC, mstykow commented on src/Frontend/Components/ReportView/ReportView.tsx
> +          <div>
`div` now necessary because of the parent's flex-box behavior.

2023-10-27 15:25 UTC, mstykow commented on src/Frontend/Components/SearchTextField/SearchTextField.tsx
> +    marginTop: '8px',
necessary to prevent cutting off the label that moves to above the input field when user is entering text.

2023-10-27 15:25 UTC, mstykow commented on src/Frontend/util/has-attribution-multiple-resources.ts
> +    return (attributionsToResources[attributionId] || []).length > 1;
notice that index access can result in `undefined` so that accessing `length` may result in a null pointer exception. there is a [typescript rule](https://www.typescriptlang.org/tsconfig#noUncheckedIndexedAccess) to prevent this error but turning it on right now would result in too many places to fix.

2023-10-27 15:25 UTC, mstykow commented on src/Frontend/Components/FileSearchPopup/FileSearchPopup.tsx
> -    500 > maxPossibleHeightInPx ? maxPossibleHeightInPx : 500;
example of complicated height calculations that are no longer necessary.

2023-10-27 15:25 UTC, mstykow commented on src/Frontend/extracted/VirtualisedTree/VirtualizedTree.tsx
> -      };
another example of a complicated height calculation that is no longer necessary.

2023-10-30 08:48 UTC, leslielazzarino requested changes

2023-10-30 08:48 UTC, leslielazzarino commented on src/Frontend/Components/ResourceDetailsTabs/ResourceDetailsTabs.tsx
> -        isAddToPackageEnabled={isAddToPackageEnabled}
Unless they changed something recently, if a component is re-rendered in React its children are re-rendered too. That was the purpose of this useMemo. We need to double-check that it is not needed any longer.

2023-10-30 08:48 UTC, leslielazzarino commented on src/Frontend/extracted/VirtualisedTree/VirtualizedTree.tsx
> -      };
cool

2023-10-30 08:48 UTC, leslielazzarino commented on src/Frontend/util/has-attribution-multiple-resources.ts
> +    return (attributionsToResources[attributionId] || []).length > 1;
This place in the code was discussed a month ago or so. It was decided not to add this fix as it would only be needed in the case of a broken input file. Personally I'm not against it, but it should be redicussed before changing it.

2023-10-30 09:29 UTC, mstykow commented on src/Frontend/Components/ResourceDetailsTabs/ResourceDetailsTabs.tsx
> -        isAddToPackageEnabled={isAddToPackageEnabled}
Thanks for your comment @leslielazzarino. I was wrong and you're right that the child components will always re-render when the parent changes, even if the prop value is still the same. I have two points about this though:
1. For the purpose of memoizing components, React introduced `React.memo`. `React.useMemo` is meant for constants (objects, arrays, ...). So I suggest that we change to `React.memo` if performance is an issue here. Which brings me to the second point:
2. Have you tested that this memoization really leads to a performance optimization? I didn't notice any issues when I removed it. I mean re-rendering is a normal part of React and we could literally go as far as wrapping all components, constants, functions in memoization hooks. See here for example: https://attardi.org/why-we-memo-all-the-things/ In my opinion, doing so would at least make the code generally harder to read.

2023-10-30 10:03 UTC, mstykow commented on src/Frontend/util/has-attribution-multiple-resources.ts
> +    return (attributionsToResources[attributionId] || []).length > 1;
Discussed with Leslie: we agreed to keep this change because without it some tests are failing. In addition, it may be a good idea in general to turn on the rule referenced above in a separate PR.

2023-10-30 10:59 UTC, mstykow commented on src/Frontend/Components/ResourceDetailsTabs/ResourceDetailsTabs.tsx
> -        isAddToPackageEnabled={isAddToPackageEnabled}
I added `React.memo` to the aggregated attributions panel. We could check in a separate PR if other components could benefit from this, too.

2023-10-30 12:32 UTC, MarkusObendrauf requested changes
Nice! Im definitely a fan of using Virtuoso here, it simplifies a lot of our styling code. couldnt spot any bugs when i tried it.

i just have a few comments. im especially not sure about how we are mixing two different styling conventions in this PR.

2023-10-30 12:32 UTC, MarkusObendrauf commented on src/Frontend/Components/AttributionView/AttributionView.tsx
> +    // In AttributionView, attributionIds still serve as packageCardIds
lol nice

2023-10-30 12:32 UTC, MarkusObendrauf commented on src/Frontend/Components/NotificationPopup/NotificationPopup.tsx
> +          ...(props.fullHeight && { display: 'flex', flexDirection: 'column' }),
we usually dont inline styles, could you extract it to something like a `fullHeightDialogContent` class?

2023-10-30 12:45 UTC, mstykow commented on src/Frontend/integration-tests/all-views-tests/__tests-ci__/context-menu-all-views.test.tsx
> +    closePopup(screen);
this test was failing after my changes. tbh, i'm not sure how the test succeeded before because as far as i understand the opened "resources popup" should be blocking the UI. but i suspect that through react-testing-library it is possible to access nodes in the DOM which are visually obscured by a modal with a higher z-index. either way, it seems correct to me that the popup should be closed after interactions/assertions with it and apparently this also fixes the tests.

from my conversations with other maintainers, it seems that the existing so-called integration tests have various issues that rear their heads when refactorings are performed. in my opinion, these integration tests are one of the biggest tech debts we currently have in the project:
- they are slow (in total they run more than 20 mins here on GitHub)
- they are fragile (subject to easily be broken by internal refactorings)
- they are hard to understand because of numerous abstractions layered on top of react-testing-library which, again in my opinion, is an anti-pattern

2023-10-30 12:49 UTC, mstykow commented on src/Frontend/Components/ResizableBox/ResizableBox.tsx
> +  style?: React.CSSProperties;
i experimented a bit more and it turns out that `Resizable` already has another `sx` prop with a typing that's different from the one MUI would expect. also, using this prop does not produce the desired CSS effects. so rather than complicating things, i suggest we live with the fact that non-MUI components may use a styling system upon which the current `sx` styling system cannot be forced.

2023-10-30 13:11 UTC, mstykow commented on src/Frontend/Components/ResizableBox/ResizableBox.tsx
> +  style?: React.CSSProperties;
i found a way to revert everything back to using `sx` by casting the type in the `ResizableBox` component. although i don't think this is the best approach, it's at least consistent with how styling in this app is done in general.

2023-10-30 13:11 UTC, mstykow commented on src/Frontend/Components/NotificationPopup/NotificationPopup.tsx
> +          ...(props.fullHeight && { display: 'flex', flexDirection: 'column' }),
done

2023-10-30 13:13 UTC, mstykow commented on src/Frontend/Components/PackageList/AttributionsViewPackageList.tsx
> +        cardHeight={41}
done

2023-10-30 15:31 UTC, MarkusObendrauf commented on src/Frontend/Components/ResizableBox/ResizableBox.tsx
> +  style?: React.CSSProperties;
nice! i understand that the approach isnt the best, but for now i think this is the right choice.

2023-10-30 15:33 UTC, MarkusObendrauf approved these changes
lgtm 👍

2023-10-31 08:15 UTC, merged