feat: highlight missing namespaces
opossum-tool/OpossumUI pull request #2214
Opened 2023-10-31 09:02 UTC by mstykow

### Summary of changes

- explicitly display package type and namespace in attribution details view
- highlight PURLs whose namespace is required but missing
- create dedicated file for storing user-facing texts and extract package sub-panel labels there
- create hook to update temporarily displayed package info to avoid prop-drilling redux actions through several levels of components

![image](https://github.com/opossum-tool/OpossumUI/assets/46091730/382a1d7f-1533-48a0-a17e-68c16d442c8f)

### Context and reason for change

Progress on #2213.

2023-11-02 14:29 UTC, leslielazzarino requested changes
A second and last point: I'm not sure about the usability of the feature. Sure, we are not exposing the appendix, but the purl is much easier to edit manually through the part fields (e.g. to update the version). Disabling them might not be the best for the users.

2023-11-02 14:29 UTC, leslielazzarino commented on src/Frontend/util/is-important-attribution-information-missing.ts
> +    case 'packageType':
Are we sure about this? There will be a ton more orange in the app with this change.

2023-11-02 14:29 UTC, leslielazzarino commented on src/shared/text.ts
> +};
cool

2023-11-07 11:51 UTC, mstykow commented on src/Frontend/Components/AttributionColumn/PackageSubPanel.tsx
> +  function renderPackageType(): React.ReactElement {
yes, i always do it like this because then i can read the component like a book from top to bottom. instead of down, up, and then down again.

2023-11-07 11:52 UTC, mstykow commented on src/Frontend/util/is-important-attribution-information-missing.ts
> +    case 'packageType':
can you explain more what you mean by "orange"?

2023-11-07 13:29 UTC, leslielazzarino commented on src/Frontend/util/is-important-attribution-information-missing.ts
> +    case 'packageType':
Incomplete attributions are marked with an orange wedge. After checking a real case scenario, it turn out that your change would not make much of a difference here.

2023-11-07 13:30 UTC, leslielazzarino approved these changes

2023-11-07 13:30 UTC, merged