feat: re-enable E2E tests
opossum-tool/OpossumUI pull request #2222
Opened 2023-10-31 21:44 UTC by mstykow

### Summary of changes

- create proper playwright config
- introduce fixtures to simplify test setup
- rewrite tests with modern syntax
- simplify package.json script to run E2E tests
- consolidate vite configs using conditional modes
- handle devtools using command line arg instead of env var
- reenable E2E tests in pipeline
- allow workflow dispatch for pipelines

STACKED DIFF: IGNORE FIRST COMMIT.

### Context and reason for change

Closes #1977 and improves setup and code quality of E2E tests.

### How can the changes be tested

Run `yarn test:e2e` locally and also watch the pipeline output in CI/CD.

2023-11-02 07:47 UTC, mstykow commented on src/ElectronBackend/main/main.ts
> -      if (BrowserWindow.getAllWindows().length === 0) {
not needed since we always shut down the app as soon as there are 0 windows.

2023-11-02 07:48 UTC, mstykow commented on src/ElectronBackend/app.ts
> -app.whenReady().then(main);
`.whenReady` returns a promise. so technically we'd need to await it or void it. using `.on('ready')` is equivalent but  is an event handler.

2023-11-02 07:49 UTC, mstykow commented on package.json
> +    "test:e2e": "start-server-and-test \"tsc -p src/ElectronBackend && vite -m e2e\" \"http://localhost:5173/\" \"yarn playwright test -c src/e2e-tests/playwright.config.ts\"",
notice that we don't need to build the application using `yarn vite`. doing so was unnecessarily slowing down the test startup time.

2023-11-02 07:49 UTC, mstykow commented on src/ElectronBackend/main/__tests__/mainErrorCase.test.ts
> -    jest.spyOn(console, 'log');
just spying on `console` does nothing at all.

2023-11-02 07:51 UTC, mstykow commented on .eslintrc.js
> +    'testing-library/prefer-screen-queries': 'off',
playwright uses RTL-like syntax which triggers this linter rule but cannot be fixed.
also, i think there is nothing wrong with using non-screen queries, even in RTL.
i've usually turned this rule off in all my other projects as well.

2023-11-02 10:04 UTC, leslielazzarino requested changes
Great PR, I would just avoid the lint rule change. Btw, do you know why playwright hangs 20s (on my Windows sistems) after all tests are finished, before exiting?

2023-11-02 21:59 UTC, mstykow commented on .eslintrc.js
> +    'testing-library/prefer-screen-queries': 'off',
i'll keep the rule on for now and use an override instead, as this discussion is not material to my PR.

2023-11-03 09:51 UTC, leslielazzarino approved these changes

2023-11-03 21:33 UTC, merged