show warning popup if attribution that was preferred is modified and …
opossum-tool/OpossumUI pull request #2223
Opened 2023-11-01 15:36 UTC by alexzurbonsen

…remove wasPreferred if modification is saved

### Summary of changes

### Context and reason for change

### How can the changes be tested

Note: Please review the [guidelines for contributing](https://github.com/opossum-tool/OpossumUI/blob/main/CONTRIBUTING.md) to this repository.

2023-11-06 13:15 UTC, alexzurbonsen commented on src/Frontend/Components/ModifyWasPreferredAttributionPopup/__tests__/ModifyWasPreferredAttributionPopup.test.tsx
> +  // TODO does this test run into an actual bug? Or is the test faulty?
This still needs to be resolved.

2023-11-07 11:49 UTC, mstykow requested changes

2023-11-07 11:49 UTC, mstykow commented on src/Frontend/state/actions/popup-actions/popup-actions.ts
> +    const temporaryDisplayPackageInfo = getTemporaryDisplayPackageInfo(
if you do this, you won't need the `delete`:
```suggestion
    const { wasPreferred, ...temporaryDisplayPackageInfo } = getTemporaryDisplayPackageInfo(
```

2023-11-07 13:35 UTC, alexzurbonsen commented on src/Frontend/Components/ModifyWasPreferredAttributionPopup/__tests__/ModifyWasPreferredAttributionPopup.test.tsx
> +  // TODO does this test run into an actual bug? Or is the test faulty?
The error happened because I provide the `openPopup` action an attribution id in the test.
In Report View that sets the `currentAttributionId`. This is `undefined` in the same tests for Audit and Attribution view. Thus, a deletion process is not triggered in these tests, but it is triggered in the Report view test. The deletion then runs into an error because the attribution is not really there.

Two options:
1) kick out the attributionId when opening the popup. This means the attempted saving will stop early and no error is raised.
2) But since we rely on the currentAttributionId to be set correctly in Report View, otherwise the saving doesn't work, it would probably be better to add more data to make the test more realistic.

2023-11-07 13:42 UTC, alexzurbonsen commented on src/Frontend/Components/EditAttributionPopup/EditAttributionPopup.tsx
> +      popupAttributionId &&
good point.

2023-11-07 13:45 UTC, alexzurbonsen commented on src/Frontend/Components/ModifyWasPreferredAttributionPopup/ModifyWasPreferredAttributionPopup.tsx
> +      as was preferred.
This sounded weird to me as well. Let's discuss in a call :)

2023-11-07 13:48 UTC, alexzurbonsen commented on src/Frontend/Components/ModifyWasPreferredAttributionPopup/__tests__/ModifyWasPreferredAttributionPopup.test.tsx
> +    it('renders a ModifyWasPreferredAttributionPopup and click save', () => {
Oh yes, will change that.

2023-11-07 13:52 UTC, alexzurbonsen commented on src/Frontend/Components/ModifyWasPreferredAttributionPopup/__tests__/ModifyWasPreferredAttributionPopup.test.tsx
> +    it('renders a ModifyWasPreferredAttributionPopup and click save', () => {
One question though: I took out the assertion on the rendered popup after out last discussion with Leslie, since it seemed that this would also assert on something that is part of the test setup. Would you prefer to see that in the test again? Or is it sufficient to assert on what is in the test at the moment (minus the assertion form your comment below).

2023-11-07 13:54 UTC, alexzurbonsen commented on src/Frontend/Components/ModifyWasPreferredAttributionPopup/__tests__/ModifyWasPreferredAttributionPopup.test.tsx
> +      ).toBeTruthy();
I took it out in all the tests.

2023-11-07 13:56 UTC, alexzurbonsen commented on src/Frontend/Components/ModifyWasPreferredAttributionPopup/__tests__/ModifyWasPreferredAttributionPopup.test.tsx
> +      expect(getOpenPopup(store.getState())).toBe(null);
I get the point with testing only what can be seen by the user. But not sure about the open part. Can we discuss this shortly?

2023-11-07 13:57 UTC, alexzurbonsen commented on src/Frontend/Components/ModifyWasPreferredAttributionPopup/__tests__/ModifyWasPreferredAttributionPopup.test.tsx
> +    (view === View.Audit ? it : it.skip)(
Sure, fine for me as well.

2023-11-07 14:04 UTC, alexzurbonsen commented on src/Frontend/Components/ModifyWasPreferredAttributionPopup/__tests__/ModifyWasPreferredAttributionPopup.test.tsx
> +        hasAttributionMultipleResources.mockReturnValue(true);
I think I made a mistake here.
The logic is: the SaveGlobally Button is only shown when an attribution is attached to more than one resource.

If that is not the case, the `Save` button is using the same handler that the `Save Globally` button is using if it were present. If the `Save Globally` button is visible, the `Save` button uses a different handler.

Currently, the tests that click save and save globally, are both directed to the same handler. 

So I should change this test to click the `Save` button instead of the `Save Globally` button, such that the other handler is tested.

2023-11-07 14:10 UTC, alexzurbonsen commented on src/Frontend/integration-tests/audit-view-tests/__tests__/audit-view.test.tsx
> +    // @ts-ignore
Me neither... But for me the type checker complained. I thought that there might have been a change in the settings or an update. Not sure.

2023-11-07 14:20 UTC, alexzurbonsen commented on src/Frontend/Components/ResourceDetailsAttributionColumn/ResourceDetailsAttributionColumn.tsx
> +            attributionIdOfSelectedPackageInManualPanel as string, // showSaveGloballyButton is true, so attributionIdOfSelectedPackageInManualPanel is not null
Oh, sure... I forgot to correct that.

2023-11-07 14:28 UTC, alexzurbonsen commented on src/Frontend/state/actions/popup-actions/popup-actions.ts
> +    if (getIsSavingDisabled(getState())) {
Yes, here: https://github.com/opossum-tool/OpossumUI/pull/2223/files#diff-0709b4cabbd610f0851cb499edd81c6572c44468d915cb743dca23c75f0834f0R707

2023-11-07 14:32 UTC, alexzurbonsen commented on src/Frontend/state/actions/popup-actions/popup-actions.ts
> +    const temporaryDisplayPackageInfo = getTemporaryDisplayPackageInfo(
Neat, I didn't know about that.

2023-11-07 18:26 UTC, alexzurbonsen commented on src/Frontend/integration-tests/audit-view-tests/__tests__/audit-view.test.tsx
> +    // @ts-ignore
You were right. Must have mixed something up here. Threw them all out.

2023-11-08 09:39 UTC, mstykow approved these changes

2023-11-08 09:39 UTC, mstykow commented on src/Frontend/integration-tests/audit-view-tests/__tests__/audit-view.test.tsx
> +  it('removes was-preferred field when user has saves unsaved changes and navigates away', () => {
```suggestion
  it('removes was-preferred field when user has saved unsaved changes and navigates away', () => {
```

2023-11-08 09:39 UTC, mstykow commented on src/Frontend/integration-tests/report-view-tests/__tests__/report-view.test.tsx
> +  it('removes was-preferred field when user has saves unsaved changes and navigates away', () => {
```suggestion
  it('removes was-preferred field when user has saved unsaved changes and navigates away', () => {
```

2023-11-08 10:53 UTC, merged