Modify statistics popup
opossum-tool/OpossumUI pull request #2233
Opened 2023-11-02 17:03 UTC by vasily-pozdnyakov

### Summary of changes

* Merged signals should be counted as one item at the project statistics popup
* Use "Signals Count" instead of "Count"
* Rename "Critical signals" to "Signals by criticality" and the pie chart legend
* Modify the heuristics to take the highest criticality at the statistics when there are license variants with different criticalities (here we take the risk of false-critical signals). At the end, colors at the "Critical signals" pie chart should agree with colors at Criticality Progress bar

### Context and reason for change

Fix #2146

### How can the changes be tested

See unit tests.
Open any example file and see the changes at Project Statistics popup.

**Before**
![image](https://github.com/opossum-tool/OpossumUI/assets/85183359/104b6cae-c120-444b-a8ef-221dd726ac6f)

**After**
![image](https://github.com/opossum-tool/OpossumUI/assets/85183359/86705a3b-7762-4451-9150-f4226929603d)

2023-11-02 22:24 UTC, mstykow requested changes

2023-11-02 22:24 UTC, mstykow commented on src/Frontend/Components/CriticalLicensesTable/CriticalLicensesTable.tsx
>  const COUNT_COLUMN_NAME_IN_TABLE = 'Count';
what is the reason we need to keep the old "Count" column name? it seems that if you also adjust line 113 to use the new value, there is no need to introduce two different names for the same column.

2023-11-02 22:24 UTC, mstykow commented on src/Frontend/Components/AccordionWithPieChart/__tests__/accordion-with-pie-chart-helpers.test.tsx
> +        name: 'Highly critical signals',
please don't repeat user facing text in tests. instead, reference the enum you created.

2023-11-02 22:24 UTC, mstykow commented on src/Frontend/Components/ProjectStatisticsPopup/__tests__/ProjectStatisticsPopup.test.tsx
> +    expect(screen.getByText('Signals by Criticality')).toBeInTheDocument();
here too you can use the enum

2023-11-02 22:24 UTC, mstykow commented on src/Frontend/Components/ProjectStatisticsPopup/__tests__/project-statistics-popup-helpers.test.tsx
> +  it('obtains the highest high criticality', () => {
i don't see how this test is any different from the one that's called "obtains high criticality". i don't really see you testing something new and so i suggest you revert adding this test.

2023-11-02 22:24 UTC, mstykow commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +        if (hash) {
typescript says that `hash` is always a string because we haven't turned on the rule [noUncheckedIndexAccess](https://www.typescriptlang.org/tsconfig#noUncheckedIndexedAccess) (this is a tech debt IMHO).

i think you're performing this check not because you're concerned about the empty string but because you know that `hash` could be undefined, correct?

but then it seems you should perform this null check before line 201 where you use `useHashes.has(hash)` which even has a risk of a null-pointer exception because `has` requires `hash` to always be a string.

2023-11-03 08:18 UTC, vasily-pozdnyakov commented on src/Frontend/Components/CriticalLicensesTable/CriticalLicensesTable.tsx
>  const COUNT_COLUMN_NAME_IN_TABLE = 'Count';
good point, you are right.

2023-11-03 08:51 UTC, vasily-pozdnyakov commented on src/Frontend/Components/ProjectStatisticsPopup/__tests__/project-statistics-popup-helpers.test.tsx
> +  it('obtains the highest high criticality', () => {
It was slightly different, but I get your point. Will delete it and slightly change "obtains high criticality" test.

2023-11-03 09:31 UTC, vasily-pozdnyakov commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +        if (hash) {
I made a refactoring here.

2023-11-03 09:45 UTC, mstykow approved these changes

2023-11-03 09:45 UTC, mstykow commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +      if (attributionId in externalAttributionsToHashes) {
this seen-check can and probably should be moved to the beginning of the for-loop.

2023-11-03 09:45 UTC, mstykow commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +  const usedHashes: Set<string> = new Set<string>();
unnecessary type declaration

2023-11-03 10:19 UTC, merged