feat: replace integration with E2E tests
opossum-tool/OpossumUI pull request #2235
Opened 2023-11-03 22:11 UTC by mstykow

### Summary of changes

- turn on linter rule to catch floating promises and fix issues
- replace static E2E assets with dynamically generated ones that are cleaned up after each run
- create DEBUG environment variable to skip post-run cleanup
- set up faker and custom faker module to generate opossum I/O data
- replace first batch (most slow-running) integration tests with real E2E tests
- create POMs for components used in E2E tests
- give aria-labels to some common components that are otherwise hard to select during tests

### Context and reason for change

Closes #2151.

### How can the changes be tested

Run integration and E2E tests locally and in the CI/CD pipeline and compare execution times between this branch and main.

2023-11-03 22:12 UTC, mstykow commented on .eslintrc.js
> +    '@typescript-eslint/no-floating-promises': 'error',
this rule is generally helpful, but particularly so in tests where it's quite easy to forget to await some actions or assertions.

2023-11-03 22:13 UTC, mstykow commented on src/Frontend/Components/AggregatedAttributionsPanel/WorkerAccordionPanel.tsx
> +  useEffect(() => {
`useMemo` is meant for constants, not for functions returning void.

2023-11-03 22:13 UTC, mstykow commented on src/Frontend/Components/Button/__tests__/Button.test.tsx
> +    await expect(
example of floating test assertion that was missed before and now got fixed by the new linter rule.

2023-11-03 23:02 UTC, mstykow commented on src/Frontend/Components/Button/__tests__/Button.test.tsx
> +    expect(await screen.findByText(testTooltipText)).toBeInTheDocument();
example of floating promises that lead to green tests which are actually failing

2023-11-03 23:03 UTC, mstykow commented on src/Frontend/Components/FetchLicenseInformationButton/__tests__/FetchLicenseInformationButton.test.tsx
> +      expect(await screen.findByText('Network Error')).toBeInTheDocument();
another example where floating promises have led to green tests whose setup was completely broken.

2023-11-03 23:04 UTC, mstykow commented on src/e2e-tests/__tests__/audit-view/confirming-preselected-attributions.test.ts
> +    );
notice how each block (separated by empty lines) begins with some actions and ends with some assertions.

2023-11-06 11:51 UTC, mstykow commented on .eslintrc.js
> +    '@typescript-eslint/no-floating-promises': 'error',
other than that, i just sorted the rules alphabetically to make it easier to find them

2023-11-06 11:52 UTC, mstykow commented on .eslintrc.js
> -  plugins: ['react', 'testing-library', 'jest-dom', 'filenames'],
there is no need to specify something as plugin that's already used as an extension (line 22)

2023-11-06 11:53 UTC, mstykow commented on src/ElectronBackend/types/types.ts
> -interface RawPackageInfo {
this interface was an unncessary duplication of the one in shared types

2023-11-06 11:54 UTC, mstykow commented on src/ElectronBackend/types/types.ts
> -export interface RawBaseUrlsForSources {
this is the same as in shared types

2023-11-06 17:41 UTC, mstykow commented on src/Frontend/Components/ResourcesTree/ResourcesTree.tsx
> +    props.onSelect?.(nodeId);
there was a bug here that i discovered while writing the tests: the resource path popup was not closing when the user clicked on a resource but only changed the selected resource in the background.

to fix this, i introduce the optional `onSelect` prop which i use in `ResourcePathPopup.tsx` to ensure that the popup close handler is executed here.

2023-11-07 13:34 UTC, leslielazzarino requested changes

2023-11-08 09:45 UTC, leslielazzarino requested changes

2023-11-08 09:45 UTC, leslielazzarino commented on src/e2e-tests/__tests__/browsing-resources.test.ts
> +        [resourceId1]: {
This is confusing. In the app we call resource id its path. You should replace everywhere in this PR resourceId with resourceName

2023-11-08 09:45 UTC, leslielazzarino commented on src/e2e-tests/__tests__/basic-ui-elements.test.ts
> -  test('displays correct app title', async ({ window }) => {
I cannot find a test equivalent to this one

2023-11-08 09:46 UTC, leslielazzarino commented
This PR could have been split into multiple smaller ones, to make the review easier.

2023-11-08 10:05 UTC, mstykow commented on src/Frontend/integration-tests/audit-view-tests/__tests-ci__/context-menu-audit-view.test.tsx
> -  it('is not shown for add new attribution PackageCard', () => {
i now added this assertion to the test that checks general navigation (navigating-through-views.test.ts).

2023-11-08 10:05 UTC, mstykow commented on src/e2e-tests/__tests__/basic-ui-elements.test.ts
> -  test('displays correct app title', async ({ window }) => {
i now added this assertion to the test that checks general navigation (navigating-through-views.test.ts).

2023-11-08 10:10 UTC, mstykow commented on src/e2e-tests/__tests__/browsing-resources.test.ts
> +        [resourceId1]: {
Done.

2023-11-08 10:12 UTC, mstykow commented on src/Frontend/integration-tests/audit-view-tests/__tests-ci__/context-menu-audit-view.test.tsx
> -  it('is not shown for add new attribution PackageCard', () => {
in a follow-up PR, i'm working on replacing the tests which add attributions. i've made myself a note to add this assertion there. i don't want to add an entire e2e test right now just for this one assertion.

2023-11-08 10:45 UTC, leslielazzarino commented on src/e2e-tests/__tests__/basic-ui-elements.test.ts
> -  test('displays correct app title', async ({ window }) => {
There you are testing the top bar, not the electron window above.

2023-11-08 10:58 UTC, leslielazzarino approved these changes

2023-11-08 14:02 UTC, mstykow commented on src/Frontend/Components/ProgressBar/FolderProgressBar.tsx
> +    void loadProgressBarData(
we discussed this: using `useMemo` in an unusual way to fix bugs is not self-explanatory. it would be interesting to see where the bug happened and check if a better solution can be found, or at least add some documentation there why `useMemo` is indeed necessary albeit unconventional.

we agreed to follow standard react practices to load/fetch data using side-effects instead of calling a memoization hook.

2023-11-09 06:59 UTC, leslielazzarino approved these changes

2023-11-09 07:49 UTC, merged