Updated docs
opossum-tool/OpossumUI pull request #2247
Opened 2023-11-08 16:13 UTC by vasily-pozdnyakov

### Summary of changes

Updated docs

### How can the changes be tested

See the changed files

2023-11-08 17:15 UTC, mstykow requested changes

2023-11-08 17:15 UTC, mstykow commented on CONTRIBUTING.md
> +**Important:** `wine` must be installed to build a Windows installer on a non-Windows system.
this does not seem to be correct. i'm on a mac and did not have to install wine. also, if you reference an actual library it's probably better to link it instead of just putting it into backticks.

2023-11-09 08:44 UTC, vasily-pozdnyakov commented on CONTRIBUTING.md
> +**Important:** `wine` must be installed to build a Windows installer on a non-Windows system.
good point, we tested it on all the systems and adjusted the guideline accordingly.

2023-11-09 09:11 UTC, mstykow approved these changes

2023-11-09 09:22 UTC, merged