feat: replace audit view tests part 1
opossum-tool/OpossumUI pull request #2257
Opened 2023-11-08 17:28 UTC by mstykow

### Summary of changes

- replace first half of audit view integration tests with E2E tests
- bugfix discovered while testing: properly omit the plus-icon on a package card when the signal it represents is hidden (previously the plus-icon only had hidden visibility but was still clickable)

### Context and reason for change

Part of #2253.

### How can the changes be tested

Run locally and see CI/CD.

2023-11-09 08:23 UTC, mstykow commented on src/Frontend/Components/PackageCard/PackageCard.tsx
> -            ...(props.cardConfig.isResolved ? classes.hiddenIcon : {}),
this is a bug: all we're doing here is made the visibility of the plus-icon hidden but it's still there and thus still clickable. you can see that in the UI when hovering over the empty spot at the beginning of the package card.
thus: i'm now not rendering the plus-icon at all instead to fix this bug.

2023-11-09 14:41 UTC, MarkusObendrauf requested changes
Thanks for this, I love the new style of tests.

Btw, could you try splitting the pr more in the future? I think review time grows quadratically with diff size. To review this I spent a lot of time just trying to figure out which tests were converted to what. Please try to split the next part more or i might just reject it right away

2023-11-09 14:41 UTC, MarkusObendrauf commented on src/e2e-tests/__tests__/using-app-without-a-file.test.ts
> +  await menuBar.assert.showsExpectedTitle();
I would prefer to have `showsTitle("OpossumUI")` or similar here

2023-11-09 15:59 UTC, mstykow commented on src/e2e-tests/utils/fixtures.ts
>    /** Run this function at any point in a test to abort the test at that point and inspect the opossum file. */
because by default the test is executed without any data at all, i.e., no opossum file

2023-11-09 16:00 UTC, mstykow commented on src/e2e-tests/utils/opossum-files.ts
> +  openManually?: boolean;
to me reading `opossumData.openManually` makes sense. but now i'll be deleting this anyway since opening a file is too flaky.

2023-11-09 16:41 UTC, mstykow commented on src/e2e-tests/__tests__/using-app-without-a-file.test.ts
> +  await menuBar.assert.showsExpectedTitle();
done

2023-11-09 16:50 UTC, mstykow commented on src/e2e-tests/__tests__/browsing-resources.test.ts
> +test('shows expected resources as user browses through resources or clicks on progress bar', async ({
i've split it now

2023-11-09 17:03 UTC, mstykow commented on src/Frontend/integration-tests/audit-view-tests/__tests__/audit-view.test.tsx
> -  it('show confidence correctly', () => {
i'm already testing most of this as part of other tests. for example, the assertion that the attribution details are empty/blank also asserts that the confidence is high.
reading through this test one more time just now, there is only one thing i haven't already tested: that the confidence changes to high when you convert a signal to an attribution on a resource. i have made myself a note that i will add this assertion to the tests about adding attributions in general (next PR).

2023-11-10 09:15 UTC, MarkusObendrauf approved these changes
cool, lgtm

2023-11-10 09:15 UTC, MarkusObendrauf commented on src/e2e-tests/playwright.config.ts
> +  retries: process.env.CI ? 1 : 0,
what does this do?

2023-11-10 10:02 UTC, mstykow commented on src/e2e-tests/playwright.config.ts
> +  retries: process.env.CI ? 1 : 0,
it allows one retry per test in the CI pipeline to help combat flakiness.

2023-11-10 10:02 UTC, merged