feat: add popup to warn user if attribution is saved globally that is marked as preferred
opossum-tool/OpossumUI pull request #2263
Opened 2023-11-09 17:14 UTC by alexzurbonsen

### Summary of changes

This PR introduces a new warning popup that is warning the user if changes to an attribution are saved globally and these changes encompass that the attribution is marked as preferred. 

This PR is part of a stack and just adds the popup without wiring it to the code base. Opening the popup and sufficient integration testing follows in the next PRs.

### Context and reason for change

We want to give the user the possibility to globally mark attributions as preferred. But since that should be handled with caution a user should be alerted and asked for confirmation if he saves changes to an attribution globally that include that the attribution is marked as preferred.

This PR introduces the popup. In the next PR saving globally will be enabled and in a subsequent PR the warning popup will be opened. 

### How can the changes be tested

Can't be tested at this stage.

2023-11-09 18:48 UTC, mstykow requested changes
I'm not sure if we want to go the way of having diffs so small that they cannot even be tested. Even with stacked diffs, I would still prefer that the smallest diff is not something that just results in unreachable code.

2023-11-09 18:48 UTC, mstykow commented on src/Frontend/Components/PreferGloballyPopup/PreferGloballyPopup.tsx
> +  const content = 'Do you really want to prefer the attribution globally?';
let's put user-facing text into `text.ts` (i started doing this a few PRs ago).

2023-11-10 08:12 UTC, alexzurbonsen commented on src/Frontend/Components/PreferGloballyPopup/PreferGloballyPopup.tsx
> +  const content = 'Do you really want to prefer the attribution globally?';
sounds like a good idea.

2023-11-10 08:13 UTC, alexzurbonsen commented
I made a small change: renamed the `Apply` button to `Ok` - that was what the ticket actually said.

2023-11-10 08:29 UTC, alexzurbonsen commented
> I'm not sure if we want to go the way of having diffs so small that they cannot even be tested. Even with stacked diffs, I would still prefer that the smallest diff is not something that just results in unreachable code.

Yes, that is a problem. I thought that it might make things potential more reviewable, but without proper tests that expectation doesn't hold. I can also keep adding to this diff, if it is more convenient for you?

2023-11-10 10:32 UTC, alexzurbonsen commented
reopened directly on opossum upstream #2270

2023-11-10 10:32 UTC, closed without merging