feat: replacing audit view tests part 2
opossum-tool/OpossumUI pull request #2264
Opened 2023-11-09 18:34 UTC by mstykow

### Summary of changes

- replace more int by E2E tests
- bugfix discovered while testing: the save globally button became and then remained disabled when a QA user toggled the was-preferred attribute twice although this is an idempotent operation

### Context and reason for change

Part of #2253.

### How can the changes be tested

Run locally and see CI/CD.

2023-11-09 18:53 UTC, mstykow commented on src/Frontend/Components/AttributionColumn/AttributionColumn.tsx
> -    temporaryDisplayPackageInfo.preferred;
there was a bug here: initially we may be comparing `undefined !== undefined` but after toggling the was-preferred attribute twice this would become `undefined !== false` thus disabling the global save button. but a double-toggle is idempotent and the user should thus be returned to the initial state.

2023-11-10 10:35 UTC, MarkusObendrauf requested changes
It's always a good sign when the tests find new bugs!

2023-11-10 10:35 UTC, MarkusObendrauf commented on src/shared/Faker.ts
> +        [faker.string.alpha({ length: 2 })]: this.externalAttributionSource(),
the key here is the essentially an id so it needs to be unique, please add this constraint.

2023-11-10 10:35 UTC, MarkusObendrauf commented on src/e2e-tests/__tests__/saving-attributions.test.ts
> +  );
in `audit-view.test.tsx` line 269, the asssertion was `expectAttributionIsMarkedAsWasPreferred(screen);`. why are we now asserting the opposite?

2023-11-10 12:28 UTC, mstykow commented on src/e2e-tests/__tests__/preferring-attributions.test.ts
> +  await attributionDetails.assert.saveGloballyButtonIsEnabled();
done

2023-11-10 12:29 UTC, mstykow commented on src/shared/Faker.ts
> +        [faker.string.alpha({ length: 2 })]: this.externalAttributionSource(),
since this fallback object only contains a single key uniqueness is guaranteed. but for consistency, i've changed it now to be the name of the source, as also the app would do it like this.

2023-11-10 12:33 UTC, mstykow commented on src/e2e-tests/__tests__/saving-attributions.test.ts
> +  );
i've rewritten, and in my opinion improved, the test slightly. if you check the previous test, it just asserted generally that some grey star is still present at the end. i don't find this assertion as useful as asserting one-by-one that grey stars are disappearing so that at the end of my test all grey stars are gone.

2023-11-10 14:03 UTC, MarkusObendrauf commented on src/shared/Faker.ts
> +        [faker.string.alpha({ length: 2 })]: this.externalAttributionSource(),
oh youre right, diregard that

2023-11-14 11:54 UTC, MarkusObendrauf approved these changes
lgtm

2023-11-14 12:09 UTC, merged