[WIP] feat: enable preferring attribution globally and add warning popup
opossum-tool/OpossumUI pull request #2270
Opened 2023-11-10 10:25 UTC by alexzurbonsen

### Summary of changes

create popup
enable save globally if marked as preferred
open warning popup on save
- save globally button
- via unsaved changes warning
- via menu and hotkey

### Context and reason for change

We want to give the user the possibility to globally mark attributions as preferred. But since that should be handled with caution a user should be alerted and asked for confirmation if he saves changes globally that mark the attribution as preferred.

### How can the changes be tested

Note: Please review the [guidelines for contributing](https://github.com/opossum-tool/OpossumUI/blob/main/CONTRIBUTING.md) to this repository.

2023-11-10 10:31 UTC, alexzurbonsen commented
originated from #2263
This version doesn't use the fork workflow to enable stacking if necessary.

2023-11-11 07:59 UTC, alexzurbonsen commented
The ticket originally said to name the buttons of the warning popup "Ok" and "Cancel". But while implementing it, I changed it to "Yes" instead of "Ok" because the was the more in accordance with the question asked in the popup. And I changed "Cancel" to "Undo" because the current implementation undoes changes, which seemed to be the expected effect to me.

2023-11-11 08:00 UTC, alexzurbonsen commented on src/Frontend/Components/ChangePreferredStatusGloballyPopup/ChangePreferredStatusGloballyPopup.tsx
> +    // TODO I am not sure the deep clone is needed, but might be safer...
still need to figure this out.

2023-11-11 08:03 UTC, alexzurbonsen commented on src/Frontend/integration-tests/audit-view-tests/__tests__/audit-view.test.tsx
> +    // TODO do I really need the next two fields? test is green without them
clarification needed

2023-11-11 08:04 UTC, alexzurbonsen commented on src/Frontend/Components/AttributionColumn/attribution-column-helpers.ts
> -    ? AllowedSaveOperations.Local
I am not sure why the `savingStatus` was computed within this function. It is not tested and I didn't understand it sufficiently to write a test.

2023-11-16 12:21 UTC, alexzurbonsen commented on src/Frontend/Components/AttributionColumn/attribution-column-helpers.ts
> -      : AllowedSaveOperations.All;
I don't know why `savingStatus` was defined here. There is no test for the function and I didn't understand it sufficiently to write one.

2023-11-16 14:49 UTC, alexzurbonsen commented on src/e2e-tests/__tests__/saving-preferred-attributions-globally.test.ts
> +test('marks and unmarks an attribution as preferred globally if user saves globally via button', async ({
With this structure the tests take between 10s-14s for me locally. Seems more suitable.

2023-11-17 14:49 UTC, mstykow requested changes

2023-11-17 14:49 UTC, mstykow commented on src/Frontend/enums/enums.ts
> +  Ok = 'Ok',
we could avoid introducing this new enum value and just use the existing "confirm". together with my other comment, that means the two buttons in the dialog are simply: "confirm" or "cancel". what do you think?

2023-11-17 14:49 UTC, mstykow commented on src/Frontend/Components/ChangePreferredStatusGloballyPopup/ChangePreferredStatusGloballyPopup.tsx
> +        buttonText: ButtonText.Undo,
just now testing your PR, i was suprised that this button is not just a simple "cancel" button.

the dialog here opens, when i press "save globally" so my first thought would have been to either have the option to confirm saving my change globally, or to simply cancel my attempt.

that this button here not only cancels my attempt to save globally but also undoes my change to the preferred state, seems too much to me.

so my suggestion would be to simplify the logic here and just have a simple cancel button. if i as a user really want to undo my change to the preferred attribute, i can do so myself.

2023-11-17 14:49 UTC, mstykow commented on src/e2e-tests/__tests__/saving-preferred-attributions-globally.test.ts
> +  source: { name: externalAttributionSource.name, documentConfidence: 100 },
please use `faker.opossum.source` to build the source. this avoid you needing to hard-code values such as 100 and avoids putting undue importance on specific attributes. right now reading 100, i would wonder if this is essential to the test being green.

2023-11-17 14:49 UTC, mstykow commented on src/e2e-tests/__tests__/saving-preferred-attributions-globally.test.ts
> +test('marks and unmarks an attribution as preferred globally if user saves globally via button', async ({
yes, for me only 5sec.

2023-11-17 14:49 UTC, mstykow commented on src/e2e-tests/__tests__/saving-preferred-attributions-globally.test.ts
> +const resourceName4 = 'resource4';
here you can use this new function: https://github.com/opossum-tool/OpossumUI/pull/2272/files#diff-3df6fa26c7089e828b9b5129bf858d652e646ab294bf10ba6e30b0cb201ebefdR51

2023-11-17 14:49 UTC, mstykow commented on src/e2e-tests/__tests__/saving-preferred-attributions-globally.test.ts
> +test('popup is only shown if necessary and undo reverts preferrence status only', async ({
```suggestion
test('popup is only shown if necessary and undo reverts preference status only', async ({
```

...but this test will change if we no longer actually undo the operation.

2023-11-17 14:49 UTC, mstykow commented on src/e2e-tests/page-objects/ChangePreferredStatusGloballyPopup.ts
> +      expect(innerText).toMatch(regex);
using a regex seems unnecessarily complicated to me. does this not work?
```
await expect(
        this.node.getByText(
          text.changePreferredStatusGloballyPopup.markAsPreferred,
        ),
      ).toBeVisible();
```

2023-11-17 14:49 UTC, mstykow commented on src/e2e-tests/page-objects/PackageCard.ts
> +    return this.node(packageInfo).getByLabel('preferred icon');
here we need to use `exact: true` lest it also matches the "was preferred icon" (see below).

2023-11-17 14:49 UTC, mstykow commented on src/shared/text.ts
> +  changePreferredStatusGloballyPopup: {
👍

2023-11-20 08:46 UTC, alexzurbonsen commented on src/Frontend/enums/enums.ts
> +  Ok = 'Ok',
I discussed the "confirm" option with Benedikt last week. His argument was that "confirm" is used to confirm attributions, i.e. it has a clear meaning that he didn't want to overload. Which seemed reasonable to me.

2023-11-20 08:52 UTC, alexzurbonsen commented on src/Frontend/Components/ChangePreferredStatusGloballyPopup/ChangePreferredStatusGloballyPopup.tsx
> +        buttonText: ButtonText.Undo,
Also discussed that with Benedikt. I initially started off with a cancel button. It can lead to confusion of the user because there is no visual feedback on the preferred status before it was saved.

If you press cancel, afterwards you are in a state where the package card doesn't show any golden star. But the hamburger menu only gives you the option to unmark the attribution as preferred (and the other way around for preferred attributions).

We decided to create the visual feedback first, and then add a cancel button to the popup.

When I played around with it, I also found it convenient to undo the mark when cancelling the save action. Otherwise you have to do two extra clicks to do something you probably want to do anyways.

2023-11-20 08:53 UTC, alexzurbonsen commented on src/Frontend/Components/ChangePreferredStatusGloballyPopup/ChangePreferredStatusGloballyPopup.tsx
> +        buttonText: ButtonText.Undo,
Sorry, I should have mentioned that in the PR somewhere!

2023-11-20 08:54 UTC, alexzurbonsen commented on src/e2e-tests/__tests__/saving-preferred-attributions-globally.test.ts
> +const resourceName4 = 'resource4';
Nice!

2023-11-20 08:56 UTC, alexzurbonsen commented on src/e2e-tests/page-objects/ChangePreferredStatusGloballyPopup.ts
> +      expect(innerText).toMatch(regex);
I didn't work for some reason if I remeber correctly. But I think there would be a better way: Make the aria label depend on the content line of the pop up as well. Then I can simply assert on that?!

2023-11-20 08:56 UTC, alexzurbonsen commented on src/e2e-tests/page-objects/PackageCard.ts
> +    return this.node(packageInfo).getByLabel('preferred icon');
Oh, right...

2023-11-20 08:59 UTC, alexzurbonsen commented on src/e2e-tests/__tests__/saving-preferred-attributions-globally.test.ts
> +test('marks and unmarks an attribution as preferred globally if user saves globally via button', async ({
that's quite a difference :D

2023-11-20 10:16 UTC, alexzurbonsen commented on src/e2e-tests/page-objects/ChangePreferredStatusGloballyPopup.ts
> +      expect(innerText).toMatch(regex);
I checked again. It seems that it didn't work because I forgot the await. (And I didn't forget it in the regex solution.)
I am changing it to what you proposed.

2023-11-21 09:43 UTC, alexzurbonsen commented
another rebase to resolve conflicts.

2023-11-21 11:50 UTC, mstykow commented on src/e2e-tests/page-objects/ChangePreferredStatusGloballyPopup.ts
> +    showsMarkAsPreferredWarning: async (): Promise<void> => {
let's stick with the pattern:
```suggestion
    markAsPreferredWarningIsVisible: async (): Promise<void> => {
```
and similar for the hidden state.

2023-11-21 13:59 UTC, alexzurbonsen commented on src/Frontend/Components/ChangePreferredStatusGloballyPopup/ChangePreferredStatusGloballyPopup.tsx
> +        buttonText: ButtonText.Undo,
Thanks for the discussion. It now is a cancel button that just cancels.

2023-11-21 14:31 UTC, mstykow approved these changes

2023-11-21 14:31 UTC, mstykow commented on src/Frontend/Components/ChangePreferredStatusGloballyPopup/ChangePreferredStatusGloballyPopup.tsx
> +  function handleCancelClick(): void {
could you please create the task here in opossum to display/hide the golden star as the user changes the preferred status via the hamburger/context menu?

2023-11-21 14:38 UTC, alexzurbonsen commented on src/Frontend/Components/ChangePreferredStatusGloballyPopup/ChangePreferredStatusGloballyPopup.tsx
> +  function handleCancelClick(): void {
Sure,  #2330.

2023-11-21 14:40 UTC, merged