feat: replacing audit view tests part 4
opossum-tool/OpossumUI pull request #2271
Opened 2023-11-10 12:49 UTC by mstykow

### Summary of changes

- replace more int by E2E tests
- fix yarn test:changed script (do not run E2E tests with jest)
- remove unnecessary NumberBox from AuditingSubPanel: this number box was only shown in the case when the input was disabled anyways thus defeating its purpose

### Context and reason for change

Closes #2253

### How can the changes be tested

Run locally and see CI/CD.

2023-11-10 12:52 UTC, mstykow commented on src/Frontend/Components/AttributionColumn/AuditingSubPanel.tsx
> -          <NumberBox
i checked all logic paths leading to the rendering of this `NumberBox` and found that it's only shown when the input is disabled anyways. thus, it does not provide any advantage over rendering the usual disabled dropdown.

however, it adds the burden of code maintenance and complicates tests because one needs to assert/interact differently between a dropdown vs. number box.

2023-11-10 12:54 UTC, mstykow commented on jest.config.js
> +  roots: ['<rootDir>/src/Frontend', '<rootDir>/src/ElectronBackend'],
this fixes `yarn test:changed` because E2E tests cannot be run with jest.

2023-11-10 15:44 UTC, meretp requested changes
Looks good to me (just one nitpicking comment from my side) and thanks for the explanatory comments concerning the changes not directly related to the replacement. As discussed I think there is one [test](https://github.com/opossum-tool/OpossumUI/blob/93bd0dac367ef064453434a96ae4818100481139/src/Frontend/integration-tests/audit-view-tests/__tests-ci__/add-to-attribution.test.tsx#L339) missing about adding a merged signal, would be good if you could add this one as well.

2023-11-10 15:44 UTC, meretp commented on src/e2e-tests/__tests__/displaying-attributions.test.ts
> +test('shows aggregated, parent, and merged attributions correctly', async ({
```suggestion
test('shows aggregated, parent and merged attributions correctly', async ({
```

2023-11-10 15:57 UTC, mstykow commented on src/e2e-tests/__tests__/displaying-attributions.test.ts
> +test('shows aggregated, parent, and merged attributions correctly', async ({
https://en.wikipedia.org/wiki/Serial_comma

2023-11-10 16:44 UTC, mstykow commented
> Looks good to me (just one nitpicking comment from my side) and thanks for the explanatory comments concerning the changes not directly related to the replacement. As discussed I think there is one [test](https://github.com/opossum-tool/OpossumUI/blob/93bd0dac367ef064453434a96ae4818100481139/src/Frontend/integration-tests/audit-view-tests/__tests-ci__/add-to-attribution.test.tsx#L339) missing about adding a merged signal, would be good if you could add this one as well.

Thanks for catching that. I've added assertions to ensure that a merged signal which multiple comments, when converted to an attribution, no longer contains any comments.

2023-11-10 16:44 UTC, mstykow commented on src/e2e-tests/__tests__/showing-aggregated-and-parent-attributions.test.ts
> -test('shows aggregated and parent attributions correctly', async ({
the assertions in this test have been integrated into the tests for adding attributions

2023-11-11 15:11 UTC, meretp approved these changes
Looks good to me

2023-11-14 11:55 UTC, merged