Restyle license search in Locator Popup
opossum-tool/OpossumUI pull request #2295
Opened 2023-11-14 17:19 UTC by meretp

### Summary of changes
![image](https://github.com/opossum-tool/OpossumUI/assets/50019307/250c7d84-ae58-4b03-8c65-396c3039d730)
### Context and reason for change

#2266

### How can the changes be tested

Only style changes, green CI shows that the functionality to filter for licenses didn't break.

2023-11-15 08:03 UTC, mstykow requested changes

2023-11-15 08:03 UTC, mstykow commented on src/Frontend/Components/LocatorPopup/LocatorPopup.tsx
the height of the license input field jumps, even when i select only a single license. let's ensure that at least one row of chips fits without any need for height changes of the wrapping input field.

https://github.com/opossum-tool/OpossumUI/assets/46091730/7a8009bc-be7e-4121-953d-6b9c9aa03b99

2023-11-15 15:12 UTC, mstykow requested changes

2023-11-15 15:12 UTC, mstykow commented on src/Frontend/Components/LocatorPopup/LocatorPopup.tsx
> +      height: '25px',
in design circles it is common to make all sizes divisible by 4. only exception usually is 2px.

2023-11-15 15:12 UTC, mstykow commented on src/Frontend/Components/LocatorPopup/LocatorPopup.tsx
> +      height: '25px',
also, the label/placeholder is now no longer vertically centered.

![image](https://github.com/opossum-tool/OpossumUI/assets/46091730/350d5cd3-7733-45b3-a10d-c73530aa8413)

2023-11-16 10:36 UTC, meretp commented on src/Frontend/Components/LocatorPopup/LocatorPopup.tsx
> +      height: '25px',
I tried my best to align this vertically but it seems to me that this is also not centered if I would not set the height. Decreasing the padding for the bottom seems to solve it but feels a bit hacky. If you have another suggestion how to fix it I'm happy to hear it.

2023-11-16 14:12 UTC, mstykow approved these changes

2023-11-16 14:35 UTC, merged