feat: add browser history
opossum-tool/OpossumUI pull request #2301
Opened 2023-11-15 12:24 UTC by mstykow

### Summary of changes

- add buttons to navigate back and forth through resource browser history
- enable navigation via keyboard shortcuts
- enable/disable path bar buttons and show appropriate tooltips instead of hiding them completely
- add tooltip delay to icon buttons to make them feel less jumpy

![image](https://github.com/opossum-tool/OpossumUI/assets/46091730/4db27cb0-9a93-41c1-afd3-6844a9086693)

![image](https://github.com/opossum-tool/OpossumUI/assets/46091730/bfa42d9d-53da-4737-a486-8b4e8032d141)

### Context and reason for change

Closes #2299.

### How can the changes be tested

Use mouse and keyboard to navigate through the browser history. Pay special attention to edge cases such as being at the beginning at the beginning or end of the history stack.

2023-11-15 15:57 UTC, MarkusObendrauf requested changes
Right now, undo could jump to a resource which is not shown in the resource browser. If that happens, it's very hard to find your place. Imo that doesn't need to be fixed in this PR.

2023-11-15 15:57 UTC, MarkusObendrauf commented on src/Frontend/Components/IconButton/IconButton.tsx
> +      enterDelay={1500}
if i first hover somewhere else, eg the top bar, then the hint appears without delay.
also, 1500ms is a bit long imo (maybe that's just personal preference)

2023-11-15 15:57 UTC, MarkusObendrauf commented on src/Frontend/Components/PathBar/PathBar.tsx
> +      setActiveIndex((prev) => prev - 1);
what does `prev` mean here? previous?

2023-11-15 15:57 UTC, MarkusObendrauf commented on src/Frontend/Components/PathBar/PathBar.tsx
> +                activeIndex === history.length - 1
im reading this condition a lot - maybe `isLastHistoryItemActive()` and `isFirstHistoryItemActive()` is nicer?

2023-11-15 16:09 UTC, mstykow commented on src/Frontend/Components/IconButton/IconButton.tsx
> +      enterDelay={1500}
yes, that's intentional: once any tooltip is open, the next one should not wait again.
i picked the duration from what google chrome does on its back/forward buttons.

2023-11-15 16:09 UTC, mstykow commented on src/Frontend/Components/PathBar/PathBar.tsx
> +      setActiveIndex((prev) => prev - 1);
yes

2023-11-15 16:11 UTC, mstykow commented
> Right now, undo could jump to a resource which is not shown in the resource browser. If that happens, it's very hard to find your place. Imo that doesn't need to be fixed in this PR.

Sorry, I'm not understanding this comment. What do you mean by "undo"? Do you mean "go back"? And how can I reproduce what you're saying here: in particular, how can it be that there is a resource that's not part of the resource browser? Do you mean part of the viewport (in case of long lists of resources)?

2023-11-15 16:19 UTC, mstykow commented on src/Frontend/Components/PathBar/PathBar.tsx
> +                activeIndex === history.length - 1
good point. done.

2023-11-15 20:02 UTC, mstykow commented
> > Right now, undo could jump to a resource which is not shown in the resource browser. If that happens, it's very hard to find your place. Imo that doesn't need to be fixed in this PR.
> 
> Sorry, I'm not understanding this comment. What do you mean by "undo"? Do you mean "go back"? And how can I reproduce what you're saying here: in particular, how can it be that there is a resource that's not part of the resource browser? Do you mean part of the viewport (in case of long lists of resources)?

@MarkusObendrauf I think you've discovered a very valid point and I think I created a fix now. Please try again. :)

2023-11-16 08:32 UTC, MarkusObendrauf commented on src/Frontend/Components/IconButton/IconButton.tsx
> +      enterDelay={1500}
TIL chrome has tooltips. but even if we're using chrome as a reference: in chrome, the tooltips for different sections of the UI are not connected.
what makes this really wierd in opossumui is the fact that the progress bar's tooltip appears instantly. so if you move your cursor over the progress bar and then the arrows, the tooltip on the arrow shows instantly.

2023-11-16 08:35 UTC, MarkusObendrauf commented on src/Frontend/Components/PathBar/PathBar.tsx
> +      setActiveIndex((prev) => prev - 1);
i don't understand why it's `prev` and not `current`

2023-11-16 11:55 UTC, mstykow commented
> There are a couple of strange things regarding collapsing folders:
> 
> 1. If you select a resource in a folder, and then collapse that folder, the resource browser scrolls to the top of the screen.
> 2. It's quite difficult to find a resource contained in a collapsed folder. Imo, navigating in history or clicking a breadcrumb should expand the resource tree so that the current resource is shown.

Both issues should be fixed now. Please check again.

2023-11-16 12:05 UTC, mstykow commented on src/Frontend/Components/PathBar/PathBar.tsx
> +      setActiveIndex((prev) => prev - 1);
it's a convention to call this state "previous" or "pending": https://react.dev/reference/react/useState#updating-state-based-on-the-previous-state

i guess one could argue either way. so better just stick to the naming convention they recommend.

2023-11-16 12:08 UTC, mstykow commented on src/Frontend/Components/IconButton/IconButton.tsx
> +      enterDelay={1500}
the instant response you're observing happens, because you move quickly from the progress bar to the icon buttons. if you first pause your mouse somewhere else and then move to the icon buttons, you'll see that the usual 1.5 secs kick in.

i do like that the progress bar tooltip shows up quicker because it actually contains essential information which is not the case for the helper text on the icon buttons. there, a fast tooltip just creates noise because in most cases i already know what that icon button does and don't need to be reminded every time i want to click on it.

i don't think this point is worth discussing much more.

2023-11-16 13:26 UTC, MarkusObendrauf requested changes
Nice! I'm loving the new scrolling and file tree opening. However, if you do both in a single operation, the scroll doesn't work.

2023-11-16 13:26 UTC, MarkusObendrauf commented on src/Frontend/Components/IconButton/IconButton.tsx
> +      enterDelay={1500}
ah i see, theres no problem then :)

2023-11-20 10:13 UTC, MarkusObendrauf requested changes

2023-11-20 10:13 UTC, MarkusObendrauf commented on src/Frontend/util/use-previous.ts
> +export function usePrevious<T>(value: T, fallback?: T): T | undefined {
something went wrong here

2023-11-20 10:26 UTC, mstykow commented on src/Frontend/util/use-previous.ts
> +export function usePrevious<T>(value: T, fallback?: T): T | undefined {
why do you say this? this is how function overloading in typescript looks like.

2023-11-20 11:16 UTC, MarkusObendrauf commented on src/Frontend/util/use-previous.ts
> +export function usePrevious<T>(value: T, fallback?: T): T | undefined {
thx for the explanation

2023-11-20 11:16 UTC, MarkusObendrauf approved these changes
lgtm

2023-11-20 12:42 UTC, merged