Feat improve virtualized list performance
opossum-tool/OpossumUI pull request #2313
Opened 2023-11-17 13:40 UTC by mstykow

### Summary of changes

- memoize expensive calculations and components
- render placeholders for or omit expensive components while scrolling is in progress (inside PackageCard, the left and right icons/elements are expensive)

https://github.com/opossum-tool/OpossumUI/assets/46091730/afd1c381-92c1-4ce1-8ec2-b77f443b2218

### Context and reason for change

Closes #1312.

### How can the changes be tested

Do a before/after comparison as you scroll through the attribution list in attribution view.
Also check other virtualized lists such as the resource browser.

2023-11-20 15:49 UTC, leslielazzarino requested changes
Only minor comments, a great improvement!

2023-11-20 15:49 UTC, leslielazzarino commented on src/Frontend/Components/ListCard/ListCard.tsx
> +  const paddingRight = useMemo(
How do these useMemo help, as when scrolling that specific card does not exist any longer?

2023-11-20 15:49 UTC, leslielazzarino commented on src/Frontend/Components/PackageCard/PackageCard.tsx
> +          rightIcons={useMemo(
I find this use memo a bit too long to be inlined, can you extract it?

2023-11-21 11:42 UTC, mstykow commented on src/Frontend/Components/ListCard/ListCard.tsx
> +  const paddingRight = useMemo(
the calculation is performed on each render. there are many reasons why a re-render may occur and scrolling is just one of them.

2023-11-21 11:44 UTC, mstykow commented
> Only minor comments, a great improvement!

@leslielazzarino please, if you only have minor comments don't block the PR but instead approve it and trust that i'll make the necessary changes.

2023-11-21 12:21 UTC, leslielazzarino approved these changes

2023-11-21 13:03 UTC, merged