feat: improve file opening state
opossum-tool/OpossumUI pull request #2325
Opened 2023-11-21 09:27 UTC by mstykow

### Summary of changes

- replace loading spinner with new popup that displays detailed information about the loading process
- introduce `dayjs` to format dates and times
- create logger class which writes to stdout in the backend but also sends the log to the frontend
- fix `ipcRenderer` subscription mechanism which was not correctly unsubscribing from backend event listeners (the attempt to fix issue #825 in #828 was not correct as it only partly mitigated the problem but didn't fix the underlying cause that `removeListener` was not called on the correct listener)

![image](https://github.com/opossum-tool/OpossumUI/assets/46091730/6bbeb0a8-2156-4148-8da2-ae26c3738b9a)

### Context and reason for change

Closes #2323.

### How can the changes be tested

- Open some files that take longer or shorter to load. Notice that for files that load in less than 270ms, the new dialog should not appear at all (built in delay to avoid flashing).
- Also test that exporting a file for follow-up does not create multiple exports. This is regression for #825.

2023-11-21 10:18 UTC, mstykow commented on src/Frontend/Components/OpenFilePopup/OpenFilePopup.style.ts
I'm using the styled components pattern here as per #2131

2023-11-21 10:22 UTC, mstykow commented on src/ElectronBackend/preload.ts
> -    ipcRenderer.removeAllListeners(channel);
we should not remove all listeners of a particular channel because then we cause race conditions between subscribers: only the last subscriber wins the subscription.
so the "fix" introduced here is actually causing other bugs. the proper fix is to call `.removeListener` on the correct listener. see line 35 below.

2023-11-21 10:24 UTC, mstykow commented on src/ElectronBackend/preload.ts
> -  removeListener,
having a `removeListener` separate from the subscriber (`on`) is the cause of the bug from #825.

2023-11-22 09:55 UTC, leslielazzarino requested changes
Cool popup.

2023-11-22 09:55 UTC, leslielazzarino commented on setupTests.ts
> +// We suppress recharts warning that is due to our mocking in tests.
...the recharts...

2023-11-22 09:55 UTC, leslielazzarino commented on src/ElectronBackend/input/importFromFile.ts
> +  logger.info('Preparing output file');
As there is only one .opossum file, the new messages are a bit confusing. Something like"Writing output to file" and "Reading output from file" would be clearer.

2023-11-22 09:55 UTC, leslielazzarino commented on src/ElectronBackend/input/importFromFile.ts
> +  logger.info('Parsing output file');
Same for this function

2023-11-22 09:55 UTC, leslielazzarino commented on src/ElectronBackend/main/listeners.ts
> +        '~',
This is confusing for a Windows user.

2023-11-22 09:55 UTC, leslielazzarino commented on src/ElectronBackend/input/importFromFile.ts
> +  logger.info('Sanitizing external resources to attributions');
This one was already wrong before, it should have been resources to external attributions. Anyway, the user knows external attributions as signals, so now that it is surfaced, it should read "Sanitizing resources to signals".

2023-11-22 12:30 UTC, mstykow commented on src/ElectronBackend/input/importFromFile.ts
> +  logger.info('Preparing output file');
I agree that speaking of an output file when there is only a .opossum file may be confusing.

I've changed it to just say "preparing output". Reason: at this point we're not writing any output to a file but we're just setting up the output.json inside the .opossum archive.

2023-11-23 08:27 UTC, leslielazzarino approved these changes

2023-11-23 09:41 UTC, merged