fix: correctly display dates in project metadata popup
opossum-tool/OpossumUI pull request #2329
Opened 2023-11-21 12:44 UTC by mstykow

### Summary of changes
- use dayjs to display dates in a user-friendly way
- extend list of expected attributes (automatically trying to parse all strings as dates may lead to false positives)

![image](https://github.com/opossum-tool/OpossumUI/assets/46091730/4730c68a-51f0-4df6-a893-1455c05d05a7)

### Context and reason for change

Closes #2328.

### How can the changes be tested

Open the project metadata popup.

2023-11-22 09:17 UTC, leslielazzarino requested changes

2023-11-22 09:17 UTC, leslielazzarino commented on src/Frontend/Components/ProjectMetadataTable/ProjectMetadataTable.tsx
> +            {Object.entries(projectMetadata).map(([key, value]) => (
I find such inline maps to html pretty  hard to read. Can we keep it extracted?

2023-11-22 09:17 UTC, leslielazzarino commented on src/Frontend/Components/ProjectMetadataTable/ProjectMetadataTable.tsx
> +                          ? dayjs(value).format('lll')
How this date format is defined is not explicit, it would be best to have a comment here, explaining what date format it corresponds to, i.e. MMMM D, YYYY h:mm A

2023-11-22 11:07 UTC, mstykow commented on src/Frontend/Components/ProjectMetadataTable/ProjectMetadataTable.tsx
> +                          ? dayjs(value).format('lll')
First, this is a localized date format and so there is no universal definition.
Second, repeating the definition as a comment almost defeats the purpose of using the shorthand. If somebody needs to know, they should look into the documentation. Also, if the library makes a change, I don't want to be updating all my comments.

2023-11-22 11:10 UTC, mstykow commented on src/Frontend/Components/ProjectMetadataTable/ProjectMetadataTable.tsx
> +            {Object.entries(projectMetadata).map(([key, value]) => (
Sure.

2023-11-23 08:25 UTC, leslielazzarino approved these changes

2023-11-23 09:28 UTC, merged