feat: make project statistics popup optional
opossum-tool/OpossumUI pull request #2352
Opened 2023-11-23 16:42 UTC by mstykow

### Summary of changes
- introduce electron app user settings
- allow user to toggle preference of showing project statistic on startup
- create state and hook for using a redux-persisted variable
- create hook for working with user settings
- create CLI arg to start app without project statistics and use it to simplify E2E tests

### Context and reason for change
Closes #2351 .

### How can the changes be tested
Change the new checkbox inside the project statistics popup and observe the effect when opening a file.

2023-11-23 16:46 UTC, mstykow commented on src/ElectronBackend/main/__tests__/main.test.ts
> -  it('calls ipc handler', async () => {
this test did nothing more than assert that a certain line of code existed. in my opinion, this kind of test does not add to my confidence that the functionality of the app is as expected and merely makes it harder for me to work with/refactor the code.

it is also rather uncommon to unit test the main entry point to an electron app. probably better done using E2E tests.

2023-11-24 10:52 UTC, MarkusObendrauf approved these changes
Looks good, I just have some questions

2023-11-24 10:52 UTC, MarkusObendrauf commented on src/Frontend/Components/ProjectStatisticsPopup/ProjectStatisticsPopup.tsx
> +          disabled={!hydrated}
what's this?

2023-11-24 10:52 UTC, MarkusObendrauf commented on src/Frontend/test-helpers/render-component-with-store.tsx
> +/* eslint-disable @typescript-eslint/explicit-function-return-type */
is this intentional?

2023-11-24 10:52 UTC, MarkusObendrauf commented on src/Frontend/test-helpers/render-component-with-store.tsx
> +}
i dont understand what this function does, could you explain it for me?

2023-11-24 10:52 UTC, MarkusObendrauf commented on src/Frontend/util/__tests__/use-user-setting.test.ts
> +    await waitFor(() => expect(result.current[2]).toBe(true));
what's `result.current[2]`? I don't understand at all what result is

2023-11-24 16:03 UTC, mstykow commented on src/Frontend/Components/ProjectStatisticsPopup/ProjectStatisticsPopup.tsx
> +          disabled={!hydrated}
retrieving user settings from the file system is an asynchronous process. the `hydrated` flag indicates that the process has completed because other processes can/should not be blocked by the disk read operation. but until hydration is complete we also don't want to allow the user to make a change.

2023-11-24 16:03 UTC, mstykow commented on src/Frontend/test-helpers/render-component-with-store.tsx
> +/* eslint-disable @typescript-eslint/explicit-function-return-type */
yes it was, but since the linter changes no longer necessary so it's gone now.

2023-11-24 16:05 UTC, mstykow commented on src/Frontend/test-helpers/render-component-with-store.tsx
> +}
yes: react-testing-library offers a tool for testing hooks without needing to render them inside a component. but we often need a context around the hook, such as the redux store. so this function here combines the RTL `renderHook` tool with our custom context which ATM is just the redux provider. we can extend this function in the future if need be.

2023-11-24 16:07 UTC, mstykow commented on src/Frontend/util/__tests__/use-user-setting.test.ts
> +    await waitFor(() => expect(result.current[2]).toBe(true));
the `result` is the return value of the hook we're testing. `result.current` is this value at the time that `current` is called. since the hook returns `[value, setValue, hydrated]`, `result.current[2]` is the value of `hydrated` at the time this line of code is executed.

2023-11-24 16:15 UTC, MarkusObendrauf requested changes

2023-11-24 16:15 UTC, MarkusObendrauf commented on src/Frontend/util/__tests__/use-user-setting.test.ts
> +    await waitFor(() => expect(result.current[2]).toBe(true));
I really don't like that, please make it more cleat in the code

2023-11-24 16:26 UTC, MarkusObendrauf approved these changes

2023-11-24 16:26 UTC, merged