Add bash script to check out a PR and directly open a file in OpossumUI
opossum-tool/OpossumUI pull request #2360
Opened 2023-11-28 09:02 UTC by meretp

### Summary of changes

This PR adds a script to make development easier. 
```
Usage: ./tools/checkout_PR_and_start_opossum_ui.sh [OPTIONS]
Options:
 -p, Set the number of the PR to use
 -c, Set the commit hash to use
 -n, Set the name of the remote, default: origin
 -f, Set absolute path to file which should be opened
 -o, Checkout only, don't open the app
Note: either use -c or -p
Note: The script assumes to be run in the root directory of a local clone of the original repo

```

### Context and reason for change

This script should help developers to test changes on large files,

### How can the changes be tested
Play around with the script.
Note that you need to store a duplicate of the script (for example change the name and don't add it to Git afterwards) as the script will check out a different PR where this script no  longer exists. Run e.g.
`./tools/checkout_PR_and_start_opossum_ui.sh -p 2359 -f ./example-files/opossum_input.json` . See that the respective PR is checked out and the OpossumUI is opened with the provided file.

2023-11-28 09:03 UTC, meretp commented on tools/checkout_PR_and_start_opossum_ui.sh
I decided to put the script in a tools directory as this seems to be best practice (see https://medium.com/code-factory-berlin/github-repository-structure-best-practices-248e6effc405 and https://backrightup.com/blog/how-to-organize-github-repositories/)

2023-11-28 15:44 UTC, mstykow requested changes

2023-11-29 18:41 UTC, meretp commented on tools/checkout_PR_and_start_opossum_ui.sh
I agree "yet another folder" containing only one script is not the best approach. Concerning the naming I feel like we have two clashing opinions here (see https://github.com/opossum-tool/OpossumUI/pull/2207#discussion_r1395544931) but imho the best solution with respect to the content of the blogposts is to put the script in the yarn_scripts folder and name it tools.

2023-11-30 08:12 UTC, mstykow approved these changes

2023-11-30 08:57 UTC, merged