feat: create package autocompletes
opossum-tool/OpossumUI pull request #2371
Opened 2023-12-04 10:38 UTC by mstykow

### Summary of changes

- enforce import of custom faker via linter
- create generic Autocomplete component
- create specific PackageAutocomplete component
- replace MuiAutocomplete in LocatorPopup with new generic Autocomplete
- properly hide icon button instead of only applying hidden visibility (which means the button is still interactive by mouse and keyboard)
- add util for pluralizing nouns

![image](https://github.com/opossum-tool/OpossumUI/assets/46091730/442e87fb-e378-437e-90b3-6d7194012457)

![image](https://github.com/opossum-tool/OpossumUI/assets/46091730/d142320f-91d2-4931-92c2-7196d693d82f)

![image](https://github.com/opossum-tool/OpossumUI/assets/46091730/b00f6a10-3d9c-4bdc-8383-93682f27ba74)

### Context and reason for change

#2343 

### How can the changes be tested

Test all input fields that involve autocompletes:
- package name
- package type (also contains defaults)
- package version
- package namespace
- license (also contains defaults)
- locator popup

2023-12-04 16:11 UTC, MarkusObendrauf requested changes
Feature is cool

One small bug:
1. fill in the license name
2. unselect the license name field
3. click on the license name field
I expect the suggestions to be filtered, but they are not.

2023-12-04 16:11 UTC, MarkusObendrauf commented on src/Frontend/Components/AttributionColumn/PackageAutocomplete.tsx
> +      }, []);
again, please extract! and i dont like the choice to use reduce, i dont find it elegant here and think a for loop is easier

2023-12-04 17:27 UTC, mstykow commented on src/Frontend/util/maybe-pluralize.ts
> +    before = '',
ok, i guess this abstraction isn't strictly necessary or that helpful

2023-12-04 17:31 UTC, mstykow commented on src/Frontend/Components/Autocomplete/Autocomplete.tsx
> +export function Autocomplete<
i've extracted the props into a separate type now. that should improve the situation.

2023-12-04 17:36 UTC, mstykow commented on src/Frontend/Components/Autocomplete/Autocomplete.tsx
> +  | 'renderOption'
because these props have already been set by me to make the component look exactly like i need it to look in opossumUI. i don't want the user of my component to be able to use these props as part of the component's API as it would destroy the way i want the component to work/look/feel in opossumUI.

what i'm doing here is quite standard for anyone familiar with building component libraries. i think i mentioned [storybook](https://storybook.js.org/) to you the other day?

2023-12-04 17:38 UTC, mstykow commented on src/Frontend/Components/Autocomplete/Autocomplete.tsx
> +}) {
no, i don't believe in putting return types on every single function. i want to leverage typescript's auto-inference in certain situations. when it comes to react components there is really not much gained by giving them a return type since react can handle pretty much anything. especially, we should not use `React.ReactElement` because that means we wouldn't be able to return `null` which is actually quite common in react components under certain auspices.

2023-12-04 18:19 UTC, mstykow commented on src/Frontend/Components/Autocomplete/Autocomplete.tsx
> +      ) => (
good point. i've extracted most of the styling into separate styled components and even a separate file now.

2023-12-04 18:29 UTC, mstykow commented on src/Frontend/Components/Autocomplete/__tests__/Autocomplete.test.tsx
> +      expect(screen.queryByText(option)).not.toBeInTheDocument();
faker internally uses a randomizer with a high enough entropy that we can safely generate 5 strings without a clash. that, plus faker also internally keeps track of the number of calls to ensure that subsequent calls don't produce the same result.

2023-12-04 19:32 UTC, mstykow commented on src/Frontend/Components/AttributionColumn/LicenseSubPanel.tsx
> +  const frequentLicensesNames = useAppSelector(getFrequentLicensesNameOrder);
good catch. i've sorted alphabetically now, here and also in the locator popup.

2023-12-04 19:33 UTC, mstykow commented on src/shared/text.ts
> +    useAutocompleteSuggestion: 'Adopt all coordinates from suggestion',
this becomes clear when you look at the UI:
![image](https://github.com/opossum-tool/OpossumUI/assets/46091730/50f8b2c2-4937-47f4-a9a8-a19b68e0c81a)

2023-12-04 19:34 UTC, mstykow commented on src/Frontend/Components/AttributionColumn/PackageAutocomplete.tsx
> +            event.stopPropagation();
the icon button is rendered on top of a list item which itself has a click handler. by using `stopPropagation`, you prevent the icon button click event to also trigger the list item click event.

2023-12-04 19:36 UTC, mstykow commented on src/Frontend/Components/AttributionColumn/PackageAutocomplete.tsx
> +    signals: useMemo(() => {
i don't see how i would gain anything from that. right now, i can see very clearly how `signals` are calculated. by extracting this hook, i then have to jump through the code base to follow the code wherever it got extracted to, for one, and i also need to introduce some complicated interface of passing all the props around that i would need to put into this function.

2023-12-04 19:36 UTC, mstykow commented on src/Frontend/Components/AttributionColumn/PackageAutocomplete.tsx
> +      const getUniqKey = (item: PackageInfo) =>
sure

2023-12-04 19:37 UTC, mstykow commented on src/Frontend/Components/AttributionColumn/PackageAutocomplete.tsx
> +function useSignals({ attribute }: Pick<Props, 'attribute'>) {
same answer as above: there is nothing complicated before the `useMemo` (just some selectors accessing the state), and the actual function inside `useMemo` is not getting simpler by extracting it.

2023-12-04 19:39 UTC, mstykow commented on src/Frontend/Components/AttributionColumn/PackageAutocomplete.tsx
> +      }, []);
whether `reduce` is elegant or not is a matter of opinion, i suppose. the fact is that it's exactly the right tool for the job (though of course there may be other ways of arriving at the goal).

as for me, i don't want to use a for loop here because then i'd have to mutate an array and i prefer writing immutable code.

2023-12-04 19:42 UTC, mstykow commented
> Feature is cool
> 
> One small bug:
> 
> 1. fill in the license name
> 2. unselect the license name field
> 3. click on the license name field
>    I expect the suggestions to be filtered, but they are not.

this is intentional. i want the user to be able to still see all options in case they want to change their opinion. if i were to only show the current selection when the dropdown opens, i'd then have to delete my input to be able to see more choices again.

2023-12-05 13:02 UTC, MarkusObendrauf commented
> > Feature is cool
> > One small bug:
> > 
> > 1. fill in the license name
> > 2. unselect the license name field
> > 3. click on the license name field
> >    I expect the suggestions to be filtered, but they are not.
> 
> this is intentional. i want the user to be able to still see all options in case they want to change their opinion. if i were to only show the current selection when the dropdown opens, i'd then have to delete my input to be able to see more choices again.

Alright, makes sense

2023-12-12 16:45 UTC, merged