fix: include all resources attached to an attribution when preferring globally
opossum-tool/OpossumUI pull request #2374
Opened 2023-12-04 13:13 UTC by alexzurbonsen

### Summary of changes

Use all resources that an attribution is attached to when computing the preferred over ids for that attribution if it gets preferred globally.

### Context and reason for change

Fixes #2370 

### How can the changes be tested

Added unit test.

2023-12-04 20:16 UTC, mstykow requested changes
Thank you for creating this separate PR and associated issue. I understand the problem now. However, could you also explain why the current behavior needs fixing at all? After all, if this bug cannot be seen inside OpossumUI then at what point is there actually any issue at all?

2023-12-04 20:16 UTC, mstykow commented on src/Frontend/state/actions/resource-actions/__tests__/preference-actions.test.ts
> +    const pathFile2 = `/${file2}`;
the e2e tests had the same problem of needing to create file paths from resource names. that's why faker actually provides a method `.filePath`. all you have to do is put the resource names into it where needed.

2023-12-04 20:16 UTC, mstykow commented on src/Frontend/state/actions/resource-actions/__tests__/preference-actions.test.ts
> +    const resources: Resources = faker.opossum.resources({
the function is already fully typed so there is no need for re-declaring the type
```suggestion
    const resources = faker.opossum.resources({
```

2023-12-04 20:16 UTC, mstykow commented on src/Frontend/state/actions/resource-actions/__tests__/preference-actions.test.ts
> +    const testSource = faker.opossum.source();
we don't gain anything by prefixing variables in test with "test" or "mock".
```suggestion
    const testSource = faker.opossum.source();
```

2023-12-04 20:16 UTC, mstykow commented on src/Frontend/state/actions/resource-actions/__tests__/preference-actions.test.ts
> +    const expectedOriginUuids = [originUuid1, originUuid2];
why not just inline this in the next line?

2023-12-04 20:16 UTC, mstykow commented on src/Frontend/state/actions/resource-actions/__tests__/preference-actions.test.ts
> +    const actualOriginUuids = getOriginIdsToPreferOver(
how about just inlining this in the assertion? so
```
expect(getOriginIdsToPreferOver(...)).toEqual([..., ...])
```

2023-12-04 20:16 UTC, mstykow commented on src/Frontend/state/actions/resource-actions/preference-actions.ts
> +export function setOriginIdsToPreferOverGlobally(
it's fine. you're following the established pattern...

2023-12-04 20:16 UTC, mstykow commented on src/Frontend/state/actions/resource-actions/preference-actions.ts
> +    const newTemporaryDisplayPackageInfo = cloneDeep(packageInfo);
i don't think we need to clone anything deeply here, do we? could this work as well?
```
dispatch(
      setTemporaryDisplayPackageInfo({
        ...packageInfo,
        preferredOverOriginIds: getOriginIdsToPreferOver(
          getResourceIdsOfSelectedAttribution(state) ?? [],
          getResources(state) ?? {},
          getResourcesToExternalAttributions(state),
          getResourcesToManualAttributions(state),
          getExternalAttributions(state),
          getExternalAttributionSources(state),
        ),
      }),
    );
```

2023-12-05 09:04 UTC, alexzurbonsen commented on src/Frontend/state/actions/resource-actions/__tests__/preference-actions.test.ts
> +    const testSource = faker.opossum.source();
true, was a left over of the old test naming conventions...

2023-12-05 09:15 UTC, alexzurbonsen commented on src/Frontend/state/actions/resource-actions/preference-actions.ts
> +    const newTemporaryDisplayPackageInfo = cloneDeep(packageInfo);
I wasn't sure either. My assumption was that it is not necessary but then I wasn't sure I understood enough of react hooks and if this change could trigger any rerendering etc. I then followed the example from the action `toggleIsSelectedPackagePreferred`.

2023-12-05 11:12 UTC, alexzurbonsen commented on src/Frontend/state/actions/resource-actions/preference-actions.ts
> +    const newTemporaryDisplayPackageInfo = cloneDeep(packageInfo);
Though about it again, and I think I am a bit confused about what changing a field in an object can actually trigger... In case there is anything to keep in mind, should we have a short chat? Otherwise I would just remove the deepclone.

2023-12-06 08:48 UTC, merged