fix: warn user of unsaved changes if file is opened via button in top bar
opossum-tool/OpossumUI pull request #2378
Opened 2023-12-04 18:53 UTC by alexzurbonsen

### Summary of changes

The user is warned about unsaved changes if he clicks the "open file" button in the top bar.
Buttons of the warning popup show the following behaviour:
Cancel -> changes are not saved and open file dialog is not displayed
Undo -> changes are discarded and open file dialog is displayed
Save -> popups that apply are shown (was preferred or prefer globally warning), changes are saved eventually and open file dialog is displayed in the end

### Context and reason for change

Closes #2234.

This is a full solution for the bug described in #2234 but only a partial solution to the problem. There is also the possibility to open a file via the menu. But this is handled entirely in the backend currently and would require som more changes if we want to handle it in the same way.

### How can the changes be tested

2023-12-05 16:49 UTC, alexzurbonsen commented on src/e2e-tests/__tests__/saving-attributions.test.ts
> +test.use({
is it okay to redeclare test data in a file or is that a sign to move the test to a new file?

2023-12-07 20:45 UTC, mstykow approved these changes

2023-12-07 20:45 UTC, mstykow commented on src/e2e-tests/__tests__/open-file-warnings.test.ts
> +  wasPreferred: true,
why is this test also mixing in the `wasPreferred` attribute? if this is important, i'd say we should mention something about it in the test title. if it's not important, i'd suggest to simplify the test by removing this attribute here.

2023-12-07 20:45 UTC, mstykow commented on src/e2e-tests/__tests__/open-file-warnings.test.ts
> +  count: 4,
```suggestion
  count: 2,
```

2023-12-07 20:45 UTC, mstykow commented on src/e2e-tests/__tests__/open-file-warnings.test.ts
> +const [attributionId1, packageInfo1] = faker.opossum.manualAttribution({
nitpick:
```suggestion
const [attributionId, packageInfo] = faker.opossum.manualAttribution({
```

2023-12-07 20:50 UTC, mstykow requested changes

2023-12-07 20:50 UTC, mstykow commented on src/Frontend/state/actions/popup-actions/popup-actions.ts
> +      dispatch(setOpenFileRequest(false));
isn't there a problem here? what if the popup opens but i click cancel. then `openFileRequest` in the reducer remains `true` although no open-file request is is progress any longer.

so the next time i have unsaved changes and just want to navigate somewhere without opening a file, the open-file dialog will still appear.

2023-12-08 09:10 UTC, alexzurbonsen commented on src/Frontend/state/actions/popup-actions/popup-actions.ts
> +      dispatch(setOpenFileRequest(false));
Oh yes, you are right...

2023-12-08 09:20 UTC, alexzurbonsen commented on src/Frontend/state/actions/popup-actions/popup-actions.ts
> +      dispatch(setOpenFileRequest(false));
Added the same logic to the cancel handler that is called in all the popups involved in saving (NotSaved, ModifyWasPreferred, ChangePreferredGlobally).

2023-12-08 09:23 UTC, alexzurbonsen commented on src/e2e-tests/__tests__/open-file-warnings.test.ts
> +  wasPreferred: true,
I thought it might be valueable to test if the process is working if a "follow up" popup is shown after the not saved popup. Setting `wasPreferred` is an easy way to do it.
I will clarify the test title.

2023-12-08 13:03 UTC, mstykow approved these changes

2023-12-08 13:03 UTC, mstykow commented on src/e2e-tests/__tests__/open-file-warnings.test.ts
> +  packageType: undefined,
is it important the package type is undefined here? if not, i'd say we also remove this line.
same with the licenses: it seems that we don't need them. by defining them we're making it seem like the test somehow depends on this setup.

2023-12-08 13:03 UTC, mstykow commented on src/Frontend/state/actions/popup-actions/popup-actions.ts
> +    if (openFileRequest) {
is this if-check really necessary? it seems we could always set the value back to false.

2023-12-08 17:14 UTC, alexzurbonsen commented on src/Frontend/state/actions/popup-actions/popup-actions.ts
> +    if (openFileRequest) {
True, that may be better.

2023-12-08 17:14 UTC, alexzurbonsen commented on src/e2e-tests/__tests__/open-file-warnings.test.ts
> +  packageType: undefined,
Copy paste... sorry.

2023-12-12 08:25 UTC, merged