Add multiselect in place of checkbox for the filters
opossum-tool/OpossumUI pull request #239
Opened 2021-12-02 09:44 UTC by mayayunx

### Summary of changes

- Add new Filter component for the multiselect and replace the checkbox
- implement the filtering logic with the new component

### Context and reason for change

- Filters for only first party and hide first party are required 

### How can the changes be tested

- run `yarn test:unit`, `yarn test:integration-ci`, `yarn test:e2e` and test in the UI

2021-12-02 10:36 UTC, nicarl commented on src/Frontend/Components/AttributionView/AttributionView.tsx
> +          <Filter
Maybe `FilterForm` or `FilterMutliSelect` is a better component name

2021-12-02 10:36 UTC, nicarl commented on src/Frontend/Components/AttributionView/AttributionView.tsx
> +  const { handleFilterChange, getFilteredAttributions } = provideFilters(
Optional: I think this could actually be a custom hook.

2021-12-02 10:36 UTC, nicarl commented on src/Frontend/Components/Filter/Filter.tsx
> +  return (
It is really hard to distinguish the component from the background. Maybe we can play with background colors a bit?

2021-12-02 10:36 UTC, nicarl commented on src/Frontend/Components/Filter/Filter.tsx
> +      filterName.indexOf(filter) === -1
What is the motivation to increase the fontweight for unknown filters? Does it ever happen?

2021-12-02 10:36 UTC, nicarl commented on src/Frontend/Components/Filter/Filter.tsx
> +  selected: string[];
`selectedFilters`

2021-12-02 10:36 UTC, nicarl commented on src/Frontend/Components/Filter/Filter.tsx
> +          data-testid="multiple-chip"
Do we need this?

2021-12-02 10:36 UTC, nicarl commented on src/Frontend/Components/Filter/Filter.tsx
> +          input={<MuiOutlinedInput id="select-multiple-chip" label="Chip" />}
Do we need the id here?

2021-12-02 10:36 UTC, nicarl commented on src/Frontend/Components/Filter/Filter.tsx
> +                    selected.splice(selected.indexOf(value), 1);
Could be moved to an `onDelete` function.

2021-12-02 10:36 UTC, nicarl commented on src/Frontend/Components/Filter/Filter.tsx
> +  const [filterName, setFilters] = React.useState<string[]>([]);
Do we actually needs this? The props contain this somehow.

2021-12-02 10:36 UTC, nicarl commented on src/Frontend/Components/Filter/Filter.tsx
> +  };
This logic is rather complicated. We on the ordering and indexes which makes it tough to understand. Instead of using a list as a data structure it might be better to come up with something else.
A set or an object containing `[filterName :string]: boolean` would be an idea?

2021-12-02 10:36 UTC, nicarl commented on src/Frontend/Components/ReportView/ReportView.tsx
> +          <Filter
Could be 
`<Filter ... />`

2021-12-02 10:47 UTC, mayayunx commented on src/Frontend/Components/Filter/Filter.tsx
> +          data-testid="multiple-chip"
data-testid is used in the test helper function for opening dropdow. But labelId can be removed.

2021-12-02 12:07 UTC, benedikt-richter commented
The styling seems to be broken

![Screenshot 2021-12-02 at 13 06 53](https://user-images.githubusercontent.com/46576389/144419055-c14aa434-183c-4d60-989d-e7c2890babcd.png)

2021-12-02 12:19 UTC, mayayunx commented on src/Frontend/Components/Filter/Filter.tsx
> +      filterName.indexOf(filter) === -1
You are right, it was from the MUI documentation for multiple select and I forgot to delete it

2021-12-02 12:22 UTC, benedikt-richter commented on src/Frontend/Components/AttributionView/AttributionView.tsx
>    );
I agree with Nico. This should be a custom hook and be called like

`const { handleFilterChange, getFilteredAttributions } = useFilters()`

2021-12-02 12:22 UTC, benedikt-richter commented on src/Frontend/Components/AttributionView/AttributionView.tsx
> +          <Filter
`FilterMultiSelect` sounds nice

2021-12-02 12:24 UTC, benedikt-richter commented on src/Frontend/Components/AttributionView/AttributionView.tsx
> +            selected={Array.from(activeFilters)}
There seems to be no need to convert the set to an array here

2021-12-02 12:25 UTC, benedikt-richter commented on src/Frontend/Components/AttributionView/AttributionView.tsx
> +            updateFilter={handleFilterChange}
`updateFilter` could be called `handleFilterChange`

2021-12-02 12:26 UTC, benedikt-richter commented on src/Frontend/Components/Filter/Filter.tsx
> +};
Would be nice to use `useStyles` like in the other components

2021-12-02 12:26 UTC, benedikt-richter commented on src/Frontend/Components/Filter/Filter.tsx
> +}
Would be nice to use `useStyles` like in the other components

2021-12-02 12:26 UTC, benedikt-richter commented on src/Frontend/Components/Filter/Filter.tsx
> +];
could be ALL_CAPS

2021-12-02 12:27 UTC, benedikt-richter commented on src/Frontend/Components/Filter/Filter.tsx
> +  selected: string[];
`string[]` -> `Array<string>`

2021-12-02 12:27 UTC, benedikt-richter commented on src/Frontend/Components/Filter/Filter.tsx
> +  selected: string[];
or actually `set<string>` (see comment above)

2021-12-02 12:32 UTC, mayayunx commented on src/Frontend/Components/AttributionView/AttributionView.tsx
> +            selected={Array.from(activeFilters)}
I get an error "Type 'Set<FilterType>' is missing the following properties from type 'string[]': length, pop, push, concat, and 24 more." if I don't convert it

2021-12-02 12:45 UTC, benedikt-richter commented
Looking at the current state. I'd like to suggest to create a custom hook

`const getFilteredAttributions = useFilters()`

to be used in AttributionView and in ReportView.

All the logic regarding mutually exclusive filters and related stuff can be in the `FilterMultiSelect`.

2021-12-02 13:06 UTC, benedikt-richter requested changes
comments

2021-12-06 14:00 UTC, nicarl commented on src/Frontend/Components/Filter/FilterMultiSelect.tsx
> +  return (
This is much easier to digest than the previous version :-) 
I just have some remaining comments concerning the styling:
- I think the width of the `FilterMultiSelect` should be constant. Adding the first filter changes its width
- the position of the `FilterMultiSelect` changes when two elements are selected
- the height of the filter and overall size of the elements in the filter is quite large compared to the heading in `Attribution` view. Maybe we can reduce it a bit?
- the top margin in `Report` view could be a bit larger

2021-12-08 09:44 UTC, benedikt-richter commented on src/Frontend/Components/Filter/FilterMultiSelect.tsx
> +    <div>
do we need this div?

2021-12-08 09:44 UTC, benedikt-richter commented on src/Frontend/Components/Filter/FilterMultiSelect.tsx
> +        <MuiInputLabel id="multiple-chip-label">Filter</MuiInputLabel>
do we need this id?

2021-12-08 09:45 UTC, benedikt-richter commented on src/Frontend/Components/Filter/FilterMultiSelect.tsx
> +          data-testid="multiple-chip"
can we name this `test-id-filter-multi-select`?

2021-12-08 09:45 UTC, benedikt-richter commented on src/Frontend/Components/Filter/FilterMultiSelect.tsx
> +          input={<MuiOutlinedInput label="Chip" />}
do we need this label?

2021-12-08 09:46 UTC, benedikt-richter commented on src/Frontend/Components/Filter/FilterMultiSelect.tsx
> +              },
would be nice to extract

2021-12-08 09:46 UTC, benedikt-richter commented on src/Frontend/Components/Filter/FilterMultiSelect.tsx
> +            </MuiMenuItem>
could be extracted into something like `getMenuItems`

2021-12-08 09:47 UTC, benedikt-richter commented on src/Frontend/Components/Filter/FilterMultiSelect.tsx
> +                updateFilters(event.currentTarget.textContent as FilterType);
would be great to avoid type cast

2021-12-08 09:47 UTC, benedikt-richter commented on src/Frontend/Components/Filter/FilterMultiSelect.tsx
> +              aria-label={filter}
is this aria-label needed?

2021-12-08 09:47 UTC, benedikt-richter commented on src/Frontend/Components/Filter/FilterMultiSelect.tsx
> +export function FilterMultiSelect(): ReactElement {
nice 👍

2021-12-08 09:48 UTC, benedikt-richter commented on src/Frontend/Components/InputElements/shared.ts
> +  dropDownField: {
seems not to be shared

2021-12-08 09:48 UTC, benedikt-richter commented on src/Frontend/Components/ReportView/ReportView.tsx
>            ) as AttributionsWithResources
can this type cast be avoided?

2021-12-08 09:56 UTC, benedikt-richter commented on src/Frontend/util/use-filters.ts
> +): AttributionsWithResources | Attributions {
should be 

```

export function useFilters(
  attributions: AttributionsWithResources
): AttributionsWithResources;
export function useFilters(attributions: Attributions): Attributions;
export function useFilters(
  attributions: AttributionsWithResources | Attributions
): AttributionsWithResources | Attributions {

```

2021-12-08 09:56 UTC, benedikt-richter commented on src/Frontend/util/use-filters.ts
> +): AttributionsWithResources | Attributions {
This is the correct typing

2021-12-08 09:56 UTC, benedikt-richter requested changes
some minor points

2021-12-08 10:50 UTC, mayayunx commented on src/Frontend/Components/Filter/FilterMultiSelect.tsx
> +              aria-label={filter}
yes, it is used in the function `expectFilterIsShown` in the `FilterMultiSelect.test.tsx`

2021-12-08 14:30 UTC, benedikt-richter approved these changes
nice 👍 

just squash commits before merging

2021-12-08 14:59 UTC, nicarl approved these changes
Nice, thanks for fixing the styling. I only have one suggestion for function renaming.

2021-12-08 14:59 UTC, nicarl commented on src/Frontend/Components/Filter/FilterMultiSelect.tsx
> +  function getMenuItems(filter: FilterType): ReactElement {
I think `getMenuItem` is more appropriate as function name

2021-12-08 16:04 UTC, merged