feat: Create SPDX document and add it to release
opossum-tool/OpossumUI pull request #2421
Opened 2023-12-14 16:31 UTC by antonbauhofer

Create an SPDX document for the project and add it to the release

### Summary of changes

- Add the Yarn plugin [@yarnpkg/plugin-spdx](https://github.com/spdx/yarn-plugin-spdx)
- Use the plugin in CI/CD workflow `publish-release` to generate an SPDX document for the project and add it to the release
- Use the plugin in CI/CD workflow `build-and-e2e-test`

### Context and reason for change

It is desirable for the OpossumUI releases to contain an SBOM document.

### How can the changes be tested

Run the command `yarn spdx` verify that an SPDX document with the name opossum-ui.spdx.json is created in the root of the project and inspect it.
To visualize the generated document, the [SPDX Python tooling](https://github.com/spdx/tools-python) can be used. To do so, use the command pyspdxtools -I <local path to generated spdx document> --graph -o <output path>.
![opossum-ui](https://github.com/opossum-tool/OpossumUI/assets/48415604/cb6a736f-8638-427f-bbb8-fb4295a97d3e)

### Note

The generated SPDX document is currently invalid because the dependency `babel-plugin-transform-import-meta` has the license `BSD` declared, which is not in the [SPDX license list](https://spdx.org/licenses/).
There is a ticket for this in the plugin implementation: https://github.com/spdx/yarn-plugin-spdx/issues/12
We should wait for this to be fixed before landing this PR.

Note: Please review the [guidelines for contributing](https://github.com/opossum-tool/OpossumUI/blob/main/CONTRIBUTING.md) to this repository.

2023-12-14 18:25 UTC, mstykow commented
@antonbauhofer how can i tell that the SPDX doc is invalid, as you say? i would have expected an error to occur in the pipeline here telling me that `babel-plugin-transform-import-meta` uses an unexpected license.

2023-12-18 09:40 UTC, antonbauhofer commented
> @antonbauhofer how can i tell that the SPDX doc is invalid, as you say? i would have expected an error to occur in the pipeline here telling me that `babel-plugin-transform-import-meta` uses an unexpected license.

The plugin itself does currently not validate the created SPDX documents (at least not completely). So, the pipeline only verifies, that the creation of the SPDX document is successful and not the validity of the document itself.
To check the validity of the SPDX document, one can for example use the [SPDX Python tooling](https://github.com/spdx/tools-python).
For now, I think we can still use it as it is (an invalid SPDX document is still better than none).
This issue will be fixed in the future in the [@spdx/tools](https://github.com/spdx/tools-ts) library that the yarn plugin uses.

2023-12-18 15:27 UTC, antonbauhofer commented
Issue for the feature request that would make the SPDX document valid: 
https://github.com/spdx/tools-ts/issues/227

2023-12-18 15:45 UTC, mstykow approved these changes

2023-12-19 08:20 UTC, maxhbr requested changes
Please fix the copyright.

2023-12-19 08:20 UTC, maxhbr commented on .yarn/plugins/@yarnpkg/plugin-spdx.cjs
> +// SPDX-FileCopyrightText: Meta Platforms, Inc. and its affiliates
this are the wrong copyrights. This should just be `//  SPDX-FileCopyrightText: 2023 SPDX contributors`, as it just contains IP from SPDX.

2023-12-19 08:20 UTC, maxhbr commented on .github/workflows/build-and-e2e-test.yml
> +      - run: yarn spdx
Why is it ran in the `e2e-test` without any assertions or check?

2023-12-19 09:34 UTC, antonbauhofer commented on .github/workflows/build-and-e2e-test.yml
> +      - run: yarn spdx
The idea here was to verify that running the command `yarn spdx` does not fail (same as `yarn ship:auto`).
It would be nice to validate the created document here, but at this point I think it would be overkill to use another tool for validation.
Alternatively, we could also remove it from here.
What do you think?

2023-12-19 09:37 UTC, maxhbr commented on .github/workflows/build-and-e2e-test.yml
> +      - run: yarn spdx
You could validate that the expected file exists or that the file contains the name of the opossum tool. But might not be necessary.

2023-12-19 09:38 UTC, antonbauhofer commented on .yarn/plugins/@yarnpkg/plugin-spdx.cjs
> +// SPDX-FileCopyrightText: Meta Platforms, Inc. and its affiliates
So, the complete header will then be

// SPDX-FileCopyrightText: 2023 SPDX contributors
//
// SPDX-License-Identifier: MIT

Since the plugin is licensed under MIT.
Consequently, we then need to add MIT to the licenses.

Do you agree?

2023-12-19 09:40 UTC, antonbauhofer commented on .github/workflows/build-and-e2e-test.yml
> +      - run: yarn spdx
Sounds good. I'll do that 👍

2023-12-19 13:49 UTC, maxhbr approved these changes
LGTM

2023-12-19 14:23 UTC, merged