feat: sort signals by criticality
opossum-tool/OpossumUI pull request #2457
Opened 2024-01-03 11:20 UTC by antonbauhofer

### Summary of changes

- add toggle state for critical signals progress bar to store
- extend sorting algorithm to consider criticality
- extend test of sorting

### Context and reason for change

There is highlighting for critical signals but before this change it was still hard to find critical signals in long lists of signals coming from e.g. ScanCode.

### How can the changes be tested

Open an input file that contains critical signals and look at the sorting.

2024-01-03 13:54 UTC, MarkusObendrauf submitted a review, later dismissed
You've introduced a new `progressBarCriticalityState` but we don't actually use it anywhere besides the `TopProgressBar` itself - so what is the advantage of this over `useState<boolean>(false);`?

iirc the requirement was that we sort by criticality only if the criticality bar is selected, in which case the global state is needed.

2024-01-04 10:57 UTC, antonbauhofer commented
> You've introduced a new `progressBarCriticalityState` but we don't actually use it anywhere besides the `TopProgressBar` itself - so what is the advantage of this over `useState<boolean>(false);`?
> 
> iirc the requirement was that we sort by criticality only if the criticality bar is selected, in which case the global state is needed.

I have fixed it, so that the sorting is only applied when the critical progress bar is toggled.

2024-01-04 11:34 UTC, mstykow requested changes
There are multiple high-level issues with this PR:
1. Please read the task description again. It says there that both the LOCAL and GLOBAL tabs should be sorted by criticality. At the moment, only the LOCAL tab is sorted.
2. Reading the task description, also the attribution view should sort by criticality.
3. I find it unintuitive that the progress bar toggle affects the sorting. The two seem unrelated and I doubt that I would understand this behavior, especially as a less experienced user. In addition, there is no progress bar in attribution view so that clearly the sorting can/should not depend on the toggle. Perhaps we can have a call how to handle this.

2024-01-05 18:05 UTC, mstykow commented on src/Frontend/Components/AttributionList/AttributionList.tsx
> +  sortingElement?: JSX.Element | null;
i just refactored the `AttributionList` component to simplify it in another PR.
could you please rebase this PR to #2471 and then also add a test like this one here? https://github.com/opossum-tool/OpossumUI/pull/2471/files#diff-98e02d5e99b935f7b1ee96ffec1851a973d193b0430ae82865411e07780c6877R20

2024-01-08 09:29 UTC, mstykow requested changes

2024-01-08 09:29 UTC, mstykow commented on src/Frontend/web-workers/signals-worker.ts
> +          sortByCriticality: this.state.sortingByCriticalityIsActive,
maybe we can also rename the attribute inside the state to have the simpler name `sortByCriticality`

2024-01-08 13:15 UTC, antonbauhofer commented on src/Frontend/Components/AttributionList/AttributionList.tsx
> +  sortingElement?: JSX.Element | null;
I rebased it an added an integration test as suggested.

2024-01-08 13:20 UTC, antonbauhofer commented on src/Frontend/Components/ResourceDetailsTabs/ResourceDetailsTabs.tsx
> +    setShowSortingSelect(!showSortingSelect);
Great suggestion! Actually that simplifies it to just setting the initial value to `!defaultSortingIsActive`.

2024-01-08 13:28 UTC, antonbauhofer commented on src/Frontend/Components/AllAttributionsPanel/AllAttributionsPanel.tsx
> +  const [activeSorting] = useVariable(
Extracted it to utils.

2024-01-08 13:53 UTC, antonbauhofer commented on src/Frontend/util/__tests__/get-alphabetical-comparer.test.tsx
> +        copyright: 'Copyright John Doe',
I replaced it with fakers, but left the basic test structure in place. I also left the additional infos in to test that those do not influence the sorting behavior.

2024-01-09 08:45 UTC, closed without merging