feat: offer multiple sorting options for attributions
opossum-tool/OpossumUI pull request #2481
Opened 2024-01-09 15:41 UTC by antonbauhofer

Summary of changes

add toggle state for critical signals progress bar to store
extend sorting algorithm to consider criticality
extend test of sorting
Context and reason for change

There is highlighting for critical signals but before this change it was still hard to find critical signals in long lists of signals coming from e.g. ScanCode.

How can the changes be tested

Open an input file that contains critical signals and look at the sorting.

2024-01-09 15:45 UTC, antonbauhofer commented on src/Frontend/Components/AllAttributionsPanel/AllAttributionsPanel.tsx
> +  );
[Original comment](https://github.com/opossum-tool/OpossumUI/pull/2478/files#r1445875580)
this doesn't seem right: in the case that we are not sorting by criticality we are now sorting alphabetically here although before your changes no sorting was necessary at all.

2024-01-09 15:46 UTC, antonbauhofer commented on src/Frontend/Components/AllAttributionsPanel/AllAttributionsPanel.tsx
> +  );
Correct, before this pull request we didn't sort the attributions at this point. I think, however, that this was a bug or at least not the desired behavior, so I decided to introduce sorting in any case.

2024-01-09 15:51 UTC, antonbauhofer commented on src/Frontend/Components/AttributionList/AttributionList.tsx
> +  }
[original comment](https://github.com/opossum-tool/OpossumUI/pull/2478/files#r1446222486)
i think we talked about how we wanted to move this logic into the initial value of useState to avoid unnecessary setting of state on each render.

2024-01-09 15:51 UTC, antonbauhofer commented on src/Frontend/Components/AttributionList/AttributionList.tsx
> +  }
Correct. I fixed this in the ResourceDetailsTab, but overlooked it here. Will fix it.

2024-01-09 16:03 UTC, antonbauhofer commented on src/Frontend/Components/AttributionList/AttributionList.tsx
> +        </MuiBox>
[original comment](https://github.com/opossum-tool/OpossumUI/pull/2478/files/9d4b63197be8331fba5026be9f794c6ce9f550f4#r1446225129)
we're taking up a lot of vertical space now and also the padding between the elements is not equal. i think we should fix at least the basic layout/padding. the fact that we're taking up so much space i'll fix later in #2480.

i also suggest we just write "sorting" without "algorithm"

2024-01-09 16:03 UTC, antonbauhofer commented on src/Frontend/Components/AttributionList/AttributionList.tsx
> +        </MuiBox>
I fixed the padding and removed "algorithm".

2024-01-09 16:07 UTC, antonbauhofer commented on src/Frontend/util/use-active-sorting.ts
> +export function useActiveSorting(): [
[original comment](https://github.com/opossum-tool/OpossumUI/pull/2478#discussion_r1445862711)
i think we said you'd change the naming here so that it reflects the fact that this sorting is only used in audit view.
please remove the return type annotation on both of these hooks. they are just repeating the annotation of useVariable which means that if useVariable is refactored, we'd break the typing here for no good reason because this function is nothing but a thin wrapper around useVariable.
Member
Author
@[antonbauhofer](https://github.com/antonbauhofer) antonbauhofer [43 minutes ago](https://github.com/opossum-tool/OpossumUI/pull/2481/files#discussion_r1446234493)
Without the type annotation the type checker was not happy.
Member
@[mstykow](https://github.com/mstykow) mstykow [41 minutes ago](https://github.com/opossum-tool/OpossumUI/pull/2481/files#discussion_r1446237584)
this is again just a local problem on your end, i believe
Member
Author
@[antonbauhofer](https://github.com/antonbauhofer) antonbauhofer [10 minutes ago](https://github.com/opossum-tool/OpossumUI/pull/2481/files#discussion_r1446280319)
Fixed the naming, but it the typing problem remains, if I remove the annotations, even though I fixed the local setup.

2024-01-09 20:13 UTC, mstykow commented on src/Frontend/util/use-active-sorting.ts
> +export function useActiveSorting(): [
ah, you need to write `as const` behind the returned array. then you can delete the annotation. by doing so, you're telling typescript not to widen the type which was causing the error.

2024-01-09 20:59 UTC, mstykow requested changes

2024-01-09 20:59 UTC, mstykow commented on src/Frontend/Components/AttributionList/AttributionList.tsx
> +            tooltipTitle="Sort"
please extract user-facing text

2024-01-09 20:59 UTC, mstykow commented on src/Frontend/Components/AttributionList/AttributionList.tsx
> +            tooltipTitle={'Filters'}
extract please since you're touching it

2024-01-09 20:59 UTC, mstykow commented on src/Frontend/Components/ResourceDetailsTabs/ResourceDetailsTabs.tsx
> +          tooltipTitle="Choose sorting algorithm for the displayed signals"
extract...

2024-01-09 20:59 UTC, mstykow commented on src/Frontend/Components/ResourceDetailsTabs/ResourceDetailsTabs.tsx
> +                  : classes.largeClickableIcon
it would be easier to understand code if you simply drop the `!` and turn the ternary around

2024-01-09 20:59 UTC, mstykow commented on src/shared/text.ts
> +    search: 'Search signals by name, license name, copyright text and version',
better to group semantically than by technical function. so this would be part of "attributionColumn".

2024-01-10 07:32 UTC, antonbauhofer commented on src/Frontend/util/use-active-sorting.ts
> +export function useActiveSorting(): [
Implemented it as suggested.

2024-01-10 07:51 UTC, antonbauhofer commented on src/shared/text.ts
> +    search: 'Search signals by name, license name, copyright text and version',
Changed it as suggested. However, I don't quite agree with you here. The name "attributionColumn" indicates grouping the texts by components. Hence, we will either eventually end up defining the same text multiple times or using texts from other components. The name "tooltips", on the other hand, can be understood as the user-facing behavior in the frontend. So these texts could, for example be used for the tooltips in the auditView and in the attributionView.

2024-01-10 07:56 UTC, mstykow commented on src/shared/text.ts
> +    search: 'Search signals by name, license name, copyright text and version',
yes, good point. one needs to see if the text is reused or not. it seems to me this one is not. what do you think?

2024-01-10 08:11 UTC, mstykow approved these changes

2024-01-10 08:11 UTC, mstykow commented on src/shared/text.ts
> +    sortTooltip: 'Sort',
I think it would be better to say "Sorting" here because then we match the noun "Filter" instead of using the verb "sort".

2024-01-10 08:18 UTC, antonbauhofer commented on src/shared/text.ts
> +    search: 'Search signals by name, license name, copyright text and version',
In this case it probably doesn't matter, since we are using different texts anyway. But in general I don't think that it is a good idea to start grouping the texts by components.

2024-01-10 08:33 UTC, mstykow commented on src/shared/text.ts
> +    sortTooltip: 'Sort',
ok, but it currently says "filters", not "filter"

2024-01-10 09:28 UTC, antonbauhofer commented on src/shared/text.ts
> +    sortTooltip: 'Sort',
I removed the "s"

2024-01-10 10:03 UTC, merged