Sort package cards by displayed title
opossum-tool/OpossumUI pull request #252
Opened 2021-12-08 14:53 UTC by jonas-tai

### Summary of changes

Change package card sorting to sort by displayed title (first line).

### Context and reason for change

The sorting in the attribution lists only compared the package names of the attribution to sort the attributions. This was confusing for the user, because the card displays additional / different information, depending on the available information (e.g. package name and package version combined, only the comment, ...). This commit adds a sorting by the first line that is displayed in the package card. Empty attributions are sorted to the bottom.

### How can the changes be tested

Run tests in get-alphabetical-comparer.test.tsx or test with input file.

2021-12-08 14:57 UTC, benedikt-richter commented on src/Frontend/util/get-alphabetical-comparer.ts
> +import { getCardLabels } from '../Components/PackageCard/package-card-helpers';
As ´getCardLabels´is used in utils it should be moved to utils itself

2021-12-08 15:08 UTC, benedikt-richter commented on src/Frontend/util/get-alphabetical-comparer.ts
> +        : defaultName;
could be extracted into something like `getElementTitle(element:string) => string` and used twice here

2021-12-08 15:10 UTC, benedikt-richter requested changes
works nicely. Just some ideas for refactoring.

Also it might be nice to sort letters before e.g. `(` in order to have the packages that display copyrights a la `(c)` last

2021-12-08 17:13 UTC, jonas-tai commented
> works nicely. Just some ideas for refactoring.
> 
> Also it might be nice to sort letters before e.g. `(` in order to have the packages that display copyrights a la `(c)` last

I changed the sorting logic to sort special characters after strings (empty attributions still last).

2021-12-09 07:06 UTC, benedikt-richter approved these changes

2021-12-10 13:55 UTC, FlorianSchepers approved these changes

2021-12-13 07:08 UTC, benedikt-richter commented on src/Frontend/util/__tests__/get-alphabetical-comparer.test.tsx
>          copyright: '(C) Copyright John Doe',
It would be sorted behind. The motivation is to list attributions with no package name but only copyright after attributions with package name

2021-12-13 07:09 UTC, benedikt-richter commented on src/Frontend/util/__tests__/get-alphabetical-comparer.test.tsx
> +        copyright: 'John Doe',
The idea here is to sort according to what the user sees such that sorting feature is transparent to the user.

2021-12-13 07:10 UTC, benedikt-richter commented on src/Frontend/util/get-alphabetical-comparer.ts
> +    return elementTitle.localeCompare(otherElementTitle, undefined, {
For now the second line is not used for sorting. In case we encounter cases where there are many attributions with identical first line this would be anatural improvement.

2021-12-13 07:10 UTC, merged