feat: add static diff popup
opossum-tool/OpossumUI pull request #2521
Opened 2024-01-23 11:04 UTC by alexzurbonsen

Displays origin and current package info without highlighting colours or revert functionality

### Summary of changes

### Context and reason for change

#2488 

### How can the changes be tested

2024-01-24 20:23 UTC, alexzurbonsen commented on src/Frontend/Components/AttributionColumn/ButtonRow.tsx
> +    // TODO unpacking just tricks the compiler? asserting non-null is not allowed by linter rule
still to be solved...

2024-01-25 15:06 UTC, mstykow commented on src/Frontend/Components/DiffPopup/DiffPopup.tsx
> +function DiffView(props: DiffViewProps): ReactElement {
it's not great having multiple react comps inside the same file. if you really think it's worth extracting this, then let's do it properly and create a sub-folder of `DiffPopup` for a component called `DiffView`.

alternatively, you could inline this component at the end of `DiffPopup` as a function that starts with the word "render", as I've done for example in `AttributionList.tsx`. this has the advantage, that you can access all the parent's variables directly without needing to define yet another interface like the one in line 31.

when the component is small-ish, as it is in your case, i personally prefer this latter option.

2024-01-25 15:08 UTC, mstykow commented on src/Frontend/enums/enums.ts
> +  Grey = 'Grey',
do we still need this? i thought you are using `visiblity: none` now.

2024-01-25 15:08 UTC, mstykow commented on src/Frontend/enums/enums.ts
> +  RevertAll = 'Revert all',
using this enum is deprecated in favor of the `text.ts` file. i should probably open a PR to mark it as such but in the meanwhile, please move your new user-facing texts to that file instead.

2024-01-25 15:10 UTC, mstykow commented on src/Frontend/Components/AttributionColumn/AuditingOptions.tsx
> +  isDiffView?: boolean;
this prop is too specific for a component that knows nothing about a "diff view". instead, please introduce an `sx` prop that you can use as the parent to set `flex: 1`.

this comment applies also to the other sub-components where you introduced this prop.

2024-01-25 15:12 UTC, mstykow commented on src/Frontend/Components/AttributionColumn/ButtonRow.tsx
> +    // TODO unpacking just tricks the compiler? asserting non-null is not allowed by linter rule
there is no need for a trick here. both the compare button and the diff popup should not be rendered when the original package info does not exist. so you're missing if statements that return null when there is no such package info.

2024-01-25 15:16 UTC, mstykow commented on src/Frontend/Components/AttributionColumn/CopyrightSubPanel.tsx
> +  isDiffView,
here, a diff-view-agnostic name for this prop could be "expanded".

maybe even better: create a prop called "variant" which has the three options `'default' | 'expanded' | 'hidden'` then you don't need to introduce two separate, but related, props.

2024-01-25 15:20 UTC, mstykow commented on src/Frontend/Components/AttributionColumn/AttributionForm.tsx
> +            isHidden={true}
you can see here that something is quite confusing about the new props: if the component is always hidden, why would i need to render it at all?

2024-01-25 15:21 UTC, mstykow commented on src/Frontend/Components/AttributionColumn/AttributionForm.tsx
> +      {props.packageInfo.firstParty && props.isDiffView ? (
introducing this second but related ternary to the one in line 66 is making the code hard to understand. i think once you change your props to use the `variant` i suggested in another comment, you won't need this entire block anymore.

2024-01-25 16:40 UTC, alexzurbonsen commented on src/Frontend/Components/DiffPopup/DiffPopup.tsx
> +const classes = {
Sure, I was wondering about that at some point but must have forgotten.

2024-01-25 16:41 UTC, alexzurbonsen commented on src/Frontend/enums/enums.ts
> +  Grey = 'Grey',
Right. Oversight on my side.

2024-01-25 16:43 UTC, alexzurbonsen commented on src/Frontend/Components/AttributionColumn/AttributionForm.tsx
> +            isHidden={true}
True, that is hidden in the if statement around it.

2024-01-25 17:09 UTC, alexzurbonsen commented on src/Frontend/Components/AttributionColumn/AuditingOptions.tsx
> +  isDiffView?: boolean;
Good idea.

2024-01-25 18:55 UTC, alexzurbonsen commented on src/Frontend/Components/AttributionColumn/CopyrightSubPanel.tsx
> +  isDiffView,
good point.

2024-01-26 11:40 UTC, mstykow requested changes

2024-01-26 11:40 UTC, mstykow commented on src/shared/text.ts
> +    revertAll: 'Revert all',
i would prefer if we create a new object "diffPopup" here instead of merging these diff-popup-specific texts with the generic "buttons" object.

2024-01-26 11:40 UTC, mstykow commented on src/Frontend/Components/DiffPopup/DiffPopup.tsx
> +          label={'diff displayed'}
"displayed"? i don't quite understand that term. do you mean "current"?

2024-01-26 11:40 UTC, mstykow commented on src/Frontend/Components/DiffPopup/DiffPopup.tsx
> +            comments: undefined,
this seems hacky and unnecessary: in diff view, the attribution form already does not render any comments. so why do i need to set them to undefined here?

2024-01-26 11:40 UTC, mstykow commented on src/Frontend/Components/AttributionColumn/AttributionForm.tsx
> +function getVariant({
instead of extracting this function outside the FC, defining (repeating) variables names and types, and calling it multiple times, i'd put it inside the component and wrap it in a `useMemo`. in fact, you then don't need a function at all since it'll be a memoized constant.

2024-01-26 11:40 UTC, mstykow commented on src/Frontend/Components/AttributionColumn/AttributionForm.tsx
> +        {...(props.isDiffView ? { sx: { flexGrow: 1 } } : {})}
```suggestion
        sx={{ flex: props.isDiffView ? 1 : undefined }}
```

2024-01-26 11:40 UTC, mstykow commented on src/Frontend/Components/DiffPopup/DiffPopup.tsx
> +export function DiffPopup(props: DiffPopupProps): ReactElement {
```suggestion
export function DiffPopup(props: DiffPopupProps) {
```

2024-01-26 11:40 UTC, mstykow commented on src/Frontend/Components/DiffPopup/DiffPopup.tsx
> +  packageInfosForDiff: DiffViewProps;
```suggestion
  original: DisplayPackageInfo;
  current: DisplayPackageInfo;
  ...
```

2024-01-26 11:40 UTC, mstykow commented on src/Frontend/Components/DiffPopup/DiffPopup.tsx
> +import { Dispatch, ReactElement, SetStateAction } from 'react';
since these are all types, the import is unnecessary if you write `React.X` everywhere instead (global namespace).

2024-01-26 11:40 UTC, mstykow commented on src/Frontend/Components/AttributionColumn/PackageAutocomplete.tsx
> +  temporaryPackageInfo: DisplayPackageInfo;
i don't think we gain much by calling this "temporary".
```suggestion
  packageInfo: DisplayPackageInfo;
```

2024-01-26 11:40 UTC, mstykow commented on src/Frontend/Components/AttributionColumn/ButtonRow.tsx
> +  const [openDiffPopup, setOpenDiffPopup] = useState(false);
"openDiffPopup" sounds like an action but it's actually a boolean. i could see either "isDiffPopupOpen" or "diffPopupOpen".

2024-01-26 11:40 UTC, mstykow commented on src/Frontend/Components/AttributionColumn/ButtonRow.tsx
> +      const originDisplayedPackageInfo = convertPackageInfoToDisplayPackageInfo(
could you do this conversion as part of the `useMemo` above?

2024-01-26 11:40 UTC, mstykow commented on src/Frontend/Components/AttributionColumn/AuditingOptions.tsx
> +        sx={[
```suggestion
        sx={{...classes.container, ...sx}}
```

2024-01-26 11:40 UTC, mstykow commented on src/shared/shared-types.ts
> +export type VariantProp =
this variant is specific to the attribution form and thus deserves a specific name such as "AttributionFormVariant". also, this folder is not the right one for it since the `src/shared` folder is for shared stuff across all parts of the repo but you only need this type as part of the frontend.
since this type belongs to the attribution form, why not just keep it there and import from there instead of putting it into such a high-level shared place?

2024-01-26 15:16 UTC, alexzurbonsen commented on src/shared/text.ts
> +    revertAll: 'Revert all',
Okay :)

2024-01-26 15:17 UTC, alexzurbonsen commented on src/Frontend/Components/DiffPopup/DiffPopup.tsx
> +          label={'diff displayed'}
Yes. I am distinguishing `original` and `displayed` (which is the currently displayed package info). At some point I thought that was more clear, but I don't mind to change this.

2024-01-26 15:43 UTC, alexzurbonsen commented on src/Frontend/Components/DiffPopup/DiffPopup.tsx
> +            comments: undefined,
Right. Good catch.

2024-01-26 16:31 UTC, alexzurbonsen commented on src/Frontend/Components/DiffPopup/DiffPopup.tsx
> +import { Dispatch, ReactElement, SetStateAction } from 'react';
What is the advantage of doing that by the way? As I mentioned in another PR, my IDE always displays a warning about usage of global variables.

2024-01-26 16:32 UTC, alexzurbonsen commented on src/Frontend/Components/AttributionColumn/PackageAutocomplete.tsx
> +  temporaryPackageInfo: DisplayPackageInfo;
True.

2024-01-26 16:42 UTC, alexzurbonsen commented on src/Frontend/Components/AttributionColumn/AuditingOptions.tsx
> +        sx={[
I looked this up and they said it is the recommended way to do it because `sx` can be an array. But at least the compiler does not complain, seems to work.

2024-01-26 16:45 UTC, alexzurbonsen commented on src/shared/shared-types.ts
> +export type VariantProp =
Sounds reasonable. For some reason I thought that was a pattern that we used. But now it doesn't seem so reasonable to me either. Moved it.

2024-01-26 16:50 UTC, alexzurbonsen commented on src/shared/shared-types.ts
> +export type VariantProp =
About the naming: the two components that use it are Copyright- and LicenseSubPanel. Are you okay with `PanelVariantProp`? I named it such for now.

2024-01-27 12:24 UTC, mstykow commented on src/shared/text.ts
> +    revertAll: 'Revert all',
some of my comments are opinionated. feel free to disagree!

2024-01-27 12:26 UTC, mstykow commented on src/Frontend/Components/DiffPopup/DiffPopup.tsx
> +export function DiffPopup(props: DiffPopupProps): ReactElement {
btw: what you did is of course not incorrect. it's just my opinionated suggestion to make my life easier in future refactorings, for example if suddenly the component returns null in a certain situation i'll have to touch this line for no good reason since the actual return value of an FC is `React.ReactNode` which is wider than `React.ReactElement`. but instead of arguing over the correct return type, why not ignore it completely since it doesn't add much value. it's almost like saying that the function can return anything...

2024-01-27 12:27 UTC, mstykow commented on src/Frontend/Components/DiffPopup/DiffPopup.tsx
> +import { Dispatch, ReactElement, SetStateAction } from 'react';
again, my opinionated suggestion. i personally prefer to write fewer lines of code and not deal with adding/removing or re-ordering imports. so if i don't _need_ to import something, why would i? it would be good if you could find out why your IDE is complaining. is it not correctly configured or does it actually think it's an antipattern to use the global namespace?

2024-01-27 12:29 UTC, mstykow commented on src/Frontend/Components/AttributionColumn/AuditingOptions.tsx
> +        sx={[
yes, i saw the MUI docs too but it's just so much simpler doing it this way...

2024-01-29 08:00 UTC, mstykow requested changes

2024-01-29 09:18 UTC, alexzurbonsen commented on src/shared/text.ts
> +    revertAll: 'Revert all',
I think it is good idea to start this way. As long as the buttons are all next to each other it should be fine.

2024-01-29 10:13 UTC, alexzurbonsen commented on src/Frontend/Components/AttributionColumn/ButtonRow.tsx
> +      : undefined;
We decided to always show the button if there is a diff for two reasons:
- stability of the UI, no buttons jump around
- hidding it when there is no diff, means that the button can be hidden for two reasons. Either there is no origin or no changes were made. This may be confusing to the user who is not sure whether the attribution was edited already.

2024-01-30 11:53 UTC, merged