feat: add revert functionality to diff popup
opossum-tool/OpossumUI pull request #2557
Opened 2024-02-06 15:01 UTC by alexzurbonsen

### Summary of changes

This diff adds revert functionality to the diff popup. Every field that is changed compared to the original value, can be reverted individually with a button. You can also restore the modified value again with a redo button, that replaces the revert/undo button once the change was reverted.

We decided to not show the auditing options in the Diff popup since they are related to a manual attribution and not to a signal.

We also decided to always show license and copyright fields, also in the first party case. 

### Context and reason for change

Story: https://github.com/opossum-tool/OpossumUI/issues/2488

Closes https://github.com/opossum-tool/OpossumUI/issues/2515

### How can the changes be tested

Adapted unit tests. 
Added e2e tests.

Manually play around with the new feature and test if it behaves as expected.

2024-02-06 16:08 UTC, alexzurbonsen commented on src/Frontend/Components/AttributionColumn/AttributionForm.util.tsx
> +// SPDX-FileCopyrightText: Meta Platforms, Inc. and its affiliates
Introduced this file to resolve the circular dependency chain I had.

Previously the types were in `AttritbutionForm.tsx` and `getComparableAttributes` was in `DiffPopup.util.tsx`.
That resulted in a circular dependency because AttributionForm was importing from DiffPopup.util via AuditingOptions.util and DiffPopup.util was importing from AttributionForm.

2024-02-06 16:11 UTC, alexzurbonsen commented on src/Frontend/Components/DiffPopup/DiffPopup.util.tsx
> +  }, [isOpen, current, setBufferPackageInfo]);
I kept the `useEffect` for now. The only other way I found to update the state when the popup is opened was forcing a re-mount via the key prop. If we want to do that we would probably want to do something like `key={someHashFunction(getComparableAttributes(packageInfo))}`.

2024-02-07 09:52 UTC, mstykow requested changes

2024-02-07 09:52 UTC, mstykow commented on src/Frontend/Components/AttributionColumn/LicenseSubPanel.tsx
> +              ) : packageInfo.licenseText ? (
```suggestion
              config?.licenseName?.endIcon || packageInfo.licenseText ? (
```

2024-02-07 09:52 UTC, mstykow commented on src/Frontend/Components/AttributionColumn/LicenseSubPanel.tsx
> +            }
```suggestion
            endIcon={config?.licenseText?.endIcon}
```

2024-02-07 09:52 UTC, mstykow commented on src/Frontend/Components/AttributionColumn/PackageSubPanel.tsx
> +        }
```suggestion
        endAdornment={config?.packageName?.endIcon}
```

2024-02-07 09:52 UTC, mstykow commented on src/Frontend/Components/AttributionColumn/PackageSubPanel.tsx
> +        }
```suggestion
        endAdornment={config?.packageNamespace?.endIcon}
```

2024-02-07 09:52 UTC, mstykow commented on src/Frontend/Components/AttributionColumn/PackageSubPanel.tsx
> +        }
```suggestion
        endAdornment={config?.packageVersion?.endIcon}
```

2024-02-07 09:52 UTC, mstykow commented on src/Frontend/Components/AttributionColumn/PackageSubPanel.tsx
> +        }
```suggestion
        endAdornment={config?.packageType?.endIcon}
```

2024-02-07 09:52 UTC, mstykow commented on src/Frontend/Components/AttributionColumn/PackageSubPanel.tsx
> +          ) : (
```suggestion
          config?.url?.endIcon || (
```

2024-02-07 09:52 UTC, mstykow commented on src/Frontend/Components/DiffPopup/DiffPopup.tsx
> +      buffer.wasPreferred = true;
this is a cardinal error in react: you are mutating state that's managed by `useState`. this means react has no idea a change occurred and thus cannot display the most recent state. the only reason we don't see errors is because immediately after this mutation you're unmounting the component that manages the state, but any refactoring to the code will introduce bugs and spooky-action-at-a-distance outside the react framework.

mutation of reactive state must be avoided at all cost. in this situation, you'd use the spread operator inside `setTemporaryDisplayPackageInfo`.

2024-02-07 09:52 UTC, mstykow commented on src/Frontend/Components/DiffPopup/DiffPopup.tsx
> +        ),
this is the same check as in line 73-76. i suggest we extract into a named const.

2024-02-07 09:52 UTC, mstykow commented on src/Frontend/Components/DiffPopup/DiffPopup.tsx
> +          setOpen(false);
not a fan of these long names that already don't make sense anymore as soon as i refactor the code even just slightly.
let's rename `checkIfWasPreferredAndLicenseInfoResetNecessaryAndApply` to `handleApplyChanges` and include `setOpen(false)` in it.

2024-02-07 09:52 UTC, mstykow commented on src/Frontend/Components/DiffPopup/DiffPopup.tsx
> +            ...FORM_ATTRIBUTES.reduce(
there is no need for the spread operator here, i.e., we don't need to make a copy of the return value of `reduce`.

2024-02-07 09:52 UTC, mstykow commented on src/Frontend/Components/DiffPopup/DiffPopup.tsx
> +        },
this will do the job without type errors or accidentally mutating reactive state:
```suggestion
        onClick: () => {
          setBufferPackageInfo({
            ...bufferPackageInfo,
            ...FORM_ATTRIBUTES.reduce(
              (acc, attribute) => ({
                ...acc,
                [attribute]: original[attribute],
              }),
              {},
            ),
          });
        },
```

2024-02-07 09:52 UTC, mstykow commented on src/Frontend/Components/DiffPopup/DiffPopup.util.tsx
> +) {
please use object notation for the arguments. reading `getEndIcon('undo', 'foo', () => {}, 'small')` is not very helpful when it comes to function signatures and forces me to look up the order of the arguments, or worse, make a mistake confusing them. same as kwargs in python...

2024-02-07 09:52 UTC, mstykow commented on src/Frontend/Components/DiffPopup/DiffPopup.util.tsx
> +        )
To reduce the number of lines of code unnecessarily repeated, I suggest initially defining:
```
const Icon = variant === 'undo' ? UndoIcon : RedoIcon
```

2024-02-07 09:52 UTC, mstykow commented on src/Frontend/Components/DiffPopup/DiffPopup.util.tsx
> +function getEndIcon(
this is actually a full-blooded react component. so why not extract it into a separate sub-component (file) and just call it `DiffEndIcon` or something like that.

2024-02-07 09:52 UTC, mstykow commented on src/Frontend/Components/DiffPopup/DiffPopup.util.tsx
> +  }, [isOpen, current, setBufferPackageInfo]);
if the trick with `key` works, it would be preferable i'd say. can you give it a try? maybe using the `packageInfo.id` could work as key?

2024-02-07 09:52 UTC, mstykow commented on src/Frontend/Components/DiffPopup/DiffPopup.util.tsx
> +              const isThirdPartyUnchanged =
always try to use as few NOTs as possible to reduce complexity. so can we turn the logic around and call this "isThirdPartyChanged"?

2024-02-07 09:52 UTC, mstykow commented on src/Frontend/Components/DiffPopup/DiffPopup.util.tsx
> +) {
EDIT: once you convert this to a real FC, you'll be forced to give names to your args anyways.

2024-02-07 09:52 UTC, mstykow commented on src/Frontend/Components/DiffPopup/DiffPopup.util.tsx
> +                      : undefined,
nested ternaries are best avoided as they make the code more difficult to understand. i think a chain of if-statements would be easier here. alternatively, you can probably move your ternaries inside the first two props, as the third prop is the same, and handle the `undefined` case upfront.

2024-02-07 09:52 UTC, mstykow commented on src/Frontend/Components/DiffPopup/DiffPopup.util.tsx
> +                      : undefined,
nested ternaries are best avoided as they make the code more difficult to understand. i think a chain of if-statements would be easier here. alternatively, you can probably move your ternaries inside the first two props, as the third prop is the same, and handle the `undefined` case upfront.

2024-02-07 09:52 UTC, mstykow commented on src/Frontend/Components/DiffPopup/__test__/DiffPopup.util.test.tsx
> +  };
please generate these using `reduce`. same for the object in line 18.

2024-02-07 09:52 UTC, mstykow commented on src/shared/text.ts
> +    },
i'm not convinced we need any of these. isn't it clear without a tooltip what the revert/undo buttons do?

2024-02-07 15:21 UTC, alexzurbonsen commented on src/Frontend/Components/AttributionColumn/AttributionForm.util.tsx
> +// SPDX-FileCopyrightText: Meta Platforms, Inc. and its affiliates
The problem here is `FORM_ATTRIBUTES` I think. It is a `const`. To resolve the loop I put `getComparableAttributes` and `FORM_ATTRIBUTES` next to each other. And since the types are related, I put them all in the same place.
Just moving `getComparableAttributes` doesn't help unfortunately.

2024-02-07 15:27 UTC, alexzurbonsen commented on src/Frontend/Components/AttributionColumn/ButtonRow.tsx
> +
Missed that, not sure how they got here...

2024-02-07 15:43 UTC, alexzurbonsen commented on src/Frontend/Components/DiffPopup/DiffPopup.tsx
> +      buffer.wasPreferred = true;
Okay, sure. I just thought that it might be okay since this is the last thing this state does for us. But of course that might change...

2024-02-07 15:45 UTC, alexzurbonsen commented on src/Frontend/Components/DiffPopup/DiffPopup.tsx
> +        ),
Just realized: didn't do this because one is comparing with `current`, the other one with `original`. Could introduce a function for that, but I don't think that is worth it?

2024-02-07 15:48 UTC, alexzurbonsen commented on src/Frontend/Components/DiffPopup/DiffPopup.tsx
> +        },
Nice.

2024-02-07 17:21 UTC, alexzurbonsen commented on src/Frontend/Components/DiffPopup/DiffPopup.util.tsx
> +              const isThirdPartyUnchanged =
What did you have in mind here? I introduced the `Unchanged` since it removed some NOTs and it seemed to me that made it easier to understand.
We have an expression like `!isThirdPartyChanged && isAttributeValueChanged` were we want to check if one side changed and the other one didn't. I also considered something like `bothAreThirdParty`? But that breaks the "something changed" naming schema.

2024-02-07 17:53 UTC, alexzurbonsen commented on src/Frontend/Components/DiffPopup/DiffPopup.util.tsx
> +                      : undefined,
After pulling creating the `DiffEndIcon` component I created a new `getEndIcon` function which does the choosing of the correct icon. What do you think about that?

2024-02-07 18:09 UTC, alexzurbonsen commented on src/shared/text.ts
> +    },
Fair point. I am not sure either. I guess it might be reassuring to some users, but I don't think it is terribly necessary.

2024-02-07 18:31 UTC, alexzurbonsen commented on src/Frontend/Components/DiffPopup/DiffPopup.util.tsx
> +  }, [isOpen, current, setBufferPackageInfo]);
I implemented a variant of this. `packageInfo.id` is not enough since it only changes when we change the attribution that is shown, but not if we change something in the attribution form.

2024-02-08 07:53 UTC, mstykow commented on src/Frontend/Components/DiffPopup/DiffPopup.tsx
> +        ),
yes, nevermind then

2024-02-08 07:55 UTC, mstykow commented on src/Frontend/Components/DiffPopup/DiffPopup.util.tsx
> +              const isThirdPartyUnchanged =
ok, nevermind then

2024-02-08 07:56 UTC, mstykow commented on src/shared/text.ts
> +    },
i feel like excessive use of tooltips causes noise and distraction

2024-02-08 12:54 UTC, alexzurbonsen commented on src/Frontend/Components/DiffPopup/DiffPopup.util.tsx
> +  }, [isOpen, current, setBufferPackageInfo]);
It indeed works with `key={isDiffPopupOpen.toString()}`.

2024-02-12 09:49 UTC, mstykow approved these changes

2024-02-12 11:05 UTC, merged