Add icon to hide multiselect in attribution view
opossum-tool/OpossumUI pull request #258
Opened 2021-12-09 16:12 UTC by mayayunx

Signed-off-by: Ruiyun Xie <ruiyun.xie@tum.de>

### Summary of changes
- Add an icon in attribution view to hide or show the multiselect filter

### Context and reason for change
- The multiselect component is too prominent and is not used so frequently

### How can the changes be tested
- The icon can be tested in the UI

2021-12-09 19:06 UTC, nicarl requested changes

2021-12-09 19:06 UTC, nicarl commented on src/Frontend/Components/Filter/FilterMultiSelect.tsx
> +    const filterFormControl = document.getElementById('filter-form-control');
I think the more "react"-like way is to use a boolean state to indicate if the element is shown. I think the state should be declared in `AttributionView`

``` typescript
const [showMultiSelect, setShowMultiselect] = useState<boolean>(false);
``` 
The onClick function of the icon will then just use 
``` typescript
onClick = () => {setShowMultiselect(!showMultiSelect)}

2021-12-10 07:29 UTC, leslielazzarino requested changes

2021-12-10 07:29 UTC, leslielazzarino commented on src/Frontend/Components/Filter/FilterMultiSelect.tsx
> +    const filterFormControl = document.getElementById('filter-form-control');
It would also be cool if the multiselect menu would open when the icon is clicked. As the filters multiselect is not shown without selected filters, if I click on it it is to select some.

2021-12-15 11:50 UTC, leslielazzarino approved these changes

2021-12-15 12:17 UTC, nicarl commented on src/Frontend/Components/Filter/FilterMultiSelect.tsx
> +      id="filter-form-control"
Do we need this id ?

2021-12-15 12:17 UTC, nicarl commented on src/Frontend/Components/AttributionView/AttributionView.tsx
> +  }
I think this can be deleted

2021-12-15 12:26 UTC, nicarl commented on src/Frontend/Components/AttributionView/AttributionView.tsx
> +  }
It is actually needed as `showMultiSelect` is not in the store and we might have a conflict when changing views

2021-12-15 12:31 UTC, nicarl approved these changes

2021-12-15 12:47 UTC, merged