feat: add keyboard navigation to attributions and signals lists
opossum-tool/OpossumUI pull request #2583
Opened 2024-02-23 21:41 UTC by mstykow

### Summary of changes

- merge PackageCard and ListCard components
- track keyboard selected item in list and grouped-list
- add focus styling to package card

### Context and reason for change

closes #971

### How can the changes be tested

Check keyboard navigation after clicking on a package card in the attributions or signals lists. Pay special attention also to switching tabs: the previously focused package card should not carry over to another tab.

2024-02-26 09:50 UTC, MarkusObendrauf approved these changes
Cool. Sometimes using arrow keys is a bit slow (still less that 0.5s but its noticeable). For example, if you're on the second-last item and press down, it takes a while for the highlighted item to move.

2024-02-26 09:50 UTC, MarkusObendrauf commented on src/Frontend/util/use-virtuoso-refs.ts
> +  const [focusedIndex, setFocusedIndex] = useState(selectedIndex ?? -1);
I would prefer not to use -1 here

2024-02-26 09:50 UTC, MarkusObendrauf commented on src/e2e-tests/__tests__/selecting-attributions.test.ts
> +  );
this test is really really satisfying

2024-03-04 12:11 UTC, mstykow commented
> Hey, finally figured out that a bug I'm encountering in the follow-up already exists in this version.
> 
> To reproduce:
> 
> 1. Select a resource without attributions
> 2. Focus on the attributions panel, eg. by clicking on the scrollbar
> 3. Scroll down using the down arrow
> 4. Select a different resource without attributions
> 5. Focus on the attributions panel, eg. by clicking on the scrollbar
> 6. Scroll down using the down arrow
> 
> Notice that the focused index was preserved from the previous list.

I think I found a pretty simple solution to this issue that should also help you with the focus-stealing problems you faced in your follow-up task.

2024-03-04 12:43 UTC, MarkusObendrauf commented on src/Frontend/util/use-virtuoso-refs.ts
> +    [data?.length, focusedIndex],
what's the `data?.length` for? is it for the file tree?

2024-03-04 12:48 UTC, MarkusObendrauf requested changes
It's still a little buggy:
1. Click a resource with no attached attributions
2. Click on an attribution
3. Click on a resource with an attached attribution
4. Click on a resource with no attached attributions
Notice that the focus index from step 2 was preserved.

2024-03-04 13:21 UTC, mstykow commented
> It's still a little buggy:
> 
> 1. Click on a resource with no attached attributions
> 2. Click on an attribution
> 3. Click on a resource with an attached attribution
> 4. Click on a resource with no attached attributions
>    Notice that the focus index from step 2 was preserved.

Good catch. Please try again now.

2024-03-04 13:51 UTC, mstykow commented on src/Frontend/util/use-virtuoso-refs.ts
> +    [data?.length, focusedIndex],
since this is a generic hook, it has nothing to do with a specific component such as a file tree.

in this implementation of `keyDownCallback` you can see that we need to know the number of items the list is dealing with because we don't want to set the focused index to something lower than the first or higher than the last possible index.

2024-03-04 13:54 UTC, mstykow commented
> Member

The slowness resulted from only changing the focused index once the scrolling was complete. But there is actually no need to wait. So I changed the behavior to immediately set the new index regardless of the scroll state.

2024-03-04 13:54 UTC, mstykow commented
> Cool. Sometimes using arrow keys is a bit slow (still less that 0.5s but its noticeable). For example, if you're on the second-last item and press down, it takes a while for the highlighted item to move.

The slowness resulted from only changing the focused index once the scrolling was complete. But there is actually no need to wait. So I changed the behavior to immediately set the new index regardless of the scroll state.

2024-03-04 14:18 UTC, MarkusObendrauf approved these changes
Seems to work, I'm just praying that I never have to open up `use-virtuoso-refs.ts` again.

2024-03-06 17:20 UTC, merged