feat: use nivo responsive bar chart for progress and criticality bar
opossum-tool/OpossumUI pull request #2639
Opened 2024-05-29 08:25 UTC by meretp

### Summary of changes

To improve the progress bar this PR adds a new library nivo and introduces a ResponsiveBar. 

### Context and reason for change

fixes part of #2622 

### How can the changes be tested

TODO

Note: Please review the [guidelines for contributing](https://github.com/opossum-tool/OpossumUI/blob/main/CONTRIBUTING.md) to this repository.

2024-06-24 11:11 UTC, meretp commented on src/Frontend/Components/ProgressBar/__tests__/ProgressBar.test.tsx
I decided to replace this unit test with an e2e test.

2024-08-25 18:55 UTC, mstykow requested changes

2024-08-25 18:55 UTC, mstykow commented on src/Frontend/Components/ProgressBar/ProgressBar.util.tsx
> +    'z-index': 100,
this is not a valid css prop as is and should be `zIndex`. but given that it doesn't do anything right now we should probably just delete it then.

2024-08-25 18:55 UTC, mstykow commented on src/Frontend/Components/ProgressBar/ProgressBar.util.tsx
> +        ></span>
here and everywhere else:

```suggestion
        <span
          style={{
            ...classes.colorBlock,
            background: OpossumColors.pastelDarkGreen,
          }}
        />
```

2024-08-25 18:55 UTC, mstykow commented on src/Frontend/Components/ProgressBar/ProgressBar.util.tsx
> +          )}{' '}
here and below: i don't see why we need a trailing space after the item

2024-08-25 18:55 UTC, mstykow commented on src/Frontend/Components/ProgressBar/ProgressBar.util.tsx
> +    top: 100,
the positioning is not working consistently: depending on the bar's mode, the tooltip appears higher or lower below the cursor. could you find a way to make the positioning consistent?

2024-08-25 18:55 UTC, mstykow commented on src/Frontend/Components/ProgressBar/ProgressBar.util.tsx
> +    fontSize: 10,
to me this seems quite small. i'm not aware of us using 10px anywhere else. i've seen 12px for captions and i think that's the smallest size we should use.

2024-08-25 18:55 UTC, mstykow commented on src/Frontend/Components/ProgressBar/ProgressBar.util.tsx
> +  div: { display: 'flex', 'align-items': 'center' },
the name "div" for a css class that's applied to any of the many divs an app may have is really not the best. it's better to choose class names by the function they fulfill.

2024-08-25 18:55 UTC, mstykow commented on src/Frontend/Components/ProgressBar/ProgressBar.tsx
> +        margin={{ top: 5, right: 1, bottom: 5, left: 6 }}
these margins are asymmetrical and deviate from the multiples-of-4 rule. i think there is no reason to break the rules and introduce asymmetry here:
```suggestion
        margin={{ top: 4, bottom: 4 }}
```

2024-08-25 18:55 UTC, mstykow commented on src/Frontend/Components/ProgressBar/ProgressBar.tsx
> +          high_critical:
here and below: JavaScript uses camel case

2024-08-25 18:55 UTC, mstykow commented on src/Frontend/Components/ProgressBar/ProgressBar.tsx
> +      opacity: 1,
do we still need this opacity declaration?

2024-08-25 18:55 UTC, mstykow commented on src/Frontend/Components/ProgressBar/ProgressBar.tsx
> +  const data: Array<{ [key: string]: number }> = props.showCriticalSignals
could you use nivo's built-in type (`BarDatum`) to ensure that the object we're defining here always matches what nivo expects, even if nivo gets refactored?

2024-08-25 18:55 UTC, mstykow commented on src/Frontend/Components/ProgressBar/ProgressBar.util.tsx
> +    flex: 1,
this prop doesn't seem to have any effect

2024-08-25 18:55 UTC, mstykow commented on src/Frontend/Components/ProgressBar/ProgressBar.util.tsx
> +  tooltip: {
could you give the interior of the tooltip a little more room to breathe? right now the lines of text have hardly any space between them and are also really close to the edge of the container.

2024-09-13 05:20 UTC, meretp commented on src/Frontend/Components/ProgressBar/ProgressBar.util.tsx
> +    top: 100,
This is still to do, but so far I couldn't find a way.

2024-09-22 08:11 UTC, mstykow commented on src/Frontend/Components/ProgressBar/ProgressBar.util.tsx
> +    // top: 'auto',
can we delete these commented props?

2024-09-22 08:11 UTC, mstykow commented on src/Frontend/Components/ProgressBar/ProgressBar.util.tsx
> +          ...with attributions:{' '}
here and above: let's use either three separate dots "..." or the special three dot symbol "…" consistently.

2024-09-22 08:11 UTC, mstykow commented on src/Frontend/Components/ProgressBar/ProgressBar.util.tsx
> +    top: 100,
ok, i'll have a look

2024-09-24 06:06 UTC, meretp commented on src/Frontend/Components/ProgressBar/ProgressBar.util.tsx
> +    // top: 'auto',
sure, I was trying to debug and find a solution for the positioning, I reverted it to the previous state.

2024-09-24 06:06 UTC, meretp commented on src/Frontend/Components/ProgressBar/ProgressBar.util.tsx
> +          ...with attributions:{' '}
done

2025-01-02 16:14 UTC, mstykow commented
The following issues need to be solved before this PR can merge:
1. the position differs between tooltip modes
2. when resizing the window down, the new bar chart does not resize itself thus causing x-overflow

2025-01-20 07:15 UTC, meretp commented
Added some commits that fixes the second issue and updates nivo bar - there has been a new release in the meantime. Also I updated the diff to use the ariaLabel from ResponsiveBar.

2025-01-20 07:22 UTC, meretp commented
To fix the first issue the only idea I could come up with is to use sepearate CSS styling like
 ```
transformProgress: { transform: 'translate(0px, 168px)' } as CSSProperties,
 transformCritical: { transform: 'translate(0px, 144px)' } as CSSProperties,
```
to transform the tooltips separately. This does not feel like a stable solution so I only add this as a comment not commit yet, what do you think?

2025-01-20 07:38 UTC, meretp commented
Have to take a look at why the unit tests are failing now

2025-02-02 23:17 UTC, mstykow commented
Closing for now since no work done in a while.

2025-02-02 23:17 UTC, closed without merging