Add web workers without ejecting & extra packages
opossum-tool/OpossumUI pull request #284
Opened 2021-12-17 15:44 UTC by leslielazzarino

### Summary of changes

Introduce web workers and compute accordion data in a worker (async, not in the main process). Since Webpack 5 web workers are supported by default, not requiring any external package or change in the Webpack configuration.

### Summary of remaining issues

- Web worker can run out of memory with big files, such error should be catch and the calculation should be performed as fallback on main asynchronously
- jest does not support web workers yet, therefore they need to be mocked in the test. The mock could just throw an error in the worker and trigger the fall back on main
- some refactoring is needed, in particular better naming and typing

### Context and reason for change

The app gets stuck for a while when clicking on a folder with a lot of signals inside. Web workers allow to calculate the accordion faster, meanwhile leaving the main process free to process user input.

### How can the changes be tested

Open keycloak input and navigate away from the root folder (somewhere where there is an attribution). Then click on the root folder. On the right and above the accordion the UI will change instantly, meanwhile the old accordion will be shown until the new one is ready.

2022-01-24 14:14 UTC, benedikt-richter commented on src/Frontend/Components/AppContainer/__tests__/AppContainer.test.tsx
> +jest.mock('../../ResourceDetailsTabs/get-new-accordion-worker');
As discussed: move to `setupTests.js`

2022-01-24 14:16 UTC, benedikt-richter commented on src/Frontend/Components/ResourceDetailsTabs/__mocks__/get-new-accordion-worker.ts
> +// SPDX-FileCopyrightText: Facebook, Inc. and its affiliates
This should probably not be placed here, next to ResourceDetailsTabs

2022-01-24 14:18 UTC, benedikt-richter commented on src/Frontend/Components/ResourceDetailsTabs/accordion-worker.ts
> +  },
Might be useful to extract an interface for this type

2022-01-24 16:06 UTC, nicarl commented on src/Frontend/Components/ResourceDetailsTabs/ResourceDetailsTabs.tsx
> +          const output = getPanelData(
A comment for the `try .. catch` block would be nice

2022-01-25 11:53 UTC, benedikt-richter commented
Just did a quick performance test with the build version. Opening the root folder of a huge app:
Before: 800ms (total) = approx 1s
Now: 260ms (to display the root folders attributions) + 1100ms (load package panels) + approx 700ms (idle) = approx 2s

2022-01-25 12:16 UTC, benedikt-richter commented on src/Frontend/Components/ResourceDetailsTabs/ResourceDetailsTabs.tsx
> +      return (): never => {
never -> void

2022-01-25 12:34 UTC, benedikt-richter requested changes
performance issues shave to be fixed

2022-02-09 08:14 UTC, closed without merging