Add button to fetch license information from pypi
opossum-tool/OpossumUI pull request #288
Opened 2021-12-18 19:50 UTC by nicarl

### Summary of changes

This is a first POC for #216. A button is added which loads information from the pypi api if the entered url is a valid pypi url.

- add new button
- add interface which can be extended for other providers (github, npm, ...)

### Context and reason for change

- external APIs can be useful for fetching data

### How can the changes be tested

- create an attribution with url: `https://pypi.org/pypi/Faker` for success case, `https://pypi.org/pypi/qwadsadadsad` for error case.

2021-12-18 19:53 UTC, nicarl commented on src/Frontend/Components/FetchLicenseInformationButton/FetchLicenseInformationButton.tsx
> +    useState<{ selectedResourceId: string; packageInfo: PackageInfo }>();
one needs to remember the resourceId as it could change in the meantime. This is a tradeoff: we give the user the freedom to chance the attribution, which makes this step necessary.

2021-12-18 20:06 UTC, nicarl commented on src/Frontend/Components/FetchLicenseInformationButton/pypi-fetching-helpers.ts
> +    packageName: convertedPayload.info.name as string,
should we also set parts of the purl?

2021-12-19 09:39 UTC, nicarl commented on src/Frontend/Components/FetchLicenseInformationButton/pypi-fetching-helpers.ts
> +    packageName: convertedPayload.info.name as string,
I added type which gives us a valid purl (without version). I think this is a good push forward to more attributions with purl (and eventual a lookup in clearly defined)

2021-12-20 07:47 UTC, benedikt-richter reviewed
not et completely done. Will continue later

2021-12-20 07:47 UTC, benedikt-richter commented on src/Frontend/Components/FetchLicenseInformationButton/pypi-fetching-helpers.ts
> +const PYPISCHEMA: Schema = {
-> `PYPI_SCHEMA`

2021-12-20 07:47 UTC, benedikt-richter commented on src/Frontend/Components/FetchLicenseInformationButton/license-fetching-helpers.ts
> +// SPDX-FileCopyrightText: Facebook, Inc. and its affiliates
this file could be merged with the other helpers file. Both are solely for pypi

2021-12-20 07:47 UTC, benedikt-richter commented on src/Frontend/Components/FetchLicenseInformationButton/FetchLicenseInformationButton.tsx
> +  const dispatch = useDispatch();
-> `useAppDispatch`

2021-12-20 07:47 UTC, benedikt-richter commented on src/Frontend/Components/FetchLicenseInformationButton/FetchLicenseInformationButton.tsx
> +  const temporaryPackageInfo = useSelector(getTemporaryPackageInfo);
-> `useAppSelector`

2021-12-20 07:47 UTC, benedikt-richter commented on src/Frontend/Components/FetchLicenseInformationButton/FetchLicenseInformationButton.tsx
> +  convertPayload: (payload: Response) => Promise<PackageInfo>
the interface matches `LicenseFetchingInformation`

2021-12-20 07:47 UTC, benedikt-richter commented on src/Frontend/Components/FetchLicenseInformationButton/FetchLicenseInformationButton.tsx
> +  const [error, setError] = useState<string>();
here we could explicitly set a default

2021-12-20 07:47 UTC, benedikt-richter commented on src/Frontend/Components/FetchLicenseInformationButton/FetchLicenseInformationButton.tsx
> +  }, [success, fetchedPackageInfo]);
Why do we not set all dependencies?

2021-12-20 07:47 UTC, benedikt-richter commented on src/Frontend/Components/FetchLicenseInformationButton/FetchLicenseInformationButton.tsx
> +interface FetchLicenseInformationButtonProps {
this matches `LicenseFetchingInformation`

2021-12-20 07:47 UTC, benedikt-richter commented on src/Frontend/Components/FetchLicenseInformationButton/FetchLicenseInformationButton.tsx
> +    } else if (success === false) {
-> ` !success`

2021-12-20 07:47 UTC, benedikt-richter commented on src/Frontend/Components/AttributionColumn/PackageSubPanel.tsx
> +  const licenseFetching = getLicenseFetchingInformation(
`licenseFetching` ->`licenseFetchingInformation`

2021-12-20 07:47 UTC, benedikt-richter commented on src/Frontend/Components/AttributionColumn/PackageSubPanel.tsx
> +            )}
It might be nice to provide to the `FetchLicenseInformationButton` the values `props.displayPackageInfo.url` and `props.isEditable` as properties (e.g. `url` and `?disabled`) and then inside the button to decide whether it is disabled or not.

2021-12-20 08:00 UTC, benedikt-richter commented on src/Frontend/Components/FetchLicenseInformationButton/pypi-fetching-helpers.ts
> +    packageName: convertedPayload.info.name as string,
Just noted: When there is a PURL already present. Some parts are replaced such that the resulting PURL might be "broken". Maybe the old one could be removed?

2021-12-20 09:50 UTC, benedikt-richter requested changes
see comments

2021-12-21 13:07 UTC, nicarl commented on src/Frontend/Components/FetchLicenseInformationButton/license-fetching-helpers.ts
> +// SPDX-FileCopyrightText: Facebook, Inc. and its affiliates
For now, I already have the `npm` support in draft and would like to keep the actual payload handling for the different types of urls separate.

2021-12-21 15:05 UTC, nicarl commented on src/Frontend/Components/FetchLicenseInformationButton/pypi-fetching-helpers.ts
> +    packageName: convertedPayload.info.name as string,
Fixed this

2021-12-21 15:06 UTC, nicarl commented on src/Frontend/Components/FetchLicenseInformationButton/FetchLicenseInformationButton.tsx
> +interface FetchLicenseInformationButtonProps {
I added everything except `temporaryPackageInfo` as the app freezes with it if you start typing anything in the `PackageSubPanel`. Any idea?

2021-12-21 15:06 UTC, nicarl commented on src/Frontend/Components/FetchLicenseInformationButton/FetchLicenseInformationButton.tsx
> +    } else if (success === false) {
As discussed this was changed to enum covering all possible states of the query

2021-12-21 15:07 UTC, nicarl commented on src/Frontend/Components/AttributionColumn/PackageSubPanel.tsx
> +            )}
I added a third wrapper component for this

2021-12-21 15:11 UTC, nicarl commented on src/Frontend/Components/FetchLicenseInformationButton/FetchLicenseInformationButton.tsx
> +  }, [success, fetchedPackageInfo]);
I added everything except temporaryPackageInfo as the app freezes with it if you start typing anything in the PackageSubPanel. Any idea?

2021-12-21 15:32 UTC, benedikt-richter commented on src/Frontend/Components/FetchLicenseInformationButton/FetchLicenseInformationButton.tsx
> +  isEditable: boolean;
`isEditable` -> `isDisabled`

2021-12-21 15:33 UTC, benedikt-richter commented on src/Frontend/Components/FetchLicenseInformationButton/FetchLicenseInformationButton.tsx
> +export function EnabledFetchLicenseInformationButton(
does probably not need to be exported

2021-12-21 15:33 UTC, benedikt-richter commented on src/Frontend/Components/FetchLicenseInformationButton/FetchLicenseInformationButton.tsx
> +export function DisabledFetchLicenseInformationButton(): ReactElement {
does probably not need to be exported

2021-12-21 15:33 UTC, benedikt-richter commented on src/Frontend/Components/FetchLicenseInformationButton/FetchLicenseInformationButton.tsx
> +      return <CachedIcon className={classes.clickableIcon} />;
(optional) might be switch case

2021-12-21 15:34 UTC, benedikt-richter commented on src/Frontend/Components/FetchLicenseInformationButton/__tests__/FetchLicenseInformationButton.test.tsx
> +  EnabledFetchLicenseInformationButton,
Instead of these, we probably want to test `FetchLicenseInformationButton` to ensure the integration works

2021-12-21 15:36 UTC, benedikt-richter reviewed
might be nice to adapt the tests to test the wrapper component. Should be a relatively easy refactor

2021-12-21 16:01 UTC, nicarl commented on src/Frontend/Components/FetchLicenseInformationButton/FetchLicenseInformationButton.tsx
> +      return <CachedIcon className={classes.clickableIcon} />;
I changed it to switch case + the tooltip too. Previously I had some annoying issues with typescript enums and switch, seems to work now :+1:

2021-12-21 16:33 UTC, FlorianSchepers approved these changes
Looks good.

2021-12-21 16:57 UTC, benedikt-richter approved these changes
👍

2021-12-21 16:57 UTC, merged