Remove white border at the bottom of the resources list
opossum-tool/OpossumUI pull request #30
Opened 2021-09-28 12:46 UTC by antonbauhofer

Before this fix, the resources list in the attribution view had a white border when horizontal scrolling was deactivated.

Signed-off-by: Anton Bauhofer <anton.bauhofer@tngtech.com>

2021-09-28 13:24 UTC, benedikt-richter commented on src/Frontend/Components/List/List.tsx
> +  horizontalScrollbarFix: { overflowX: 'scroll' },
are these used?

2021-09-28 13:27 UTC, benedikt-richter commented
there is a scrollbar for a single resource in the resource popup 
![Screenshot 2021-09-28 at 15 27 01](https://user-images.githubusercontent.com/46576389/135095984-be563efe-fa0a-4b7d-bb63-7a7288fc19d8.png)

2021-09-30 06:13 UTC, leslielazzarino requested changes
It looks fine, but the unnecessary scroll bar in the linked resources popup should be fixed.

2021-09-30 13:22 UTC, benedikt-richter reviewed
looks broken for long paths

![Screenshot 2021-09-30 at 15 21 56](https://user-images.githubusercontent.com/46576389/135463168-e5f478b3-a9a5-42fb-be5f-db35203da2d2.png)

2021-10-04 06:40 UTC, leslielazzarino approved these changes

2021-10-04 06:49 UTC, benedikt-richter reviewed
Unfortunately, highlighting is broken for the resource list in search
![Screenshot 2021-10-04 at 08 47 20](https://user-images.githubusercontent.com/46576389/135805796-4560faa0-12ca-43b7-9b5c-07800a46731b.png)

It seems the vertical scroll bar is not necessary if we have two elements in the list
![Screenshot 2021-10-04 at 08 48 16](https://user-images.githubusercontent.com/46576389/135805850-18c965e9-95b9-42e2-b8c7-a45da2652801.png)

2021-10-04 06:50 UTC, benedikt-richter requested changes
see comment

2021-10-04 09:15 UTC, leslielazzarino commented
> Unfortunately, highlighting is broken for the resource list in search ![Screenshot 2021-10-04 at 08 47 20](https://user-images.githubusercontent.com/46576389/135805796-4560faa0-12ca-43b7-9b5c-07800a46731b.png)
> 
> It seems the vertical scroll bar is not necessary if we have two elements in the list ![Screenshot 2021-10-04 at 08 48 16](https://user-images.githubusercontent.com/46576389/135805850-18c965e9-95b9-42e2-b8c7-a45da2652801.png)

I cannot fix the first issue, it is already on master, working on the second one.

2021-10-05 12:39 UTC, benedikt-richter approved these changes
👍

2021-10-05 12:52 UTC, merged