Bring back show resources icon
opossum-tool/OpossumUI pull request #343
Opened 2022-01-12 12:15 UTC by mayayunx

Signed-off-by: Ruiyun Xie <ruiyun.xie@tum.de>

### Summary of changes
- Bring back show resources icon for attributions and signals

### Context and reason for change
- show resources icon was moved to the context menu, but still wanted in the package cards

### How can the changes be tested
The changes can be tested in the UI.

2022-01-12 13:08 UTC, benedikt-richter requested changes
would be nice to have at least one test

2022-01-12 13:58 UTC, nicarl reviewed
Did we have the button also for `Resources` and not only `Signals`?

2022-01-13 07:40 UTC, benedikt-richter approved these changes
👍 

don't forget to squash before merge

2022-01-13 09:01 UTC, nicarl approved these changes

2022-01-13 09:04 UTC, merged