add the following lint plugin: plugin:testing-library/react
opossum-tool/OpossumUI pull request #35
Opened 2021-09-29 13:12 UTC by benedikt-richter

add the following lint plugin: plugin:testing-library/react

2021-09-29 13:45 UTC, sebathomas approved these changes

2021-09-30 06:42 UTC, leslielazzarino requested changes

2021-09-30 06:42 UTC, leslielazzarino commented on .eslintrc.js
> +    'testing-library/no-node-access': 'off', // TODO: remove this line and fix warnings
If they are just warnings I would remove this line, so that we keep seeing them and fix them at some point. This todo will be forgotten.

2021-09-30 07:01 UTC, benedikt-richter commented on .eslintrc.js
> +    'testing-library/no-node-access': 'off', // TODO: remove this line and fix warnings
These are errors. Therefore, we have tp turn these off

2021-09-30 07:26 UTC, leslielazzarino approved these changes

2021-09-30 07:27 UTC, merged