Remove hint if resource or its parent has signal
opossum-tool/OpossumUI pull request #363
Opened 2022-01-20 15:15 UTC by mayayunx

Signed-off-by: Ruiyun Xie <ruiyun.xie@tum.de>

### Summary of changes
- While inputting data, concatenate attributions with children's attributions, and check whether hint and other signals exists
- If it is the case, remove the hint signal 

### Context and reason for change
User does not want to see the hint signal if the resource has other signals or its parent have other signals.

### How can the changes be tested
The changes can be tested by running `yarn test:unit` or add a  signal (external attribution) in the `oppsum_input.json` file for either `/package.json` or its parent (`/`) and test in the UI.

2022-01-24 14:11 UTC, benedikt-richter commented on src/ElectronBackend/input/cleanInputData.ts
> +export function removeHintIfSignalsExist(
this seems not to be tested in `cleanInputData.test.ts`

2022-01-24 16:34 UTC, nicarl commented on src/ElectronBackend/input/cleanInputData.ts
> +  const resourcesToExternalAttributionsIncludeChildren = Object.assign(
I think we can skip the `Object.assign` here as we already create a new object in line 223 -237.

2022-01-24 16:34 UTC, nicarl commented on src/ElectronBackend/input/cleanInputData.ts
> +    const externalNonHintAttribtion =
typo: `Attribtion` instead of `Attribution`

2022-01-24 16:34 UTC, nicarl commented on src/ElectronBackend/input/cleanInputData.ts
> +    const externalHintAttribtion =
same typo here

2022-01-24 16:34 UTC, nicarl commented on src/ElectronBackend/input/cleanInputData.ts
> +  const resourcesToExternalAttributionsIncludeChildren = Object.assign(
I am not sure if the variable name makes much sense here. It `resourcesToExternalAttributions` already contains the children?

2022-01-24 16:34 UTC, nicarl commented on src/ElectronBackend/input/cleanInputData.ts
> +  for (const resource of Object.keys(
This function is very long and quite complicated. Just to help me understanding what is going on I summarize the steps:

1. Sort `resourcesToExternalAttributions` by resource (we should double check if this is necessary)
2. Loop over `resourcesToExternalAttributions` (`resource`)
2.1 Loop over `resourcesToExternalAttributions` (`otherResource`) (watch out this gives `O(N**2)` run time behavior)
2.1.1 If `resource` and `otherResource` are not identical and `otherResource` is a child of `resource` merge the attributions to the parent
2.1.2 Get all attributions with and without hint for `resource`
2.1.3 If `externalNonHintAttribution` > 0 and `externalHintAttribution` delete `externalHintAttribtion` entry for `resource`
2.1.4 Remove attributions for `resourceId` which are not in `externalAttributions`
2.1.5 If there are not attributions for `resourceId` left, delete the entry

2022-01-24 16:34 UTC, nicarl commented on src/ElectronBackend/input/cleanInputData.ts
> +  for (const resource of Object.keys(
An alternative could be to:
1. Find all attributions/`attributionId` which are `HINTS`
2. For each `attributionId` get all `resourceIds`
2.1 For each `resourceId` look if the attribution itself or a parent has a non hint attribution
2.1.1 If yes remove it
2.2.2 if not continue

We can discuss together with @benedikt-richter

2022-01-25 15:35 UTC, leslielazzarino requested changes

2022-01-25 15:35 UTC, leslielazzarino commented on src/ElectronBackend/input/cleanInputData.ts
> +
This looks like a feature that does not belong in the app.

2022-01-26 08:38 UTC, benedikt-richter commented on src/ElectronBackend/input/cleanInputData.ts
> +  for (const resource of Object.keys(
I think the approach Nico is suggesting sounds good.

2022-01-27 09:04 UTC, nicarl requested changes

2022-01-27 09:04 UTC, nicarl commented on src/ElectronBackend/input/cleanInputData.ts
> +      resourcesToExternalAttributions[resource] =
Can't we delete the reference in `resourcesToExternalAttributions` after line 203 ?

2022-01-27 09:34 UTC, mayayunx commented on src/ElectronBackend/input/cleanInputData.ts
> +      resourcesToExternalAttributions[resource] =
I thought there might be the case where other resource has the same hint signal, then it should also be deleted. Therefore, the deletion of the reference in `resourcesToExternalAttributions` shouldn't only be in the if-loop.

2022-01-27 10:00 UTC, leslielazzarino requested changes

2022-01-27 10:06 UTC, leslielazzarino commented on src/ElectronBackend/input/importFromFile.ts
> +  removeHintIfSignalsExist(
We should have a comment here explaining that hints are now a special kind of external attribution, and that we plan to support them in a less hacky way in the near future.

2022-01-27 10:06 UTC, leslielazzarino commented on src/ElectronBackend/input/importFromFile.ts
> +  removeHintIfSignalsExist(
It also should be documented in the docs.

2022-01-27 16:34 UTC, nicarl approved these changes

2022-01-28 08:17 UTC, leslielazzarino approved these changes

2022-01-28 08:17 UTC, merged