Extract hard-coded root folder.
opossum-tool/OpossumUI pull request #366
Opened 2022-01-21 12:52 UTC by leslielazzarino

Signed-off-by: Leslie Lazzarino <leslie.lazzarino@tngtech.com>

### Summary of changes

The resource root folder, added in the UI to the resources provided in the input file, was hardcoded inside the VirtualizedTree. Now it added to the resources before giving them to the tree. 

### Context and reason for change

Step in the direction of making the VirtualizedTree more generic and extract it to a separate package

### How can the changes be tested

Basically just a refactoring. The file tree in the app should still look and work as before.

Note: Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

2022-01-22 09:55 UTC, nicarl approved these changes

2022-01-22 09:55 UTC, nicarl commented on src/Frontend/Components/ResourceBrowser/ResourceBrowser.tsx
> +      resources={{ '': resources }}
Can you move this to a constant? 
```typescript
const ROOT_FOLDER = "";

2022-01-22 09:55 UTC, nicarl commented on src/Frontend/Components/VirtualisedTree/VirtualizedTree.tsx
>      : [];
If `VirtualizedTree` becomes a "public" component I am not sure if resources should be nullable.
I would expect.
```typescript
resources: Resources;
```

2022-01-22 09:55 UTC, nicarl commented on src/Frontend/Components/VirtualisedTree/VirtualizedTree.tsx
> +          treeItems = treeItems.concat(
A note for the future:
This could become a bottleneck for huge trees. `concat` returns a new array instead of modifying the existing `treeItems'. Before publishing the tree on npm it would be amazing to test the component with a really large tree.

2022-01-24 10:48 UTC, benedikt-richter commented on src/Frontend/Components/VirtualisedTree/VirtualizedTree.tsx
> +    ? Object.keys(props.resources).reduce(
should be tested

2022-01-24 14:08 UTC, benedikt-richter requested changes
see comment

2022-01-25 08:00 UTC, leslielazzarino commented on src/Frontend/Components/VirtualisedTree/VirtualizedTree.tsx
> +    ? Object.keys(props.resources).reduce(
Turns out it wasn't needed.

2022-01-25 08:00 UTC, leslielazzarino commented on src/Frontend/Components/VirtualisedTree/VirtualizedTree.tsx
> +          treeItems = treeItems.concat(
Turns out it wasn't needed.

2022-01-25 08:14 UTC, benedikt-richter approved these changes

2022-01-25 09:13 UTC, merged