Add max tree height and card height to VirtualizedTree props.
opossum-tool/OpossumUI pull request #367
Opened 2022-01-21 13:44 UTC by leslielazzarino

Signed-off-by: Leslie Lazzarino <leslie.lazzarino@tngtech.com>

### Summary of changes

maxTreeHeight and cardHeight are now properties of the VirtualizedTree, instead of being hard coded somewhere inside. Also the naming scheme in RenderTree has been made more consistent, avoiding the use of terms like "folder" and "file" where expandable/simple nodes are meant.
 
### Context and reason for change

Making VirtualizedTree more generic for package extraction.

### How can the changes be tested

Basically a refactoring, the file tree in the app should work like before.

Note: Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

2022-01-24 10:05 UTC, nicarl approved these changes

2022-01-24 10:50 UTC, benedikt-richter commented on src/Frontend/Components/ResourceBrowser/ResourceBrowser.tsx
> +  const treeMaxHeight: number = useWindowHeight() - topBarHeight - 4;
treeMaxHeight -> maxTreeHeight or simply maxHeight

2022-01-24 10:51 UTC, benedikt-richter commented on src/Frontend/Components/ResourceBrowser/ResourceBrowser.tsx
> +      cardHeight={20}
`20` should be extracted as constant

2022-01-24 10:52 UTC, benedikt-richter commented on src/Frontend/Components/VirtualisedTree/VirtualizedTree.tsx
> +          }
could be extracted

2022-01-24 10:53 UTC, benedikt-richter commented on src/Frontend/Components/VirtualisedTree/VirtualizedTree.tsx
> +                  numberOfDisplayedItems: min([treeItems.length, 5]) as number,
`5`should be extracted as constant

2022-01-24 10:58 UTC, benedikt-richter commented on src/Frontend/Components/VirtualisedTree/render-tree.tsx
> +    containedNodes.length == 1 &&
`==` -> `===`

2022-01-24 14:09 UTC, benedikt-richter requested changes
see comments

2022-01-25 10:43 UTC, benedikt-richter approved these changes

2022-01-25 12:02 UTC, merged