Add a popup for Report view for editing
opossum-tool/OpossumUI pull request #380
Opened 2022-01-26 16:08 UTC by mayayunx

Signed-off-by: Ruiyun Xie <ruiyun.xie@tum.de>

### Summary of changes
- Add new component EditAttributionPopup and open it when clicking on the edit button in report view
- The Popup contains the attribution column and allows user to edit the selected attribution and save changes
- If changes are not saved, open the NotSavedPopup
- Cancel NotSavedPopup leads to the EditAttributionPopup again

### Context and reason for change
- User wants to edit the attribution in report view directly without being redirected to attribution view

### How can the changes be tested
The changes can be test with `yarn test:unit` and in the UI

2022-01-27 06:36 UTC, benedikt-richter commented
Some observations:
* when opening the popup and editing some fields, the text does not appear immediately after typing
* on click away no popup for unsaved changes appears
* somehow when changing the confidence the following exception appeared
![Screenshot 2022-01-27 at 07 34 34](https://user-images.githubusercontent.com/46576389/151304908-1cdf12c6-1f7b-4ef2-9b49-54e2e113030a.png)
:

2022-01-27 06:37 UTC, benedikt-richter commented
Styling and intended functionality are nice 👍

2022-01-27 06:49 UTC, benedikt-richter commented on src/Frontend/Components/Button/Button.tsx
> +  onClick?: (event: React.MouseEvent<HTMLButtonElement>) => void;
this property should probably not be optional, as a button without onClick has no functionality

2022-01-27 06:52 UTC, benedikt-richter commented on src/Frontend/Components/NotSavedPopup/NotSavedPopup.tsx
> +        openPopupWithSelectedAttributionId(
on which `cancel`click do we want to open the popup?

2022-01-27 07:04 UTC, benedikt-richter commented on src/Frontend/state/reducers/view-reducer.ts
> +  selectedAttributionId: '',
The `selectedAttributionId` only exisits in report view and only has a meaning if the popup is open. This seems the wrong place in state. Therefore, it feels it should live in report view state. On the other hand it only makes sense in the context of the new popup being open. We should discuss on this one. Maybe the other reviewer also has an opinion on this.

2022-01-27 07:19 UTC, benedikt-richter requested changes
see comments

2022-01-27 07:22 UTC, benedikt-richter commented on src/Frontend/state/reducers/view-reducer.ts
> +  selectedAttributionId: '',
Looking at it, wouldn't be `openPopupWithTargetAttributionId` sufficient for our use case?

2022-01-27 09:27 UTC, benedikt-richter commented on src/Frontend/state/reducers/view-reducer.ts
> +  selectedAttributionId: '',
Following our discussion. Let's go for something like

```

interface PopupInfo {
  openPopup: PopupType;
  attributionId?: string;
}

export interface ViewState {
  view: View;
  targetView: View | null;
  popupInfo: PopupInfo | null;
  activeFilters: Set<FilterType>;
}

```

2022-01-27 10:16 UTC, leslielazzarino requested changes

2022-01-27 10:16 UTC, leslielazzarino commented on src/Frontend/Components/EditAttributionPopup/__tests__/EditAttributionPopup.test.tsx
> +// SPDX-FileCopyrightText: Facebook, Inc. and its affiliates
I would also add a single integration test for the new popup.

2022-01-27 12:38 UTC, mayayunx commented
> Some observations:
> 
> * when opening the popup and editing some fields, the text does not appear immediately after typing
> * on click away no popup for unsaved changes appears

2022-01-27 14:13 UTC, benedikt-richter commented on src/Frontend/Components/EditAttributionPopup/EditAttributionPopup.tsx
> +import { setUpdateTemporaryPackageInfoForCreator } from '../ResourceDetailsAttributionColumn/resource-details-attribution-column-helpers';
we should not import from these helpers, as these are only intended for the component next to it

2022-01-27 14:13 UTC, benedikt-richter commented on src/Frontend/Components/EditAttributionPopup/EditAttributionPopup.tsx
> +import { setUpdateTemporaryPackageInfoForCreator } from '../ResourceDetailsAttributionColumn/resource-details-attribution-column-helpers';
Maybe move to a shared place

2022-01-27 14:14 UTC, benedikt-richter commented on src/Frontend/Components/EditAttributionPopup/EditAttributionPopup.tsx
> +      }}
should be extracted

2022-01-27 14:15 UTC, benedikt-richter commented on src/Frontend/Components/NotSavedPopup/NotSavedPopup.tsx
> +  function reopenEditAttributionPopup(): void {
`reopenEditAttributionPopup` -> `reopenEditAttributionPopupIfItWasPreviouslyOpen`  or similar

2022-01-27 14:16 UTC, benedikt-richter commented on src/Frontend/Components/NotSavedPopup/__tests__/NotSavedPopup.test.tsx
> +    fireEvent.click(screen.queryByText('Cancel') as Element);
use enum istead of 'Cancel'

2022-01-27 14:19 UTC, benedikt-richter commented on src/Frontend/state/actions/view-actions/view-actions.ts
> +  openPopup: PopupType,
`openPopup` -> `openPopup` (it's clear from function name that it's the popup that's about to be opened)

2022-01-27 14:21 UTC, benedikt-richter commented on src/Frontend/state/reducers/view-reducer.ts
> +        },
could be:

```

{ popupInfo: action.payload }

```

2022-01-27 14:22 UTC, benedikt-richter commented on src/Frontend/state/selectors/all-views-resource-selectors.ts
> +  }
could be switch case

2022-01-27 14:30 UTC, benedikt-richter commented
lines 116 and 118 in attributionDetailsViewer can now be removed

2022-01-27 14:49 UTC, benedikt-richter requested changes
performance of popup in response of typing should be improved

2022-02-03 12:30 UTC, benedikt-richter approved these changes
the performance is good now 👍

2022-02-03 13:26 UTC, leslielazzarino approved these changes

2022-02-03 13:41 UTC, merged