Web workers in accordion optimized
opossum-tool/OpossumUI pull request #404
Opened 2022-02-04 12:51 UTC by leslielazzarino

### Summary of changes

New version, much optimized. Tests and css must still be fixed.

### Context and reason for change

Much shorter time to last bit.

### How can the changes be tested

With the keycloak test file.

Note: Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

2022-02-07 11:10 UTC, benedikt-richter commented
Seems to be less performant than on main

2022-02-21 09:23 UTC, benedikt-richter commented
Performance is good! 👍

2022-02-21 09:41 UTC, benedikt-richter requested changes
See comments. In particular, the architecture regarding imports should be respected

2022-02-21 09:41 UTC, benedikt-richter commented on src/Frontend/Components/AggregatedAttributionsPanel/AccordionPanel.tsx
> +// SPDX-FileCopyrightText: Facebook, Inc. and its affiliates
the copyright should be updated

2022-02-21 09:41 UTC, benedikt-richter commented on src/Frontend/Components/AggregatedAttributionsPanel/AccordionPanel.tsx
> +  const [expanded, setExpanded] = React.useState<boolean>(false);
`React.useState<boolean>(false);` -> `useState<boolean>(false);`

2022-02-21 09:41 UTC, benedikt-richter commented on src/Frontend/Components/AggregatedAttributionsPanel/AccordionPanel.tsx
> +function isDisabled(
typically we define these functions in the scope of the component

2022-02-21 09:41 UTC, benedikt-richter commented on src/Frontend/Components/AggregatedAttributionsPanel/WorkerAccordionPanel.tsx
> +export function WorkerAccordionPanel(
would be nice to try cleaning up typescript issues in this file. There are lot of ignore statements

2022-02-21 09:41 UTC, benedikt-richter commented on src/Frontend/Components/AggregatedAttributionsPanel/__tests__/AggregatedAttributionsPanel.test.tsx
> +} from '../../ResourceDetailsTabs/get-new-accordion-worker';
we should not import from the folders of other components (also some other occurences).

2022-02-21 09:41 UTC, benedikt-richter commented on src/Frontend/Components/App/App.tsx
> +} from '../ResourceDetailsTabs/get-new-accordion-worker';
App should not import from here

2022-02-21 09:41 UTC, benedikt-richter commented on src/Frontend/Components/App/App.tsx
> +          <AuditView resourceDetailsTabsWorkers={resourceDetailsTabsWorkers} />
would be good to use a context provider instead of passing it down the tree manually

2022-02-21 09:41 UTC, benedikt-richter commented on src/Frontend/Components/ResourceDetailsTabs/contained-external-attributions-accordion-worker.ts
> +let lestWeForget: AttributionData | null = null;
`lestWeForget`: hard to undertstand variable name

2022-02-22 12:57 UTC, benedikt-richter commented on src/Frontend/web-workers/contained-external-attributions-accordion-worker.ts
> +import { getContainedExternalPackages } from '../Components/ResourceDetailsTabs/resource-details-tabs-helpers';
should probably not import from `Components`

2022-02-22 12:57 UTC, benedikt-richter commented on src/Frontend/web-workers/contained-manual-attributions-accordion-worker.ts
> +import { getContainedManualPackages } from '../Components/ResourceDetailsTabs/resource-details-tabs-helpers';
should probably not import from `Components`

2022-02-22 12:59 UTC, nicarl reviewed
I agree with Benedikt for the imports and in particular I am for creating a context provider for the web workers

2022-02-22 12:59 UTC, nicarl commented on src/Frontend/Components/AggregatedAttributionsPanel/AccordionPanel.tsx
> +// SPDX-FileCopyrightText: Meta Platforms, Inc. and its affiliates
This should not be added anymore I guess

2022-02-22 12:59 UTC, nicarl commented on src/Frontend/Components/AggregatedAttributionsPanel/AccordionPanel.tsx
> +function isDisabled(
I think it depends a bit. This one here is solely a helper which would be fine for me outside of the component. I would like to see it before the `export function ...`

2022-02-22 12:59 UTC, nicarl commented on src/Frontend/Components/AggregatedAttributionsPanel/SyncAccordionPanel.tsx
> +// SPDX-FileCopyrightText: Meta Platforms, Inc. and its affiliates
Same here

2022-02-22 12:59 UTC, nicarl commented on src/Frontend/Components/AggregatedAttributionsPanel/WorkerAccordionPanel.tsx
> +export function WorkerAccordionPanel(
Maybe we can deactivate the `any` eslint rule for this file

2022-02-22 15:48 UTC, benedikt-richter commented on src/Frontend/Components/AggregatedAttributionsPanel/AccordionPanel.tsx
> +    setExpanded(Boolean(props.panelData.attributionIdsWithCount?.length > 0));
`Boolean` not needed

2022-02-22 15:48 UTC, benedikt-richter commented on src/Frontend/Components/AggregatedAttributionsPanel/AccordionPanel.tsx
> +function isDisabled(
no stong opinion, here

2022-02-22 15:48 UTC, benedikt-richter commented on src/Frontend/Components/AggregatedAttributionsPanel/AggregatedAttributionsPanel.tsx
> +} from '../ResourceDetailsTabs/resource-details-tabs-helpers';
should not import these helpers, as these should be component scoped

2022-02-22 15:48 UTC, benedikt-richter commented on src/Frontend/Components/AggregatedAttributionsPanel/SyncAccordionPanel.tsx
> +import { PanelData } from '../ResourceDetailsTabs/resource-details-tabs-helpers';
as above

2022-02-22 15:48 UTC, benedikt-richter commented on src/Frontend/Components/AggregatedAttributionsPanel/WorkerAccordionPanel.tsx
> +import { PanelData } from '../ResourceDetailsTabs/resource-details-tabs-helpers';
as above. Extract type to common place

2022-02-22 15:48 UTC, benedikt-richter commented on src/Frontend/Components/AggregatedAttributionsPanel/WorkerAccordionPanel.tsx
> +    return (): never => {
I don't think we need or should have a `never` here

2022-02-22 15:48 UTC, benedikt-richter commented on src/Frontend/Components/App/App.tsx
> +  };
as it seems we only need this combination. We could instead export a single getter for these.

2022-02-22 15:48 UTC, benedikt-richter commented on src/Frontend/web-workers/contained-external-attributions-accordion-worker.ts
> +let lestWeForget: AttributionData | null = null;
lestWeForget?

2022-02-23 13:32 UTC, leslielazzarino commented on src/Frontend/Components/AggregatedAttributionsPanel/AccordionPanel.tsx
> +function isDisabled(
I think what can be declared outside has no reason to stay inside, the execution is just less efficient. Concerning the position, I prefer to have the exported function first, and the dependencies below it, so that in the file you have a top-down approach. It does not work with every programming language, but when it works I find it easier to read: as you read down the page you move deeper into the code.

2022-02-23 13:40 UTC, leslielazzarino commented on src/Frontend/Components/AggregatedAttributionsPanel/WorkerAccordionPanel.tsx
> +export function WorkerAccordionPanel(
I have deactivated it for the file, typing improvement in this file will happen in a followup.

2022-02-23 13:42 UTC, leslielazzarino commented on src/Frontend/Components/App/App.tsx
> +          <AuditView resourceDetailsTabsWorkers={resourceDetailsTabsWorkers} />
That will be the follow up. For that reason, I will not unify the get workers, as they will be possibly needed separated.

2022-02-23 13:43 UTC, leslielazzarino commented on src/Frontend/web-workers/contained-external-attributions-accordion-worker.ts
> +import { getContainedExternalPackages } from '../Components/ResourceDetailsTabs/resource-details-tabs-helpers';
has been moved

2022-02-23 13:44 UTC, leslielazzarino commented on src/Frontend/web-workers/contained-external-attributions-accordion-worker.ts
> +let lestWeForget: AttributionData | null = null;
sorry, leftover from a moment of frustration :D

2022-02-23 13:46 UTC, leslielazzarino commented on src/Frontend/web-workers/contained-manual-attributions-accordion-worker.ts
> +import { getContainedManualPackages } from '../Components/ResourceDetailsTabs/resource-details-tabs-helpers';
Changed

2022-02-25 09:58 UTC, benedikt-richter requested changes

2022-02-25 09:58 UTC, benedikt-richter commented on .github/workflows/build-and-e2e-test.yml
> +            E2E: ''
a comment would be nice

2022-02-25 09:58 UTC, benedikt-richter commented on src/Frontend/Components/AggregatedAttributionsPanel/AccordionPanel.tsx
> +  disabledAccordion: {},
is this class needed?

2022-02-25 09:58 UTC, benedikt-richter commented on src/Frontend/Components/AggregatedAttributionsPanel/AggregatedAttributionsPanel.tsx
> +  const resolvedExternalAttributions: Set<string> = useAppSelector(
why do we state the type here?

2022-02-25 09:58 UTC, benedikt-richter commented on src/Frontend/Components/AggregatedAttributionsPanel/AggregatedAttributionsPanel.tsx
> +  const containedExternalPackagesWorkerArgs = useMemo(
could be useCallback

2022-02-25 09:58 UTC, benedikt-richter commented on src/Frontend/Components/AggregatedAttributionsPanel/AggregatedAttributionsPanel.tsx
> +  const containedExternalPackagesSyncFallbackArgs = useMemo(
could be useCallback

2022-02-25 09:58 UTC, benedikt-richter commented on src/Frontend/Components/AggregatedAttributionsPanel/AggregatedAttributionsPanel.tsx
> +  const containedManualPackagesWorkerArgs = useMemo(
could be useCallback

2022-02-25 09:58 UTC, benedikt-richter commented on src/Frontend/Components/App/App.tsx
> +  useMemo(() => {
could be useCallback

2022-02-25 09:58 UTC, benedikt-richter commented on src/Frontend/Components/ResourceDetailsTabs/ResourceDetailsTabs.tsx
> +  const aggregatedAttributionsPanel = useMemo(
could be useCallback

2022-02-25 15:39 UTC, leslielazzarino commented on src/Frontend/Components/App/App.tsx
> +  };
I would not unify the get workers, as they will be possibly needed separated in the context manager follow up.

2022-02-28 10:16 UTC, benedikt-richter approved these changes

2022-02-28 18:34 UTC, nicarl approved these changes
Just two tiny comments

2022-02-28 18:34 UTC, nicarl commented on src/Frontend/Components/AggregatedAttributionsPanel/WorkerAccordionPanel.tsx
> +    let active = true;
Would be good to have a comment on the `let active` variable

2022-03-03 07:56 UTC, benedikt-richter commented on src/Frontend/Components/AggregatedAttributionsPanel/WorkerAccordionPanel.tsx
> +export interface AttributionIdsWithCountAndResourceId {
should go into shared types

2022-03-03 09:37 UTC, leslielazzarino commented on src/Frontend/Components/AggregatedAttributionsPanel/WorkerAccordionPanel.tsx
> +  console.log(`Error in ResourceDetailsTab ${panelTitle}: `, error);
console is, between other things, a powerful logging library, that includes .info, .warning, .error functions. Is there a specific feature you would want, that I'm not using and that is not available with console? Otherwise I do not think we need any special library.

2022-03-03 09:37 UTC, leslielazzarino commented on src/Frontend/Components/App/App.tsx
> +      console.log('WebWorker error in App component: ', error);
See other comment.

2022-03-03 09:38 UTC, leslielazzarino commented on src/Frontend/Components/AggregatedAttributionsPanel/WorkerAccordionPanel.tsx
> +    let active = true;
Due to an edge-case I have rewritten how I handle race conditions.

2022-03-03 10:36 UTC, benedikt-richter requested changes
There are many console logs that spam the test terminal:

` console.log
      WebWorker error in App component:  Error: JEST-MOCK-GET-NEW-CONTAINED-EXTERNAL-ATTRIBUTIONS-ACCORDION-WORKER`

2022-03-03 13:23 UTC, benedikt-richter approved these changes

2022-03-03 14:13 UTC, merged