Extract virtualized tree
opossum-tool/OpossumUI pull request #405
Opened 2022-02-04 13:00 UTC by benedikt-richter

### Summary of changes

Extract virtualized tree into own folder

### Context and reason for change

Preparation for publishing in own package

2022-02-07 16:48 UTC, nicarl approved these changes
Nit: `get-tree-node-props.test.ts` has one variable left which is called `item`

2022-02-08 07:14 UTC, nicarl approved these changes

2022-02-08 07:22 UTC, leslielazzarino requested changes

2022-02-08 07:22 UTC, leslielazzarino commented on src/Frontend/Components/ResourceBrowser/ResourceBrowser.tsx
> +    height: 19,
This should be controlled through cardHeight, not through styling

2022-02-08 07:22 UTC, leslielazzarino commented on src/Frontend/extracted/VirtualisedTree/VirtualizedTree.tsx
> +  treeNodeStyle?: TreeNodeStyle;
I would like to have our style as default here, for quick fist use by the user. The user-defined classes should be added to the default ones with clsx, so that the user can even just overwrite a few.

2022-02-08 07:27 UTC, benedikt-richter commented on src/Frontend/extracted/VirtualisedTree/VirtualizedTree.tsx
> +  treeNodeStyle?: TreeNodeStyle;
Our style depends on the opossum colors. Not sure how this could be the default without duplicating the colors. However, having some reasonable default style is a good idea.

2022-02-08 07:44 UTC, benedikt-richter commented on src/Frontend/extracted/VirtualisedTree/VirtualizedTree.tsx
> +  treeNodeStyle?: TreeNodeStyle;
I'd suggest a separate diff to come up with a solid default styling.

2022-02-08 07:52 UTC, leslielazzarino approved these changes

2022-02-08 08:19 UTC, merged