Propagate green if all children have attributions
opossum-tool/OpossumUI pull request #425
Opened 2022-02-09 15:02 UTC by mayayunx

Signed-off-by: Ruiyun Xie <ruiyun.xie@tum.de>

### Summary of changes
- Green color will be propagated to parent folder if all resources inside have an attribution

### Context and reason for change
- User shall get visible feedback about that, If all resources in a folder have an attribution
- Fix: #424

### How can the changes be tested
- In the UI

2022-02-23 15:43 UTC, benedikt-richter commented
Looks good!

I'll still test performance.

2022-02-24 09:33 UTC, leslielazzarino requested changes

2022-02-24 09:33 UTC, leslielazzarino commented on src/Frontend/Components/ResourceBrowser/get-tree-item-label.tsx
> +    resourcesWithExternalAttributedChildren[nodeId] &&
The logic in this function is extremely inefficient for folders with a lot of signals. We look for (mostly parent) attributions for each and every resource with signals. We should navigate the node sub-tree top-down recursively, ignoring branches as soon as a folder has an attribution. That would be much more efficient. 
If one wanted to be thorough, the children with external/manual attributions was implemented a while ago, when we wanted to show arrows for each resource. Now that we want to show other information it would be best to rebuild it, optimized for the new visuals. But it would be more expensive and should be packed in a technical debt ticket.

2022-02-24 14:31 UTC, benedikt-richter approved these changes

2022-02-24 15:07 UTC, leslielazzarino approved these changes

2022-02-24 15:53 UTC, merged