Fix purl handling
opossum-tool/OpossumUI pull request #450
Opened 2022-02-17 13:30 UTC by mayayunx

Signed-off-by: Ruiyun Xie <ruiyun.xie@tum.de>

### Summary of changes
- display what user enters in the purl box and do not regenerate the purl after each input
- check and regenerate purl on save or undo

### Context and reason for change
The purl handling does not work for some cases as it regenerates the purl after each input

### How can the changes be tested
The changes can be tested by runnning `yarn test:integration-ci` and in the UI

2022-02-21 09:55 UTC, benedikt-richter commented
Observations:
* when modifying PURL:
1) the first character of the change makes PURL invalid -> clicking on another resource in the tree just navigates there without popup
2) the first character modifies e.g. package name and subsequent changes make PURL invalid -> clicking on another resource in the tree shows popup (if I click undo the changes are undone)
3) the first character modifies e.g. package name and subsequent changes make PURL invalid -> clicking on other attribution of same resource  shows popup (if I click undo the changes are undone BUT the PURL is not reset)

2022-02-21 10:43 UTC, benedikt-richter commented on src/Frontend/Components/AttributionColumn/AttributionColumn.tsx
> +    generateAndUpdatePurlOnSaveOrUndo,
`generateAndUpdatePurlOnSaveOrUndo` could be named `generateAndUpdatePurl`

2022-02-21 10:50 UTC, benedikt-richter requested changes
see comments

2022-02-21 10:52 UTC, leslielazzarino requested changes

2022-02-21 10:52 UTC, leslielazzarino commented on src/Frontend/Components/AttributionColumn/__tests__/AttributionColumn.test.tsx
> +    expectValueInTextBox(
These test cases should be separated into several tests. The general pattern is each test should test only for one thing. That allows you to write in the test name exactly what you are testing for.

2022-02-21 10:52 UTC, leslielazzarino commented on src/Frontend/Components/AttributionColumn/attribution-column-helpers.ts
> +  function generateAndUpdatePurlOnSaveOrUndo(packageInfo: PackageInfo): void {
I think just "updatePurlOnSaveOrUndo" would be enough, the generate is implicit in most functions.

2022-02-23 12:43 UTC, benedikt-richter approved these changes
👍

2022-02-23 12:44 UTC, benedikt-richter commented
> Observations:
> 
>     * when modifying PURL:
> 
> 
>     1. the first character of the change makes PURL invalid -> clicking on another resource in the tree just navigates there without popup
> 
>     2. the first character modifies e.g. package name and subsequent changes make PURL invalid -> clicking on another resource in the tree shows popup (if I click undo the changes are undone)
> 
>     3. the first character modifies e.g. package name and subsequent changes make PURL invalid -> clicking on other attribution of same resource  shows popup (if I click undo the changes are undone BUT the PURL is not reset)


As discussed the last one is related to a bug in the navigation and will be fixed independently.

2022-02-23 15:53 UTC, leslielazzarino approved these changes

2022-02-23 16:50 UTC, merged