Add support for searching information on clearly defined
opossum-tool/OpossumUI pull request #472
Opened 2022-02-27 20:31 UTC by nicarl

### Summary of changes

This adds support for fetching information from ClearlyDefined as described in #299.

### Context and reason for change

Motivation described in #299.

### How can the changes be tested

See screenshot + execute unit tests

Fix #299

2022-02-27 20:36 UTC, nicarl commented on package.json
> +    "axios": "^0.26.0",
I decided to add axios at it is more convenient than `fetch`

2022-02-27 20:36 UTC, nicarl commented on package.json
> +    "url": "^0.11.0",
I had to add this because `webpack 5` does not support polyfill anymore. We should look into this together.

2022-02-27 20:36 UTC, nicarl commented on src/Frontend/Components/PackageSearchPopup/ClearlyDefinedPackageCard.tsx
> +    width: '25%',
There are still two problems with the css here.I was not able to solve these problems:

![css_hell2](https://user-images.githubusercontent.com/26271333/155898951-f708ab41-1709-4bbc-a073-6f86c27df304.png)
![css_hell_1](https://user-images.githubusercontent.com/26271333/155898953-696af803-2690-4008-b52e-e5ea369893e4.png)

2022-02-28 07:36 UTC, nicarl commented on src/Frontend/Components/PackageSearchPopup/ClearlyDefinedPackageCard.tsx
> +    width: '25%',
One problem seems to be that `width` in percentage does not play along with ellipsis :-(

2022-02-28 11:51 UTC, benedikt-richter commented on src/Frontend/Components/PackageSearchPopup/ClearlyDefinedPackageCard.tsx
> +import { Accordion as MuiAccordion } from '@mui/material';
Imports should follow the pattern used in line 6

2022-02-28 11:51 UTC, benedikt-richter commented on src/Frontend/Components/PackageSearchPopup/ClearlyDefinedPackageCard.tsx
> +import { Accordion as MuiAccordion } from '@mui/material';
also other occurences

2022-02-28 11:51 UTC, benedikt-richter commented on src/Frontend/Components/PackageSearchPopup/PackageSearchPopup.tsx
> +      enabled: !!currentSearchTerm,
(suggestion) `enabled: !!currentSearchTerm` -> `enabled: Boolean(currentSearchTerm)`

2022-02-28 11:51 UTC, benedikt-richter commented on src/Frontend/Components/PackageSearchPopup/PackageSearchPopup.tsx
> +        </div>
Would be nice to extract to use consistently throughout the app

2022-02-28 11:51 UTC, benedikt-richter commented on src/Frontend/Components/PackageSearchPopup/PackageSearchPopup.tsx
> +        </MuiAlert>
Would be nice to extract to use consistently throughout the app

2022-02-28 11:51 UTC, benedikt-richter commented on src/Frontend/Components/AttributionColumn/PackageSubPanel.tsx
> +              icon={<SearchIcon aria-label={'Search packages icon'} />}
the icon should be styled like to other icons in the app. Would also be good to move it to Icons.tsx

2022-02-28 11:51 UTC, benedikt-richter commented on src/Frontend/Components/AttributionColumn/PackageSubPanel.tsx
> +                dispatch(openPopup(PopupType.PackageSearchPopup));
so far the sub panel is not connected to the Redux store. However, not sure this callback should be provided as prop from parent

2022-02-28 12:03 UTC, benedikt-richter commented
Some observations:
* the search icon also works for empty name and version in attributions. Maybe disable it if there is no name?
* the search icon does not work for signals. However, this is not transparent to the user as visually it looks the same as in the case of attributions
* if I open the edit attribution popup and click on the search icon the search popup opens. When clicking on "cancel", I do not get back to the edit attribution popup
* in the case where no results are found in the search popup it would be nice to display a hint like "no results found". Curently, the user might suspect it's broken in this case

2022-02-28 20:03 UTC, nicarl commented
> Some observations:
> 
>     * the search icon also works for empty name and version in attributions. Maybe disable it if there is no name?
This should be fixed now. The field is only populated if there is a package name.

>     * the search icon does not work for signals. However, this is not transparent to the user as visually it looks the same as in the case of attributions

I changed the styling to make the icon grey if it not activated.

>     * if I open the edit attribution popup and click on the search icon the search popup opens. When clicking on "cancel", I do not get back to the edit attribution popup

This should be fixed now, the openPopup needs to be an array to "remember" the previously opened popups

>     * in the case where no results are found in the search popup it would be nice to display a hint like "no results found". Curently, the user might suspect it's broken in this case
I added the text :+1:

2022-03-01 12:11 UTC, leslielazzarino requested changes

2022-03-01 12:53 UTC, nicarl commented on src/Frontend/Components/PackageSearchPopup/ClearlyDefinedPackageCard.tsx
> +              {isLoading ? <MuiSkeleton width="60px" /> : data?.url ?? ''}
The `<MuiSkeleton />` detects the type of `MuiTypography` from the parent (https://mui.com/components/skeleton/#inferring-dimensions)

2022-03-01 19:09 UTC, nicarl commented
I will squash the commits before merging.

2022-03-01 19:09 UTC, nicarl commented on src/Frontend/Components/PackageSearchPopup/ClearlyDefinedPackageCard.tsx
> +              {isLoading ? <MuiSkeleton width="60px" /> : data?.url ?? ''}
I decided to do as you suggested

2022-03-02 11:47 UTC, benedikt-richter commented
It seems the PURL is not updated after adding an entry from clearly defined

![Screenshot 2022-03-02 at 12 39 38](https://user-images.githubusercontent.com/46576389/156355998-516c7050-6b5a-4cdc-b106-c60d2e07ea33.png)

2022-03-02 11:48 UTC, benedikt-richter commented
The two icons could be a bit smaller

![Screenshot 2022-03-02 at 12 39 38](https://user-images.githubusercontent.com/46576389/156356166-6455dd9b-f5ba-4ac3-b32a-8035f47beea8.png)

2022-03-02 11:49 UTC, benedikt-richter commented
It might be good to exclude the namespace from the search term, while keeping the type

2022-03-02 18:25 UTC, nicarl commented on src/Frontend/Components/AttributionColumn/attribution-column-helpers.ts
> -    // Dependency for displayPackageInfo is not included because otherwise displayed purl will be regenerated after every new input
Did we see any performance penalty for this?

2022-03-03 06:57 UTC, benedikt-richter commented on src/Frontend/Components/AttributionColumn/attribution-column-helpers.ts
> -    // Dependency for displayPackageInfo is not included because otherwise displayed purl will be regenerated after every new input
If you add  displaypackageInfo to the dependency array, the UI has some delay if you type fast.  It's not too bad but you'll recognize.

2022-03-03 07:01 UTC, nicarl commented on src/Frontend/Components/AttributionColumn/attribution-column-helpers.ts
> -    // Dependency for displayPackageInfo is not included because otherwise displayed purl will be regenerated after every new input
I think in this case we should debounce the input via the debounce hook I added in this PR. What do you think?

2022-03-03 07:08 UTC, benedikt-richter commented
New behaviour:
* open the edit popup on report view
* edit some field
* press "cancel"
* the unsaved changes popup is shown
* press "undo" or "save" there
* expected: there is no popup shown and you're back to report view
* reality: you're still on edit popup

2022-03-03 07:11 UTC, benedikt-richter commented on src/Frontend/Components/AttributionColumn/attribution-column-helpers.ts
> -    // Dependency for displayPackageInfo is not included because otherwise displayed purl will be regenerated after every new input
That should work :)

2022-03-03 07:16 UTC, benedikt-richter commented on src/Frontend/Components/AttributionColumn/attribution-column-helpers.ts
> -    // Dependency for displayPackageInfo is not included because otherwise displayed purl will be regenerated after every new input
(optional if you want to look into it) btw we also debounce the input for file search. Maybe this could also use the same hook

2022-03-08 20:21 UTC, nicarl commented
> 

Should be fixed now

2022-03-08 20:23 UTC, nicarl commented on src/Frontend/Components/AttributionColumn/attribution-column-helpers.ts
> -    // Dependency for displayPackageInfo is not included because otherwise displayed purl will be regenerated after every new input
I decided to use namespace, type and name in the dependency array. This should fix 90% of the problems. I think rethinking purl input is out of scope for this feature.

2022-03-09 08:41 UTC, benedikt-richter approved these changes
awesome 👍

2022-03-09 10:16 UTC, leslielazzarino approved these changes

2022-03-09 10:16 UTC, merged