Use context provider for passing web workers
opossum-tool/OpossumUI pull request #482
Opened 2022-03-02 13:53 UTC by mayayunx

Signed-off-by: Ruiyun Xie <ruiyun.xie@tum.de>

### Summary of changes
- Use context provider to pass and get accordion web workers

### Context and reason for change
- Now web workers are loaded in the App component and forwarded through multiple components 

### How can the changes be tested
- Run `yarn test:unit`, `yarn test:integration-ci` and `yarn test:e2e`

2022-03-02 14:29 UTC, benedikt-richter commented on src/Frontend/Components/App/App.tsx
these lines could be moved to AppContainer

2022-03-02 14:38 UTC, benedikt-richter commented on src/Frontend/Components/AggregatedAttributionsPanel/WorkerAccordionPanel.tsx
> +  const worker =
would be nice to also check the title in the else case.

2022-03-03 07:32 UTC, benedikt-richter commented on src/Frontend/Components/App/App.tsx
If you move these lines, you can remove the `useContext(WorkersContext);`.
Actually, we could create a new component for the context. Let's discuss later. It could look something like


```

const resourceDetailsTabsWorkers: ResourceDetailsTabsWorkers = {
  containedExternalAttributionsAccordionWorker:
    getNewContainedExternalAttributionsAccordionWorker(),
  containedManualAttributionsAccordionWorker:
    getNewContainedManualAttributionsAccordionWorker(),
};
export const WorkersContext = React.createContext(resourceDetailsTabsWorkers);

const ContextProvider: FC = ({ children }) => {
  const externalData = useAppSelector(getExternalData);

  function loadExternalDataInWebWorker(
    externalData: AttributionData,
    worker: Worker
  ): void {
    worker.postMessage({ externalData });
  }

  useMemo(() => {
    try {
      loadExternalDataInWebWorker(
        externalData,
        resourceDetailsTabsWorkers.containedExternalAttributionsAccordionWorker
      );
    } catch (error) {
      console.log('WebWorker error in App component: ', error);
    }
  }, [externalData]);
  return (
    <WorkersContext.Provider value={resourceDetailsTabsWorkers}>
      {children}
    </WorkersContext.Provider>
  );
};

```

2022-03-03 07:36 UTC, benedikt-richter requested changes
let's extract a new component for the worker context provider

2022-03-03 07:39 UTC, benedikt-richter commented on src/Frontend/Components/AggregatedAttributionsPanel/WorkerAccordionPanel.tsx
> +      : null;
if null we could throw an error

2022-03-03 13:25 UTC, benedikt-richter commented
needs to be rebased

2022-03-03 14:44 UTC, leslielazzarino requested changes

2022-03-03 14:44 UTC, leslielazzarino commented on src/Frontend/Components/ContextProvider/ContextProvider.tsx
> +      console.log('WebWorker error in App component: ', error);
After rebasing this .log should be changed to .info

2022-03-03 14:44 UTC, leslielazzarino commented on src/Frontend/Components/AggregatedAttributionsPanel/WorkerAccordionPanel.tsx
> +      : null;
I would slightly prefer a switch here, but probably Benedikt does not agree :D

2022-03-03 14:44 UTC, leslielazzarino commented on src/Frontend/Components/AggregatedAttributionsPanel/WorkerAccordionPanel.tsx
> +  }
I do not think we should throw here, we have fallback sync code that will work just fine if no worker is returned.

2022-03-03 14:44 UTC, leslielazzarino commented on src/Frontend/Components/AggregatedAttributionsPanel/WorkerAccordionPanel.tsx
> +      : null;
Also having a switch over an enum yopu do not need to cover the null case. To do that, you need to brake the Package panel titles in worker and non worker enums, and join them.

2022-03-03 14:44 UTC, leslielazzarino commented on src/Frontend/Components/AggregatedAttributionsPanel/WorkerAccordionPanel.tsx
> +  if (worker) {
This if should be replaced by better typing

2022-03-04 09:26 UTC, benedikt-richter commented on src/Frontend/Components/ContextProvider/ContextProvider.tsx
> +function loadExternalDataInWebWorker(
not sure it's worth extracting this function that contains a single line

2022-03-04 09:26 UTC, benedikt-richter commented on src/Frontend/Components/ContextProvider/ContextProvider.tsx
> +      console.info('WebWorker error in App component: ', error);
the message should be updated

2022-03-04 09:26 UTC, benedikt-richter commented on src/Frontend/Components/ContextProvider/ContextProvider.tsx
> +export const ContextProvider: FC = ({ children }) => {
the name is very generic. Could be `WorkersContextProvider`

2022-03-04 09:27 UTC, benedikt-richter reviewed
Nice. Just minor comments

2022-03-04 09:34 UTC, leslielazzarino approved these changes

2022-03-04 09:34 UTC, leslielazzarino commented on src/Frontend/Components/ContextProvider/ContextProvider.tsx
> +    getNewContainedExternalAttributionsAccordionWorker(),
Merge the two getters

2022-03-04 09:52 UTC, benedikt-richter approved these changes

2022-03-04 11:12 UTC, merged