Highlight incomplete attributions attribution view
opossum-tool/OpossumUI pull request #487
Opened 2022-03-03 10:08 UTC by mayayunx

Signed-off-by: Ruiyun Xie <ruiyun.xie@tum.de>

### Summary of changes
- Highlight missing fields in attribution view with the same logic as in report view
- Highlight package card on the left side with triangle if there are missing fields

### Context and reason for change
- As a user I want to be able to quickly see which attributions are missing some important fields. 

### How can the changes be tested
The changes can be tested in the UI.

2022-03-03 10:18 UTC, benedikt-richter commented on src/Frontend/Components/AttributionColumn/AuditingSubPanel.tsx
> +                props.displayPackageInfo.attributionConfidence < 50)
this is duplicated logic

2022-03-03 10:19 UTC, benedikt-richter commented on src/Frontend/Components/ListCard/ListCard.tsx
> +        ' 44.5px, ' +
this is duplicated multiple times

2022-03-03 10:23 UTC, benedikt-richter requested changes
In the context of the report view the logic whether a field is highlighted is encoded in the function `isMarkedTableCell` this logic should not be duplicated for report view and for attribution view but only be implemented once.

2022-03-03 16:09 UTC, nicarl commented on src/Frontend/util/is-information-missing.ts
> +  attributionProperty: string,
I think we could benefit from stricter typing here. Either use an enum or a string literal

2022-03-07 07:49 UTC, benedikt-richter commented on src/Frontend/Components/ListCard/ListCard.tsx
> +const getBackground = (backgroundColor: string): string => {
this name is very generic. Would be good to find a more specific one.

2022-03-07 07:53 UTC, benedikt-richter requested changes

2022-03-07 07:53 UTC, benedikt-richter commented on src/Frontend/Components/ListCard/ListCard.tsx
> +            ? classes.highLightedSelected
`highLightedSelected` -> `highlightedSelected`

2022-03-07 07:53 UTC, benedikt-richter commented on src/Frontend/Components/ListCard/ListCard.tsx
> +        props.highlightedCard && classes.highLightedPackage
general comment:

consolidate "high**l**ighted" vs "high**L**ighted"

2022-03-07 07:53 UTC, benedikt-richter commented on src/Frontend/util/is-information-missing.ts
> +export function isInformationMissing(
this name is very generic and be made more specific

2022-03-07 07:53 UTC, benedikt-richter commented on src/Frontend/util/is-information-missing.ts
> +import { AttributionInfo } from '../Components/Table/Table';
we should not import from components to util

2022-03-07 07:53 UTC, benedikt-richter commented on src/Frontend/util/is-information-missing.ts
> +  attributionProperty: keyof PackageInfo | keyof AttributionInfo | 'icons',
if the variable `attributionInfo` is of tpye `PackageInfo` how can there be the property `icons`? Also why would we need `keyof AttributionInfo`?

2022-03-08 19:23 UTC, nicarl commented on src/Frontend/util/is-information-missing.ts
> +import { AttributionInfo } from '../Components/Table/Table';
We should have an eslint rule for this

2022-03-09 09:15 UTC, mayayunx commented on src/Frontend/util/is-information-missing.ts
> +  attributionProperty: keyof PackageInfo | keyof AttributionInfo | 'icons',
I added `keyof AttributionInfo` and `icons` since otherwise there are errors regarding to the types when using it in the report view. But I changed it now and check the type before calling the function

2022-03-09 10:22 UTC, benedikt-richter commented
When hovering the package card, the red part of the card should also change its color.

2022-03-09 14:53 UTC, benedikt-richter approved these changes

2022-03-09 15:56 UTC, nicarl approved these changes

2022-03-09 15:56 UTC, merged