Improve report view
opossum-tool/OpossumUI pull request #488
Opened 2022-03-03 15:07 UTC by mayayunx

Signed-off-by: Ruiyun Xie <ruiyun.xie@tum.de>

### Summary of changes
Improvements on report view:
- if there is a incomplete field, highlight the icon column
- the license name should be bold if it matches a frequent license
- frequent license texts should be greyed out

### Context and reason for change
- To better recognize which attribution is incomplete
- emphasize frequent license

### How can the changes be tested
In the UI

2022-03-04 09:59 UTC, antonbauhofer approved these changes
Looks good and works as expected.
Just one optional remark to consider.

2022-03-04 09:59 UTC, antonbauhofer commented on src/Frontend/Components/ReportTableItem/ReportTableItem.tsx
> +    };
Nitpick: Not sure why we write them as arrow functions. They are not used as callbacks, so I would not expect arrow functions.

2022-03-04 11:17 UTC, leslielazzarino requested changes

2022-03-04 11:17 UTC, leslielazzarino commented on src/Frontend/Components/ReportTableItem/ReportTableItem.tsx
> +          attributionInfo.licenseText ===
getAttributionsWithResourcesIncludingLicenseTexts in ReportView

2022-03-09 09:27 UTC, mayayunx commented on src/Frontend/Components/ReportTableItem/ReportTableItem.tsx
> +    };
Changed to constants

2022-03-09 11:55 UTC, benedikt-richter commented on src/Frontend/Components/ReportTableItem/ReportTableItem.tsx
> +      console.log('show grey text', showGreyText);
consloe.log ;)

2022-03-09 12:32 UTC, mayayunx commented on src/Frontend/Components/ReportTableItem/ReportTableItem.tsx
> +      console.log('show grey text', showGreyText);
This commit is only for temporary testing, since I couldn't find my error and Leslie would help me with that

2022-03-16 08:47 UTC, leslielazzarino approved these changes

2022-03-16 08:47 UTC, merged