Split ResourcePathPopup resource list in current and other folders
opossum-tool/OpossumUI pull request #51
Opened 2021-10-04 09:00 UTC by jonas-tai

If resources in other folders exist, the resource list shows the resources in the current folder at the top and the resources in other folders underneath, separated by a new header.

Signed-off-by: Jonas Tai <jonas.tai@tngtech.com>

2021-10-04 13:10 UTC, benedikt-richter commented on src/Frontend/Components/ResourcePathPopup/resource-path-popup-helpers.ts
> +  currentFolderResourceIds: string[],
Arrays should use `Array<string>`

2021-10-04 13:10 UTC, benedikt-richter commented on src/Frontend/Components/ResourcePathPopup/resource-path-popup-helpers.ts
> +  currentFolderResourceIds: string[],
also other places

2021-10-04 13:11 UTC, benedikt-richter commented on src/Frontend/Components/ResourcePathPopup/resource-path-popup-helpers.ts
> +): [string[], string[]] {
here, returning an object improves clarity, as keys can have speaking names.

2021-10-04 13:24 UTC, benedikt-richter commented on src/Frontend/Components/ResourcesList/ResourcesList.tsx
> +
would be nice to have a single return.
Instead of using 'doNothing' the prop `onClick' could be optional

2021-10-04 13:28 UTC, benedikt-richter commented on src/Frontend/Components/ResourcePathPopup/resource-path-popup-helpers.ts
> +export function insertHeaderForOtherFolderResourceIds(
functions should not have dide effects. And if they have they should not return a value.

2021-10-04 13:29 UTC, benedikt-richter commented on src/Frontend/Components/ResourcesList/ResourcesList.tsx
> +  headerIndices?: Array<number>;
instead of indices, we could provide the actual paths

2021-10-05 05:53 UTC, leslielazzarino requested changes
I agree on all comments from Benedikt, where I haven't commented.

2021-10-05 05:53 UTC, leslielazzarino commented on src/Frontend/Components/ResourcesList/ResourcesList.tsx
> +
I agree on combining the two returns int oone, makes it clear what the difference is. But I am fine with doNothing: it makes it more prominent that in this very special case the card is not clickable.

2021-10-06 09:52 UTC, leslielazzarino approved these changes

2021-10-06 09:54 UTC, benedikt-richter commented on src/Frontend/Components/ResourcePathPopup/resource-path-popup-helpers.ts
> +  };
could be 

```
  return {
    currentFolderResourceIds: currentFolderResourceIds.sort(),
    otherFolderResourceIds
  };


```

2021-10-06 09:54 UTC, benedikt-richter commented on src/Frontend/Components/ResourcePathPopup/resource-path-popup-helpers.ts
> +  currentFolderResourceIds.sort();
why are `otherFolderResourceIds` not sorted?

2021-10-06 09:55 UTC, benedikt-richter commented on src/Frontend/Components/ResourcePathPopup/resource-path-popup-helpers.ts
> +  (allResourceIds ?? []).forEach((resourceId) => {
could be `allResourceIds?.forEach((resourceId) => {`

2021-10-06 09:55 UTC, benedikt-richter commented on src/Frontend/Components/ResourcesList/ResourcesList.tsx
> +  });
shouzld probably be moved into : `convertResourcesListBatchesToResourcesListItems`

2021-10-06 09:56 UTC, benedikt-richter commented on src/Frontend/Components/ResourcePathPopup/resource-path-popup-helpers.ts
> +export function splitResourceItToCurrentAndOtherFolder(
`splitResourceItToCurrentAndOtherFolder` -> `splitResourceIdsToCurrentAndOtherFolder`

2021-10-06 09:57 UTC, benedikt-richter commented on src/Frontend/Components/ResourcesList/ResourcesList.tsx
> +import { ResourcesListBatch, ResourcesListItem } from '../../types/types';
would be nice to define `ResourcesListItem` in the component and export from there as it's quite specific

2021-10-06 09:57 UTC, benedikt-richter commented on src/Frontend/Components/ResourcesList/ResourcesList.tsx
> +        }
could be extracted into a constant as there is quite some logic involved

2021-10-06 09:58 UTC, benedikt-richter commented on src/Frontend/Components/ResourcesList/ResourcesList.tsx
> +        onClick={resourcesListItems[index].isHeader ? doNothing : onPathClick}
`resourcesListItems[index].isHeader` could be a constant as it's used repeatedly

2021-10-06 10:00 UTC, benedikt-richter commented on src/Frontend/Components/ResourcesList/__tests__/resource-list-helpers.test.ts
> +    const resourcesListBatches = [
in tests it is very helpful to declare the type for such test data `const resourcesListBatches: $TYPE`

2021-10-06 10:00 UTC, benedikt-richter commented on src/Frontend/Components/ResourcesList/__tests__/resource-list-helpers.test.ts
> +  });
should be extracted to constant. Similar in some other tests

2021-10-06 10:01 UTC, benedikt-richter commented on src/Frontend/state/helpers/action-and-reducer-helpers.ts
> +  resourceIds: Array<string>
👍

2021-10-06 10:02 UTC, benedikt-richter requested changes
Looks good and works nicely 👍 

Just some code style comments

2021-10-06 12:26 UTC, jonas-tai commented on src/Frontend/Components/ResourcePathPopup/resource-path-popup-helpers.ts
> +  };
Deleted the sorting, because the ResourcesList component already does that

2021-10-06 12:26 UTC, jonas-tai commented on src/Frontend/Components/ResourcePathPopup/resource-path-popup-helpers.ts
> +  currentFolderResourceIds.sort();
No longer required because of the ResourcesList component

2021-10-06 12:28 UTC, jonas-tai commented on src/Frontend/Components/ResourcesList/ResourcesList.tsx
> +  });
I decided to separate them, in case we do not want to sort for other use cases of the component.

2021-10-06 14:03 UTC, benedikt-richter approved these changes
nice 👍 

just a comment regarding a test

2021-10-06 14:03 UTC, benedikt-richter commented on src/Frontend/Components/ResourcePathPopup/__tests__/resource-path-popup-helpers.test.ts
> +  });
What is the purpose of this test?
The function signature suggests that `allResourceIds` is an array of strings. If it is not the function signature should be adapted. However, I guess, we can just remove this test.

2021-10-06 14:46 UTC, merged