Highlight critical signals
opossum-tool/OpossumUI pull request #510
Opened 2022-03-10 09:42 UTC by antonbauhofer

### Summary of changes

Critical signals and pre-selected attributions are highlighted in the audit and attribution view. If a critical pre-selected attribution is confirmed, it is not highlighted anymore.

### Context and reason for change

In input documents, signals can now be marked as critical, if they are specifically important to consider or marked as red flags. To make the review process more effective, these signals are highlighted in OpossumUI.

### How can the changes be tested

Open the test input file `opossum_input.json` and view the signals contained in the root folder or navigate to the attribution view.

2022-03-11 09:04 UTC, benedikt-richter commented on example-files/opossum_input.json
> +    "bb61b094-b5ba-4bd0-b218-8ec96b7c5ae1": {
Now we have typescript three times as signal. All very similar (with same url...). Therefore, it's not easy to distinguish these on e.g. package cards. Maybe this is an opportunity to improve on this

2022-03-11 09:16 UTC, benedikt-richter commented on src/Frontend/Components/AttributionList/AttributionList.tsx
> +        : undefined,
could be `attribution.preSelected && attribution.criticality`

2022-03-11 09:17 UTC, benedikt-richter commented on src/Frontend/Components/PackageList/PackageList.tsx
> +      criticality: isPreselected ? packageInfo.criticality : undefined,
as above

2022-03-11 10:23 UTC, antonbauhofer commented on src/Frontend/Components/AttributionList/AttributionList.tsx
> +        : undefined,
This gives a typing error. But we can leave out the cast to Boolean.

2022-03-11 10:53 UTC, antonbauhofer commented on example-files/opossum_input.json
> +    "bb61b094-b5ba-4bd0-b218-8ec96b7c5ae1": {
I replaced two of the occurrences.

2022-03-14 07:38 UTC, benedikt-richter approved these changes
please squash commits

2022-03-15 09:59 UTC, nicarl approved these changes
Changes and styling looks good. I just wonder one thing: for now `criticality` is a somewhat hidden property of an attribution. In particular in the `Attribution View` it is hard to distinguish between incomplete and critical attributions.
Maybe we can at least add an on hover text to display the reason why an attribution is marked?

2022-03-15 11:03 UTC, benedikt-richter requested changes
the package card looks broken on hover on attribution view

2022-03-16 08:48 UTC, nicarl commented on src/Frontend/Components/ListCard/ListCard.tsx
> +      <span>{children}</span>
I do not like the ternary operator inside `wrapInTooltip`. If I pass something into `wrapInTooltip` I want to have a tool-tip for sure and not depend on some additional logic. Otherwise the function should be named `eventuallyWrapInTooltip` :wink:

2022-03-16 08:58 UTC, benedikt-richter commented
The fact that on attribution view critical attributions are displayed the same as incomplete ones confused me and, in my opinion, should not be the case.

2022-03-16 09:01 UTC, benedikt-richter commented
I just realised that there is a tooltip. However, the placement is a bit odd. First I did not see it and then I did not realize it belongs to the card:
![Screenshot 2022-03-16 at 10 00 44](https://user-images.githubusercontent.com/46576389/158554213-736ba471-929f-45a8-a33f-1c13f11d91bc.png)

2022-03-16 09:07 UTC, benedikt-richter commented on src/Frontend/Components/ListCard/ListCard.tsx
> +  function wrapInTooltip(children: ReactElement): ReactElement {
I realized the same pattern in `IconButton`. It should not be duplicated.

2022-03-16 09:08 UTC, benedikt-richter commented on src/Frontend/Components/ListCard/ListCard.tsx
> +      <span>{children}</span>
That's true. It feels a bit odd. It would probably better to always add a tooltip and disabling or hiding it under certain conditions.

2022-03-16 09:09 UTC, benedikt-richter requested changes
see comments

2022-03-16 09:39 UTC, antonbauhofer commented on src/Frontend/Components/ListCard/ListCard.tsx
> +      <span>{children}</span>
The logic was taken from the icons that also (sometimes) have a tooltip.
I agree, and we should fix it in the icons, too.

2022-03-16 09:40 UTC, antonbauhofer commented
> The fact that on attribution view critical attributions are displayed the same as incomplete ones confused me and, in my opinion, should not be the case.

Yes, I agree. Originally, I chose a different highlighting for that reason, but it was decided in a team meeting to have the same highlighting and possibly fix it later.

2022-03-16 09:41 UTC, antonbauhofer commented
> I just realised that there is a tooltip. However, the placement is a bit odd. First I did not see it and then I did not realize it belongs to the card: ![Screenshot 2022-03-16 at 10 00 44](https://user-images.githubusercontent.com/46576389/158554213-736ba471-929f-45a8-a33f-1c13f11d91bc.png)
> 
> It would be great to anchor it at the current mouse position or otherwise much closer to the card

Agree. I'll fix the placement.

2022-03-16 13:07 UTC, antonbauhofer commented on src/Frontend/Components/ListCard/ListCard.tsx
> +  function wrapInTooltip(children: ReactElement): ReactElement {
I extracted the tooltip wrapper into a separate component that is used for both occurrences.

2022-03-17 10:15 UTC, antonbauhofer commented
After some discussion, we decided to change the styling so that it is not the same as for incomplete attributions. Consequently, we also decided to drop the tooltip.

2022-03-17 10:31 UTC, benedikt-richter approved these changes

2022-03-17 10:31 UTC, benedikt-richter commented on src/Frontend/Components/ListCard/ListCard.tsx
> +  tooltip: tooltipStyle,
unused

2022-03-17 14:29 UTC, nicarl commented on src/Frontend/Components/PackageList/PackageList.tsx
> +      criticality: props.isExternalAttribution
```typescript
props.isExternalAttribution || packageInfo.preSelect ?? packageInfo.criticality

2022-03-17 14:34 UTC, nicarl approved these changes

2022-03-29 07:09 UTC, merged