Fix bug that changes disappear after context menu
opossum-tool/OpossumUI pull request #540
Opened 2022-03-23 16:34 UTC by mayayunx

Signed-off-by: Ruiyun Xie <ruiyun.xie@tum.de>

### Summary of changes
Fixed bug that changes for one attribution disappear after delete or confirm another attribution via context menu in audit and attribution view.

### Context and reason for change
Changes should not be discarded 

### How can the changes be tested
The changes can be tested in the UI

2022-03-24 10:06 UTC, leslielazzarino requested changes

2022-03-24 10:06 UTC, leslielazzarino commented on src/Frontend/Components/PackageCard/PackageCard.tsx
>    function getContextMenuItems(): Array<ContextMenuItem> {
It wasn't in the task description, but probably it makes sense to fix the behavior also for replacing an attribution.

2022-03-24 15:47 UTC, JakobSchubert commented
We also need to fix the same bug for the case that we delete multiple selected attributions via the context menu "Delete selected globally".

2022-03-24 15:54 UTC, JakobSchubert requested changes
See my comment above (the multi-select case is missing).

2022-03-25 14:40 UTC, leslielazzarino requested changes

2022-03-25 14:40 UTC, leslielazzarino commented on src/Frontend/state/actions/resource-actions/__tests__/save-actions.test.ts
> +      [testUuidB]: {},
Please do not use empty attributions, they are not realistic.

2022-03-25 14:40 UTC, leslielazzarino commented on src/Frontend/state/actions/resource-actions/__tests__/save-actions.test.ts
> +      uuid2: {},
here too

2022-03-29 10:32 UTC, JakobSchubert approved these changes

2022-03-29 12:29 UTC, JakobSchubert approved these changes
Nice!

2022-03-31 10:02 UTC, leslielazzarino approved these changes

2022-03-31 10:02 UTC, merged