Add confirmation popup for deletion
opossum-tool/OpossumUI pull request #59
Opened 2021-10-05 11:24 UTC by jonas-tai

A new popup that asks the user for confirmation is shown, before an attribution is deleted. The confirmation popup is not shown, if the attribution was preselected.

Signed-off-by: Jonas Tai <jonas.tai@tngtech.com>

2021-10-05 11:39 UTC, benedikt-richter commented on src/Frontend/Components/ConfirmationPopup/__tests__/ConfirmPopup.test.tsx
> +// SPDX-FileCopyrightText: Facebook, Inc. and its affiliates
the naming of this file is inconsistent with the naming of the respective component

2021-10-05 11:41 UTC, benedikt-richter commented on src/Frontend/Components/ConfirmDeletionPopup/__tests__/ConfirmDeletionPopup.test.tsx
> +    const expectedContent = 'Do you really want to delete this attribution?';
Could be `'Do you really want to delete this attribution for the current file?'`

2021-10-05 11:42 UTC, benedikt-richter commented on src/Frontend/Components/ConfirmDeletionPopup/ConfirmDeletionPopup.tsx
> +      content={'Do you really want to delete this attribution?'}
Could be `'Do you really want to delete this attribution for the current file?'`

2021-10-05 11:56 UTC, benedikt-richter commented on src/Frontend/Components/ConfirmDeletionPopup/ConfirmDeletionPopup.tsx
> +    if (view == View.Audit && attributionIdOfSelectedPackageInManualPanel) {
akways use `===`

2021-10-05 11:57 UTC, benedikt-richter requested changes

2021-10-05 11:57 UTC, benedikt-richter commented on src/Frontend/Components/ConfirmDeletionPopup/ConfirmDeletionPopup.tsx
> +  }
The logic is broken:
If I select an attribution in audit view in attributions in folder content and press delete. This attribution is deleted for all

2021-10-05 12:42 UTC, nicarl commented on src/Frontend/Components/ConfirmDeletionPopup/ConfirmDeletionPopup.tsx
> +    if (view == View.Audit && attributionIdOfSelectedPackageInManualPanel) {
This check for the view seems wrong as Benedikt said. I would rather expect a check if the attribution is associated to several files. I think we have infrastructure in the selector for this.

2021-10-06 09:32 UTC, benedikt-richter approved these changes

2021-10-06 14:09 UTC, merged