Replace withStyles with sx for FilterMultiSelect
opossum-tool/OpossumUI pull request #633
Opened 2022-04-20 14:50 UTC by leslielazzarino

Signed-off-by: Leslie Lazzarino <leslie.lazzarino@tngtech.com>

### Summary of changes

Replaced withStyles with sx for FilterMultiSelect.

### Context and reason for change

Deprecation of withStyles 

### How can the changes be tested

The first party filter in attribution view behaves correctly.

2022-04-20 14:58 UTC, benedikt-richter commented on src/Frontend/util/get-sx-from-props-and-classes.ts
> +  | ((theme: {}) => SystemStyleObject)
The typing could be improved. Use `Theme` from `import { SxProps, Theme } from '@mui/material';`.
Then the linter would not have to be disabled

2022-04-21 09:00 UTC, JakobSchubert approved these changes

2022-04-21 10:53 UTC, benedikt-richter requested changes
see comment

2022-04-21 15:04 UTC, benedikt-richter approved these changes

2022-04-21 15:04 UTC, merged