replace makeStyles
opossum-tool/OpossumUI pull request #668
Opened 2022-05-04 18:04 UTC by benedikt-richter

### Summary of changes

* replace makeStyles for remaining components
* drop dependencies

### Context and reason for change

Replace makeStyles for all components to finish the migration away from `@mui/styles`.

### How can the changes be tested

![Screenshot 2022-05-04 at 20 03 06](https://user-images.githubusercontent.com/46576389/166765979-27f3c9a3-8c2c-4d1d-b164-bf7a769c56fb.png)

2022-05-05 11:24 UTC, benedikt-richter commented
Checked the built version of the app and appearance and performance match expectations.

2022-05-09 09:00 UTC, leslielazzarino requested changes
Styling of the clearly defined popup is broken. Test looking for typescript.

2022-05-09 09:58 UTC, benedikt-richter commented
> Styling of the clearly defined popup is broken. Test looking for typescript.

The issue is fixed in the previpous PR.

2022-05-09 12:49 UTC, leslielazzarino approved these changes

2022-05-09 12:51 UTC, merged