excluded files from mini bom
opossum-tool/OpossumUI pull request #765
Opened 2022-06-21 08:24 UTC by MarkusObendrauf

Signed-off-by: Markus Obendrauf <markus.obendrauf@tngtech.com>

### Summary of changes

Attributions with "exclude from notice"=True are now excluded from the Mini-BOM (aka "Compact component list") that can be exported in Opossum UI

2022-06-21 12:40 UTC, JakobSchubert commented on src/Frontend/Components/BackendCommunication/BackendCommunication.tsx
>    }
You could update the documentation: https://github.com/opossum-tool/OpossumUI/blob/main/USER_GUIDE.md#exporting-formats
It currently says
```
Compact component list: All attributions are present as csv file.
Detailed component list: All attributions are present as csv file.
```
You should write something like 
```
Compact component list: All attributions not marked as follow-up or 1st Party are exported to a csv file. Attributions marked as "exclude from notice" are not exported.
Detailed component list: All attributions not marked as follow-up or 1st Party are exported to a csv file.
```

2022-06-21 13:13 UTC, leslielazzarino requested changes

2022-06-21 13:13 UTC, leslielazzarino commented on src/Frontend/Components/BackendCommunication/BackendCommunication.tsx
> +  function getBomAttributions(
Expand or create tests for this function.

2022-06-23 11:27 UTC, FlorianSchepers approved these changes

2022-06-23 11:28 UTC, merged