License summary table
opossum-tool/OpossumUI pull request #775
Opened 2022-06-24 09:08 UTC by MarkusObendrauf

### Summary of changes

Created a Statistics popup window with a statistics table that can be opened from File -> Project Statistics. It displays the number of licenses for each signal, and totals for each license and signal.

### How can the changes be tested

You can open the window with an opossum input file.
Tests have been written in `src\Frontend\Components\ProjectStatisticsPopup\__tests__\ProjectStatisticsPopup.test.tsx`.

2022-06-27 14:29 UTC, FlorianSchepers requested changes

2022-06-27 14:29 UTC, FlorianSchepers commented on src/Frontend/types/types.ts
> +export type LicenseTotalCountPerSource = {
Maybe merge 'LicenseTotalCountPerSource' and 'SourceTotalCountPerLicense' into one type?

2022-06-27 14:29 UTC, FlorianSchepers commented on src/Frontend/Components/ProjectStatisticsPopup/__tests__/ProjectStatisticsPopup.test.tsx
> +          documentConfidence: 10,
'documentConfidence' is not needed here

2022-06-27 14:40 UTC, FlorianSchepers commented on src/Frontend/Components/ProjectStatisticsPopup/ProjectStatisticsPopup.tsx
> +//import { useAppDispatch, useAppSelector } from '../../state/hooks';
Remove commented line

2022-06-29 11:28 UTC, MarkusObendrauf commented on src/Frontend/Components/ProjectStatisticsPopup/ProjectStatisticsPopup.tsx
> +  const totalLicensesPerSource: SourceTotalCountPerLicense = { license: 0 };
Right, I'll change the types of these two variables.

2022-06-29 11:40 UTC, MarkusObendrauf commented on src/Frontend/Components/ProjectStatisticsPopup/__tests__/ProjectStatisticsPopup.test.tsx
> +          documentConfidence: 10,
Actually it is needed, see src\shared\shared-types.ts
We could discuss if this should be optional or not.

2022-06-30 09:58 UTC, leslielazzarino requested changes

2022-06-30 09:58 UTC, leslielazzarino commented on package.json
> +    "test:changed": "react-scripts test --watchAll=false --setupFilesAfterEnv=./setupTests.ts --onlyChanged",
Should still use the right regexes.

2022-06-30 09:58 UTC, leslielazzarino commented on src/Frontend/Components/ProjectStatisticsPopup/ProjectStatisticsPopup.tsx
> +export function aggregateLicensesAndSourcesFromSignals(
When I look in to a component file the main point is the component function. Helper functions should come afterwards.

2022-06-30 09:58 UTC, leslielazzarino commented on src/Frontend/Components/ProjectStatisticsPopup/ProjectStatisticsPopup.tsx
> +  signals: PackageInfo[]
We do not use this form. We write Array<PackageInfo>. It is more consistent with Typescript typing, as TemplateType<Something> means "a template type of TemplateType with Something as parameter type".

2022-06-30 09:58 UTC, leslielazzarino commented on src/Frontend/Components/ProjectStatisticsPopup/ProjectStatisticsPopup.tsx
> +): [LicenseCountPerSource[], LicenseTotalCountPerSource] {
Same here.

2022-06-30 09:58 UTC, leslielazzarino commented on src/Frontend/Components/ProjectStatisticsPopup/ProjectStatisticsPopup.tsx
> +  const licensesForSources: { [key: string]: { [key: string]: number } } = {};
licenceCountBySource ?

2022-06-30 09:58 UTC, leslielazzarino commented on src/Frontend/Components/ProjectStatisticsPopup/ProjectStatisticsPopup.tsx
> +  const totalLicensesPerSource: LicenseTotalCountPerSource = { license: 0 };
Why not licenseTotalCountPerSource?

2022-06-30 09:58 UTC, leslielazzarino commented on src/Frontend/Components/ProjectStatisticsPopup/ProjectStatisticsPopup.tsx
> +  const totalSourcesPerLicense: SourceTotalCountPerLicense = {};
Why not sourceTotalCountPerLicense?

2022-06-30 09:58 UTC, leslielazzarino commented on src/Frontend/Components/ProjectStatisticsPopup/ProjectStatisticsPopup.tsx
> +export function aggregateLicensesAndSourcesFromSignals(
Actually there is already an helpers file for this component, just move it there.

2022-06-30 09:58 UTC, leslielazzarino commented on src/Frontend/Components/ProjectStatisticsPopup/ProjectStatisticsPopup.tsx
> +  const licensesForSources: { [key: string]: { [key: string]: number } } = {};
Also I cannot understand what's meant here. You can replace "key" with whatever wort, use it to make it clear what is what here. I would also reccoment to extract such a complex type.

2022-06-30 09:58 UTC, leslielazzarino commented on src/Frontend/Components/ProjectStatisticsPopup/ProjectStatisticsPopup.tsx
> +  const sourcesTableEntries: LicenseCountPerSource[] = [];
Array<>

2022-06-30 09:58 UTC, leslielazzarino commented on src/Frontend/Components/ProjectStatisticsPopup/ProjectStatisticsPopup.tsx
> +  function close(): void {
just inline this

2022-06-30 09:58 UTC, leslielazzarino commented on src/Frontend/Components/ProjectStatisticsPopup/ProjectStatisticsPopup.tsx
> +  function close(): void {
I know you use it 3 times, but it is just so short

2022-06-30 09:58 UTC, leslielazzarino commented on src/Frontend/types/types.ts
> +  [key: string]: string | number;
the string value feels wrong

2022-06-30 15:09 UTC, vasily-pozdnyakov commented on package.json
> +    "test:changed": "react-scripts test --watchAll=false --setupFilesAfterEnv=./setupTests.ts --onlyChanged",
This is already within the main branch. See pull request #773.

2022-06-30 15:34 UTC, vasily-pozdnyakov commented on src/Frontend/Components/ProjectStatisticsPopup/ProjectStatisticsPopup.tsx
> +export function aggregateLicensesAndSourcesFromSignals(
you are right, done.

2022-06-30 15:40 UTC, vasily-pozdnyakov commented on src/Frontend/Components/ProjectStatisticsPopup/ProjectStatisticsPopup.tsx
> +  signals: PackageInfo[]
ok, corrected.

2022-06-30 15:41 UTC, vasily-pozdnyakov commented on src/Frontend/Components/ProjectStatisticsPopup/ProjectStatisticsPopup.tsx
> +): [LicenseCountPerSource[], LicenseTotalCountPerSource] {
done

2022-07-01 06:50 UTC, vasily-pozdnyakov commented on src/Frontend/Components/ProjectStatisticsPopup/ProjectStatisticsPopup.tsx
> +  const sourcesTableEntries: LicenseCountPerSource[] = [];
done

2022-07-01 06:52 UTC, vasily-pozdnyakov commented on src/Frontend/Components/ProjectStatisticsPopup/ProjectStatisticsPopup.tsx
> +  function close(): void {
ok

2022-07-06 12:23 UTC, MarkusObendrauf commented
![Project statistics popup](https://user-images.githubusercontent.com/107913663/177549269-4fe100d0-b20f-486e-bb8a-3608a4656324.png)
A picture of the new popup window.

2022-07-06 14:01 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helper.tsx
> +  licenseNames.sort();
would be good to avoid side effects

2022-07-06 14:01 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helper.tsx
> +  sourceNamesOrTotal.push('Total');
could extract `'Total'` to constant

2022-07-06 14:03 UTC, leslielazzarino requested changes

2022-07-06 14:03 UTC, leslielazzarino commented on src/Frontend/Components/ProjectStatisticsPopup/__tests__/ProjectStatisticsPopup.test.tsx
> +  test('counts licenses and sources', () => {
Add a test with no signal, to check that nothing breaks.

2022-07-06 14:55 UTC, MarkusObendrauf commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helper.tsx
> +  sourceNamesOrTotal.push('Total');
extracted it to `const TOTAL = 'Total'`

2022-07-06 14:59 UTC, MarkusObendrauf commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helper.tsx
> +      <Paper sx={{ width: '100%', mb: 2 }}>
I tried removing Paper and couldn't see any difference

2022-07-06 15:13 UTC, MarkusObendrauf commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helper.tsx
> +  sourceNamesOrTotal.push('Total');
I also saw that we are using the string '-' often like a constant, so I extracted it into the constant `PLACEHOLDER_STRING`.

2022-07-07 08:46 UTC, leslielazzarino approved these changes

2022-07-07 12:02 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helper.tsx
> +type SignalCountPerSourcePerLicense = {
this should be an interface

2022-07-07 12:03 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helper.tsx
> +const PLACEHOLDER_STRING = '-';
the name should not reflect the type of the constant. Probably `STRING`should not be part of the constants name

2022-07-07 12:06 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helper.tsx
> +    signalCountPerSourcePerLicense[TOTAL][TOTAL] = 0;
this seems very fragile. It working relys on having the same value for licenses and sources. This should be changed. The constant used for accessing a value in the object could have the same value ( for licenses and sources) but should not be the same single constant.

2022-07-07 12:10 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helper.tsx
> +          aria-labelledby="tableTitle"
what is this label used for?

2022-07-07 12:10 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helper.tsx
> +                    {index == 0
`==` -> `===`

2022-07-07 12:19 UTC, FlorianSchepers requested changes

2022-07-07 13:08 UTC, MarkusObendrauf commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helper.tsx
> +const TOTAL = 'Total';
Split it into two constants called `SOURCE_TOTAL` and `LICENSE_TOTAL`.

2022-07-07 13:09 UTC, MarkusObendrauf commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helper.tsx
> +const PLACEHOLDER_STRING = '-';
Renamed it to PLACEHOLDER

2022-07-07 13:10 UTC, MarkusObendrauf commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helper.tsx
> +export function getProjectStatisticsTableContent(
👍

2022-07-07 13:13 UTC, MarkusObendrauf commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helper.tsx
> +          aria-labelledby="tableTitle"
it doesn't seem necessary. removed it.

2022-07-08 08:26 UTC, FlorianSchepers approved these changes

2022-07-08 08:38 UTC, merged