fix: Enable context isolation
opossum-tool/OpossumUI pull request #815
Opened 2022-07-11 20:09 UTC by nicarl

### Summary of changes

- Activate context isolation
- Use a context bridge to expose the `ipcRenderer`
- Instead of exposing the full `ipcRenderer` API a subset of functions is exposed
    - for the ocassions where `.invoke` is called an API is defined, which describes the actual action, e.g. `openLink`
    - when listeners are used (`.on` and `.removeListener`) the respective part of the API is exposed but an allow list of channels is applied in the backend before passing anything through  

### Context and reason for change

Deactivating context isolation and exposing `ipcRenderer` globally is discouraged. An attacker could access it from the frontend with `window.ipcRenderer` and would have a rather powerful API. Instead it is recommended to use a preload script where a subset of APIs is exposed.
Details can be found [here](https://www.electronjs.org/docs/latest/tutorial/context-isolation).

### How can the changes be tested

- run all tests
- more importantly open the app and check the actions invoking the `ipcRenderer` are working (saving files, opening links, ...)

2022-07-12 11:46 UTC, benedikt-richter requested changes
Great to takle the context isolation! Looks good to me and works.
I added an idea on how to refactor the enums for the IpcChannels.

2022-07-12 11:46 UTC, benedikt-richter commented on src/shared/shared-types.ts
> +export type Listener = (event: IpcRendererEvent, ...args: any[]) => void;
`any[]` -> `Array<any>`

2022-07-12 11:46 UTC, benedikt-richter commented on src/shared/ipc-channels.ts
> +
For the channels I'd suggest to split the enum containing all channels into two
* frontend channels
* other channels

This could look like (maybe naming might be improved):

```

export enum IpcChannel {
  ExportFile = 'export-file',
  OpenFile = 'open-file',
  OpenLink = 'open-link',
  SaveFile = 'save-file',
  SendErrorInformation = 'send-error-information',
}

export enum AllowedFrontendChannels {
  ExportFileRequest = 'export-file-request',
  FileLoaded = 'file-loaded',
  Logging = 'logging',
  ResetLoadedFile = 'reset-loaded-file',
  RestoreFrontend = 'restore-frontend',
  SaveFileRequest = 'save-file-request',
  ToggleHighlightForCriticalSignals = 'toggle-highlight-for-critical-signals',
  ShowSearchPopup = 'show-search-pop-up',
  ShowProjectMetadataPopup = 'show-project-metadata-pop-up',
  ShowProjectStatisticsPopup = 'show-project-statistics-pop-up',
  SetBaseURLForRoot = 'set-base-url-for-root',
}


```

Then the checks in the backend
` if (allowedFrontendChannels.includes(channel)) {`
could read
` if (Object.values(AllowedFrontendChannels).includes(channel)) {`
and the constant
`export const allowedFrontendChannels`
would not be required.


This would avoid to add new channels to two enums in case of "allowed for frontend" and to the constant as well. Further, it would make the distinction between the two enums more explicit.

2022-07-12 18:50 UTC, nicarl commented on src/shared/ipc-channels.ts
> +
Good idea I changed it according to your suggestion.

2022-07-13 06:11 UTC, benedikt-richter approved these changes

2022-07-14 14:33 UTC, leslielazzarino approved these changes

2022-07-14 14:33 UTC, merged