Added a table to show attribution property counts.
opossum-tool/OpossumUI pull request #836
Opened 2022-07-21 11:59 UTC by MarkusObendrauf

Signed-off-by: Markus Obendrauf <markus.obendrauf@tngtech.com>

### Summary of changes

Added a new section to the project statistics popup that shows the number of 1st party and follow-up attributions

### Context and reason for change

As a user I want to see the number of follow ups.

### How can the changes be tested

Open an input file and then choose File > Project Statistics

![Project statistics popup](https://user-images.githubusercontent.com/107913663/180208457-af2899ce-b267-43e7-af9e-4cd609f69898.png)

2022-07-21 14:06 UTC, benedikt-richter requested changes

2022-07-21 14:06 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/__tests__/project-statistics-popup-helpers.test.tsx
> +    const testSignals: PackageInfo[] = [
typically we use `Array<PackageInfo>` instead of `PackageInfo[]`

2022-07-21 14:06 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.tsx
> +          width: 'calc(40%)',
better to use `width: '40vh,`

2022-07-21 14:06 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.tsx
> +      {attributionCountTable}
would be good to extract these into new files.

2022-07-21 14:08 UTC, leslielazzarino commented on src/Frontend/Components/ProjectStatisticsPopup/ProjectStatisticsPopup.tsx
> +    aggregateAttributionPropertiesFromSignals(signals);
Here you should use manualAttributions as input, and rename everything that is generic enough, like te aggregate function, from signal to attribution (it will work for both manual and external attributions, as they have the same data type).

2022-07-21 14:10 UTC, leslielazzarino commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.tsx
> +export function aggregateAttributionPropertiesFromSignals(
rename here anything signal to attribution

2022-07-21 14:17 UTC, leslielazzarino requested changes

2022-07-21 14:17 UTC, leslielazzarino commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.tsx
> +const ATTRIBUTION_PROPERTIES_SHORT_NAME_TO_LONG_NAME: {
I would call them id and display name, instead of short name and long name. It is a more standard way.

2022-07-21 14:17 UTC, leslielazzarino commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.tsx
> +}
I would prefer to see these two components in two separate files, within this same folder, with the usual component file name convention. Also this file is getting really long, splitting it into 3 will help.

2022-07-21 14:17 UTC, leslielazzarino commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.tsx
> +export function getProjectStatisticsPopupContent(
I would remove this function, and inline everything in ProjectStatisticsPopup.

2022-07-22 07:13 UTC, MarkusObendrauf commented on src/Frontend/Components/ProjectStatisticsPopup/__tests__/project-statistics-popup-helpers.test.tsx
> +    const testSignals: PackageInfo[] = [
ok, I will change it back

2022-07-22 07:21 UTC, MarkusObendrauf commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.tsx
> +          width: 'calc(40%)',
*40vw, changed it

2022-07-22 07:27 UTC, MarkusObendrauf commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.tsx
> +const ATTRIBUTION_PROPERTIES_SHORT_NAME_TO_LONG_NAME: {
ok

2022-07-22 08:07 UTC, MarkusObendrauf commented on src/Frontend/Components/ProjectStatisticsPopup/ProjectStatisticsPopup.tsx
> +    aggregateAttributionPropertiesFromSignals(signals);
ok

2022-07-22 09:41 UTC, MarkusObendrauf commented
The new table is now called "Manual Attribution Flags" instead of "Attribution types".

2022-07-22 11:31 UTC, MarkusObendrauf commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.tsx
> +}
Updated the file structure to match other components

2022-07-22 11:33 UTC, MarkusObendrauf commented
The file structure has been changed to match other components. I used `src\Frontend\Components\AttributionColumn` as a reference.

2022-07-26 06:01 UTC, benedikt-richter requested changes

2022-07-26 06:01 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/AttributionCountPerSourcePerLicenseTable.tsx
> +    String(props.attributionCountPerSourcePerLicense[LICENSE_TOTAL][sourceName])
why is `String` necessary? We should try to avoid that here.

2022-07-26 06:01 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/AttributionCountPerSourcePerLicenseTable.tsx
> +      <MuiTypography variant="h6">Signals per Sources</MuiTypography>
AS above the title could be extracted in variable and might be given as a prop

2022-07-26 06:05 UTC, benedikt-richter commented
The general styling might be a bit improved (this might be a separate diff). Here, please, adjust the title of the table to be displayed smaller than the title of the entire popup.


![Screenshot 2022-07-26 at 08 03 19](https://user-images.githubusercontent.com/46576389/180934761-e6f76583-c552-4668-90a4-cc65f248e61d.png)

2022-07-26 07:39 UTC, MarkusObendrauf commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +    if (licenseName != null) {
yes

2022-07-26 08:03 UTC, MarkusObendrauf commented on src/Frontend/Components/ProjectStatisticsPopup/AttributionCountPerSourcePerLicenseTable.tsx
> +    String(props.attributionCountPerSourcePerLicense[LICENSE_TOTAL][sourceName])
Avoided it by using an array of type `Array<string | number>` and concatenating via the `unshift` method.

2022-07-26 08:12 UTC, MarkusObendrauf commented on src/Frontend/Components/ProjectStatisticsPopup/AttributionCountPerSourcePerLicenseTable.tsx
> +    String(props.attributionCountPerSourcePerLicense[LICENSE_TOTAL][sourceName])
Replaced it with what we discussed.

2022-07-26 08:18 UTC, MarkusObendrauf commented on src/Frontend/Components/ProjectStatisticsPopup/AttributionPropertyCountTable.tsx
> +  attributionPropertyCounts: AttributionCountPerAttributionProperty;
renamed it

2022-07-26 08:19 UTC, MarkusObendrauf commented on src/Frontend/Components/ProjectStatisticsPopup/AttributionPropertyCountTable.tsx
> +    <MuiBox sx={{ width: '100%' }}>
you are right

2022-07-26 08:37 UTC, MarkusObendrauf commented on src/Frontend/Components/ProjectStatisticsPopup/AttributionPropertyCountTable.tsx
> +  /* eslint-enable @typescript-eslint/no-unused-vars */
I moved the sorting logic to `project-statistics-popup-helpers.ts`

2022-07-26 08:53 UTC, MarkusObendrauf commented on src/Frontend/Components/ProjectStatisticsPopup/ProjectStatisticsPopup.tsx
> +  const externalAttributions = Object.values(
renamed to externalAttributionValues and manualAttributionValues

2022-07-26 08:56 UTC, MarkusObendrauf commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +const UNKNOWN_SOURCE = '-';
renamed it

2022-07-26 11:16 UTC, MarkusObendrauf commented
> The general styling might be a bit improved (this might be a separate diff). Here, please, adjust the title of the table to be displayed smaller than the title of the entire popup.

Our popup headers are `H6`, which is already the smallest heading. For now I made the table titles `subtitle1`. I also reduced the size of the font used in the table from size 16 to size 14.

2022-07-26 11:21 UTC, MarkusObendrauf commented on src/Frontend/Components/ProjectStatisticsPopup/AttributionPropertyCountTable.tsx
> +      <MuiTypography variant="h6">Manual Attribution Flags</MuiTypography>
extracted & renamed it to "First Party and Follow Up Attributions"

2022-07-26 11:27 UTC, MarkusObendrauf commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +export const ATTRIBUTION_TOTAL = 'Total Attributions';
I added `HEADER` to the end of the variable names, not sure if thats clear enough.

2022-07-28 05:46 UTC, benedikt-richter requested changes
Looks good! Just one idea on how to refactor the sorting function.

Further, please do follow the guidelines for commit messages (see `CONTRIBUTING.md`):

Example:
```
Short summary of changes (72 characters or less)

More detailed explanatory text, if necessary. This text can have 
several lines.

Issue: #123  (this line is optional)
```

2022-07-28 05:46 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +}
this could be inlined by replacing it by something like `array.push(array.splice(array.indexOf(ATTRIBUTION_TOTAL_HEADER), 1)[0]);`

2022-07-28 09:45 UTC, benedikt-richter approved these changes

2022-07-29 12:04 UTC, merged