Check changed input file
opossum-tool/OpossumUI pull request #837
Opened 2022-07-22 15:39 UTC by vasily-pozdnyakov

### Summary of changes

If the md5 sum of the input file has changed but the filename not, on open, a popup dialog asks whether to update attribution file (if exists) with a new checksum or completely overwrite it using the changed input file.

### Context and reason for change

Ticket FO-2216. If the MD5 sum of the input file has changed, on open, a dialog should ask whether to keep or drop the attributions file.

### How can the changes be tested

A new test was created: src\Frontend\Components\ChangedInputFilePopup\__tests__\ChangedInputFilePopup.test.tsx

One can change input file content without changing a name of the file and try to reopen it.

2022-07-25 12:52 UTC, MarkusObendrauf requested changes

2022-07-25 12:52 UTC, MarkusObendrauf commented on src/ElectronBackend/main/listeners.ts
> +  reopenFlag: boolean
variable name is unclear imo, i would rename it to `overwriteOutputFile`

2022-07-25 12:52 UTC, MarkusObendrauf commented on src/ElectronBackend/main/listeners.ts
> +      if (!args.reopenFlag) {
I would make this `if (args.reopenFlag) {` and swap the order of the two blocks. That way, the `else` part isn't a double negative.

2022-07-25 12:52 UTC, MarkusObendrauf commented on src/ElectronBackend/main/listeners.ts
> +        if (!globalBackendState.resourceFilePath) {
Same as line 87

2022-07-25 12:52 UTC, MarkusObendrauf commented on src/ElectronBackend/main/listeners.ts
> +): (_: unknown, args: OpenFileArgs) => Promise<void> {
type is `WebContents` (might be fine as is, idk)

2022-07-25 12:52 UTC, MarkusObendrauf commented on src/ElectronBackend/main/listeners.ts
> +        if (filePath.endsWith(outputFileEnding)) {
I would extract this logic to a function `isOutputFilePath(filePath: string): boolean` to make this if statement easier to read

2022-07-25 12:52 UTC, MarkusObendrauf commented on src/ElectronBackend/input/OpossumOutputFileSchema.json
> +          "description": "Checksum to check if the input file has changed."
it should be made clear that this is an md5 checksum

2022-07-25 12:52 UTC, MarkusObendrauf commented on src/ElectronBackend/input/OpossumOutputFileSchema.json
> +          "description": "Checksum to check if the input file has changed."
optional: change the variable name as well

2022-07-25 12:52 UTC, MarkusObendrauf commented on src/Frontend/Components/ChangedInputFilePopup/ChangedInputFilePopup.tsx
> +    'The checksum of the input file has changed. Do you want to update the output file with a new checksum or completely overwrite it?';
Maybe rewrite this in a way that doesnt use "checksum"? This message might be too technical.

2022-07-26 06:42 UTC, benedikt-richter requested changes

2022-07-26 06:42 UTC, benedikt-richter commented on example-files/opossum_input copy.json
> +{
The file name should be more descriptive and not contain empty spaces

2022-07-26 06:42 UTC, benedikt-richter commented on src/ElectronBackend/main/main.ts
> +
why did you insert that line?

2022-07-26 06:42 UTC, benedikt-richter commented on src/Frontend/Components/ChangedInputFilePopup/ChangedInputFilePopup.tsx
> +    dispatch(saveTemporaryPackageInfoAndNavigateToTargetView());
why do we want to save temporary package info here?

2022-07-26 06:42 UTC, benedikt-richter commented on src/Frontend/Components/ChangedInputFilePopup/__tests__/ChangedInputFilePopup.test.tsx
> +  test('renders a ChangedInputFilePopup and clicks Overwrite', () => {
clicking "update" could also be tested

2022-07-26 06:42 UTC, benedikt-richter commented on src/shared/ipc-channels.ts
> +  ReopenFile = 'reopen-file',
what is this used for?

2022-07-26 06:42 UTC, benedikt-richter commented on src/ElectronBackend/input/__tests__/importFromFile.test.ts
> +      await loadJsonFromFilePath(mainWindow.webContents, jsonPath, false);
there should be a test added for the case of `true`

2022-07-26 06:42 UTC, benedikt-richter commented on src/ElectronBackend/input/importFromFile.ts
> +  reopenFlag: boolean
Here (and possibly other places) we could use a default argument and by default set it to false.

2022-07-26 06:42 UTC, benedikt-richter commented on src/ElectronBackend/input/importFromFile.ts
> +  }
could be extracted into a function and be unit tested.

2022-07-26 06:42 UTC, benedikt-richter commented on src/ElectronBackend/input/importFromFile.ts
> +  if (!reopenFlag) {
typically avoiding negations improves readability.

2022-07-26 06:42 UTC, benedikt-richter commented on src/ElectronBackend/main/__tests__/listeners.test.ts
> +      false
should also be tested with new feature (i.e. `true`)

2022-07-26 06:42 UTC, benedikt-richter commented on src/ElectronBackend/main/listeners.ts
> +              `\nresourceFilePath: ${globalBackendState.resourceFilePath}`
This message could be more clear. Inparticular, `reopen data` is unclear.

2022-07-26 06:42 UTC, benedikt-richter commented on src/ElectronBackend/main/listeners.ts
>  export function getOpenFileListener(
I suggest splitting that listener into two. Actually, the two have not much in common.
There are two code blocks in one function. Only one is executed based on `reopenFlag`.

2022-07-26 06:42 UTC, benedikt-richter commented on example-files/opossum_input copy.json
> +{
btw what is the use case for this file?

2022-07-26 06:42 UTC, benedikt-richter commented
also plerase squash commits

2022-07-26 06:45 UTC, benedikt-richter commented on src/ElectronBackend/input/importFromFile.ts
> +    if (inputFileChecksum === outputFileChecksum) {
I guess, we intended to write:
 If `outputFileChecksum === undefined` then don"t open the popup and always overwrite.

2022-07-26 12:19 UTC, vasily-pozdnyakov commented on example-files/opossum_input copy.json
> +{
my bad, I used this file for testing, will delete it.

2022-07-26 14:37 UTC, vasily-pozdnyakov commented on src/ElectronBackend/input/importFromFile.ts
> +    if (inputFileChecksum === outputFileChecksum) {
Are you sure that we want to overwrite, not update?

2022-07-26 14:41 UTC, vasily-pozdnyakov commented on src/ElectronBackend/main/listeners.ts
> +): (_: unknown, args: OpenFileArgs) => Promise<void> {
The changes reverted.

2022-07-26 14:43 UTC, vasily-pozdnyakov commented on src/ElectronBackend/main/listeners.ts
> +        if (filePath.endsWith(outputFileEnding)) {
I think in this case too many nested functions.

2022-07-27 11:06 UTC, vasily-pozdnyakov commented on src/Frontend/Components/ChangedInputFilePopup/ChangedInputFilePopup.tsx
> +    dispatch(saveTemporaryPackageInfoAndNavigateToTargetView());
not really, changed to saveManualAndResolvedAttributionsToFile()

2022-07-28 05:48 UTC, benedikt-richter commented
> also please squash commits

Thanks for squashing the commits!

Please do follow the guidelines for commit messages (see `CONTRIBUTING.md`):

Example:
```
Short summary of changes (72 characters or less)

More detailed explanatory text, if necessary. This text can have 
several lines.

Issue: #123  (this line is optional)
```

2022-07-28 05:52 UTC, benedikt-richter requested changes
I'd suggest to restructure the code in the following way:
There are three channels with individual listeners, one for each of the following actions:
* user clicking "open file"
* user clicking "overwrite" in popup
* user clicking "update" in popup

The listener that is initially called (the open file one), persists the file path (e.g. in `GlobalBackendState`) and checks whether the checksum changed. If no it just opens the file. If yes it opens the popup.
The listeners for the two popup actions just do what one would expect them to do.

2022-08-01 13:18 UTC, benedikt-richter reviewed
Checked that it works.
Will continue review later (tests are left)

2022-08-01 13:18 UTC, benedikt-richter commented on src/ElectronBackend/main/listeners.ts
>        await openFile(mainWindow, filePath);
here a logging statement might be nice

2022-08-01 13:18 UTC, benedikt-richter commented on src/ElectronBackend/main/listeners.ts
> +    mainWindow.webContents,
here a logging statement might be nice

2022-08-01 13:18 UTC, benedikt-richter commented on src/ElectronBackend/main/listeners.ts
> +      fs.unlinkSync(getGlobalBackendState().attributionFilePath ?? '');
we should have error handling here and throw if there is no `getGlobalBackendState().attributionFilePath`

2022-08-01 13:18 UTC, benedikt-richter commented on src/ElectronBackend/main/listeners.ts
> +      'Failed to open input file. Resource file path is incorrect:' +
This function should not know about it's usage and use a more generic error message

2022-08-01 13:18 UTC, benedikt-richter commented on src/Frontend/Components/ChangedInputFilePopup/ChangedInputFilePopup.tsx
> +    'The input file has changed. Do you want to keep the old attribution file or delete it?';
this line is long. Would be good to break it.

2022-08-01 13:18 UTC, benedikt-richter commented on src/shared/ipc-channels.ts
> +  SendErrorInformation = 'send-error-information',
why is this added here?

2022-08-01 14:22 UTC, benedikt-richter commented on src/ElectronBackend/input/__tests__/importFromFile.test.ts
> +    expect(getGlobalBackendState().projectTitle).toBe(
it should also be tested that the projectID is set and that the `inputContainsCriticalSignals` flag is set in global backend state

2022-08-01 14:22 UTC, benedikt-richter commented on src/ElectronBackend/main/__tests__/listeners.test.ts
>  describe('getOpenFileListener', () => {
CUrrently, the checksum logic is not tested for the case of non-matching check sums. Should be added as a test

2022-08-02 08:33 UTC, MarkusObendrauf commented on src/ElectronBackend/main/listeners.ts
> +function getChecksums(filePath: string): {
please rename this function

2022-08-02 08:33 UTC, MarkusObendrauf commented on src/ElectronBackend/main/listeners.ts
> +function getFilePath(): string {
getResourceFilePath?

2022-08-02 08:33 UTC, MarkusObendrauf commented on src/Frontend/Components/BackendCommunication/BackendCommunication.tsx
> +    if (showChangedInputFilePopup) {
Why do we have this variable? This check should happen outside of this function

2022-08-02 08:33 UTC, MarkusObendrauf commented on src/shared/ipc-channels.ts
> +  DeleteFile = 'delete-file',
sort these enums alphabetically?

2022-08-02 10:33 UTC, benedikt-richter commented on src/ElectronBackend/main/listeners.ts
> +function getChecksums(filePath: string): {
This function calculates the checksum of the input file and reads the (old) checksum from the output file

2022-08-03 06:23 UTC, benedikt-richter commented
The diff now looks good to me.

I just noted that there is one case that does behave (probably) different from expected.
If I open an input file and then open the same input file (after gzipping it), the app does ask me whether to keep the output file or not (the checksum do not match). This might be confusing to the user.

2022-08-03 06:39 UTC, benedikt-richter commented on src/Frontend/Components/ChangedInputFilePopup/ChangedInputFilePopup.tsx
> +  const content =
Here, we could be more explicit about the fact that the user will loose any progress made so far. Consider adding: "In case of deletion all progress is lost!"

2022-08-03 07:37 UTC, benedikt-richter approved these changes

2022-08-03 09:16 UTC, MarkusObendrauf approved these changes

2022-08-03 09:18 UTC, merged