The menu point "Highlight critical signals" grayed out if no critical signals
opossum-tool/OpossumUI pull request #843
Opened 2022-07-26 12:11 UTC by vasily-pozdnyakov

### Summary of changes

If the input file has no critical signals (none of the "medium" and "high"), the menu point "Highlight critical signals" is disabled.

### Context and reason for change

The menu point "Highlight critical signals" should be grayed out if none exists.

### How can the changes be tested

Open an input file without critical signals, e.g. `large_opossum_input.json` from example files.

2022-07-27 06:55 UTC, benedikt-richter requested changes
The menu item is ticked even if it is disabled.

![Screenshot 2022-07-27 at 08 52 33](https://user-images.githubusercontent.com/46576389/181181429-3fd7817e-5b35-4394-ba27-15c655009237.png)

2022-07-27 06:55 UTC, benedikt-richter commented on src/ElectronBackend/main/menu.ts
> +  criticalSignalsFlag: boolean
Can't we use the `GlobalBackendState` instead of explicitly parsing the flag?

2022-07-27 07:48 UTC, antonbauhofer commented
> The menu item is ticked even if it is disabled.
> 
> ![Screenshot 2022-07-27 at 08 52 33](https://user-images.githubusercontent.com/46576389/181181429-3fd7817e-5b35-4394-ba27-15c655009237.png)

In your Screenshot, the menu item is greyed out, but has a checkmark. The checkmark does not make sense, I think. If I test it myself, there is no checkmark, however. Has this already been solved and the screenshot is outdated?

2022-07-27 08:04 UTC, antonbauhofer reviewed
It looks good all together. But I left some smaller comments to consider. No strong opinions, just suggestions.

2022-07-27 08:04 UTC, antonbauhofer commented on src/ElectronBackend/input/importFromFile.ts
> +  return criticalSignalsFlag;
We use the name `criticalSignalsFlag` quite often. I think we could use a more descriptive name. Maybe something along the lines of `loadedFileContainsCriticalSignals`.

2022-07-27 10:42 UTC, benedikt-richter commented
> In your Screenshot, the menu item is greyed out, but has a checkmark. The checkmark does not make sense, I think. If I test it myself, there is no checkmark, however. Has this already been solved and the screenshot is outdated?

I also think this checkmark should not be there. This happens if the menu item is checked and then you open a new file that does not have critical signals

2022-07-28 08:40 UTC, benedikt-richter requested changes
Works nicely 👍 

Just a small refactor and moving code out of the `finally` block

2022-07-28 08:40 UTC, benedikt-richter commented on src/ElectronBackend/main/menu.ts
> +    );
I'd suggest to extract the logic as a function, like

```

function getCheckedStatusAndSyncWithFrontend(
  inputContainsCriticalSignals: boolean,
  webContents: WebContents
): boolean {
  let isHighlightCriticalSignalMenuItemChecked = Boolean(
    Menu.getApplicationMenu()?.getMenuItemById('highlightCritical')?.checked
  );

  if (
    isHighlightCriticalSignalMenuItemChecked &&
    !inputContainsCriticalSignals
  ) {
    webContents.send(
      AllowedFrontendChannels.ToggleHighlightForCriticalSignals,
      {
        toggleHighlightForCriticalSignals: true,
      }
    );
    isHighlightCriticalSignalMenuItemChecked = false;
  }

  return isHighlightCriticalSignalMenuItemChecked;
}

```

such that in `createMenu` we just have to call it

```
...

  const inputContainsCriticalSignals = Boolean(
    getGlobalBackendState().inputContainsCriticalSignals
  );
  const isHighlightCriticalSignalMenuItemChecked =
    getCheckedStatusAndSyncWithFrontend(
      inputContainsCriticalSignals,
      webContents
    );

...

```

2022-07-28 08:40 UTC, benedikt-richter commented on src/ElectronBackend/main/listeners.ts
> +    Menu.setApplicationMenu(createMenu(mainWindow));
This code should be moved into the `try` block

2022-07-29 14:21 UTC, benedikt-richter approved these changes

2022-08-01 07:58 UTC, antonbauhofer approved these changes

2022-08-01 08:03 UTC, merged