Add a search to the attribution column in the audit view.
opossum-tool/OpossumUI pull request #873
Opened 2022-08-11 12:03 UTC by MarkusObendrauf

### Summary of changes

Add a search functionality for signals. This is accessed by clicking on the search icon, which is located next to the tabs. This opens a textbox that allows a user to search attributions by package name, license name and copyright.

### Context and reason for change

As a user I would like to search attributions for problematic licenses.

2022-08-11 12:03 UTC, MarkusObendrauf commented
![keycloak_11 0 2_resources json 2022-08-10 16_17_38](https://user-images.githubusercontent.com/107913663/184129272-42ffbde3-912c-423e-87aa-e9b46ce7ed9d.png)

2022-08-12 07:59 UTC, vasily-pozdnyakov commented
Some points regarding the visual:
1.  When no signals found, the user can still see sources titles, this is confusing: 
![image](https://user-images.githubusercontent.com/85183359/184310186-0757f01d-4231-42c0-be0d-b7a5f1c1416e.png)

2. User can close the search window when there is some text and move to another file/folder/view, but the filtering is still active: 
![image](https://user-images.githubusercontent.com/85183359/184310470-9d4c920b-5075-4bf4-ac5c-30e7a0dc1c14.png)
you can either disable closing the search field when it is not empty or automatically clear it when it is closing.

3. It would be nice to make some margin between tabs local/global and the search field, as the text "Search" covers the LOCAL tab. 
![image](https://user-images.githubusercontent.com/85183359/184311186-53fdc0b1-b2f4-4673-82e7-b59c42ca0ee5.png)

2022-08-12 09:56 UTC, vasily-pozdnyakov requested changes
Nice job.

2022-08-12 09:56 UTC, vasily-pozdnyakov commented on src/Frontend/Components/PackageList/AttributionsViewPackageList.tsx
> +export function AttributionsViewPackageList(
This function is 80% identical with PackageList function, can we somehow merge them?

2022-08-12 09:56 UTC, vasily-pozdnyakov commented on src/Frontend/Components/PackagePanel/PackagePanel.tsx
> +            <>
Do we need the additional <></>? I think it is not necessary, as we use only one component MuiTypography.

2022-08-12 09:56 UTC, vasily-pozdnyakov commented on src/Frontend/Components/ResourceDetailsTabs/ResourceDetailsTabs.tsx
> +  const isAccordionSearchFieldDisplayed = useAppSelector(
Can we move all the constants closer to the top?

2022-08-12 09:56 UTC, vasily-pozdnyakov commented on src/Frontend/Components/PackageList/PackageList.tsx
>  export function PackageList(props: PackageListProps): ReactElement {
Should we test this function?

2022-08-12 10:40 UTC, MarkusObendrauf commented on src/Frontend/shared-styles.ts
> +export const largeIcon = {
fixed

2022-08-12 10:46 UTC, MarkusObendrauf commented on src/Frontend/Components/PackageList/AttributionsViewPackageList.tsx
> +export function AttributionsViewPackageList(
I discussed this with Benedikt. Context: the PackageList is used in the tabs in the audit view, while the AttributionsViewPackageList is used in the attributions view. If in the future we will make changes to both lists at once, then its better to merge them. If there will be more differences between the two components, then its better to keep them separate. Right now there are already some slight differences between these components, especially with how the search works, and we might make changes to the attibution view, so in the end we decided to keep them separate.

2022-08-12 10:47 UTC, MarkusObendrauf commented on src/Frontend/Components/PackagePanel/PackagePanel.tsx
> +            <>
fixed

2022-08-12 10:51 UTC, MarkusObendrauf commented on src/Frontend/Components/ResourceDetailsTabs/ResourceDetailsTabs.tsx
> +  const isAccordionSearchFieldDisplayed = useAppSelector(
good point, moved it. there were some more `useAppSelector`s higher up, it looks much better when they're all next to each other

2022-08-12 10:54 UTC, MarkusObendrauf commented on src/Frontend/Components/PackageList/PackageList.tsx
>  export function PackageList(props: PackageListProps): ReactElement {
i believe it is sufficiently tested in `src\Frontend\Components\ResourceDetailsTabs\__tests__\ResourceDetailsTabs.test.tsx` (tests for the parent component)

2022-08-12 10:56 UTC, MarkusObendrauf commented on src/Frontend/shared-styles.ts
> +export const largeClickableIcon = {
not sure, the question is if we will use this style again in the future

2022-08-12 12:35 UTC, leslielazzarino approved these changes

2022-08-12 12:47 UTC, MarkusObendrauf commented on src/Frontend/shared-styles.ts
> +export const largeClickableIcon = {
ok

2022-08-12 13:18 UTC, MarkusObendrauf commented
Still working on Vasily's first comment

2022-08-16 07:39 UTC, benedikt-richter commented
Would be nice to indicate the user that there are no results in case that there are no results. Possible using some text.

![Screenshot 2022-08-16 at 09 37 07](https://user-images.githubusercontent.com/46576389/184824413-f130e982-133d-4ff5-bffc-0ea6f560a1dd.png)

2022-08-16 07:40 UTC, benedikt-richter commented
Is it intended that the search is restored when navigating from audit view to attribution view and back?

2022-08-16 07:41 UTC, benedikt-richter commented
I fear it is not transparent for the user how search works. Which fields are included in search and which are not. For example, the user might try to search for a version number and might get zero results even if that version is included in the list of packages.

2022-08-16 07:43 UTC, benedikt-richter commented
It would be nice to have a "clear search" button, like we have on attribution view
![Uploading Screenshot 2022-08-16 at 09.42.43.png…]()

2022-08-16 08:23 UTC, vasily-pozdnyakov reviewed
The code looks nice, please check the comments from Benedikt.

2022-08-16 15:20 UTC, vasily-pozdnyakov approved these changes

2022-08-17 07:35 UTC, merged