Allow only one popup of a kind
opossum-tool/OpossumUI pull request #882
Opened 2022-08-19 15:41 UTC by benedikt-richter

### Summary of changes

Fix bug of allowing for several instances of a single popup kind to be open.

### Context and reason for change

Fix: #759

### How can the changes be tested

Open the same popup several times. E.g. press ctrl+F to open search popup several times and observe that now it closes once you click away once.

2022-08-22 08:52 UTC, vasily-pozdnyakov approved these changes
well done.

2022-08-22 14:52 UTC, leslielazzarino requested changes

2022-08-22 14:52 UTC, leslielazzarino commented on src/Frontend/state/reducers/view-reducer.ts
> +      const openPopups = state.popupInfo.map((popupInfo) => popupInfo.popup);
Shouldn't the logic be that we just want to show one popup, no matter the type?

2022-08-22 16:26 UTC, vasily-pozdnyakov commented on src/Frontend/state/reducers/view-reducer.ts
> +      const openPopups = state.popupInfo.map((popupInfo) => popupInfo.popup);
@leslielazzarino Please check the comment https://github.com/opossum-tool/OpossumUI/issues/759#issuecomment-1174785709

2022-08-29 06:02 UTC, leslielazzarino approved these changes

2022-08-29 06:02 UTC, merged