Modification on AttributionView
opossum-tool/OpossumUI pull request #897
Opened 2022-08-24 15:14 UTC by Billwuzl

### Summary of changes

Create the counting for follow-ups 

### Context and reason for change

Easy to know the number of follow-ups from the frontend
### How can the changes be tested

Note: Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

2022-08-25 11:39 UTC, leslielazzarino commented on src/Frontend/enums/enums.ts
> +  Attributions = 'Attributions',
Remove this. Either you use ManualPackages, or you do not use this enum. In general I think using this enum just to get the string, outside of a package panel as you are, is just confusing. Not your fault, was already the case.

2022-08-25 11:41 UTC, leslielazzarino commented on src/Frontend/enums/enums.ts
> +  Attributions = 'Attributions',
Remove this. Either you use ManualPackages, or you do not use this enum. In general I think using this enum just to get the string, outside of a package panel as you are, is just confusing. Not your fault, was already the case.

2022-08-25 11:42 UTC, leslielazzarino commented on src/Frontend/enums/enums.ts
> +  Attributions = 'Attributions',
Remove this. Either you use ManualPackages, or you do not use this enum. In general I think using this enum just to get the string, outside of a package panel as you are, is just confusing. Not your fault, was already the case.

2022-08-25 16:05 UTC, vasily-pozdnyakov requested changes
good job. Please also think about adding tests to check number of follow ups.

2022-08-26 08:30 UTC, Billwuzl commented on src/Frontend/Components/AttributionView/__tests__/AttributionView.test.tsx
> +    expect(screen.getByRole('cell', { name: 'Attributions (2 total,' }));
attribution and follow-up numbers all appear in the test cases now

2022-08-26 08:55 UTC, Billwuzl commented on src/Frontend/Components/AttributionView/AttributionView.tsx
> +      <td>
nope

2022-08-26 09:01 UTC, Billwuzl commented on src/Frontend/Components/AttributionView/AttributionView.tsx
> +  },
sure

2022-08-26 09:08 UTC, Billwuzl commented on src/Frontend/Components/AttributionView/__tests__/AttributionView.test.tsx
> +    // expect(screen.getByText('All Attributions (2)'));
yep. Deleted now

2022-08-26 09:13 UTC, Billwuzl commented on src/Frontend/Components/AttributionView/AttributionView.tsx
> +        {
Do you mean we create a new test case that contains no attribution? If there is no attribution, do we need to have (0 total, 0 (follow-up icon))  or (0 total)

2022-08-26 09:23 UTC, Billwuzl commented on src/Frontend/Components/AttributionView/AttributionView.tsx
> +      <td>
deleted now

2022-08-29 08:26 UTC, vasily-pozdnyakov commented on src/Frontend/Components/AttributionView/__tests__/AttributionView.test.tsx
> +    expect(screen.queryByDisplayValue('Attributions (2 total, 1'));
this test is always passed: try to change the string.

2022-08-29 08:26 UTC, vasily-pozdnyakov commented on src/Frontend/Components/AttributionView/__tests__/AttributionView.test.tsx
> +    expect(screen.queryByDisplayValue('Attributions (2 total, 1'));
the same

2022-08-29 08:27 UTC, vasily-pozdnyakov commented on src/Frontend/Components/AttributionView/__tests__/AttributionView.test.tsx
> +    expect(screen.queryByDisplayValue('Attributions (2 total, 1'));
the same

2022-08-29 08:27 UTC, vasily-pozdnyakov commented on src/Frontend/Components/AttributionView/__tests__/AttributionView.test.tsx
> +    expect(screen.queryByDisplayValue('Attributions (2 total, 1'));
the same

2022-08-29 08:34 UTC, vasily-pozdnyakov commented on src/Frontend/Components/AttributionView/AttributionView.tsx
> +      total,
please add a space after the comma

2022-08-29 08:36 UTC, vasily-pozdnyakov commented on src/Frontend/enums/enums.ts
> +  Attributions = 'Attributions',
do we need the duplicated value?

2022-08-29 08:58 UTC, Billwuzl commented on src/Frontend/Components/AttributionView/__tests__/AttributionView.test.tsx
> +    expect(screen.queryByDisplayValue('Attributions (2 total, 1'));
yeah. I also realized this just now. Modification made now

2022-08-29 09:21 UTC, Billwuzl commented on src/Frontend/enums/enums.ts
> +  Attributions = 'Attributions',
nope. this is removed now

2022-08-29 12:03 UTC, Billwuzl commented on src/Frontend/Components/AttributionView/AttributionView.tsx
> +      total,
I think there is already a large gap after the comma displayed in the APP UI. Do you think we need a larger gap?

2022-08-29 12:06 UTC, Billwuzl commented on src/Frontend/Components/AttributionView/__tests__/AttributionView.test.tsx
> +    expect(screen.queryByDisplayValue('Attributions (2 total, 1'));
now I have managed to use getbytext with both attribution and followups, which can only pass at the correct cases

2022-08-29 12:31 UTC, vasily-pozdnyakov commented on src/Frontend/Components/AttributionView/AttributionView.tsx
> +      total,
I can not see any gaps there, please check it again, maybe it is only my problem.

2022-08-29 12:38 UTC, Billwuzl commented on src/Frontend/Components/AttributionView/AttributionView.tsx
> +        {
if else added to make sure no followup icon if there is no attribution

2022-08-29 13:46 UTC, benedikt-richter commented on src/Frontend/Components/AttributionView/AttributionView.tsx
> +  }
Do we really need this logic?
Can't we always show the number of follow ups?

2022-08-29 14:02 UTC, Billwuzl commented on src/Frontend/Components/AttributionView/AttributionView.tsx
> +  }
ohh Vasily suggests that we avoid showing the followup if there is no attribution

2022-08-29 14:14 UTC, Billwuzl commented on src/Frontend/Components/AttributionList/AttributionList.tsx
> +        <MuiBox sx={classes.title}>{props.title}</MuiBox>
yep the muibox is not necessary

2022-08-30 05:29 UTC, benedikt-richter commented on src/Frontend/Components/AttributionView/AttributionView.tsx
> +      {`${PackagePanelTitle.ManualPackages} (${
`PackagePanelTitle.ManualPackages` is used in the `ManualPackagePanel`. We should not relay on it not changing. I'd therefore suggest to just hardcode the term "Attribtuions" here (and above).

2022-08-30 05:31 UTC, benedikt-richter commented on src/Frontend/Components/AttributionView/AttributionView.tsx
> +      {`${PackagePanelTitle.ManualPackages} (${Object.keys(attributions).length}
This caclulation (`Object.keys(attributions).length`) is done three times here. 
Consider extracting it:
`const numberOfAttributions = Object.keys(attributions).length`

2022-08-30 07:04 UTC, Billwuzl commented on src/Frontend/Components/AttributionView/AttributionView.tsx
> +      {`${PackagePanelTitle.ManualPackages} (${Object.keys(attributions).length}
that makes sense. Modified now

2022-08-30 07:10 UTC, Billwuzl commented on src/Frontend/Components/AttributionView/AttributionView.tsx
> +      {`${PackagePanelTitle.ManualPackages} (${
haha I used to have an 'attributions' in the review above. I was recommended to use ManualPackagePanel to avoid duplications.  Hard coding makes sense.

2022-08-30 07:45 UTC, benedikt-richter commented on src/Frontend/Components/AttributionView/AttributionView.tsx
> +    title = titleWithFollowUp;
Suggestion for a refactoring:

```

  function getAttributionListTitle() {
    const numberOfAttributions = Object.keys(attributions).length;
    const titleWithFollowUp = (
      <MuiTypography>
        {`Attributions (${numberOfAttributions} total, ${
          Object.keys(
            pickBy(attributions, (value: PackageInfo) => value.followUp)
          ).length
        }`}
        <FollowUpIcon sx={classes.titleFollowUp} />)
      </MuiTypography>
    );

    const titleWithoutFollowUp = (
      <MuiTypography>{`Attributions (${numberOfAttributions})`}</MuiTypography>
    );

    return numberOfAttributions ? titleWithFollowUp : titleWithoutFollowUp;
  }

```

2022-08-30 14:36 UTC, benedikt-richter approved these changes
👍

2022-08-30 14:53 UTC, leslielazzarino approved these changes

2022-08-31 07:57 UTC, vasily-pozdnyakov approved these changes

2022-08-31 08:03 UTC, merged