Accordion end-to-end test
opossum-tool/OpossumUI pull request #953
Opened 2022-09-09 09:36 UTC by Billwuzl

### Summary of changes

Accordion end-to-end test

### Context and reason for change

Checked whether the correct signals and attributions are shown on audit detailed view column

Fix: #950

Signed-off-by: Billwuzl <wu.zhuolin2000@gmail.com>
Note: Please review the [guidelines for contributing](https://github.com/opossum-tool/OpossumUI/blob/main/CONTRIBUTING.md) to this repository.

2022-09-09 10:14 UTC, leslielazzarino commented on src/e2e-tests/__tests__/e2e.test.ts
> +    await expect(window.locator(`text=${'jQuery, 16.13.1'}`)).toBeVisible();
Test should be split into two, one for opening the file and checking non-accordion things, one just for the accordion.

2022-09-09 13:16 UTC, benedikt-richter requested changes

2022-09-09 14:53 UTC, Billwuzl commented on src/e2e-tests/__tests__/e2e.test.ts
> +    await expect(window.locator(`text=${'jQuery, 16.13.1'}`)).toBeVisible();
separated into two now

2022-09-09 14:53 UTC, Billwuzl commented on src/e2e-tests/__tests__/e2e.test.ts
> +    ).toBeVisible();
yeah that's true. Solved

2022-09-09 14:53 UTC, Billwuzl commented on src/e2e-tests/__tests__/e2e.test.ts
> +    ).toBeVisible();
Commented

2022-09-09 15:14 UTC, leslielazzarino requested changes

2022-09-09 15:14 UTC, leslielazzarino commented on src/e2e-tests/__tests__/e2e.test.ts
> +    ).toBeHidden();
I would restructure the accordion testing as follows: close two out of three, and test what is in the open one. Then cycle through the others, always just keeping one open, and test what is there. It is much easier to follow, and it should also be shorter.

2022-09-12 07:25 UTC, Billwuzl commented on src/e2e-tests/__tests__/e2e.test.ts
> +    ).toBeHidden();
There are two accordions 'Signals in Folder Content' and 'Attributions in Folder Content' for 'ElectronBackend'. I have kept one open while closing the other one. It should be better now.

For 'main.js' there is only one accordion: 'signals'

2022-09-13 07:23 UTC, leslielazzarino requested changes

2022-09-13 07:23 UTC, leslielazzarino commented on src/e2e-tests/__tests__/e2e.test.ts
> +  it('should classify signals and attributions in accordions', async () => {
show, not classify

2022-09-13 07:23 UTC, leslielazzarino commented on src/e2e-tests/__tests__/e2e.test.ts
> +    // Look for the 'Test Component' within the open accordion, 'Signals in Folder Content'
One comment per line is not the right way of writing a test.

2022-09-13 08:19 UTC, Billwuzl commented on src/e2e-tests/__tests__/e2e.test.ts
> +  it('should classify signals and attributions in accordions', async () => {
tick

2022-09-13 08:20 UTC, Billwuzl commented on src/e2e-tests/__tests__/e2e.test.ts
> +    // Look for the 'Test Component' within the open accordion, 'Signals in Folder Content'
get an attribution called apache now. This avoids using first()  and last()

2022-09-14 12:44 UTC, Billwuzl commented on src/e2e-tests/__tests__/e2e.test.ts
> +    // Look for the 'Test Component' within the open accordion, 'Signals in Folder Content'
now I manage to count the number of attributions in total

2022-09-14 14:55 UTC, benedikt-richter commented
Looks good to me. Just squash commits.

2022-09-19 08:57 UTC, leslielazzarino approved these changes

2022-09-19 08:57 UTC, leslielazzarino commented on src/e2e-tests/__tests__/e2e.test.ts
> +    // Apache appears in both signals and attributions accordions
Add "in folder content" to signals and attributions, as there are two signals panes in the accordion.

2022-09-19 10:39 UTC, benedikt-richter approved these changes

2022-09-19 11:21 UTC, merged