Feature show attribution counts in report view
opossum-tool/OpossumUI pull request #983
Opened 2022-09-13 14:34 UTC by someshkhandelia

### Summary of changes

Show attribution counts in Report View

### Context and reason for change

- Moved a function out from Attribution View to construct a new component.
- This component can now be reused in the Report View as well. 

Fix: #925

2022-09-14 05:51 UTC, benedikt-richter requested changes
Looks good in general. Just tow points.

2022-09-14 05:51 UTC, benedikt-richter commented on src/Frontend/Components/Table/Table.tsx
> +  attributionCount?: ReactElement;
The property `attributionCount` basically duplicates the property `topElement`. Also the usage is quite similar. I'd suggest to remove the property `attributionCount` and to instead insert both the FIlterSelect as well as the AttributionCount components via the `topElement` property.

2022-09-14 05:51 UTC, benedikt-richter commented on src/Frontend/Components/AttributionCountsPanel/AttributionCountsPanel.tsx
> +export function AttributionCountsPanel(
This component should be tested in a file placed next to it.

2022-09-14 08:08 UTC, benedikt-richter commented on src/Frontend/Components/AttributionCountsPanel/__tests__/AttributionCountsPanel.test.tsx
> +  ];
Instead of being first initialized and then modified by side effects, the test data should be assigned the proper values on declaration. E.g.

```
const testManualAttributions: Attributions = {
[testManualUuid]:{
    attributionConfidence: 0,
    comment: 'Some comment',
    packageName: 'Test package',
    packageVersion: '1.0',
    copyright: 'Copyright John Doe',
    licenseText: 'Some license text',
    firstParty: true,
  },
[testOtherManualUuid]:{
    attributionConfidence: 0,
    comment: 'Some other comment',
    packageName: 'Test other package',
    packageVersion: '2.0',
    copyright: 'other Copyright John Doe',
    licenseText: 'Some other license text',
    followUp: FollowUp,
  }
}
```

2022-09-14 08:09 UTC, benedikt-richter commented on src/Frontend/Components/ReportView/ReportView.tsx
> +        topElement={
👍

2022-09-14 08:28 UTC, someshkhandelia commented on src/Frontend/Components/Table/Table.tsx
> +  attributionCount?: ReactElement;
Please find commit here: https://github.com/opossum-tool/OpossumUI/pull/983/commits/3b409e6f964dc77220b6b7818dd4dc3a31b48649

2022-09-14 08:29 UTC, someshkhandelia commented on src/Frontend/Components/AttributionCountsPanel/AttributionCountsPanel.tsx
> +export function AttributionCountsPanel(
Please find commit here: https://github.com/opossum-tool/OpossumUI/pull/983/commits/096e613fecaeb213367198f9cb42ad4b3b468b29

2022-09-14 08:29 UTC, someshkhandelia commented on src/Frontend/Components/ReportView/ReportView.tsx
> +        topElement={
Thank you.

2022-09-14 11:09 UTC, benedikt-richter commented on src/Frontend/Components/AttributionCountsPanel/__tests__/AttributionCountsPanel.test.tsx
> +  const testOtherManualUuid = 'a32f2f96-f40e-11ea-adc1-0242ac120003';
These are unused now

2022-09-14 11:09 UTC, benedikt-richter commented on src/Frontend/Components/AttributionCountsPanel/__tests__/AttributionCountsPanel.test.tsx
> +    testManualUuid: {
If you want to use the uuid's from above: `[testManualUuid]: {`

2022-09-14 11:09 UTC, benedikt-richter commented on src/Frontend/Components/AttributionCountsPanel/__tests__/AttributionCountsPanel.test.tsx
> +    testOtherManualUuid: {
same here

2022-09-14 11:13 UTC, someshkhandelia commented on src/Frontend/Components/AttributionCountsPanel/__tests__/AttributionCountsPanel.test.tsx
> +  const testOtherManualUuid = 'a32f2f96-f40e-11ea-adc1-0242ac120003';
![image](https://user-images.githubusercontent.com/9270691/190139012-1e0f15eb-116a-46f5-ac85-cfc3be4921b9.png)

Maybe, I am missing something here, but I think according to the image, they are being used. Generally, any unused variables would be dimmed by the intelliJ editor and they would be easier to identify. However, that's not the case for these.

2022-09-14 11:21 UTC, someshkhandelia commented on src/Frontend/Components/AttributionCountsPanel/__tests__/AttributionCountsPanel.test.tsx
> +    testManualUuid: {
Those uuid's are not used in the **testManualAttributions** variable, but in the **testResourcesToManualAttributions** variable. Please refer: https://github.com/opossum-tool/OpossumUI/pull/983#discussion_r970669392

2022-09-14 11:22 UTC, someshkhandelia commented on src/Frontend/Components/AttributionCountsPanel/__tests__/AttributionCountsPanel.test.tsx
> +    testOtherManualUuid: {
Please refer: https://github.com/opossum-tool/OpossumUI/pull/983#discussion_r970676195

2022-09-14 11:25 UTC, benedikt-richter commented on src/Frontend/Components/AttributionCountsPanel/__tests__/AttributionCountsPanel.test.tsx
> +    testManualUuid: {
`testResourcesToManualAttributions` links `testManualAttributions` to `testResources`. Therefore, these uuids should match

2022-09-14 12:00 UTC, someshkhandelia commented
In reference to comment: https://github.com/opossum-tool/OpossumUI/pull/983#issuecomment-1246625422

Please find commit here: https://github.com/opossum-tool/OpossumUI/pull/983/commits/3c21f087458210e1976ae65f32fa605b2831bdc1

2022-09-14 13:06 UTC, someshkhandelia commented on src/Frontend/Components/AttributionCountsPanel/__tests__/AttributionCountsPanel.test.tsx
> +  const testOtherManualUuid = 'a32f2f96-f40e-11ea-adc1-0242ac120003';
Please find commit here: https://github.com/opossum-tool/OpossumUI/pull/983/commits/cb7cad93fd99613691e117cffde52f10e42ce1b2

2022-09-14 13:06 UTC, someshkhandelia commented on src/Frontend/Components/AttributionCountsPanel/__tests__/AttributionCountsPanel.test.tsx
> +    testManualUuid: {
Please find commit here: https://github.com/opossum-tool/OpossumUI/pull/983/commits/cb7cad93fd99613691e117cffde52f10e42ce1b2

2022-09-14 13:06 UTC, someshkhandelia commented on src/Frontend/Components/AttributionCountsPanel/__tests__/AttributionCountsPanel.test.tsx
> +    testOtherManualUuid: {
Please find commit here: https://github.com/opossum-tool/OpossumUI/pull/983/commits/cb7cad93fd99613691e117cffde52f10e42ce1b2

2022-09-14 14:11 UTC, someshkhandelia commented
In reference to the comment: https://github.com/opossum-tool/OpossumUI/pull/983#issuecomment-1246702012

Please find commit here: https://github.com/opossum-tool/OpossumUI/pull/983/commits/15d5a78d2435b32a73a32eef8635268c4b8430a1

2022-09-14 14:33 UTC, benedikt-richter commented
LGTM. Just reorganize git commits.

2022-09-14 15:52 UTC, someshkhandelia commented
In response to https://github.com/opossum-tool/OpossumUI/pull/983#issuecomment-1246708442 and https://github.com/opossum-tool/OpossumUI/pull/983#issuecomment-1246860092, 

Please find squashed commit: https://github.com/opossum-tool/OpossumUI/pull/983/commits/7719b376b7efef55f9846d308b379c5e175767e0

2022-09-15 04:56 UTC, benedikt-richter commented
> In response to [#983 (comment)](https://github.com/opossum-tool/OpossumUI/pull/983#issuecomment-1246708442) and [#983 (comment)](https://github.com/opossum-tool/OpossumUI/pull/983#issuecomment-1246860092),
> 
> Please find squashed commit: [7719b37](https://github.com/opossum-tool/OpossumUI/commit/7719b376b7efef55f9846d308b379c5e175767e0)

`This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.`

Seems this commit has still to be (force) pushed

2022-09-15 09:30 UTC, someshkhandelia commented
In response to https://github.com/opossum-tool/OpossumUI/pull/983#issuecomment-1247582058 :

Should be resolved now.

2022-09-15 10:54 UTC, benedikt-richter approved these changes
👍

2022-09-15 11:31 UTC, merged