Improve statistics popup
opossum-tool/OpossumUI pull request #987
Opened 2022-09-14 11:31 UTC by vasily-pozdnyakov

### Summary of changes
Signals per Sources table:
- deduplication for licenses by stripping empty spaces, dashes, making everything lowercase
- For display use the license name occurring most often
- move Signals per Sources table to the bottom of the popup
- highlight criticality using color (the same we use at other places).

### Context and reason for change

Signals per Sources table shows duplicated licenses on real-world data.
No highlighting of critical licenses.

### How can the changes be tested

Visually check using the updated opossum_input file.
Tests are also updated.

2022-09-16 08:52 UTC, benedikt-richter requested changes
The current logic is difficult to reuse and should be refactored.

2022-09-16 08:52 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/AttributionCountPerSourcePerLicenseTable.tsx
>          }}
Even touch not introduced here. Better use use `sx` instead of `style`.

2022-09-16 08:52 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/AttributionCountPerSourcePerLicenseTable.tsx
> +      }}
better use use `sx` instead of `style`

2022-09-16 08:52 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/AttributionCountPerSourcePerLicenseTable.tsx
> +                    }
Refactor to not repeat `projectStatisticsPopupClasses.body` as it seems to be applied in any case.

2022-09-16 08:52 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/AttributionPropertyCountTable.tsx
>          }}
Even touch not introduced here. Better use use `sx` instead of `style`.

2022-09-16 08:52 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +export interface LicensesCriticalities {
I'd rename to `LicenseNamesWithCriticality` or `LicenseNamesToCriticality`

2022-09-16 08:52 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +        .toLowerCase();
Here a mixture of side effects and reassignment is used. We should really try to avoid side effects.
Further, the part of generating the license names for deduplication should be extracted to a function.

2022-09-16 08:52 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +        licenseNameVariantsCount;
Here we a re using a mixture of `strippedLicenseName` and `licenseNameInit` (however this is still not the inital license name). This is hard to understand.

2022-09-16 08:52 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
>  export function aggregateLicensesAndSourcesFromAttributions(
This function is too long. It is hard to understand. 
Also it uses side effects.

The function should be split and logical peaces should be extracted into own functions and be testsed. In particular, we should keep the reuse of deduplication in our mind.

For the refactor we should keep in mind that we want to reuse the deduplicated attributions also in other places, where `AttributionCountPerSourcePerLicense` is not a usable data structure to work with. Probably a data structure like

```

interface UniqueLicenseNameToAttributions {
  [strippedLicenseName: string]: Array<string>;
}

```

establishing a mapping between "unique licenses" and the uuids of the attributions that are identified could be helpful to subsequently calculate all relevant quantities.

Looping over `UniqueLicenseNameToAttributions` would then avoid motifying objects already looped over by side effects and allow to just work with groups of attributions that belong logically together.

2022-09-16 09:16 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
>  export function aggregateLicensesAndSourcesFromAttributions(
Actually, the deduplicatio should probably happen at the level of `ProjectStatisticsPopup` such that the data can be used in other components that are children of `ProjectStatisticsPopup`.

2022-09-19 09:32 UTC, FlorianSchepers commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +    attributionCountPerSourcePerLicense[mostFrequentLicenseName] =
Instead of modifying the "old" object I would create a new object using the `mostFrequentLicenseName` as key. Then you can use proper names for both objects.

2022-09-21 06:59 UTC, benedikt-richter requested changes

2022-09-21 06:59 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/AttributionCountPerSourcePerLicenseTable.tsx
>          }}
Please extract these stylings into a `classes`variable like e.g. in `PackageList.tsx`

2022-09-21 06:59 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/AttributionPropertyCountTable.tsx
> +          width: '300px',
as above

2022-09-21 06:59 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +}
there are several interfaces like this one `[someName: string]: string;` do we need all these?

2022-09-21 06:59 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +function getLicenseDataFromVariants(
instead of a tuple this function should return an object. This would improve readibility.

2022-09-21 06:59 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +  licenseVariantsUUIDs: Array<string>,
these are actually `attributionIds`

2022-09-21 06:59 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +export function getUniqueLicenseNameToAttribution(
this function should be tested

2022-09-21 06:59 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
>  export function aggregateLicensesAndSourcesFromAttributions(
this function should be tested more in detail. More test cases should be added.

2022-09-21 08:16 UTC, vasily-pozdnyakov commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +}
I think you mean `[someName: string]: number`, merged together as they are about the same thing

2022-09-21 12:31 UTC, benedikt-richter requested changes
In the UI, the highlighting for cirticality shall only be displayed if "show criticality" is selected in the menu.

2022-09-21 12:31 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/AttributionCountPerSourcePerLicenseTable.tsx
> +};
could some of these be part of `projectStatisticsPopupClasses`?

2022-09-21 12:31 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/AttributionPropertyCountTable.tsx
> +};
could this be part of `projectStatisticsPopupClasses`?

2022-09-21 12:31 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/AttributionPropertyCountTable.tsx
> +  width: {
the name `width`is very generic. Better to name after it's usage.

2022-09-21 12:31 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +interface AttributionsOrLicensesOrSourcesCounts {
This name is confusing when reading it in the functions. Probably you can inline this interface.

2022-09-21 12:31 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +  let licenseCriticality = '';
Why is this an empty string? Typically, criticality is of type optional `Criticality`

2022-09-21 12:31 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/__tests__/project-statistics-popup-helpers.test.tsx
> +const testAttributions1: Attributions = {
I do not like the `1`in the name. Having `testAttributionsX`where `X`is some number is difficult to make sense of.

2022-09-21 12:31 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/__tests__/project-statistics-popup-helpers.test.tsx
> +  });
Which different functionality do these two tests test for? 
Maybe one could have a stripped license name occuring only once in order to be more different.

2022-09-21 12:31 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/__tests__/project-statistics-popup-helpers.test.tsx
> +    const expectedStrippedLicenseNameToAttribution1 = {
as above and below we should avoid the numbers in the variable names

2022-09-21 12:31 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/__tests__/project-statistics-popup-helpers.test.tsx
> +      Total: { ScanCode: 3, reuser: 3, Total: 6 },
the expected values should be extracted into a constant

2022-09-21 12:31 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/__tests__/project-statistics-popup-helpers.test.tsx
> +      'Test license name_1': '',
the expected values should be extracted into a constant

2022-09-21 12:31 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/__tests__/project-statistics-popup-helpers.test.tsx
> +      'Test-license-name': 'high',
here we should use the enum for criticality

2022-09-21 12:31 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/__tests__/project-statistics-popup-helpers.test.tsx
> +      'Test license name_1': '',
this should be undefined instead of an empty string

2022-09-21 12:31 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/__tests__/project-statistics-popup-helpers.test.tsx
> +      Total: { ScanCode: 2, reuser: 2, HC: 1, Total: 5 },
the expected values should be extracted into a constant

2022-09-21 12:31 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/__tests__/project-statistics-popup-helpers.test.tsx
> +      'Test license name_1': 'medium',
the expected values should be extracted into a constant

2022-09-21 12:31 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/__tests__/project-statistics-popup-helpers.test.tsx
> +      'Total Attributions': 6,
the expected values should be extracted into a constant

2022-09-21 12:31 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/__tests__/project-statistics-popup-helpers.test.tsx
> +      'Total Attributions': 5,
the expected values should be extracted into a constant

2022-09-21 12:41 UTC, FlorianSchepers requested changes

2022-09-21 12:41 UTC, FlorianSchepers commented on src/Frontend/Components/ProjectStatisticsPopup/__tests__/project-statistics-popup-helpers.test.tsx
>        testlicensename: ['uuid1', 'uuid2', 'uuid3'],
Use more specific/accurate license names.

2022-09-21 12:41 UTC, FlorianSchepers commented on src/Frontend/Components/ProjectStatisticsPopup/__tests__/project-statistics-popup-helpers.test.tsx
> +    const expectedStrippedLicenseNameToAttribution1 = {
use more specific name rather than just adding a "1" - see comments above

2022-09-21 12:41 UTC, FlorianSchepers commented on src/Frontend/Components/ProjectStatisticsPopup/__tests__/project-statistics-popup-helpers.test.tsx
> +    const strippedLicenseNameToAttribution1 =
see above

2022-09-21 12:41 UTC, FlorianSchepers commented on src/Frontend/Components/ProjectStatisticsPopup/__tests__/project-statistics-popup-helpers.test.tsx
> +    expect(attributionCountPerSourcePerLicense).toEqual({
move expected output to `expectedAttributionCount..."

2022-09-21 12:41 UTC, FlorianSchepers commented on src/Frontend/Components/ProjectStatisticsPopup/__tests__/project-statistics-popup-helpers.test.tsx
> +    expect(licenseNamesWithCriticalities).toEqual({
move expected output to `expectedLicenseNames..."

2022-09-21 12:41 UTC, FlorianSchepers commented on src/Frontend/Components/ProjectStatisticsPopup/__tests__/project-statistics-popup-helpers.test.tsx
> +    expect(attributionCountPerSourcePerLicense).toEqual({
see above

2022-09-21 12:41 UTC, FlorianSchepers commented on src/Frontend/Components/ProjectStatisticsPopup/__tests__/project-statistics-popup-helpers.test.tsx
> +    expect(licenseNamesWithCriticalities).toEqual({
see above

2022-09-21 12:41 UTC, FlorianSchepers commented on src/Frontend/Components/ProjectStatisticsPopup/__tests__/project-statistics-popup-helpers.test.tsx
> +    expect(attributionPropertyCounts).toEqual({
see above

2022-09-21 12:41 UTC, FlorianSchepers commented on src/Frontend/Components/ProjectStatisticsPopup/__tests__/project-statistics-popup-helpers.test.tsx
> +  it('counts attribution propertes - testAttributions1', () => {
`propertes` -> `properties`

2022-09-21 12:41 UTC, FlorianSchepers commented on src/Frontend/Components/ProjectStatisticsPopup/__tests__/project-statistics-popup-helpers.test.tsx
> +  it('counts attribution propertes - testAttributions', () => {
`propertes` -> `properties`

2022-09-21 12:41 UTC, FlorianSchepers commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +interface AttributionsOrLicensesOrSourcesCounts {
Is there a more generic name for this interface, e.g., "PropertyCounts". Listing all possible usages seems a bit bulky.

2022-09-21 13:38 UTC, vasily-pozdnyakov commented on src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts
> +  let licenseCriticality = '';
But if there is no criticality specified, there still should be a value. Can use null instead, but not sure that it will be good.

2022-09-22 06:56 UTC, benedikt-richter commented on src/Frontend/Components/ProjectStatisticsPopup/__tests__/project-statistics-popup-helpers.test.tsx
> +const testAttributions_1: Attributions = {
Personally, I'd like more a naming like `testAttributions` and `otherTestAttributions`. But you can leave it as is.

2022-09-22 07:49 UTC, FlorianSchepers approved these changes
Looks good!

2022-09-22 07:53 UTC, vasily-pozdnyakov commented on src/Frontend/Components/ProjectStatisticsPopup/__tests__/project-statistics-popup-helpers.test.tsx
> +const testAttributions_1: Attributions = {
Nice point, but I would keep the naming for now.

2022-09-22 08:14 UTC, benedikt-richter approved these changes
👍

2022-09-22 08:45 UTC, merged